"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.DubbingListRequestOrderBy = void 0;
/** The field to use for ordering results from this query. */
exports.DubbingListRequestOrderBy = {
    CreatedAt: "created_at",
    Name: "name",
};
