"use strict";
// This file was auto-generated by Fern from our API Definition.
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.ReceiveTranscription = void 0;
const core = __importStar(require("../../../../core"));
const CommittedTranscriptPayload_1 = require("../../../types/CommittedTranscriptPayload");
const CommittedTranscriptWithTimestampsPayload_1 = require("../../../types/CommittedTranscriptWithTimestampsPayload");
const PartialTranscriptPayload_1 = require("../../../types/PartialTranscriptPayload");
const ScribeAuthErrorPayload_1 = require("../../../types/ScribeAuthErrorPayload");
const ScribeChunkSizeExceededErrorPayload_1 = require("../../../types/ScribeChunkSizeExceededErrorPayload");
const ScribeErrorPayload_1 = require("../../../types/ScribeErrorPayload");
const ScribeInputErrorPayload_1 = require("../../../types/ScribeInputErrorPayload");
const ScribeInsufficientAudioActivityErrorPayload_1 = require("../../../types/ScribeInsufficientAudioActivityErrorPayload");
const ScribeQueueOverflowErrorPayload_1 = require("../../../types/ScribeQueueOverflowErrorPayload");
const ScribeQuotaExceededErrorPayload_1 = require("../../../types/ScribeQuotaExceededErrorPayload");
const ScribeRateLimitedErrorPayload_1 = require("../../../types/ScribeRateLimitedErrorPayload");
const ScribeResourceExhaustedErrorPayload_1 = require("../../../types/ScribeResourceExhaustedErrorPayload");
const ScribeSessionTimeLimitExceededErrorPayload_1 = require("../../../types/ScribeSessionTimeLimitExceededErrorPayload");
const ScribeThrottledErrorPayload_1 = require("../../../types/ScribeThrottledErrorPayload");
const ScribeTranscriberErrorPayload_1 = require("../../../types/ScribeTranscriberErrorPayload");
const ScribeUnacceptedTermsErrorPayload_1 = require("../../../types/ScribeUnacceptedTermsErrorPayload");
const SessionStartedPayload_1 = require("../../../types/SessionStartedPayload");
exports.ReceiveTranscription = core.serialization.undiscriminatedUnion([
    SessionStartedPayload_1.SessionStartedPayload,
    PartialTranscriptPayload_1.PartialTranscriptPayload,
    CommittedTranscriptPayload_1.CommittedTranscriptPayload,
    CommittedTranscriptWithTimestampsPayload_1.CommittedTranscriptWithTimestampsPayload,
    ScribeErrorPayload_1.ScribeErrorPayload,
    ScribeAuthErrorPayload_1.ScribeAuthErrorPayload,
    ScribeQuotaExceededErrorPayload_1.ScribeQuotaExceededErrorPayload,
    ScribeThrottledErrorPayload_1.ScribeThrottledErrorPayload,
    ScribeUnacceptedTermsErrorPayload_1.ScribeUnacceptedTermsErrorPayload,
    ScribeRateLimitedErrorPayload_1.ScribeRateLimitedErrorPayload,
    ScribeQueueOverflowErrorPayload_1.ScribeQueueOverflowErrorPayload,
    ScribeResourceExhaustedErrorPayload_1.ScribeResourceExhaustedErrorPayload,
    ScribeSessionTimeLimitExceededErrorPayload_1.ScribeSessionTimeLimitExceededErrorPayload,
    ScribeInputErrorPayload_1.ScribeInputErrorPayload,
    ScribeChunkSizeExceededErrorPayload_1.ScribeChunkSizeExceededErrorPayload,
    ScribeInsufficientAudioActivityErrorPayload_1.ScribeInsufficientAudioActivityErrorPayload,
    ScribeTranscriberErrorPayload_1.ScribeTranscriberErrorPayload,
]);
