/**
 * The docs page that lists every field of the usage report, rendered from the
 * dictionary (specs/self-hosting/connected-services/usage-report.feature).
 *
 * One function, two callers: `scripts/generate-usage-report-dictionary.ts`
 * writes the page into `docs/`, and a unit test renders it again and compares
 * it with the committed file, so a dictionary change that forgot the docs
 * fails the build rather than shipping a page that describes the previous
 * release.
 */

import {
  USAGE_FIELD_CATEGORIES,
  USAGE_FIELDS,
  USAGE_NEVER_COLLECTED,
  USAGE_REPORT_SCHEMA_VERSION,
  type UsageField,
  type UsageFieldCategory,
  type UsageWindow,
} from "./dictionary";

export const USAGE_REPORT_DICTIONARY_DOC_PATH =
  "docs/self-hosting/usage-report-dictionary.mdx";

const CATEGORY_COPY: Record<
  UsageFieldCategory,
  { heading: string; lede: string; switchable: string }
> = {
  standard: {
    heading: "Standard fields",
    lede: "The identifiers that travel with every report: which install this is, which release it runs, and when the report was taken.",
    switchable:
      "Sent with every report. `DISABLE_USAGE_STATS=true` stops the report as a whole.",
  },
  operational: {
    heading: "Operational fields",
    lede: "What it takes to support this install: how it is divided up, how people sign in, and whether the license names a hosted service.",
    switchable:
      "Sent with every report. `DISABLE_USAGE_STATS=true` stops the report as a whole.",
  },
  subscription: {
    heading: "Subscription fields",
    lede: "License compliance. These travel on the license channel only, from an install whose license names a hosted service, and never in the usage report.",
    switchable: "Not part of the usage report.",
  },
  optional: {
    heading: "Optional fields",
    lede: "Who runs the install, how far they got, what they do with it and how they run it. This is the part you can switch off on the Checkup page without touching the rest.",
    switchable:
      "Switched off as a whole from **Settings, Checkup**. `hostname` has a switch of its own on the same page.",
  },
};

const WINDOW_LABEL: Record<UsageWindow, string> = {
  lifetime: "lifetime",
  "7d": "last 7 days",
  "28d": "last 28 days",
  point_in_time: "at the time of the report",
};

function escapeCell(text: string): string {
  return text.replace(/\|/g, "\\|");
}

function fieldRow(field: UsageField): string {
  const name = `\`${field.key}\`${field.ownSwitch ? " (own switch)" : ""}`;
  return `| ${name} | ${WINDOW_LABEL[field.window]} | ${escapeCell(field.why)} | ${escapeCell(field.source)} |`;
}

function categorySection(category: UsageFieldCategory): string[] {
  const fields = USAGE_FIELDS.filter((field) => field.category === category);
  const copy = CATEGORY_COPY[category];
  const lines = [`## ${copy.heading}`, "", copy.lede, "", copy.switchable, ""];
  if (fields.length === 0) {
    lines.push(
      "No field of this category is in the usage report at this schema version.",
      "",
    );
    return lines;
  }
  lines.push(
    "| Field | Window | Why it is collected | Read from |",
    "|---|---|---|---|",
    ...fields.map(fieldRow),
    "",
  );
  return lines;
}

/** The whole page, frontmatter included. */
export function renderUsageReportDictionaryPage(): string {
  const lines: string[] = [
    "---",
    'title: "Usage report dictionary: every field a self-hosted install sends"',
    'description: "The fields of the daily usage report, their category, their window, why each is collected, and what is never collected. Generated from the dictionary the install reports from."',
    "sidebarTitle: Usage report dictionary",
    "keywords: usage report, telemetry, self-hosted, dictionary, fields, opt out, privacy",
    "---",
    "",
    "{/* Generated by `bash docs/scripts/generate-usage-report-dictionary.sh` from */}",
    "{/* platform/app/src/server/usage-report/dictionary.ts. Do not edit by hand. */}",
    "",
    `This page is schema version ${USAGE_REPORT_SCHEMA_VERSION} of the report, and the report carries that number in \`report_schema_version\`. The dictionary in the code renders this page, so a field on this page is a field the report can carry and a field the report carries is on this page.`,
    "",
    "Each field has a category, and the category decides what switches it off. The report is one JSON document a day; see [Data and telemetry](/self-hosting/data-and-telemetry) for where it goes and how to read your own copy of it.",
    "",
    "<Info>",
    "**Also check:** [Data and telemetry](/self-hosting/data-and-telemetry), [Connect](/self-hosting/connect), [Environment variables](/self-hosting/configuration/environment-variables).",
    "</Info>",
    "",
  ];

  for (const category of USAGE_FIELD_CATEGORIES) {
    lines.push(...categorySection(category));
  }

  lines.push(
    "## Never collected",
    "",
    "The report carries counts and metadata. It never carries any of these, at any schema version:",
    "",
    ...USAGE_NEVER_COLLECTED.map((item) => `- ${item}`),
    "",
  );

  return `${lines.join("\n").trimEnd()}\n`;
}
