/**
 * @langwatch/identity — the isomorphic identity core (ADR-101, ADR-115).
 *
 * The frontend and the backend import this package verbatim, so it reads
 * nothing and writes nothing: no Prisma, no env, no node built-ins. What
 * lives here is what both sides must agree on — the identifier vocabulary,
 * value normalization, the fact and command shapes, the pure reducer, the
 * refusal errors, and the backfill's parity policy. Everything that derives
 * an id (node:crypto), reads a head, or appends a fact is
 * `@langwatch/identity-server`.
 */
export {
  type BackfillDiff,
  type BackfillIdentifierRow,
  backfillParityDiffs,
  type ExpectedIdentifier,
  identifierStateSatisfies,
  orphanedIdentifierRows,
} from "./backfill";
export {
  CONNECTION_ACTIVATED_EVENT_TYPE,
  CONNECTION_DISCARDED_EVENT_TYPE,
  CONNECTION_REGISTERED_EVENT_TYPE,
  CONNECTION_RESUMED_EVENT_TYPE,
  CONNECTION_SUSPENDED_EVENT_TYPE,
  CONNECTION_TORN_DOWN_EVENT_TYPE,
  compareConnectionRouting,
  type ConnectionRoutingComparison,
  type ConnectionRoutingFacts,
  connectionActivatedPayloadSchema,
  connectionDiscardedPayloadSchema,
  connectionRegisteredPayloadSchema,
  connectionResumedPayloadSchema,
  connectionSuspendedPayloadSchema,
  connectionTornDownPayloadSchema,
  DOMAIN_CLAIM_APPROVED_EVENT_TYPE,
  DOMAIN_CLAIM_REJECTED_EVENT_TYPE,
  DOMAIN_CLAIMED_EVENT_TYPE,
  DOMAIN_ATTESTED_EVENT_TYPE,
  DOMAIN_PROOF_LAPSED_EVENT_TYPE,
  DOMAIN_PROOF_RECOVERED_EVENT_TYPE,
  DOMAIN_PROOF_WAVERED_EVENT_TYPE,
  DOMAIN_VERIFIED_EVENT_TYPE,
  domainAttestedPayloadSchema,
  domainClaimApprovedPayloadSchema,
  domainClaimRejectedPayloadSchema,
  domainClaimedPayloadSchema,
  domainClaimFor,
  domainClaimQueue,
  domainClaimWaitedMs,
  domainProofFor,
  domainProofLapsedPayloadSchema,
  domainProofRecoveredPayloadSchema,
  domainProofWaveredPayloadSchema,
  domainVouchesForNewPeople,
  lapsedDomains,
  waveringDomains,
  disputedDomainClaimQueue,
  domainVerifiedPayloadSchema,
  emptySsoConnection,
  reduceSsoConnection,
  routingFactsOf,
  routingStateOf,
  SSO_CONNECTION_EVENT_TYPES,
  SSO_CONNECTION_EVENT_VERSION_LATEST,
  SSO_CONNECTION_SOURCES,
  SSO_CONNECTION_STATES,
  SSO_CONNECTION_TYPES,
  SSO_DOMAIN_CLAIM_AUTHORITIES,
  SSO_DOMAIN_CLAIM_STATES,
  SSO_DOMAIN_PROOF_STATES,
  SSO_PUBLISHED_PROOF_CHANNELS,
  SSO_VERIFICATION_CEREMONY_METHODS,
  SSO_VERIFICATION_METHODS,
  type SsoConnectionEventType,
  type SsoConnectionFact,
  type SsoConnectionFactInput,
  type SsoConnectionLifecycleState,
  type SsoConnectionSource,
  type SsoConnectionState,
  type SsoConnectionType,
  type SsoDomainClaim,
  type SsoDomainClaimAuthority,
  type SsoDomainClaimQueueEntry,
  type SsoDomainClaimState,
  type SsoDomainProofState,
  type SsoDomainVerification,
  type SsoIdpMetadata,
  type SsoPublishedProofChannel,
  type SsoVerificationCeremonyMethod,
  type SsoVerificationMethod,
  ssoConnectionFactInputSchema,
  ssoConnectionSourceSchema,
  ssoConnectionStateSchema,
  ssoConnectionTypeSchema,
  ssoDomainClaimAuthoritySchema,
  ssoDomainClaimStateSchema,
  ssoDomainProofStateSchema,
  ssoIdpMetadataSchema,
  ssoPublishedProofChannelSchema,
  ssoVerificationCeremonyMethodSchema,
  ssoVerificationMethodSchema,
  TEARDOWN_REQUESTED_EVENT_TYPE,
  teardownRequestedPayloadSchema,
  VERIFICATION_REQUESTED_EVENT_TYPE,
  verificationHasExpired,
  verificationRequestedPayloadSchema,
  waitingDomainClaims,
} from "./connection";
export {
  BREAK_GLASS_WARNING_DAYS,
  type BreakGlassBinding,
  type BreakGlassWarningDay,
  breakGlassDaysRemaining,
  breakGlassIsLive,
  breakGlassNextWarningAtMs,
  breakGlassWarningsDue,
} from "./break-glass";
export {
  SSO_DNS_PROOF_TTL_MS,
  SSO_DNS_REPROOF_GRACE_MS,
  SSO_DNS_RECORD_NAME,
  SSO_DNS_RECORD_TYPE,
  SSO_VERIFICATION_FILE_PATH,
  type SsoDeployment,
  ssoDnsRecordName,
  type SsoSelfServeAvailability,
  type SsoSelfServeContext,
  type SsoSelfServeRefusal,
  ssoSelfServeAvailability,
  ssoVerificationFileUrl,
} from "./self-serve-onboarding";
export {
  ACTIVATE_CONNECTION_COMMAND_TYPE,
  APPROVE_DOMAIN_CLAIM_COMMAND_TYPE,
  ATTEST_DOMAIN_COMMAND_TYPE,
  type ActivateConnectionCommandData,
  activateConnectionCommandDataSchema,
  type ApproveDomainClaimCommandData,
  approveDomainClaimCommandDataSchema,
  type AttestDomainCommandData,
  attestDomainCommandDataSchema,
  CLAIM_DOMAIN_COMMAND_TYPE,
  COMPLETE_TEARDOWN_COMMAND_TYPE,
  type ClaimDomainCommandData,
  claimDomainCommandDataSchema,
  type CompleteTeardownCommandData,
  completeTeardownCommandDataSchema,
  DISCARD_CONNECTION_COMMAND_TYPE,
  type DiscardConnectionCommandData,
  discardConnectionCommandDataSchema,
  GRANDFATHER_CONNECTION_COMMAND_TYPE,
  type GrandfatherConnectionCommandData,
  grandfatherConnectionCommandDataSchema,
  REGISTER_CONNECTION_COMMAND_TYPE,
  REJECT_DOMAIN_CLAIM_COMMAND_TYPE,
  REQUEST_TEARDOWN_COMMAND_TYPE,
  REQUEST_VERIFICATION_COMMAND_TYPE,
  RESUME_CONNECTION_COMMAND_TYPE,
  type RegisterConnectionCommandData,
  registerConnectionCommandDataSchema,
  type RejectDomainClaimCommandData,
  rejectDomainClaimCommandDataSchema,
  type RequestTeardownCommandData,
  requestTeardownCommandDataSchema,
  type RequestVerificationCommandData,
  requestVerificationCommandDataSchema,
  type ResumeConnectionCommandData,
  resumeConnectionCommandDataSchema,
  SSO_CONNECTION_COMMAND_TYPES,
  SUSPEND_CONNECTION_COMMAND_TYPE,
  type SsoConnectionCommand,
  type SsoConnectionCommandType,
  type SuspendConnectionCommandData,
  suspendConnectionCommandDataSchema,
  RECORD_DOMAIN_PROOF_ABSENT_COMMAND_TYPE,
  RECORD_DOMAIN_PROOF_PRESENT_COMMAND_TYPE,
  type RecordDomainProofAbsentCommandData,
  type RecordDomainProofPresentCommandData,
  recordDomainProofAbsentCommandDataSchema,
  recordDomainProofPresentCommandDataSchema,
  VERIFY_DOMAIN_COMMAND_TYPE,
  type VerifyDomainCommandData,
  verifyDomainCommandDataSchema,
} from "./connection-commands";
export {
  CannotImpersonateWithoutSecondFactorError,
  IdentityCommandRefusedError,
  IdentityDetachStrandsUserError,
  IdentityEmailInUseError,
  IdentityIdentifierAlreadyHeldError,
  IdentityIdentifierNotFoundError,
  IdentityLinkProposalNotFoundError,
  IdentityLinkProposalResolvedError,
  IdentityIdentifierNotVerifiableError,
  IdentityMfaBackupCodesExhaustedError,
  IdentityMfaCodeInvalidError,
  IdentityMfaEnrollmentExpiredError,
  IdentityMfaEnrollmentRequiredError,
  IdentityMfaLockedOutError,
  IdentityMfaPasswordInvalidError,
  IdentityMfaRequiredByOrganizationError,
  IdentityMfaRequirementNotLicensedError,
  IdentityPasskeyAlreadyRegisteredError,
  IdentityPasskeyCeremonyFailedError,
  IdentityPasskeyNotRecognizedError,
  IdentityPasswordRejectedError,
  IdentityPrimaryMustDemoteFirstError,
  IdentityPrimaryRequiresVerifiedError,
  IdentityResetLinkInvalidError,
  IdentitySignInRefusedError,
  IdentityVerificationExpiredError,
  IdentityVerificationInvalidError,
  JoinAutoConnectionAdmitsError,
  JoinAutoDomainUnprovenError,
  JoinAutoNotLicensedError,
  JoinNotAvailableError,
  JoinPolicyNotLicensedError,
  JoinRequestAlreadyPendingError,
  JoinRequestNotFoundError,
  JoinRequestNotPendingError,
  JoinRequestRefusedError,
  JoinRequestThrottledError,
  MfaCommandRefusedError,
  PasskeyCommandRefusedError,
  SsoActivationBreakGlassMissingError,
  SsoActivationDomainUnprovedError,
  SsoActivationPreconditionError,
  SsoActivationTestSignInMissingError,
  SsoConnectionActivationBlockedError,
  SsoConnectionCommandRefusedError,
  SsoConnectionDomainTakenError,
  SsoConnectionInvalidTransitionError,
  SsoCertificateInvalidError,
  SsoConnectionAlreadyRegisteredError,
  SsoConnectionOperatorActRequiredError,
  SsoConnectionStringEditRetiredError,
  SsoConnectionTeardownStrandsUsersError,
  SsoCredentialsRequiredError,
  SsoDomainClaimPendingError,
  SsoDomainClaimThrottledError,
  SsoDomainNotEligibleError,
  SsoDomainFetchFailedError,
  SsoDomainFileNotFoundError,
  SsoDomainLookupFailedError,
  SsoDomainProofExpiredError,
  SsoDomainProofNotFoundError,
  SsoIssuerUnreachableError,
  SsoLicenseRequiredError,
  SsoSamlMetadataInvalidError,
  SsoSelfServeUnavailableError,
} from "./errors";
export {
  coarseColleagueCount,
  DEFAULT_DOMAIN_JOIN_SETTING,
  DOMAIN_JOIN_SETTINGS,
  type DomainJoinSetting,
  isPublicEmailDomain,
  JOIN_REQUEST_VERIFIED_MEMBER_THRESHOLD,
  type JoinCandidateOrganization,
  type JoinLookupDecision,
  type JoinLookupInput,
  type JoinOffer,
  joinDomainOf,
  organizationAdmitsDomain,
  organizationAdmitsDomainAutomatically,
  PUBLIC_EMAIL_DOMAINS,
  resolveJoinLookup,
} from "./join-matching";
export {
  DOMAIN_AUTO_JOIN_POLICY_ID,
  emptyJoinRequest,
  isPendingJoinRequest,
  JOIN_APPROVED_EVENT_TYPE,
  JOIN_EXPIRED_EVENT_TYPE,
  JOIN_MATCH_KINDS,
  JOIN_REJECTED_EVENT_TYPE,
  JOIN_REQUEST_EVENT_TYPES,
  JOIN_REQUEST_EVENT_VERSION_LATEST,
  JOIN_REQUEST_STATES,
  JOIN_REQUESTED_EVENT_TYPE,
  JOIN_RESOLVER_TYPES,
  JOIN_WITHDRAWAL_CAUSES,
  JOIN_WITHDRAWN_EVENT_TYPE,
  type JoinApprovedPayload,
  type JoinExpiredPayload,
  type JoinMatchKind,
  type JoinRejectedPayload,
  type JoinRequestAggregateState,
  type JoinRequestEventType,
  type JoinRequestFact,
  type JoinRequestFactInput,
  type JoinRequestState,
  type JoinRequestedPayload,
  type JoinResolver,
  type JoinResolverType,
  type JoinWithdrawalCause,
  type JoinWithdrawnPayload,
  joinApprovedPayloadSchema,
  joinExpiredPayloadSchema,
  joinMatchKindSchema,
  joinRejectedPayloadSchema,
  joinRequestFactInputSchema,
  joinRequestStateSchema,
  joinRequestedPayloadSchema,
  joinResolverSchema,
  joinResolverTypeSchema,
  joinWithdrawalCauseSchema,
  joinWithdrawnPayloadSchema,
  reduceJoinRequest,
} from "./join-request";
export {
  APPROVE_JOIN_COMMAND_TYPE,
  type ApproveJoinCommandData,
  approveJoinCommandDataSchema,
  EXPIRE_JOIN_COMMAND_TYPE,
  type ExpireJoinCommandData,
  expireJoinCommandDataSchema,
  JOIN_REQUEST_COMMAND_TYPES,
  type JoinRequestCommand,
  type JoinRequestCommandType,
  REJECT_JOIN_COMMAND_TYPE,
  REQUEST_JOIN_COMMAND_TYPE,
  type RejectJoinCommandData,
  type RequestJoinCommandData,
  rejectJoinCommandDataSchema,
  requestJoinCommandDataSchema,
  WITHDRAW_JOIN_COMMAND_TYPE,
  type WithdrawJoinCommandData,
  withdrawJoinCommandDataSchema,
} from "./join-request-commands";
export {
  ATTACH_IDENTIFIER_COMMAND_TYPE,
  type AttachIdentifierCommandData,
  attachIdentifierCommandDataSchema,
  CONFIRM_LINK_COMMAND_TYPE,
  type ConfirmLinkCommandData,
  confirmLinkCommandDataSchema,
  DETACH_IDENTIFIER_COMMAND_TYPE,
  type DetachIdentifierCommandData,
  detachIdentifierCommandDataSchema,
  ERASE_USER_COMMAND_TYPE,
  emptyIdentityHeads,
  type EraseUserCommandData,
  eraseUserCommandDataSchema,
  IDENTIFIER_ATTACHED_EVENT_TYPE,
  IDENTIFIER_DEAD_ENDED_EVENT_TYPE,
  IDENTIFIER_DETACHED_EVENT_TYPE,
  IDENTIFIER_VERIFIED_EVENT_TYPE,
  IDENTITY_COMMAND_TYPES,
  IDENTITY_EVENT_TYPES,
  IDENTITY_EVENT_VERSION_LATEST,
  type IdentifierFact,
  type IdentityCommand,
  type IdentityCommandType,
  type IdentityEventType,
  type IdentityFact,
  type IdentityFactInput,
  type IdentityFactOf,
  type IdentityHeads,
  identifierAttachedPayloadSchema,
  identifierDeadEndedPayloadSchema,
  identifierDetachedPayloadSchema,
  identifierVerifiedPayloadSchema,
  identifierFactInputSchema,
  LINK_CONFIRMED_EVENT_TYPE,
  LINK_PROPOSED_EVENT_TYPE,
  LINK_REJECTED_EVENT_TYPE,
  type LinkProposalReason,
  linkProposalReasonSchema,
  linkConfirmedPayloadSchema,
  linkProposedPayloadSchema,
  linkRejectedPayloadSchema,
  MARK_PRIMARY_COMMAND_TYPE,
  type MarkPrimaryCommandData,
  markPrimaryCommandDataSchema,
  PRIMARY_CHANGED_EVENT_TYPE,
  primaryChangedPayloadSchema,
  PROPOSE_LINK_COMMAND_TYPE,
  type ProposeLinkCommandData,
  proposeLinkCommandDataSchema,
  REJECT_LINK_COMMAND_TYPE,
  type RejectLinkCommandData,
  rejectLinkCommandDataSchema,
  USER_ERASED_EVENT_TYPE,
  userErasedPayloadSchema,
  VERIFY_IDENTIFIER_COMMAND_TYPE,
  type VerifyIdentifierCommandData,
  verifyIdentifierCommandDataSchema,

} from "./facts";
export {
  identifierDomain,
  normalizeDomain,
  normalizeIdentifierValue,
} from "./identifier";
export {
  type MatchableEmail,
  matchableEmailsOf,
} from "./matchable-emails";
export {
  BACKUP_CODE_CONSUMED_EVENT_TYPE,
  BACKUP_CODES_REGENERATED_EVENT_TYPE,
  backupCodeConsumedPayloadSchema,
  backupCodesRegeneratedPayloadSchema,
  canProveSecondFactor,
  CONFIRM_MFA_COMMAND_TYPE,
  CONSUME_BACKUP_CODE_COMMAND_TYPE,
  type ConfirmMfaCommandData,
  confirmMfaCommandDataSchema,
  type ConsumeBackupCodeCommandData,
  consumeBackupCodeCommandDataSchema,
  DISABLE_MFA_COMMAND_TYPE,
  type DisableMfaCommandData,
  disableMfaCommandDataSchema,
  ENROLL_MFA_COMMAND_TYPE,
  EXPIRE_MFA_ENROLLMENT_COMMAND_TYPE,
  emptyMfaEnrollment,
  type EnrollMfaCommandData,
  enrollMfaCommandDataSchema,
  type ExpireMfaEnrollmentCommandData,
  expireMfaEnrollmentCommandDataSchema,
  MFA_COMMAND_TYPES,
  MFA_CONFIRMED_EVENT_TYPE,
  MFA_DISABLED_EVENT_TYPE,
  MFA_ENROLLED_EVENT_TYPE,
  MFA_ENROLLMENT_EXPIRED_EVENT_TYPE,
  MFA_ENROLLMENT_STATES,
  MFA_EVENT_TYPES,
  MFA_EVENT_VERSION_LATEST,
  MFA_VERIFICATION_FAILED_EVENT_TYPE,
  type MfaCommand,
  type MfaCommandType,
  type MfaDisableVia,
  type MfaEnrollmentLifecycleState,
  type MfaEnrollmentState,
  type MfaEventType,
  type MfaFact,
  type MfaFactInput,
  type MfaFactOf,
  type MfaMethod,
  mfaConfirmedPayloadSchema,
  mfaDisableViaSchema,
  mfaDisabledPayloadSchema,
  mfaEnrolledPayloadSchema,
  mfaEnrollmentExpiredPayloadSchema,
  mfaFactInputSchema,
  mfaMethodSchema,
  mfaVerificationFailedPayloadSchema,
  REGENERATE_BACKUP_CODES_COMMAND_TYPE,
  RECORD_MFA_VERIFICATION_FAILURE_COMMAND_TYPE,
  type RecordMfaVerificationFailureCommandData,
  recordMfaVerificationFailureCommandDataSchema,
  type RegenerateBackupCodesCommandData,
  regenerateBackupCodesCommandDataSchema,
  reduceMfaEnrollment,
  remainingBackupCodes,
} from "./mfa";
export {
  AMR_VALUES,
  type Amr,
  amrSchema,
  assertsSecondFactor,
  connectionAssertsSecondFactor,
  isAmr,
  isMfaChallengeMethod,
  MFA_CHALLENGE_METHODS,
  type MfaChallengeMethod,
  PASSWORD_AMR,
  PHISHING_RESISTANT_AMR,
  recordedNothing,
  SECOND_FACTOR_AMR_VALUES,
  satisfiesOrganizationMfaRequirement,
  type SecondFactorEvidence,
  type SecondFactorSatisfaction,
  secondFactorsIn,
  signInProvedSecondFactor,
  TOTP_AMR,
} from "./mfa-condition";
export {
  PASSWORD_MAXIMUM_BYTES,
  PASSWORD_MINIMUM_LENGTH,
  PASSWORD_REQUIREMENTS_HINT,
  passwordProblem,
} from "./password-policy";
export { primaryEmailOf } from "./primary-email";
export { reduceIdentity } from "./reduce";
export {
  emptyScimSync,
  reduceScimSync,
  SCIM_APPLY_FAILED_EVENT_TYPE,
  SCIM_APPLY_OPS,
  SCIM_APPLY_RECOVERED_EVENT_TYPE,
  SCIM_APPLY_REDRIVEN_EVENT_TYPE,
  SCIM_APPLY_RETIRED_EVENT_TYPE,
  SCIM_GROUP_MAPPED_EVENT_TYPE,
  SCIM_REVOKE_CAUSES,
  SCIM_SYNC_EVENT_TYPES,
  SCIM_SYNC_EVENT_VERSION_LATEST,
  SCIM_SYNC_STATES,
  SCIM_TOKEN_ISSUED_EVENT_TYPE,
  SCIM_TOKEN_REVOKED_EVENT_TYPE,
  SCIM_USER_OPS,
  SCIM_USER_PUSHED_EVENT_TYPE,
  type ScimApplyOp,
  type ScimRevokeCause,
  type ScimSyncEventType,
  type ScimSyncFact,
  type ScimSyncFactInput,
  type ScimSyncFailure,
  type ScimSyncLifecycleState,
  type ScimSyncState,
  type ScimUserOp,
  scimApplyFailedPayloadSchema,
  scimApplyOpSchema,
  scimApplyRecoveredPayloadSchema,
  scimApplyRedrivenPayloadSchema,
  scimApplyRetiredPayloadSchema,
  scimGroupMappedPayloadSchema,
  scimRevokeCauseSchema,
  scimSyncFactInputSchema,
  scimSyncIdFor,
  scimSyncStateSchema,
  scimTokenIssuedPayloadSchema,
  scimTokenRevokedPayloadSchema,
  scimUserOpSchema,
  scimUserPushedPayloadSchema,
} from "./scim-sync";
export {
  ISSUE_SCIM_TOKEN_COMMAND_TYPE,
  type IssueScimTokenCommandData,
  issueScimTokenCommandDataSchema,
  RECORD_SCIM_APPLY_FAILURE_COMMAND_TYPE,
  RECORD_SCIM_GROUP_MAPPING_COMMAND_TYPE,
  RECORD_SCIM_USER_PUSH_COMMAND_TYPE,
  REDRIVE_SCIM_APPLY_COMMAND_TYPE,
  REVOKE_SCIM_SYNC_COMMAND_TYPE,
  type RecordScimApplyFailureCommandData,
  type RecordScimGroupMappingCommandData,
  type RecordScimUserPushCommandData,
  type RedriveScimApplyCommandData,
  type RevokeScimSyncCommandData,
  recordScimApplyFailureCommandDataSchema,
  recordScimGroupMappingCommandDataSchema,
  recordScimUserPushCommandDataSchema,
  redriveScimApplyCommandDataSchema,
  revokeScimSyncCommandDataSchema,
  SCIM_SYNC_COMMAND_TYPES,
  type ScimSyncCommand,
  type ScimSyncCommandType,
} from "./scim-sync-commands";

export {
  type AccountSignInMethods,
  compareToLegacy,
  isLocalSignInMethod,
  legacyProviderOf,
  rankAccountMethods,
  type RoutableConnection,
  type RoutingDecision,
  type RoutingIdentifier,
  type RoutingInput,
  routeSignIn,
  routingIdentifierOf,
  SIGNIN_METHOD_KINDS,
  SIGNIN_ROUTING_OUTCOMES,
  SIGNIN_ROUTING_REASON_CODES,
  SSO_CONNECTION_ROUTING_STATES,
  type ShadowComparison,
  type SignInMethod,
  type SignInMethodKind,
  type SignInMethodPolicy,
  type SignInRoutingOutcome,
  type SignInRoutingReasonCode,
  type SsoConnectionRoutingState,
} from "./signin-routing";
export {
  arrivalStateForProvider,
  IDENTIFIER_LIFECYCLE_STATES,
  IDENTIFIER_PROVIDERS,
  LIVE_IDENTIFIER_STATES,
  type IdentifierArrivalState,
  type IdentifierLifecycleState,
  type IdentifierProvider,
  type IdentityActor,
  identifierArrivalStateSchema,
  identifierProviderFor,
  identifierProviderSchema,
  identityActorSchema,
  isLiveIdentifierState,
  type VerificationMethod,
  verificationMethodSchema,
} from "./vocabulary";
export {
  domainClaimRetryAfterSeconds,
  isClaimableSsoDomain,
  recentDomainClaims,
  SSO_DOMAIN_CLAIM_WINDOW_MS,
  SSO_DOMAIN_CLAIMS_PER_WINDOW,
  SSO_PUBLIC_SUFFIXES,
} from "./sso-domain-claims";
