/**
 * @langwatch/identity — the isomorphic identity core (ADR-101, ADR-115).
 *
 * The frontend and the backend import this package verbatim, so it reads
 * nothing and writes nothing: no Prisma, no env, no node built-ins. What
 * lives here is what both sides must agree on — the identifier vocabulary,
 * value normalization, the fact and command shapes, the pure reducer, the
 * refusal errors, and the backfill's parity policy. Everything that derives
 * an id (node:crypto), reads a head, or appends a fact is
 * `@langwatch/identity-server`.
 */
export {
  type BackfillDiff,
  type BackfillIdentifierRow,
  backfillParityDiffs,
  type ExpectedIdentifier,
  identifierStateSatisfies,
  orphanedIdentifierRows,
} from "./backfill";
export {
  CONNECTION_ACTIVATED_EVENT_TYPE,
  CONNECTION_DISCARDED_EVENT_TYPE,
  CONNECTION_REGISTERED_EVENT_TYPE,
  CONNECTION_RESUMED_EVENT_TYPE,
  CONNECTION_SUSPENDED_EVENT_TYPE,
  CONNECTION_TORN_DOWN_EVENT_TYPE,
  compareConnectionRouting,
  type ConnectionRoutingComparison,
  type ConnectionRoutingFacts,
  connectionActivatedPayloadSchema,
  connectionDiscardedPayloadSchema,
  connectionRegisteredPayloadSchema,
  connectionResumedPayloadSchema,
  connectionSuspendedPayloadSchema,
  connectionTornDownPayloadSchema,
  DOMAIN_CLAIM_APPROVED_EVENT_TYPE,
  DOMAIN_CLAIM_REJECTED_EVENT_TYPE,
  DOMAIN_CLAIMED_EVENT_TYPE,
  DOMAIN_VERIFIED_EVENT_TYPE,
  domainClaimApprovedPayloadSchema,
  domainClaimRejectedPayloadSchema,
  domainClaimedPayloadSchema,
  domainVerifiedPayloadSchema,
  emptySsoConnection,
  reduceSsoConnection,
  routingFactsOf,
  routingStateOf,
  SSO_CONNECTION_EVENT_TYPES,
  SSO_CONNECTION_EVENT_VERSION_LATEST,
  SSO_CONNECTION_SOURCES,
  SSO_CONNECTION_STATES,
  SSO_CONNECTION_TYPES,
  SSO_VERIFICATION_CEREMONY_METHODS,
  SSO_VERIFICATION_METHODS,
  type SsoConnectionEventType,
  type SsoConnectionFact,
  type SsoConnectionFactInput,
  type SsoConnectionLifecycleState,
  type SsoConnectionSource,
  type SsoConnectionState,
  type SsoConnectionType,
  type SsoIdpMetadata,
  type SsoVerificationCeremonyMethod,
  type SsoVerificationMethod,
  ssoConnectionFactInputSchema,
  ssoConnectionSourceSchema,
  ssoConnectionStateSchema,
  ssoConnectionTypeSchema,
  ssoIdpMetadataSchema,
  ssoVerificationCeremonyMethodSchema,
  ssoVerificationMethodSchema,
  TEARDOWN_REQUESTED_EVENT_TYPE,
  teardownRequestedPayloadSchema,
  VERIFICATION_REQUESTED_EVENT_TYPE,
  verificationRequestedPayloadSchema,
} from "./connection";
export {
  ACTIVATE_CONNECTION_COMMAND_TYPE,
  APPROVE_DOMAIN_CLAIM_COMMAND_TYPE,
  type ActivateConnectionCommandData,
  activateConnectionCommandDataSchema,
  type ApproveDomainClaimCommandData,
  approveDomainClaimCommandDataSchema,
  CLAIM_DOMAIN_COMMAND_TYPE,
  COMPLETE_TEARDOWN_COMMAND_TYPE,
  type ClaimDomainCommandData,
  claimDomainCommandDataSchema,
  type CompleteTeardownCommandData,
  completeTeardownCommandDataSchema,
  DISCARD_CONNECTION_COMMAND_TYPE,
  type DiscardConnectionCommandData,
  discardConnectionCommandDataSchema,
  GRANDFATHER_CONNECTION_COMMAND_TYPE,
  type GrandfatherConnectionCommandData,
  grandfatherConnectionCommandDataSchema,
  REGISTER_CONNECTION_COMMAND_TYPE,
  REJECT_DOMAIN_CLAIM_COMMAND_TYPE,
  REQUEST_TEARDOWN_COMMAND_TYPE,
  REQUEST_VERIFICATION_COMMAND_TYPE,
  RESUME_CONNECTION_COMMAND_TYPE,
  type RegisterConnectionCommandData,
  registerConnectionCommandDataSchema,
  type RejectDomainClaimCommandData,
  rejectDomainClaimCommandDataSchema,
  type RequestTeardownCommandData,
  requestTeardownCommandDataSchema,
  type RequestVerificationCommandData,
  requestVerificationCommandDataSchema,
  type ResumeConnectionCommandData,
  resumeConnectionCommandDataSchema,
  SSO_CONNECTION_COMMAND_TYPES,
  SUSPEND_CONNECTION_COMMAND_TYPE,
  type SsoConnectionCommand,
  type SsoConnectionCommandType,
  type SuspendConnectionCommandData,
  suspendConnectionCommandDataSchema,
  VERIFY_DOMAIN_COMMAND_TYPE,
  type VerifyDomainCommandData,
  verifyDomainCommandDataSchema,
} from "./connection-commands";
export {
  CannotImpersonateWithoutSecondFactorError,
  IdentityCommandRefusedError,
  IdentityDetachStrandsUserError,
  IdentityIdentifierNotFoundError,
  IdentityIdentifierNotVerifiableError,
  IdentityMfaBackupCodesExhaustedError,
  IdentityMfaCodeInvalidError,
  IdentityMfaEnrollmentExpiredError,
  IdentityMfaEnrollmentRequiredError,
  IdentityMfaLockedOutError,
  IdentityMfaRequiredByOrganizationError,
  IdentityPasskeyCeremonyFailedError,
  IdentityPasskeyNotRecognizedError,
  IdentityPrimaryMustDemoteFirstError,
  IdentityPrimaryRequiresVerifiedError,
  IdentityVerificationExpiredError,
  IdentityVerificationInvalidError,
  MfaCommandRefusedError,
  PasskeyCommandRefusedError,
  SsoConnectionActivationBlockedError,
  SsoConnectionCommandRefusedError,
  SsoConnectionDomainTakenError,
  SsoConnectionInvalidTransitionError,
  SsoConnectionStringEditRetiredError,
  SsoConnectionTeardownStrandsUsersError,
} from "./errors";
export {
  ATTACH_IDENTIFIER_COMMAND_TYPE,
  type AttachIdentifierCommandData,
  attachIdentifierCommandDataSchema,
  DETACH_IDENTIFIER_COMMAND_TYPE,
  type DetachIdentifierCommandData,
  detachIdentifierCommandDataSchema,
  ERASE_USER_COMMAND_TYPE,
  emptyIdentityHeads,
  type EraseUserCommandData,
  eraseUserCommandDataSchema,
  IDENTIFIER_ATTACHED_EVENT_TYPE,
  IDENTIFIER_DEAD_ENDED_EVENT_TYPE,
  IDENTIFIER_DETACHED_EVENT_TYPE,
  IDENTIFIER_VERIFIED_EVENT_TYPE,
  IDENTITY_COMMAND_TYPES,
  IDENTITY_EVENT_TYPES,
  IDENTITY_EVENT_VERSION_LATEST,
  type IdentifierFact,
  type IdentityCommand,
  type IdentityCommandType,
  type IdentityEventType,
  type IdentityFact,
  type IdentityFactInput,
  type IdentityFactOf,
  type IdentityHeads,
  identifierAttachedPayloadSchema,
  identifierDeadEndedPayloadSchema,
  identifierDetachedPayloadSchema,
  identifierVerifiedPayloadSchema,
  identifierFactInputSchema,
  LINK_PROPOSED_EVENT_TYPE,
  type LinkProposalReason,
  linkProposalReasonSchema,
  linkProposedPayloadSchema,
  MARK_PRIMARY_COMMAND_TYPE,
  type MarkPrimaryCommandData,
  markPrimaryCommandDataSchema,
  PRIMARY_CHANGED_EVENT_TYPE,
  primaryChangedPayloadSchema,
  PROPOSE_LINK_COMMAND_TYPE,
  type ProposeLinkCommandData,
  proposeLinkCommandDataSchema,
  USER_ERASED_EVENT_TYPE,
  userErasedPayloadSchema,
  VERIFY_IDENTIFIER_COMMAND_TYPE,
  type VerifyIdentifierCommandData,
  verifyIdentifierCommandDataSchema,

} from "./facts";
export {
  identifierDomain,
  normalizeDomain,
  normalizeIdentifierValue,
} from "./identifier";
export {
  type MatchableEmail,
  matchableEmailsOf,
} from "./matchable-emails";
export {
  BACKUP_CODE_CONSUMED_EVENT_TYPE,
  BACKUP_CODES_REGENERATED_EVENT_TYPE,
  backupCodeConsumedPayloadSchema,
  backupCodesRegeneratedPayloadSchema,
  canProveSecondFactor,
  CONFIRM_MFA_COMMAND_TYPE,
  CONSUME_BACKUP_CODE_COMMAND_TYPE,
  type ConfirmMfaCommandData,
  confirmMfaCommandDataSchema,
  type ConsumeBackupCodeCommandData,
  consumeBackupCodeCommandDataSchema,
  DISABLE_MFA_COMMAND_TYPE,
  type DisableMfaCommandData,
  disableMfaCommandDataSchema,
  ENROLL_MFA_COMMAND_TYPE,
  EXPIRE_MFA_ENROLLMENT_COMMAND_TYPE,
  emptyMfaEnrollment,
  type EnrollMfaCommandData,
  enrollMfaCommandDataSchema,
  type ExpireMfaEnrollmentCommandData,
  expireMfaEnrollmentCommandDataSchema,
  MFA_COMMAND_TYPES,
  MFA_CONFIRMED_EVENT_TYPE,
  MFA_DISABLED_EVENT_TYPE,
  MFA_ENROLLED_EVENT_TYPE,
  MFA_ENROLLMENT_EXPIRED_EVENT_TYPE,
  MFA_ENROLLMENT_STATES,
  MFA_EVENT_TYPES,
  MFA_EVENT_VERSION_LATEST,
  MFA_VERIFICATION_FAILED_EVENT_TYPE,
  type MfaCommand,
  type MfaCommandType,
  type MfaDisableVia,
  type MfaEnrollmentLifecycleState,
  type MfaEnrollmentState,
  type MfaEventType,
  type MfaFact,
  type MfaFactInput,
  type MfaFactOf,
  type MfaMethod,
  mfaConfirmedPayloadSchema,
  mfaDisableViaSchema,
  mfaDisabledPayloadSchema,
  mfaEnrolledPayloadSchema,
  mfaEnrollmentExpiredPayloadSchema,
  mfaFactInputSchema,
  mfaMethodSchema,
  mfaVerificationFailedPayloadSchema,
  REGENERATE_BACKUP_CODES_COMMAND_TYPE,
  RECORD_MFA_VERIFICATION_FAILURE_COMMAND_TYPE,
  type RecordMfaVerificationFailureCommandData,
  recordMfaVerificationFailureCommandDataSchema,
  type RegenerateBackupCodesCommandData,
  regenerateBackupCodesCommandDataSchema,
  reduceMfaEnrollment,
  remainingBackupCodes,
} from "./mfa";
export {
  AMR_VALUES,
  type Amr,
  amrSchema,
  assertsSecondFactor,
  connectionAssertsSecondFactor,
  isAmr,
  isMfaChallengeMethod,
  MFA_CHALLENGE_METHODS,
  type MfaChallengeMethod,
  PASSWORD_AMR,
  PHISHING_RESISTANT_AMR,
  recordedNothing,
  SECOND_FACTOR_AMR_VALUES,
  satisfiesOrganizationMfaRequirement,
  type SecondFactorEvidence,
  type SecondFactorSatisfaction,
  secondFactorsIn,
  signInProvedSecondFactor,
  TOTP_AMR,
} from "./mfa-condition";
export { primaryEmailOf } from "./primary-email";
export { reduceIdentity } from "./reduce";
export {
  compareToLegacy,
  isLocalSignInMethod,
  legacyProviderOf,
  type RoutableConnection,
  type RoutingDecision,
  type RoutingIdentifier,
  type RoutingInput,
  routeSignIn,
  routingIdentifierOf,
  SIGNIN_METHOD_KINDS,
  SIGNIN_ROUTING_OUTCOMES,
  SIGNIN_ROUTING_REASON_CODES,
  SSO_CONNECTION_ROUTING_STATES,
  type ShadowComparison,
  type SignInMethod,
  type SignInMethodKind,
  type SignInMethodPolicy,
  type SignInRoutingOutcome,
  type SignInRoutingReasonCode,
  type SsoConnectionRoutingState,
} from "./signin-routing";
export {
  arrivalStateForProvider,
  IDENTIFIER_LIFECYCLE_STATES,
  IDENTIFIER_PROVIDERS,
  LIVE_IDENTIFIER_STATES,
  type IdentifierArrivalState,
  type IdentifierLifecycleState,
  type IdentifierProvider,
  type IdentityActor,
  identifierArrivalStateSchema,
  identifierProviderFor,
  identifierProviderSchema,
  identityActorSchema,
  isLiveIdentifierState,
  type VerificationMethod,
  verificationMethodSchema,
} from "./vocabulary";
