/**
 * @langwatch/identity — the isomorphic identity core (ADR-101, ADR-115).
 *
 * The frontend and the backend import this package verbatim, so it reads
 * nothing and writes nothing: no Prisma, no env, no node built-ins. What
 * lives here is what both sides must agree on — the identifier vocabulary,
 * value normalization, the fact and command shapes, the pure reducer, the
 * refusal errors, and the backfill's parity policy. Everything that derives
 * an id (node:crypto), reads a head, or appends a fact is
 * `@langwatch/identity-server`.
 */
export {
  type BackfillDiff,
  type BackfillIdentifierRow,
  backfillParityDiffs,
  type ExpectedIdentifier,
  identifierStateSatisfies,
  orphanedIdentifierRows,
} from "./backfill";
export {
  CONNECTION_ACTIVATED_EVENT_TYPE,
  CONNECTION_DISCARDED_EVENT_TYPE,
  CONNECTION_REGISTERED_EVENT_TYPE,
  CONNECTION_RESUMED_EVENT_TYPE,
  CONNECTION_SUSPENDED_EVENT_TYPE,
  CONNECTION_TORN_DOWN_EVENT_TYPE,
  compareConnectionRouting,
  type ConnectionRoutingComparison,
  type ConnectionRoutingFacts,
  connectionActivatedPayloadSchema,
  connectionDiscardedPayloadSchema,
  connectionRegisteredPayloadSchema,
  connectionResumedPayloadSchema,
  connectionSuspendedPayloadSchema,
  connectionTornDownPayloadSchema,
  DOMAIN_CLAIM_APPROVED_EVENT_TYPE,
  DOMAIN_CLAIM_REJECTED_EVENT_TYPE,
  DOMAIN_CLAIMED_EVENT_TYPE,
  DOMAIN_ATTESTED_EVENT_TYPE,
  DOMAIN_VERIFIED_EVENT_TYPE,
  domainAttestedPayloadSchema,
  domainClaimApprovedPayloadSchema,
  domainClaimRejectedPayloadSchema,
  domainClaimedPayloadSchema,
  domainVerifiedPayloadSchema,
  emptySsoConnection,
  reduceSsoConnection,
  routingFactsOf,
  routingStateOf,
  SSO_CONNECTION_EVENT_TYPES,
  SSO_CONNECTION_EVENT_VERSION_LATEST,
  SSO_CONNECTION_SOURCES,
  SSO_CONNECTION_STATES,
  SSO_CONNECTION_TYPES,
  SSO_VERIFICATION_CEREMONY_METHODS,
  SSO_VERIFICATION_METHODS,
  type SsoConnectionEventType,
  type SsoConnectionFact,
  type SsoConnectionFactInput,
  type SsoConnectionLifecycleState,
  type SsoConnectionSource,
  type SsoConnectionState,
  type SsoConnectionType,
  type SsoDomainVerification,
  type SsoIdpMetadata,
  type SsoVerificationCeremonyMethod,
  type SsoVerificationMethod,
  ssoConnectionFactInputSchema,
  ssoConnectionSourceSchema,
  ssoConnectionStateSchema,
  ssoConnectionTypeSchema,
  ssoIdpMetadataSchema,
  ssoVerificationCeremonyMethodSchema,
  ssoVerificationMethodSchema,
  TEARDOWN_REQUESTED_EVENT_TYPE,
  teardownRequestedPayloadSchema,
  VERIFICATION_REQUESTED_EVENT_TYPE,
  verificationRequestedPayloadSchema,
} from "./connection";
export {
  ACTIVATE_CONNECTION_COMMAND_TYPE,
  APPROVE_DOMAIN_CLAIM_COMMAND_TYPE,
  ATTEST_DOMAIN_COMMAND_TYPE,
  type ActivateConnectionCommandData,
  activateConnectionCommandDataSchema,
  type ApproveDomainClaimCommandData,
  approveDomainClaimCommandDataSchema,
  type AttestDomainCommandData,
  attestDomainCommandDataSchema,
  CLAIM_DOMAIN_COMMAND_TYPE,
  COMPLETE_TEARDOWN_COMMAND_TYPE,
  type ClaimDomainCommandData,
  claimDomainCommandDataSchema,
  type CompleteTeardownCommandData,
  completeTeardownCommandDataSchema,
  DISCARD_CONNECTION_COMMAND_TYPE,
  type DiscardConnectionCommandData,
  discardConnectionCommandDataSchema,
  GRANDFATHER_CONNECTION_COMMAND_TYPE,
  type GrandfatherConnectionCommandData,
  grandfatherConnectionCommandDataSchema,
  REGISTER_CONNECTION_COMMAND_TYPE,
  REJECT_DOMAIN_CLAIM_COMMAND_TYPE,
  REQUEST_TEARDOWN_COMMAND_TYPE,
  REQUEST_VERIFICATION_COMMAND_TYPE,
  RESUME_CONNECTION_COMMAND_TYPE,
  type RegisterConnectionCommandData,
  registerConnectionCommandDataSchema,
  type RejectDomainClaimCommandData,
  rejectDomainClaimCommandDataSchema,
  type RequestTeardownCommandData,
  requestTeardownCommandDataSchema,
  type RequestVerificationCommandData,
  requestVerificationCommandDataSchema,
  type ResumeConnectionCommandData,
  resumeConnectionCommandDataSchema,
  SSO_CONNECTION_COMMAND_TYPES,
  SUSPEND_CONNECTION_COMMAND_TYPE,
  type SsoConnectionCommand,
  type SsoConnectionCommandType,
  type SuspendConnectionCommandData,
  suspendConnectionCommandDataSchema,
  VERIFY_DOMAIN_COMMAND_TYPE,
  type VerifyDomainCommandData,
  verifyDomainCommandDataSchema,
} from "./connection-commands";
export {
  IdentityCommandRefusedError,
  IdentityIdentifierNotFoundError,
  IdentityIdentifierNotVerifiableError,
  IdentityPrimaryMustDemoteFirstError,
  IdentityPrimaryRequiresVerifiedError,
  IdentityVerificationExpiredError,
  IdentityVerificationInvalidError,
  SsoConnectionActivationBlockedError,
  SsoConnectionCommandRefusedError,
  SsoConnectionDomainTakenError,
  SsoConnectionInvalidTransitionError,
  SsoConnectionOperatorActRequiredError,
  SsoConnectionStringEditRetiredError,
  SsoConnectionTeardownStrandsUsersError,
  SsoSamlNotSelfServeError,
} from "./errors";
export {
  ATTACH_IDENTIFIER_COMMAND_TYPE,
  type AttachIdentifierCommandData,
  attachIdentifierCommandDataSchema,
  DETACH_IDENTIFIER_COMMAND_TYPE,
  type DetachIdentifierCommandData,
  detachIdentifierCommandDataSchema,
  ERASE_USER_COMMAND_TYPE,
  emptyIdentityHeads,
  type EraseUserCommandData,
  eraseUserCommandDataSchema,
  IDENTIFIER_ATTACHED_EVENT_TYPE,
  IDENTIFIER_DEAD_ENDED_EVENT_TYPE,
  IDENTIFIER_DETACHED_EVENT_TYPE,
  IDENTIFIER_VERIFIED_EVENT_TYPE,
  IDENTITY_COMMAND_TYPES,
  IDENTITY_EVENT_TYPES,
  IDENTITY_EVENT_VERSION_LATEST,
  type IdentifierFact,
  type IdentityCommand,
  type IdentityCommandType,
  type IdentityEventType,
  type IdentityFact,
  type IdentityFactInput,
  type IdentityFactOf,
  type IdentityHeads,
  identifierAttachedPayloadSchema,
  identifierDeadEndedPayloadSchema,
  identifierDetachedPayloadSchema,
  identifierVerifiedPayloadSchema,
  identityFactInputSchema,
  LINK_PROPOSED_EVENT_TYPE,
  type LinkProposalReason,
  linkProposalReasonSchema,
  linkProposedPayloadSchema,
  MARK_PRIMARY_COMMAND_TYPE,
  type MarkPrimaryCommandData,
  markPrimaryCommandDataSchema,
  PRIMARY_CHANGED_EVENT_TYPE,
  primaryChangedPayloadSchema,
  PROPOSE_LINK_COMMAND_TYPE,
  type ProposeLinkCommandData,
  proposeLinkCommandDataSchema,
  USER_ERASED_EVENT_TYPE,
  userErasedPayloadSchema,
  VERIFY_IDENTIFIER_COMMAND_TYPE,
  type VerifyIdentifierCommandData,
  verifyIdentifierCommandDataSchema,
} from "./facts";
export {
  identifierDomain,
  normalizeDomain,
  normalizeIdentifierValue,
} from "./identifier";
export {
  type MatchableEmail,
  matchableEmailsOf,
} from "./matchable-emails";
export { primaryEmailOf } from "./primary-email";
export { reduceIdentity } from "./reduce";
export {
  compareToLegacy,
  isLocalSignInMethod,
  legacyProviderOf,
  type RoutableConnection,
  type RoutingDecision,
  type RoutingIdentifier,
  type RoutingInput,
  routeSignIn,
  routingIdentifierOf,
  SIGNIN_METHOD_KINDS,
  SIGNIN_ROUTING_OUTCOMES,
  SIGNIN_ROUTING_REASON_CODES,
  SSO_CONNECTION_ROUTING_STATES,
  type ShadowComparison,
  type SignInMethod,
  type SignInMethodKind,
  type SignInMethodPolicy,
  type SignInRoutingOutcome,
  type SignInRoutingReasonCode,
  type SsoConnectionRoutingState,
} from "./signin-routing";
export {
  arrivalStateForProvider,
  IDENTIFIER_LIFECYCLE_STATES,
  IDENTIFIER_PROVIDERS,
  LIVE_IDENTIFIER_STATES,
  type IdentifierArrivalState,
  type IdentifierLifecycleState,
  type IdentifierProvider,
  type IdentityActor,
  identifierArrivalStateSchema,
  identifierProviderFor,
  identifierProviderSchema,
  identityActorSchema,
  isLiveIdentifierState,
  type VerificationMethod,
  verificationMethodSchema,
} from "./vocabulary";
