/**
 * Serves the generated OpenAPI description of the LangWatch REST API at
 * GET /api/gateway/v1/openapi.json, the location published in
 * specs/ai-gateway/_shared/contract.md section 12.
 *
 * The document is the build artifact `src/app/api/openapiLangWatch.json`,
 * regenerated by `pnpm run task generateOpenAPISpec`. It is imported rather
 * than read from disk per request so the file resolves through the module
 * graph and cannot go missing at runtime in a deployment that only ships
 * compiled output.
 */
import { createServiceApp, publicEndpoint } from "~/server/api/security";
import openapiDocument from "../../app/api/openapiLangWatch.json";

/**
 * The typed shape of the import is a 1.3 MB object literal that no caller
 * benefits from. Narrowing it here keeps that type out of the handler's
 * inference and out of every module that touches this router.
 */
const document = openapiDocument as unknown as Record<string, unknown>;

const secured = createServiceApp({ basePath: "/api/gateway/v1" });

secured
  .access(
    publicEndpoint(
      "the description of a public API, listing the endpoints and the credentials they want; a caller reads it to learn how to authenticate, so requiring authentication to read it would be circular, and it carries no tenant data",
    ),
  )
  .get("/openapi.json", (c) => c.json(document));

export const app = secured.hono;
