// This file is automatically generated
export const METADATA = {
    "name": "@openai/agents-openai",
    "version": "0.3.9",
    "versions": {
        "@openai/agents-openai": "0.3.9",
        "@openai/agents-core": "workspace:*",
        "openai": "^6"
    }
};
export default METADATA;
//# sourceMappingURL=metadata.mjs.map