"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.TelephonyDirection = void 0;
exports.TelephonyDirection = {
    Inbound: "inbound",
    Outbound: "outbound",
};
