"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.WebhookToolApiSchemaConfigInputMethod = void 0;
/** The HTTP method to use for the webhook */
exports.WebhookToolApiSchemaConfigInputMethod = {
    Get: "GET",
    Post: "POST",
    Put: "PUT",
    Patch: "PATCH",
    Delete: "DELETE",
};
