"use strict";
// This file was auto-generated by Fern from our API Definition.
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.ConversationalConfigApiModelWorkflowOverrideInput = void 0;
const core = __importStar(require("../../core"));
const AgentConfigApiModelWorkflowOverrideInput_1 = require("./AgentConfigApiModelWorkflowOverrideInput");
const AsrConversationalConfigWorkflowOverride_1 = require("./AsrConversationalConfigWorkflowOverride");
const ConversationConfigWorkflowOverrideInput_1 = require("./ConversationConfigWorkflowOverrideInput");
const LanguagePresetInput_1 = require("./LanguagePresetInput");
const TtsConversationalConfigWorkflowOverrideInput_1 = require("./TtsConversationalConfigWorkflowOverrideInput");
const TurnConfigWorkflowOverride_1 = require("./TurnConfigWorkflowOverride");
const VadConfigWorkflowOverride_1 = require("./VadConfigWorkflowOverride");
exports.ConversationalConfigApiModelWorkflowOverrideInput = core.serialization.object({
    asr: AsrConversationalConfigWorkflowOverride_1.AsrConversationalConfigWorkflowOverride.optional(),
    turn: TurnConfigWorkflowOverride_1.TurnConfigWorkflowOverride.optional(),
    tts: TtsConversationalConfigWorkflowOverrideInput_1.TtsConversationalConfigWorkflowOverrideInput.optional(),
    conversation: ConversationConfigWorkflowOverrideInput_1.ConversationConfigWorkflowOverrideInput.optional(),
    languagePresets: core.serialization.property("language_presets", core.serialization.record(core.serialization.string(), LanguagePresetInput_1.LanguagePresetInput.optional()).optional()),
    vad: VadConfigWorkflowOverride_1.VadConfigWorkflowOverride.optional(),
    agent: AgentConfigApiModelWorkflowOverrideInput_1.AgentConfigApiModelWorkflowOverrideInput.optional(),
});
