-- AlterEnum
ALTER TYPE "PlanTypes" ADD VALUE 'GROWTH_SEAT_EUR_MONTHLY';
ALTER TYPE "PlanTypes" ADD VALUE 'GROWTH_SEAT_EUR_ANNUAL';
ALTER TYPE "PlanTypes" ADD VALUE 'GROWTH_SEAT_USD_MONTHLY';
ALTER TYPE "PlanTypes" ADD VALUE 'GROWTH_SEAT_USD_ANNUAL';

