-- AlterEnum
ALTER TYPE "PlanTypes" ADD VALUE 'GROWTH_SEAT_EUR_MONTHLY';
ALTER TYPE "PlanTypes" ADD VALUE 'GROWTH_SEAT_EUR_ANNUAL';
ALTER TYPE "PlanTypes" ADD VALUE 'GROWTH_SEAT_USD_MONTHLY';
ALTER TYPE "PlanTypes" ADD VALUE 'GROWTH_SEAT_USD_ANNUAL';

-- CreateEnum
CREATE TYPE "PricingModel" AS ENUM ('TIERED', 'SEAT_EVENT');

-- AlterTable
ALTER TABLE "Organization" ADD COLUMN "pricingModel" "PricingModel" NOT NULL DEFAULT 'TIERED';
