export const PAYLOAD_BLOCKLIST_EXACT: Readonly<Record<string, true>> = {
  "gen_ai.prompt": true,
  "gen_ai.completion": true,
  "gen_ai.response.choices": true,
  "gen_ai.response.finish_reasons": true,
  "raw_input": true,
  "input.value": true,
  "output.value": true,
  "input": true,
  "output": true,
  "mastra.output": true,
  "mastra.agent_run.input": true,
  "mastra.agent_run.output": true,
  "mastra.model_step.output": true,
  "mastra.model_step.input": true,
  "traceloop.entity.input": true,
  "traceloop.entity.output": true,
  "langwatch.input": true,
  "langwatch.output": true,
  "langwatch.claude_code.request_body": true,
  "langwatch.claude_code.response_body": true,
  "retrieval.documents": true,
  "llm.input_messages": true,
  "llm.output_messages": true,
};

export const PAYLOAD_BLOCKLIST_PREFIXES: readonly string[] = [
  "gen_ai.prompt.",
  "gen_ai.completion.",
  "gen_ai.response.choices.",
  "gen_ai.response.finish_reasons.",
  "llm.input_messages.",
  "llm.output_messages.",
];
