"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.VoiceRecordingQuality = void 0;
exports.VoiceRecordingQuality = {
    Studio: "studio",
    Good: "good",
    Ok: "ok",
    Poor: "poor",
    Bad: "bad",
};
