{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  {{- if .Values.ingress.labels }}
  labels:
    {{- .Values.ingress.labels | toYaml | nindent 4 }}
  {{- end }}
  {{- if .Values.ingress.annotations }}
  annotations:
    {{- .Values.ingress.annotations | toYaml | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- range . }}
    - secretName: {{ .secretName }}
      hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
    {{- end }}
  {{- end }}
  rules:
    {{- if .Values.ingress.hosts }}
    {{- .Values.ingress.hosts | toYaml | nindent 4 }}
    {{- end }}
{{- end }}
