// The registry: every rule now lives in `@langwatch/lint-core`, built with
// `defineRule` so the message shape, the per-file classification, and the
// fixture-tree test harness are shared instead of hand-rolled per rule. This
// file only wires the rule objects into the plugin oxlint loads.

import {
  apiContextServicesRule,
  awaitedReturnChainRule,
  booleanWallRule,
  boundaryRule,
  cognitiveComplexityRule,
  commentBlockSizeRule,
  commentBlockSizeWarningRule,
  conditionShapeRule,
  conditionalTypeDepthRule,
  environmentBoundariesRule,
  fallibleResultNamingRule,
  featureModuleClassesRule,
  featureSourceFilenameRule,
  featureSourceLayoutRule,
  featureSourceSubjectRule,
  layerClassRule,
  logicalStatementSpacingRule,
  maxStatementsPerLineRule,
  nestedTernaryRule,
  noRawHonoMountRule,
  overloadByLiteralRule,
  prismaContainmentRule,
  runtimeUndefinedRule,
  serviceClassesRule,
  serviceDependenciesRule,
  serviceMemberSpacingRule,
  serviceQualityRule,
  typedPrismaSeamRule,
} from "@langwatch/lint-core";

export const rules = {
  "api-context-services": apiContextServicesRule,
  "comment-block-size": commentBlockSizeRule,
  "comment-block-size-warning": commentBlockSizeWarningRule,
  "conditional-type-depth": conditionalTypeDepthRule,
  "fallible-result-naming": fallibleResultNamingRule,
  "feature-source-filename": featureSourceFilenameRule,
  "feature-source-layout": featureSourceLayoutRule,
  "feature-source-subject": featureSourceSubjectRule,
  "layer-class": layerClassRule,
  "no-raw-hono-mount": noRawHonoMountRule,
  "overload-by-literal": overloadByLiteralRule,
  "prisma-containment": prismaContainmentRule,
  "typed-prisma-seam": typedPrismaSeamRule,
  "cognitive-complexity": cognitiveComplexityRule,
  "condition-shape": conditionShapeRule,
  "environment-boundaries": environmentBoundariesRule,
  "package-boundaries": boundaryRule,
  "feature-module-classes": featureModuleClassesRule,
  "service-classes": serviceClassesRule,
  "service-quality": serviceQualityRule,
  "max-statements-per-line": maxStatementsPerLineRule,
  "nested-ternary": nestedTernaryRule,
  "service-member-spacing": serviceMemberSpacingRule,
  "service-dependencies": serviceDependenciesRule,
  "runtime-undefined": runtimeUndefinedRule,
  "logical-statement-spacing": logicalStatementSpacingRule,
  "boolean-wall": booleanWallRule,
  "awaited-return-chain": awaitedReturnChainRule,
};

export default {
  meta: { name: "eslint-plugin-langwatch", version: "0.1.0" },
  rules,
};
