"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.TurnEagerness = void 0;
/** Agent's eagerness to respond. Higher values make agent wait for higher turn probability. */
exports.TurnEagerness = {
    Patient: "patient",
    Normal: "normal",
    Eager: "eager",
};
