"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.InteractionBudget = void 0;
exports.InteractionBudget = {
    Realtime: "realtime",
    FiveMinutes: "5_minutes",
    TenMinutes: "10_minutes",
    OneHour: "1_hour",
};
