package workerpool

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/url"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
	"sync"
	"syscall"
	"time"

	"go.uber.org/zap"

	"github.com/langwatch/langwatch/pkg/clog"
	"github.com/langwatch/langwatch/services/langyagent/adapters/egress"
	"github.com/langwatch/langwatch/services/langyagent/app"
	"github.com/langwatch/langwatch/services/langyagent/domain"
)

// Worker is the pool's bookkeeping for one OpenCode subprocess. It satisfies
// app.Worker so the app orchestrator can drive a turn without importing this
// adapter.
type Worker struct {
	conversationID string
	// port is the externally-advertised port the manager dials. It belongs to
	// the per-worker authProxy below, which checks bearerToken and forwards to
	// the opencode process on internalPort.
	port int
	// internalPort is opencode's actual TCP listen, fronted by authProxy. Never
	// exposed to callers — they always go via port.
	internalPort int
	// bearerToken is the per-worker shared secret. Required in every
	// Authorization header on requests to port. Generated by the manager at
	// spawn and not persisted anywhere.
	bearerToken string
	// baseURL is the precomputed "http://127.0.0.1:<port>" for the external port,
	// so per-turn PostMessage/StreamEvents don't re-Sprintf the host every call.
	baseURL string
	// authProxy fronts opencode with bearer-token auth. Shutdown on worker exit
	// so the externally-advertised port frees up.
	authProxy *AuthProxy
	// egress is the per-worker OUTBOUND egress handle (ADR-043) returned by the
	// egress guard's PrepareWorker: it carries the loopback forward-proxy port
	// the worker's HTTPS_PROXY points at (0 when the guard runs no proxy) and a
	// Close that tears the proxy down. Closed on every teardown path (kill /
	// exit / spawn failure), exactly like authProxy, so it never outlives the
	// worker or leaks across a recycle.
	egress            egress.WorkerEgress
	openCodeSessionID string
	cmd               *exec.Cmd
	uid               uint32

	// credSig is set at spawn and compared on each reuse. A mismatch means the
	// caller's capability set differs from this worker's — we must recreate the
	// worker rather than continue with stale env.
	credSig domain.CredentialSignature

	// apiKeyID + langwatchEndpoint are the two things needed to revoke this
	// worker's session key when it dies, and nothing else. They are recorded at
	// spawn because that is the only moment we have them: the key itself goes into
	// the subprocess env and is never readable again, and later turns on a reused
	// worker deliberately arrive with no credentials at all.
	//
	// The key's lifetime IS this worker's lifetime — it was injected at spawn and
	// a reused worker keeps it — so the worker is the right thing to hang the
	// revocation handle off.
	apiKeyID          string
	langwatchEndpoint string

	mu sync.Mutex
	// lastSeen drives the idle reaper.
	lastSeen time.Time
	// inFlight serialises turns on the same conversation. Two simultaneous
	// /chat requests for one conversationID would otherwise both subscribe to
	// the same /event stream and each terminate on the other's terminal event,
	// splicing replies. Claim/Release wrap it.
	inFlight bool
}

// compile-time proof Worker satisfies the app port.
var _ app.Worker = (*Worker)(nil)

// Touch updates the worker's idle timer. Called whenever a turn arrives.
func (w *Worker) Touch() {
	w.mu.Lock()
	w.lastSeen = time.Now()
	w.mu.Unlock()
}

// idleSince reports the elapsed idle duration without taking ownership.
func (w *Worker) idleSince() time.Duration {
	w.mu.Lock()
	defer w.mu.Unlock()
	return time.Since(w.lastSeen)
}

// Claim is true if the worker was idle and now belongs to the caller — the
// caller MUST call Release() when its turn is done (success or error). False
// means another turn is already running; the orchestrator converts that into a
// conversation-busy error (409).
func (w *Worker) Claim() bool {
	w.mu.Lock()
	defer w.mu.Unlock()
	if w.inFlight {
		return false
	}
	w.inFlight = true
	return true
}

// Release marks the worker idle again.
func (w *Worker) Release() {
	w.mu.Lock()
	w.inFlight = false
	w.mu.Unlock()
}

// PostMessage queues a turn on the worker's opencode session. resumeToken
// (ADR-048) is the opaque checkpoint from a prior turn that handed off on
// shutdown; empty on a normal cold start. It is forwarded verbatim to opencode,
// never parsed by the manager.
func (w *Worker) PostMessage(ctx context.Context, system, prompt, resumeToken string) error {
	return PostMessage(ctx, w.baseURL, w.bearerToken, w.openCodeSessionID, system, prompt, resumeToken)
}

// NotifyShutdownImminent posts a shutdown-imminent notice to this worker's
// opencode control API (ADR-048), asking it to checkpoint the in-flight turn and
// emit a terminal `handoff` frame before the process-group kill. deadline is the
// absolute instant the worker must checkpoint before.
func (w *Worker) NotifyShutdownImminent(ctx context.Context, deadline time.Time) error {
	return NotifyShutdownImminent(ctx, w.baseURL, w.bearerToken, w.openCodeSessionID, deadline)
}

// isInFlight reports whether a turn currently owns this worker (Claimed but not
// yet Released). The shutdown-handoff step waits on this clearing so the
// in-flight turn's StreamEvents can forward the terminal `handoff` frame to the
// control plane before the drain kills the process group (ADR-048).
func (w *Worker) isInFlight() bool {
	w.mu.Lock()
	defer w.mu.Unlock()
	return w.inFlight
}

// StreamEvents tails the worker's /event stream and forwards this session's
// events as ndjson into the sink until a terminal event lands or ctx is
// cancelled.
func (w *Worker) StreamEvents(ctx context.Context, sink app.ChatSink) error {
	return StreamSession(ctx, w.baseURL, w.bearerToken, w.openCodeSessionID, sink, sink.Flush)
}

// sensitiveEnvPattern matches env names that must never reach a worker. The JS
// manager listed these by name; the Go version mirrors that policy and extends
// it with two suffix classes so arbitrary provider keys inherited from a
// local-dev .env (OPENAI_API_KEY, ANTHROPIC_API_KEY, GROQ_API_KEY,
// API_TOKEN_JWT_SECRET, ...) cannot reach a per-conversation OpenCode
// subprocess. The worker still receives its own llmVirtualKey + langwatch API
// key via Credentials.* — those are written into the env explicitly after this
// filter, so blocking the inherited variants is the desired posture (only the
// per-project Langy VK reaches the model, never the human's personal provider
// key).
//
// This stays a DENYLIST for compatibility. ACKNOWLEDGED SUFFIX-GAP (ADR-047,
// left as a comment ONLY — not widened in this PR): a denylist can never be
// exhaustive; a var like `MY_APIKEY` (no separator before KEY) or a novel
// secret prefix slips through. A true ALLOWLIST (PATH, HOME, LANG, USER, TZ +
// the OTEL_/LANGY_/OPENCODE_ vars actually needed) is the more secure
// long-term shape but requires testing every var an OpenCode subprocess might
// legitimately read. Add new prefixes here when introducing manager-only
// secrets; the allowlist migration is tracked separately.
var sensitiveEnvPattern = regexp.MustCompile(
	`^(LANGY_INTERNAL_SECRET$|GITHUB_LANGY_|CREDENTIALS_SECRET$|NEXTAUTH_|DATABASE_URL$|AWS_SECRET_|LW_GATEWAY_|LW_VIRTUAL_KEY_)` +
		// `AWS_ACCESS_KEY_ID` ends in `_ID`, NOT `_KEY` — the suffix rules below
		// would miss it. Anchor an explicit literal so the access-key half of an
		// AWS credential pair can't leak.
		`|^AWS_ACCESS_KEY_ID$` +
		`|_(API_)?KEY$` +
		`|_SECRET(_|$)` +
		// `_TOKEN(_|$)` catches `GH_TOKEN`, `GITHUB_TOKEN`, `API_TOKEN_*`, etc. —
		// the worker still receives an explicit `GH_TOKEN=` from spawnOpenCode
		// AFTER this filter, so blocking the inherited variant is correct (it
		// would shadow the per-conversation creds otherwise). `_PASSWORD(_|$)`
		// catches `POSTGRES_PASSWORD`/`REDIS_PASSWORD` and anything else an
		// `envFrom: secretRef` mounts under that convention.
		`|_TOKEN(_|$)` +
		`|_PASSWORD(_|$)` +
		// `_URL$` / `_URI$` block credential-bearing connection strings
		// (`REDIS_URL=redis://user:pass@host:6379/0`, `POSTGRES_URL`,
		// `MONGODB_URI`, `CLICKHOUSE_URL`, ...). The worker runs model-driven
		// shell with HTTPS egress, so a prompt-injected turn could otherwise
		// `env | grep -iE 'redis|postgres'` and exfiltrate the password embedded
		// in the URL userinfo. `_DSN$` covers `SENTRY_DSN` and similar telemetry
		// creds (DSNs embed the project key in the URL).
		`|_URL$` +
		`|_URI$` +
		`|_DSN$`,
)

// filterSensitiveEnv returns the process env minus anything matching
// sensitiveEnvPattern. The worker gets its own credentials injected explicitly
// after this filter.
func filterSensitiveEnv() []string {
	env := os.Environ()
	out := make([]string, 0, len(env))
	for _, kv := range env {
		eq := strings.IndexByte(kv, '=')
		if eq < 0 {
			continue
		}
		if sensitiveEnvPattern.MatchString(kv[:eq]) {
			continue
		}
		out = append(out, kv)
	}
	return out
}

// openCodeSkillsDir is the directory opencode scans for a worker's skills:
// $HOME/.config/opencode/skills. Each <name>/SKILL.md beneath it is discovered
// at startup and exposed to the model as an invokable skill. Kept as one helper
// so the spawn path and its test agree on exactly where skills must land.
func openCodeSkillsDir(workerHome string) string {
	return filepath.Join(workerHome, ".config", "opencode", "skills")
}

// maybeChown chowns path to uid unless per-worker UID isolation is disabled, in
// which case it is a no-op (returns nil). Isolation is only ever disabled in
// local dev (LANGY_UNSAFE_DEV_DISABLE_ISOLATION; LoadConfig refuses it in
// production), where the manager is unprivileged and os.Chown would fail EPERM.
func maybeChown(path string, uid uint32, disableIsolation bool) error {
	if disableIsolation {
		return nil
	}
	return os.Chown(path, int(uid), int(uid))
}

// maybeLchown is maybeChown for symlinks (chowns the link itself, not its
// target). No-op when isolation is disabled.
func maybeLchown(path string, uid uint32, disableIsolation bool) error {
	if disableIsolation {
		return nil
	}
	return os.Lchown(path, int(uid), int(uid))
}

// setupWorkerHome creates a per-worker home dir with its own opencode config, a
// substituted AGENTS.md, and a symlink to the shared skills/ under workspaceRoot.
// Every file is chown'd to the per-conversation UID and chmod'd 0700/0600 BEFORE
// any credential material lands, so a sibling worker (running as a different UID)
// can never open(2) this worker's files even with knowledge of the path.
// Requires CAP_CHOWN + CAP_DAC_OVERRIDE.
//
// When disableIsolation is set (LANGY_UNSAFE_DEV_DISABLE_ISOLATION, local dev
// only — LoadConfig refuses it in production) the chowns are skipped so the
// unprivileged manager can create these files as its own user; the chmods stay
// (chmod on files you own needs no privilege). Sibling isolation is gone in that
// mode — acceptable ONLY on a single-tenant dev box.
func setupWorkerHome(workerHome, workspaceRoot string, creds domain.Credentials, uid uint32, otelPluginVersion, agentsTemplate string, disableIsolation bool) error {
	// Lock down the worker's home BEFORE writing anything sensitive.
	if err := maybeChown(workerHome, uid, disableIsolation); err != nil {
		return fmt.Errorf("chown home: %w", err)
	}
	if err := os.Chmod(workerHome, 0o700); err != nil {
		return fmt.Errorf("chmod home: %w", err)
	}

	// Per-worker tmp dir. Without this, npm/git/opencode scratch lands in the
	// shared pod /tmp (world-writable, readable by all worker UIDs). Setting
	// TMPDIR to a 0700 subdirectory of the worker home puts the same
	// UID-enforced boundary on scratch files as on config.json.
	tmpDir := filepath.Join(workerHome, "tmp")
	if err := os.MkdirAll(tmpDir, 0o700); err != nil {
		return fmt.Errorf("mkdir tmp: %w", err)
	}
	if err := maybeChown(tmpDir, uid, disableIsolation); err != nil {
		return fmt.Errorf("chown tmp: %w", err)
	}

	configDir := filepath.Join(workerHome, ".config", "opencode")
	if err := os.MkdirAll(configDir, 0o700); err != nil {
		return fmt.Errorf("mkdir config: %w", err)
	}
	// MkdirAll inherits the manager's UID (root). chown every newly created
	// intermediate so the worker UID owns the whole chain — anything left owned
	// by root with mode 0700 would EACCES the worker on traversal.
	for _, dir := range []string{
		filepath.Join(workerHome, ".config"),
		configDir,
	} {
		if err := maybeChown(dir, uid, disableIsolation); err != nil {
			return fmt.Errorf("chown %s: %w", dir, err)
		}
		if err := os.Chmod(dir, 0o700); err != nil {
			return fmt.Errorf("chmod %s: %w", dir, err)
		}
	}

	model := creds.Model
	if model == "" {
		model = "openai/gpt-5-mini"
	}

	plugin := fmt.Sprintf("@devtheops/opencode-plugin-otel@%s", otelPluginVersion)

	// No "mcp" block. The worker reaches LangWatch through the `langwatch` CLI
	// and nothing else — that is the transport every skill is written against
	// (each skill's frontmatter says so outright: "the `langwatch` CLI is the
	// only interface"). Attaching the MCP server as a second transport injected
	// its whole tool-schema set into EVERY turn's context for capability the CLI
	// already has. The worker's credentials reach the CLI through the process env
	// (see buildWorkerEnv), not through a server config block.
	//
	// This is about what the AGENT consumes. The MCP server package itself is
	// untouched — it remains the customer-facing surface for Claude Desktop /
	// Cursor.
	config := map[string]any{
		"$schema": "https://opencode.ai/config.json",
		"model":   model,
		"plugin":  []string{plugin},
	}

	configPath := filepath.Join(configDir, "config.json")
	configBytes, err := json.MarshalIndent(config, "", "  ")
	if err != nil {
		return fmt.Errorf("marshal config: %w", err)
	}
	if err := os.WriteFile(configPath, configBytes, 0o600); err != nil {
		return fmt.Errorf("write config: %w", err)
	}
	// WriteFile keeps ownership at the writing process (root). Explicit chown is
	// what makes "only the worker UID" literal — without it, the manager (root)
	// could still read the plaintext API key.
	if err := maybeChown(configPath, uid, disableIsolation); err != nil {
		return fmt.Errorf("chown config: %w", err)
	}

	// Per-worker AGENTS.md with ${LANGWATCH_ENDPOINT} substituted. The shared
	// /workspace/AGENTS.md keeps the literal placeholder; we resolve it here so
	// each worker emits concrete URLs in its replies. The template bytes are read
	// once at Pool.New and cached — only the per-worker ReplaceAll happens here,
	// so a spawn no longer touches disk for AGENTS.md.
	if agentsTemplate == "" {
		return fmt.Errorf("shared AGENTS.md unavailable (not readable at startup)")
	}
	rendered := strings.ReplaceAll(agentsTemplate, "${LANGWATCH_ENDPOINT}", creds.LangwatchEndpoint)
	agentsPath := filepath.Join(workerHome, "AGENTS.md")
	if err := os.WriteFile(agentsPath, []byte(rendered), 0o600); err != nil {
		return fmt.Errorf("write AGENTS.md: %w", err)
	}
	if err := maybeChown(agentsPath, uid, disableIsolation); err != nil {
		return fmt.Errorf("chown AGENTS.md: %w", err)
	}

	// Symlink opencode's skills directory to the shared template directory.
	// opencode discovers global skills under $HOME/.config/opencode/skills,
	// where each <name>/SKILL.md is exposed to the model as an invokable skill —
	// so the link MUST land there, not at $HOME/skills (which opencode never
	// scans). The shared dir is root-owned and world-readable (see
	// entrypoint.sh), so workers following the link can READ but not mutate it.
	skillsLink := openCodeSkillsDir(workerHome)
	if err := os.Symlink(filepath.Join(workspaceRoot, "skills"), skillsLink); err != nil && !errors.Is(err, os.ErrExist) {
		return fmt.Errorf("symlink skills: %w", err)
	}
	// lchown the symlink itself; target permissions are what actually gate reads
	// but lchowning prevents another UID from tampering with the link.
	_ = maybeLchown(skillsLink, uid, disableIsolation)

	return nil
}

// buildWorkerEnv assembles the environment for a worker's opencode subprocess:
// the filtered inherited env plus per-worker credentials and the per-worker
// OPENCODE_SERVER_PASSWORD. Pure and side-effect free — factored out of
// spawnOpenCode so it's unit-testable without spawning a real subprocess.
//
// egressPort is the loopback port of THIS worker's egress adapter (ADR-043),
// 0 when the guard runs no proxy. When set, it is injected as HTTPS_PROXY/
// HTTP_PROXY so the worker's tools (`gh`, `git`, `npm`, `curl`, `pip`) egress
// THROUGH the adapter, which enforces the require-TLS / throttle / allow-list /
// FQDN-floor rungs. The in-cluster control-plane + gateway hosts and loopback
// are put in NO_PROXY so the `langwatch` CLI's LangWatch-API calls and opencode's
// LLM traffic go direct (they have their own explicit NetworkPolicy egress
// rules; routing them through the per-worker proxy would add a hop and expose
// LLM streaming to the throttle).
func buildWorkerEnv(conversationID, workerHome string, creds domain.Credentials, openCodePassword string, egressPort int) []string {
	env := filterSensitiveEnv()
	env = append(env,
		"HOME="+workerHome,
		"TMPDIR="+filepath.Join(workerHome, "tmp"),
		"OPENAI_BASE_URL="+creds.GatewayBaseURL,
		"OPENAI_API_KEY="+creds.LLMVirtualKey,
		"LANGWATCH_API_KEY="+creds.LangwatchAPIKey,
		"LANGWATCH_ENDPOINT="+creds.LangwatchEndpoint,
		// OpenCode OTel plugin: opencode auto-loads it by name; the plugin reads
		// OPENCODE_OTLP_* and exports gen_ai.usage.* spans into the user's
		// LangWatch project. The OTel endpoint appends /v1/traces so we hand it
		// the /api/otel base.
		"OPENCODE_ENABLE_TELEMETRY=1",
		"OPENCODE_OTLP_ENDPOINT="+strings.TrimRight(creds.LangwatchEndpoint, "/")+"/api/otel",
		"OPENCODE_OTLP_PROTOCOL=http/protobuf",
		"OPENCODE_OTLP_HEADERS=Authorization=Bearer "+creds.LangwatchAPIKey,
		"OPENCODE_RESOURCE_ATTRIBUTES=tag.tags=langy,service.name=langyagent,langwatch.thread.id="+conversationID,
		// Requires opencode's HTTP control server to authenticate with HTTP
		// Basic (user "opencode", this password) instead of serving every
		// request unauthenticated. This is the sibling-isolation guarantee
		// (ADR-033 Fix A′): env-injected, not a CLI flag, so it never lands in
		// the world-readable /proc/<pid>/cmdline — only in /proc/<pid>/environ,
		// which is 0400 and UID-gated.
		"OPENCODE_SERVER_PASSWORD="+openCodePassword,
	)
	if creds.GithubToken != "" {
		env = append(env,
			"GH_TOKEN="+creds.GithubToken,
			"GITHUB_LOGIN="+creds.GithubLogin,
		)
	}
	if egressPort > 0 {
		proxyURL := fmt.Sprintf("http://127.0.0.1:%d", egressPort)
		noProxy := noProxyHosts(creds)
		env = append(env,
			// Lower- and upper-case both: `gh`/`git`/`curl` read the lower-case
			// forms, some Go/Node tooling the upper-case ones.
			"HTTPS_PROXY="+proxyURL,
			"https_proxy="+proxyURL,
			"HTTP_PROXY="+proxyURL,
			"http_proxy="+proxyURL,
			"NO_PROXY="+noProxy,
			"no_proxy="+noProxy,
		)
	}
	return env
}

// noProxyHosts is the NO_PROXY list for a worker: loopback plus the in-cluster
// control-plane and gateway hosts, which egress via their own explicit
// NetworkPolicy rules and must NOT be funnelled through the per-worker egress
// adapter (ADR-043: "loopback and the in-cluster control-plane/gateway paths
// are unaffected").
func noProxyHosts(creds domain.Credentials) string {
	hosts := []string{"127.0.0.1", "localhost", "::1"}
	seen := map[string]struct{}{"127.0.0.1": {}, "localhost": {}, "::1": {}}
	for _, raw := range []string{creds.LangwatchEndpoint, creds.GatewayBaseURL} {
		h := hostFromURL(raw)
		if h == "" {
			continue
		}
		if _, dup := seen[h]; dup {
			continue
		}
		seen[h] = struct{}{}
		hosts = append(hosts, h)
	}
	return strings.Join(hosts, ",")
}

// hostFromURL extracts the bare hostname from a URL, tolerating a value with no
// scheme. Returns "" when nothing host-like can be parsed.
func hostFromURL(raw string) string {
	raw = strings.TrimSpace(raw)
	if raw == "" {
		return ""
	}
	if !strings.Contains(raw, "://") {
		raw = "//" + raw
	}
	u, err := url.Parse(raw)
	if err != nil {
		return ""
	}
	return u.Hostname()
}

// workerSysProcAttr builds the SysProcAttr for the opencode subprocess. Normally
// it drops the child into the per-conversation UID via a setuid Credential (with
// an explicit empty supplementary-group set) so a sibling worker's files are
// unreachable at the kernel level. When disableIsolation is set (local dev only —
// LoadConfig refuses it in production), it omits the Credential so opencode runs
// as the manager's own (unprivileged) user, since a non-root manager cannot
// setuid. Setpgid is kept in BOTH modes so opencode + its shelled children share
// one process group the manager can signal as a unit on shutdown.
func workerSysProcAttr(uid uint32, disableIsolation bool) *syscall.SysProcAttr {
	if disableIsolation {
		return &syscall.SysProcAttr{Setpgid: true}
	}
	return &syscall.SysProcAttr{
		Credential: &syscall.Credential{
			Uid: uid,
			Gid: uid,
			// Explicit empty Groups forces setgroups([]) on exec — without this,
			// the child inherits root's supplementary groups (the manager runs
			// as root). Combined with the unique per-conv UID, the worker now
			// belongs to exactly one identity at the kernel level, no shared
			// group footing from the manager process.
			Groups: []uint32{},
		},
		// Setpgid puts opencode in its own process group so a SIGTERM to the
		// manager doesn't tear down the worker before we've gracefully reaped
		// it; we send the explicit signal during shutdown.
		Setpgid: true,
	}
}

// spawnOpenCode starts the opencode subprocess with the per-worker env and
// drops into the per-conversation UID before exec (unless disableIsolation is
// set — local dev only, see workerSysProcAttr). Combined with mode 0700 on
// workerHome and mode 0600 on config.json, the UID handoff makes a sibling
// worker's files unreachable to this process at the kernel level — open(2)
// returns EACCES regardless of how the path is constructed.
//
// ctx is the POOL-LIFETIME context (not a single request's): the worker
// outlives the turn that spawned it and only dies on idle/shutdown, but binding
// to the pool context (rather than context.Background as the flat version did)
// means a pool Shutdown / deadline still propagates to the subprocess.
func spawnOpenCode(
	ctx context.Context,
	openCodeBinaryPath string,
	conversationID, workerHome string,
	uid uint32,
	port int,
	creds domain.Credentials,
	openCodePassword string,
	egressPort int,
	disableIsolation bool,
) (*exec.Cmd, error) {
	cmd := exec.CommandContext(ctx, openCodeBinaryPath,
		"serve", "--port", strconv.Itoa(port), "--hostname", "127.0.0.1",
	)
	cmd.Env = buildWorkerEnv(conversationID, workerHome, creds, openCodePassword, egressPort)
	cmd.Dir = workerHome
	// Discard opencode's stdout/stderr. opencode emits LLM completions, tool
	// outputs (env dumps, file contents), and the raw user prompt — all of which
	// are the highest-density PII/secret surface in the worker. The OpenCode
	// OTel plugin already exports structured spans (gen_ai.usage, tool spans)
	// into the user's LangWatch project — that's the auditable telemetry
	// channel. Pod stdout/stderr lands in cluster log storage with no
	// per-conversation TTL and no redaction, so piping the same bytes there
	// would re-leak everything OTel already structures.
	cmd.Stdout = io.Discard
	cmd.Stderr = io.Discard
	cmd.SysProcAttr = workerSysProcAttr(uid, disableIsolation)
	if err := cmd.Start(); err != nil {
		return nil, fmt.Errorf("start opencode: %w", err)
	}
	return cmd, nil
}

// tombstoneWorkerHome atomically renames the per-worker home to a unique sibling
// path under sessionsRoot and returns that path for out-of-lock deletion. The
// rename is metadata-only (same directory) so it completes in microseconds while
// the pool lock is held; the caller then os.RemoveAll(tombstone) OUTSIDE the
// lock, off the pool-wide hot path (every Acquire/kill/reap/Status blocks on the
// lock, so the old in-lock tree-walk unlink stalled them all).
//
// Renaming — not deleting — under the lock still frees the canonical home path
// atomically, so the replacement-race invariant holds: a concurrent Acquire that
// creates a fresh home at the canonical path can't collide with our teardown,
// and the uniquely-named tombstone can't be clobbered by (or clobber) a new
// worker. The config.json inside holds the plaintext LangWatch API key and
// ${HOME}/work holds cloned repos, so the caller MUST delete the returned
// tombstone — nothing sensitive may linger on the pod volume.
//
// Returns "" (nothing to delete) when conversationID is invalid, the resolved
// path escapes SESSIONS_ROOT, the home is already gone, or the rename fails.
func tombstoneWorkerHome(ctx context.Context, sessionsRoot, conversationID string) string {
	if !domain.IsValidConversationID(conversationID) {
		return ""
	}
	workerHome := filepath.Join(sessionsRoot, conversationID)
	resolvedRoot, err := filepath.Abs(sessionsRoot)
	if err != nil {
		return ""
	}
	resolvedHome, err := filepath.Abs(workerHome)
	if err != nil {
		return ""
	}
	if !strings.HasPrefix(resolvedHome, resolvedRoot+string(filepath.Separator)) {
		return ""
	}
	// A leading dot + ".dead-<nanos>" suffix keeps the tombstone OUT of the
	// conversationID namespace (IsValidConversationID rejects dots), so it can
	// never collide with a live worker home or a future spawn's canonical path.
	tombstone := filepath.Join(sessionsRoot, fmt.Sprintf(".%s.dead-%d", conversationID, time.Now().UnixNano()))
	if err := os.Rename(workerHome, tombstone); err != nil {
		if !os.IsNotExist(err) {
			clog.Get(ctx).Warn("tombstone worker home failed",
				zap.String("conversation", conversationID),
				zap.Error(err),
			)
		}
		return ""
	}
	return tombstone
}
