"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.DubbingListRequestDubbingModelsItem = void 0;
exports.DubbingListRequestDubbingModelsItem = {
    DubbingV1: "dubbing_v1",
    DubbingV2: "dubbing_v2",
};
