"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.AudioNativeCreateRequestApplyTextNormalization = void 0;
exports.AudioNativeCreateRequestApplyTextNormalization = {
    Auto: "auto",
    On: "on",
    Off: "off",
    ApplyEnglish: "apply_english",
};
