version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/langwatch"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 50

  - package-ecosystem: "npm"
    directory: "/typescript-sdk"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 50

  - package-ecosystem: "npm"
    directory: "/mcp-server"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 50

  - package-ecosystem: "uv"
    directory: "/python-sdk"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 50

  - package-ecosystem: "uv"
    directory: "/langwatch_nlp"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 50

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 50

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 50
