/**
 * Framework default templates, extracted from the previously hardcoded
 * trigger email/Slack output so existing triggers (all template columns NULL)
 * render exactly as before. A NULL template column means "render with these".
 */

export const DEFAULT_EMAIL_SUBJECT_TEMPLATE =
  "{% if trigger.alertType %}({{ trigger.alertType }}) {% endif %}Trigger - {{ trigger.name }}";

export const DEFAULT_EMAIL_BODY_TEMPLATE = `# {% if trigger.alertType %}({{ trigger.alertType }}) {% endif %}LangWatch Trigger

### {{ trigger.name }}

This is an automated email generated by your configured triggers. Below, you will find the messages that initiated this action.
{% if trigger.message %}
{{ trigger.message }}
{% endif %}
{% for m in matches %}
- [{% if m.trace.id %}{{ m.trace.id }}{% else %}View{% endif %}]({{ m.trace.url }})
{% endfor %}`;

export const DEFAULT_SLACK_TEMPLATE = `{% if trigger.alertType == 'INFO' %}:information_source:{% elsif trigger.alertType == 'WARNING' %}:warning:{% elsif trigger.alertType == 'CRITICAL' %}:red_circle:{% else %}:bell:{% endif %} LangWatch Trigger - *{{ trigger.name }}*
{% if trigger.message %}
*Msg:* {{ trigger.message }}
{% endif %}
{% for m in matches %}
<{{ m.trace.url }}|{% if m.trace.id %}{{ m.trace.id }}{% else %}View{% endif %}>
{% endfor %}`;

/**
 * Block Kit starter — a valid Block Kit JSON document with Liquid variables
 * inside string values. Authors edit this as JSON and Liquid renders before
 * `JSON.parse` in `renderSlack`, so variables expand into the final blocks.
 */
export const DEFAULT_SLACK_BLOCK_KIT_TEMPLATE = `[
  {
    "type": "header",
    "text": {
      "type": "plain_text",
      "text": "{% if trigger.alertType %}({{ trigger.alertType }}) {% endif %}{{ trigger.name }}"
    }
  },
  {% if trigger.message %}
  {
    "type": "section",
    "text": { "type": "mrkdwn", "text": {{ trigger.message | json }} }
  },
  {
    "type": "divider"
  },
  {% endif %}
  {
    "type": "section",
    "text": {
      "type": "mrkdwn",
      "text": "{% for m in matches %}<{{ m.trace.url }}|{% if m.trace.id %}{{ m.trace.id }}{% else %}View{% endif %}>{% unless forloop.last %}\\n{% endunless %}{% endfor %}"
    }
  }
]`;
