/**
 * Framework default templates, extracted from the previously hardcoded
 * trigger email/Slack output so existing triggers (all template columns NULL)
 * render exactly as before. A NULL template column means "render with these".
 */

export const DEFAULT_EMAIL_SUBJECT_TEMPLATE =
  "{% if trigger.alertType %}({{ trigger.alertType }}) {% endif %}Trigger - {{ trigger.name }}";

export const DEFAULT_EMAIL_BODY_TEMPLATE = `# {% if trigger.alertType %}({{ trigger.alertType }}) {% endif %}LangWatch Trigger

### {{ trigger.name }}

This is an automated email generated by your configured triggers. Below is the matched trace.
{% if trigger.message %}
{{ trigger.message }}
{% endif %}

- [{% if match.trace.id %}{{ match.trace.id }}{% else %}View{% endif %}]({{ match.trace.url }})`;

export const DEFAULT_SLACK_TEMPLATE = `{% if trigger.alertType == 'INFO' %}ℹ️{% elsif trigger.alertType == 'WARNING' %}⚠️{% elsif trigger.alertType == 'CRITICAL' %}🔴{% else %}🔔{% endif %} LangWatch Trigger - *{{ trigger.name }}*
{% if trigger.message %}
*Msg:* {{ trigger.message }}
{% endif %}
<{{ match.trace.url }}|{% if match.trace.id %}{{ match.trace.id }}{% else %}View{% endif %}>`;

/**
 * Block Kit starter — a valid Block Kit JSON document with Liquid variables
 * inside string values. Authors edit this as JSON and Liquid renders before
 * `JSON.parse` in `renderSlack`, so variables expand into the final blocks.
 */
export const DEFAULT_SLACK_BLOCK_KIT_TEMPLATE = `[
  {
    "type": "header",
    "text": {
      "type": "plain_text",
      "text": "{% if trigger.alertType %}({{ trigger.alertType }}) {% endif %}{{ trigger.name }}"
    }
  },
  {% if trigger.message %}
  {
    "type": "section",
    "text": { "type": "mrkdwn", "text": {{ trigger.message | json }} }
  },
  {
    "type": "divider"
  },
  {% endif %}
  {
    "type": "section",
    "text": {
      "type": "mrkdwn",
      "text": "<{{ match.trace.url }}|{% if match.trace.id %}{{ match.trace.id }}{% else %}View{% endif %}>"
    }
  }
]`;
