/**
 * Framework default templates, extracted from the previously hardcoded
 * trigger email/Slack output so existing triggers (all template columns NULL)
 * render as close to the legacy output as practical. A NULL template column
 * means "render with these".
 *
 * Parity choices vs. the previous hardcoded senders:
 * - Cap at 10 matches via `limit:10`, mirroring `triggerData.slice(0, 10)`
 *   in both senders.
 * - Use `m.trace.label` (computed in `templateContext.ts`) so the link text
 *   becomes "View Graph" for custom-graph matches and `traceId`/"View" for
 *   regular trace matches.
 * - Skip the empty `{{ trigger.message }}` paragraph by gating on the
 *   `trigger.message` truthiness check that already wraps the block.
 *
 * Intentionally NOT preserved (operators can opt back in via a custom
 * template): the Slack sender's per-trace input/output dump and event-metric
 * unrolling. Those depend on a `trace.events` shape that the variable
 * contract doesn't (yet) expose, and the legacy output is verbose and
 * Slack-formatting-specific. The simpler default reads better in practice.
 */

export const DEFAULT_EMAIL_SUBJECT_TEMPLATE =
  "{% if trigger.alertType %}({{ trigger.alertType }}) {% endif %}Trigger - {{ trigger.name }}";

export const DEFAULT_EMAIL_BODY_TEMPLATE = `# {% if trigger.alertType %}({{ trigger.alertType }}) {% endif %}LangWatch Trigger

### {{ trigger.name }}

This is an automated email generated by your configured triggers. Below, you will find the messages that initiated this action.
{% if trigger.message %}

{{ trigger.message }}
{% endif %}
{% for m in matches limit:10 %}
- [{{ m.trace.label }}]({{ m.trace.url }})
{% endfor %}`;

export const DEFAULT_SLACK_TEMPLATE = `{% if trigger.alertType == 'INFO' %}:information_source:{% elsif trigger.alertType == 'WARNING' %}:warning:{% elsif trigger.alertType == 'CRITICAL' %}:red_circle:{% else %}:bell:{% endif %} LangWatch Trigger - *{{ trigger.name }}*
{% if trigger.message %}
*Msg:* {{ trigger.message }}
{% endif %}
{% for m in matches limit:10 %}
<{{ m.trace.url }}|{{ m.trace.label }}>
{% endfor %}`;
