"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.MockNoMatchBehavior = void 0;
exports.MockNoMatchBehavior = {
    CallRealTool: "call_real_tool",
    RaiseError: "raise_error",
};
