# Test environment with isolated ports
# Does not conflict with local development (compose.yml)
#
# Usage:
#   docker compose -f compose.test.yml up -d
#   cd agentic-e2e-tests && pnpm test
#   docker compose -f compose.test.yml down

services:
  app:
    image: langwatch/langwatch:latest
    environment:
      SKIP_ENV_VALIDATION: true
      DISABLE_PII_REDACTION: true
      DATABASE_URL: postgresql://prisma:prisma@postgres:5432/testdb?schema=testdb
      ELASTICSEARCH_NODE_URL: http://opensearch:9200
      IS_OPENSEARCH: true
      REDIS_URL: redis://redis:6379
      LANGWATCH_NLP_SERVICE: http://langwatch_nlp:5561
      LANGEVALS_ENDPOINT: http://langevals:5562
      INSTALL_METHOD: docker-test
      NODE_ENV: test
      NEXTAUTH_SECRET: test-secret-for-e2e-testing
      NEXTAUTH_URL: http://localhost:5561
      API_TOKEN_JWT_SECRET: test-jwt-secret-for-e2e
    ports:
      - "5561:5560"  # Test port (dev uses 5560)
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      opensearch:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5560/api/health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  langwatch_nlp:
    image: langwatch/langwatch_nlp:latest
    ports:
      - "5563:5561"  # Test port (dev uses 5561)
    restart: always
    environment:
      - LANGWATCH_ENDPOINT=http://app:5560

  langevals:
    image: langwatch/langevals:latest
    ports:
      - "5564:5562"  # Test port (dev uses 5562)
    restart: always
    environment:
      - DISABLE_EVALUATORS_PRELOAD=true

  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    ports:
      - "5433:5432"  # Test port (dev uses 5432)
    volumes:
      - test-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U prisma -d testdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    ports:
      - "6380:6379"  # Test port (dev uses 6379)
    volumes:
      - test-redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  opensearch:
    image: langwatch/opensearch-lite:latest
    environment:
      - discovery.type=single-node
      - DISABLE_SECURITY_PLUGIN=true
      - "OPENSEARCH_JAVA_OPTS=-Xms256m -Xmx256m"
      - "cluster.routing.allocation.disk.threshold_enabled=false"
      - "bootstrap.memory_lock=false"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=test-password-for-e2e
      - "node.store.allow_mmap=false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9201:9200"  # Test port (dev uses 9200)
      - "9601:9600"
    volumes:
      - test-opensearch-data:/usr/share/opensearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200 || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 256m
          cpus: "1.0"
    restart: always

volumes:
  test-db-data:
  test-redis-data:
  test-opensearch-data:
