import type { PyMember, PyModule } from "./python-api.types";

const fn = (name: string, signature: string, doc: string): PyMember => ({
  name,
  kind: "function",
  signature,
  doc,
});

const cls = (name: string, signature: string, doc: string): PyMember => ({
  name,
  kind: "class",
  signature,
  doc,
});

const con = (name: string, doc: string): PyMember => ({
  name,
  kind: "constant",
  doc,
});

/**
 * Subset of Python stdlib modules that are commonly used inside workflow code
 * nodes. Each lists the most frequently accessed top-level members so
 * `module.<member>` autocomplete is useful without the bundle exploding.
 */
export const PYTHON_STDLIB_MODULES: PyModule[] = [
  {
    name: "math",
    doc: "Mathematical functions.",
    members: [
      fn("ceil", "ceil(x)", "Smallest int >= x."),
      fn("floor", "floor(x)", "Largest int <= x."),
      fn("sqrt", "sqrt(x)", "Square root of x."),
      fn("log", "log(x, base=e)", "Logarithm of x."),
      fn("log2", "log2(x)", "Base-2 log of x."),
      fn("log10", "log10(x)", "Base-10 log of x."),
      fn("exp", "exp(x)", "e**x."),
      fn("pow", "pow(x, y)", "x**y."),
      fn("sin", "sin(x)", "Sine of x (radians)."),
      fn("cos", "cos(x)", "Cosine of x (radians)."),
      fn("tan", "tan(x)", "Tangent of x (radians)."),
      fn("atan2", "atan2(y, x)", "arctan(y/x), full quadrant."),
      fn("isnan", "isnan(x)", "True if x is NaN."),
      fn("isinf", "isinf(x)", "True if x is infinite."),
      fn(
        "isclose",
        "isclose(a, b, *, rel_tol=1e-9, abs_tol=0.0)",
        "Approximate equality.",
      ),
      fn("gcd", "gcd(*integers)", "Greatest common divisor."),
      fn("lcm", "lcm(*integers)", "Least common multiple."),
      con("pi", "Mathematical constant π."),
      con("e", "Mathematical constant e."),
      con("inf", "Floating-point infinity."),
      con("nan", "Floating-point NaN."),
      con("tau", "Mathematical constant τ (2π)."),
    ],
  },
  {
    name: "json",
    doc: "JSON encoder and decoder.",
    members: [
      fn(
        "dumps",
        "dumps(obj, *, indent=None, sort_keys=False, default=None)",
        "Serialize to JSON string.",
      ),
      fn("loads", "loads(s)", "Parse JSON string."),
      fn("dump", "dump(obj, fp, *, indent=None)", "Serialize to file."),
      fn("load", "load(fp)", "Parse JSON from file."),
      cls(
        "JSONDecodeError",
        "JSONDecodeError(msg, doc, pos)",
        "Raised on parse failure.",
      ),
    ],
  },
  {
    name: "re",
    doc: "Regular expressions.",
    members: [
      fn("match", "match(pattern, string, flags=0)", "Match at the start of string."),
      fn("search", "search(pattern, string, flags=0)", "Find first match anywhere."),
      fn("findall", "findall(pattern, string, flags=0)", "All non-overlapping matches."),
      fn("finditer", "finditer(pattern, string, flags=0)", "Iterator over matches."),
      fn("sub", "sub(pattern, repl, string, count=0, flags=0)", "Replace matches."),
      fn(
        "subn",
        "subn(pattern, repl, string, count=0, flags=0)",
        "Replace, return count.",
      ),
      fn("split", "split(pattern, string, maxsplit=0, flags=0)", "Split by pattern."),
      fn("compile", "compile(pattern, flags=0)", "Compile a Pattern object."),
      fn("escape", "escape(pattern)", "Escape regex metacharacters."),
      con("IGNORECASE", "Case-insensitive matching flag."),
      con("MULTILINE", "Multi-line ^/$ matching flag."),
      con("DOTALL", "Dot matches newline flag."),
      con("VERBOSE", "Verbose pattern flag."),
    ],
  },
  {
    name: "datetime",
    doc: "Date and time types.",
    members: [
      cls("datetime", "datetime(year, month, day, ...)", "Date + time + tz."),
      cls("date", "date(year, month, day)", "Calendar date."),
      cls("time", "time(hour=0, minute=0, second=0, ...)", "Time of day."),
      cls("timedelta", "timedelta(days=0, seconds=0, ...)", "Time interval."),
      cls("timezone", "timezone(offset)", "Fixed-offset timezone."),
    ],
  },
  {
    name: "os",
    doc: "Operating system interfaces (sandbox-restricted).",
    members: [
      fn("getcwd", "getcwd()", "Current working directory."),
      fn("getenv", "getenv(key, default=None)", "Read env var."),
      fn("listdir", "listdir(path='.')", "List directory entries."),
      con("environ", "Mapping of env vars."),
      con("path", "Submodule with path manipulation utilities."),
      con("sep", "Path separator for the platform."),
      con("linesep", "Line separator for the platform."),
    ],
  },
  {
    name: "sys",
    doc: "System-specific parameters.",
    members: [
      con("argv", "Command-line arguments."),
      con("path", "Module search path."),
      con("platform", "Platform identifier."),
      con("version", "Python version string."),
      con("version_info", "Named tuple with version parts."),
      con("maxsize", "Largest representable size_t."),
      fn("exit", "exit(code=0)", "Exit interpreter."),
    ],
  },
  {
    name: "collections",
    doc: "Specialized container datatypes.",
    members: [
      cls("OrderedDict", "OrderedDict(...)", "Dict that remembers insertion order."),
      cls(
        "defaultdict",
        "defaultdict(default_factory, ...)",
        "Dict with default factory.",
      ),
      cls("Counter", "Counter(iterable=None)", "Count hashable objects."),
      cls("deque", "deque(iterable=(), maxlen=None)", "Double-ended queue."),
      cls("namedtuple", "namedtuple(typename, field_names)", "Named tuple factory."),
      cls("ChainMap", "ChainMap(*maps)", "View of multiple mappings."),
    ],
  },
  {
    name: "itertools",
    doc: "Iterator algebra.",
    members: [
      fn("chain", "chain(*iterables)", "Chain multiple iterables."),
      fn("count", "count(start=0, step=1)", "Infinite counter."),
      fn("cycle", "cycle(iterable)", "Cycle indefinitely."),
      fn("repeat", "repeat(object, times=None)", "Repeat an object."),
      fn(
        "islice",
        "islice(iterable, stop) | islice(iterable, start, stop, step)",
        "Slice an iterator.",
      ),
      fn("groupby", "groupby(iterable, key=None)", "Group consecutive equal items."),
      fn("product", "product(*iterables, repeat=1)", "Cartesian product."),
      fn("permutations", "permutations(iterable, r=None)", "Permutations."),
      fn("combinations", "combinations(iterable, r)", "Combinations."),
      fn(
        "combinations_with_replacement",
        "combinations_with_replacement(iterable, r)",
        "With replacement.",
      ),
      fn(
        "accumulate",
        "accumulate(iterable, func=operator.add, *, initial=None)",
        "Running totals.",
      ),
      fn("compress", "compress(data, selectors)", "Filter by selector iterable."),
      fn("dropwhile", "dropwhile(predicate, iterable)", "Drop while true."),
      fn("takewhile", "takewhile(predicate, iterable)", "Take while true."),
      fn("starmap", "starmap(function, iterable)", "Map with unpacked args."),
      fn("tee", "tee(iterable, n=2)", "Split iterator into n."),
      fn(
        "zip_longest",
        "zip_longest(*iterables, fillvalue=None)",
        "Zip filling shorter.",
      ),
    ],
  },
  {
    name: "functools",
    doc: "Higher-order functions and operations on callables.",
    members: [
      fn(
        "reduce",
        "reduce(function, iterable, initializer=...)",
        "Apply function cumulatively.",
      ),
      fn("cache", "@cache", "Unbounded function-result cache."),
      fn(
        "lru_cache",
        "@lru_cache(maxsize=128, typed=False)",
        "Least-recently-used cache.",
      ),
      fn("partial", "partial(func, *args, **kwargs)", "Bind arguments."),
      fn("wraps", "@wraps(wrapped)", "Decorator helper."),
      cls(
        "partialmethod",
        "partialmethod(func, *args, **kwargs)",
        "Method version of partial.",
      ),
    ],
  },
  {
    name: "random",
    doc: "Pseudo-random number generation.",
    members: [
      fn("random", "random()", "Float in [0.0, 1.0)."),
      fn("uniform", "uniform(a, b)", "Float in [a, b]."),
      fn("randint", "randint(a, b)", "Int in [a, b]."),
      fn(
        "randrange",
        "randrange(stop) | randrange(start, stop[, step])",
        "Random range.",
      ),
      fn("choice", "choice(seq)", "Random element of seq."),
      fn("choices", "choices(population, weights=None, *, k=1)", "k random selections."),
      fn("sample", "sample(population, k)", "k unique random elements."),
      fn("shuffle", "shuffle(x)", "Shuffle list in place."),
      fn("seed", "seed(a=None)", "Initialize RNG state."),
      fn("gauss", "gauss(mu=0.0, sigma=1.0)", "Gaussian distribution."),
    ],
  },
  {
    name: "string",
    doc: "Common string operations.",
    members: [
      con("ascii_letters", "All ASCII letters."),
      con("ascii_lowercase", "ASCII lowercase letters."),
      con("ascii_uppercase", "ASCII uppercase letters."),
      con("digits", "Decimal digits 0-9."),
      con("hexdigits", "Hex digits 0-f."),
      con("printable", "All printable ASCII."),
      con("punctuation", "ASCII punctuation."),
      con("whitespace", "ASCII whitespace."),
      cls("Template", "Template(template)", "String template with $name placeholders."),
      cls("Formatter", "Formatter()", "Custom string formatter."),
    ],
  },
  {
    name: "base64",
    doc: "RFC 3548 Base16, Base32, Base64 codecs.",
    members: [
      fn("b64encode", "b64encode(s, altchars=None)", "Standard Base64 encode."),
      fn(
        "b64decode",
        "b64decode(s, altchars=None, validate=False)",
        "Standard Base64 decode.",
      ),
      fn("urlsafe_b64encode", "urlsafe_b64encode(s)", "URL-safe Base64 encode."),
      fn("urlsafe_b64decode", "urlsafe_b64decode(s)", "URL-safe Base64 decode."),
      fn("b32encode", "b32encode(s)", "Base32 encode."),
      fn("b32decode", "b32decode(s, casefold=False, map01=None)", "Base32 decode."),
      fn("b16encode", "b16encode(s)", "Base16 encode."),
      fn("b16decode", "b16decode(s, casefold=False)", "Base16 decode."),
    ],
  },
  {
    name: "hashlib",
    doc: "Secure hash and message digest algorithms.",
    members: [
      fn("md5", "md5(data=b'')", "MD5 hash (legacy use only)."),
      fn("sha1", "sha1(data=b'')", "SHA-1 hash."),
      fn("sha224", "sha224(data=b'')", "SHA-224 hash."),
      fn("sha256", "sha256(data=b'')", "SHA-256 hash."),
      fn("sha384", "sha384(data=b'')", "SHA-384 hash."),
      fn("sha512", "sha512(data=b'')", "SHA-512 hash."),
      fn("blake2b", "blake2b(data=b'', *, digest_size=64)", "BLAKE2b hash."),
      fn("blake2s", "blake2s(data=b'', *, digest_size=32)", "BLAKE2s hash."),
      fn("new", "new(name, data=b'')", "Generic hash constructor."),
    ],
  },
  {
    name: "uuid",
    doc: "UUID objects per RFC 4122.",
    members: [
      fn("uuid1", "uuid1(node=None, clock_seq=None)", "Host/time based UUID."),
      fn("uuid3", "uuid3(namespace, name)", "MD5 namespace UUID."),
      fn("uuid4", "uuid4()", "Random UUID."),
      fn("uuid5", "uuid5(namespace, name)", "SHA-1 namespace UUID."),
      cls("UUID", "UUID(hex=None, ...)", "UUID class."),
    ],
  },
  {
    name: "textwrap",
    doc: "Text wrapping and filling.",
    members: [
      fn("wrap", "wrap(text, width=70)", "Wrap text into lines."),
      fn("fill", "fill(text, width=70)", "Wrap and join with newlines."),
      fn("dedent", "dedent(text)", "Remove common leading whitespace."),
      fn("indent", "indent(text, prefix, predicate=None)", "Prefix every line."),
      fn("shorten", "shorten(text, width, *, placeholder='...')", "Truncate text."),
    ],
  },
  {
    name: "statistics",
    doc: "Mathematical statistics functions.",
    members: [
      fn("mean", "mean(data)", "Arithmetic mean."),
      fn("median", "median(data)", "Median of data."),
      fn("median_low", "median_low(data)", "Low median."),
      fn("median_high", "median_high(data)", "High median."),
      fn("mode", "mode(data)", "Most common value."),
      fn("multimode", "multimode(data)", "All most-common values."),
      fn("stdev", "stdev(data, xbar=None)", "Sample standard deviation."),
      fn("pstdev", "pstdev(data, mu=None)", "Population standard deviation."),
      fn("variance", "variance(data, xbar=None)", "Sample variance."),
      fn("pvariance", "pvariance(data, mu=None)", "Population variance."),
      fn("quantiles", "quantiles(data, *, n=4, method='exclusive')", "Cut points."),
    ],
  },
  {
    name: "decimal",
    doc: "Fixed and floating point arithmetic.",
    members: [
      cls("Decimal", "Decimal(value='0')", "Decimal floating-point number."),
      cls(
        "Context",
        "Context(prec=28, rounding=ROUND_HALF_EVEN, ...)",
        "Computational context.",
      ),
      fn("getcontext", "getcontext()", "Return current context."),
      fn("setcontext", "setcontext(ctx)", "Set current context."),
    ],
  },
  {
    name: "urllib.parse",
    doc: "URL parsing utilities.",
    members: [
      fn("urlparse", "urlparse(url)", "Parse URL into 6-tuple."),
      fn("urlunparse", "urlunparse(parts)", "Re-assemble parsed URL."),
      fn(
        "urlencode",
        "urlencode(query, doseq=False)",
        "Encode mapping/sequence to query string.",
      ),
      fn("quote", "quote(string, safe='/')", "Percent-encode."),
      fn("quote_plus", "quote_plus(string)", "Percent-encode with spaces as +."),
      fn("unquote", "unquote(string)", "Percent-decode."),
      fn("unquote_plus", "unquote_plus(string)", "Percent-decode with + as space."),
      fn("parse_qs", "parse_qs(qs)", "Parse query string to dict of lists."),
      fn("parse_qsl", "parse_qsl(qs)", "Parse query string to list of pairs."),
    ],
  },
];
