import type { PyMember } from "./python-api.types";

export const PYTHON_BUILTINS: PyMember[] = [
  {
    name: "abs",
    kind: "function",
    signature: "abs(x)",
    doc: "Return the absolute value of a number.",
  },
  {
    name: "all",
    kind: "function",
    signature: "all(iterable)",
    doc: "Return True if all elements are truthy.",
  },
  {
    name: "any",
    kind: "function",
    signature: "any(iterable)",
    doc: "Return True if any element is truthy.",
  },
  {
    name: "ascii",
    kind: "function",
    signature: "ascii(object)",
    doc: "Return an ASCII-only repr of object.",
  },
  {
    name: "bin",
    kind: "function",
    signature: "bin(x)",
    doc: "Convert an integer to a binary string.",
  },
  {
    name: "bool",
    kind: "class",
    signature: "bool(x=False)",
    doc: "Truth value testing.",
  },
  {
    name: "bytearray",
    kind: "class",
    signature: "bytearray(...)",
    doc: "Mutable sequence of bytes.",
  },
  {
    name: "bytes",
    kind: "class",
    signature: "bytes(...)",
    doc: "Immutable sequence of bytes.",
  },
  {
    name: "callable",
    kind: "function",
    signature: "callable(object)",
    doc: "Return True if object is callable.",
  },
  {
    name: "chr",
    kind: "function",
    signature: "chr(i)",
    doc: "Return the character at code point i.",
  },
  {
    name: "classmethod",
    kind: "function",
    signature: "@classmethod",
    doc: "Class method decorator.",
  },
  {
    name: "complex",
    kind: "class",
    signature: "complex(real, imag)",
    doc: "Complex number.",
  },
  {
    name: "dict",
    kind: "class",
    signature: "dict(**kwargs)",
    doc: "Mapping container.",
  },
  {
    name: "dir",
    kind: "function",
    signature: "dir(object)",
    doc: "List attributes of object.",
  },
  {
    name: "divmod",
    kind: "function",
    signature: "divmod(a, b)",
    doc: "Return (a // b, a % b).",
  },
  {
    name: "enumerate",
    kind: "function",
    signature: "enumerate(iterable, start=0)",
    doc: "Index/value pairs.",
  },
  {
    name: "eval",
    kind: "function",
    signature: "eval(expression)",
    doc: "Evaluate a Python expression.",
  },
  {
    name: "exec",
    kind: "function",
    signature: "exec(object)",
    doc: "Execute Python code dynamically.",
  },
  {
    name: "filter",
    kind: "function",
    signature: "filter(function, iterable)",
    doc: "Filter elements.",
  },
  {
    name: "float",
    kind: "class",
    signature: "float(x=0.0)",
    doc: "Floating point number.",
  },
  {
    name: "format",
    kind: "function",
    signature: "format(value, format_spec='')",
    doc: "Format a value.",
  },
  {
    name: "frozenset",
    kind: "class",
    signature: "frozenset(iterable)",
    doc: "Immutable set.",
  },
  {
    name: "getattr",
    kind: "function",
    signature: "getattr(object, name, default=...)",
    doc: "Get attribute.",
  },
  {
    name: "hasattr",
    kind: "function",
    signature: "hasattr(object, name)",
    doc: "Check for attribute.",
  },
  {
    name: "hash",
    kind: "function",
    signature: "hash(object)",
    doc: "Return hash of object.",
  },
  {
    name: "hex",
    kind: "function",
    signature: "hex(x)",
    doc: "Convert an integer to a hex string.",
  },
  {
    name: "id",
    kind: "function",
    signature: "id(object)",
    doc: "Return the identity of object.",
  },
  {
    name: "input",
    kind: "function",
    signature: "input(prompt='')",
    doc: "Read a line from stdin.",
  },
  { name: "int", kind: "class", signature: "int(x=0)", doc: "Integer number." },
  {
    name: "isinstance",
    kind: "function",
    signature: "isinstance(obj, class_or_tuple)",
    doc: "Instance check.",
  },
  {
    name: "issubclass",
    kind: "function",
    signature: "issubclass(cls, class_or_tuple)",
    doc: "Subclass check.",
  },
  {
    name: "iter",
    kind: "function",
    signature: "iter(object)",
    doc: "Return an iterator.",
  },
  {
    name: "len",
    kind: "function",
    signature: "len(s)",
    doc: "Return the length of an object.",
  },
  {
    name: "list",
    kind: "class",
    signature: "list(iterable=())",
    doc: "Mutable sequence.",
  },
  {
    name: "locals",
    kind: "function",
    signature: "locals()",
    doc: "Local variable dict.",
  },
  {
    name: "map",
    kind: "function",
    signature: "map(function, iterable)",
    doc: "Map function over iterable.",
  },
  {
    name: "max",
    kind: "function",
    signature: "max(iterable, *, key=None, default=...)",
    doc: "Largest item.",
  },
  {
    name: "memoryview",
    kind: "class",
    signature: "memoryview(object)",
    doc: "Memory view of buffer.",
  },
  {
    name: "min",
    kind: "function",
    signature: "min(iterable, *, key=None, default=...)",
    doc: "Smallest item.",
  },
  {
    name: "next",
    kind: "function",
    signature: "next(iterator, default=...)",
    doc: "Next item from iterator.",
  },
  {
    name: "object",
    kind: "class",
    signature: "object()",
    doc: "Base class for all objects.",
  },
  {
    name: "oct",
    kind: "function",
    signature: "oct(x)",
    doc: "Convert an integer to an octal string.",
  },
  {
    name: "open",
    kind: "function",
    signature: "open(file, mode='r', ...)",
    doc: "Open a file.",
  },
  {
    name: "ord",
    kind: "function",
    signature: "ord(c)",
    doc: "Return code point of character.",
  },
  {
    name: "pow",
    kind: "function",
    signature: "pow(base, exp, mod=None)",
    doc: "Power.",
  },
  {
    name: "print",
    kind: "function",
    signature: "print(*objects, sep=' ', end='\\n')",
    doc: "Print to stdout.",
  },
  {
    name: "property",
    kind: "function",
    signature: "@property",
    doc: "Property decorator.",
  },
  {
    name: "range",
    kind: "class",
    signature: "range(stop) | range(start, stop[, step])",
    doc: "Range of integers.",
  },
  {
    name: "repr",
    kind: "function",
    signature: "repr(object)",
    doc: "Printable representation.",
  },
  {
    name: "reversed",
    kind: "function",
    signature: "reversed(seq)",
    doc: "Reverse iterator.",
  },
  {
    name: "round",
    kind: "function",
    signature: "round(number, ndigits=None)",
    doc: "Round to ndigits.",
  },
  {
    name: "set",
    kind: "class",
    signature: "set(iterable=())",
    doc: "Mutable set.",
  },
  {
    name: "setattr",
    kind: "function",
    signature: "setattr(object, name, value)",
    doc: "Set attribute.",
  },
  {
    name: "slice",
    kind: "class",
    signature: "slice(stop) | slice(start, stop[, step])",
    doc: "Slice object.",
  },
  {
    name: "sorted",
    kind: "function",
    signature: "sorted(iterable, *, key=None, reverse=False)",
    doc: "Sorted list.",
  },
  {
    name: "staticmethod",
    kind: "function",
    signature: "@staticmethod",
    doc: "Static method decorator.",
  },
  {
    name: "str",
    kind: "class",
    signature: "str(object='')",
    doc: "Text string.",
  },
  {
    name: "sum",
    kind: "function",
    signature: "sum(iterable, start=0)",
    doc: "Sum of iterable.",
  },
  {
    name: "super",
    kind: "function",
    signature: "super()",
    doc: "Proxy for parent class.",
  },
  {
    name: "tuple",
    kind: "class",
    signature: "tuple(iterable=())",
    doc: "Immutable sequence.",
  },
  {
    name: "type",
    kind: "class",
    signature: "type(object) | type(name, bases, dict)",
    doc: "Type of object.",
  },
  {
    name: "vars",
    kind: "function",
    signature: "vars(object=...)",
    doc: "Return __dict__ of object.",
  },
  {
    name: "zip",
    kind: "function",
    signature: "zip(*iterables, strict=False)",
    doc: "Aggregate iterables.",
  },
  { name: "True", kind: "constant", doc: "Boolean true." },
  { name: "False", kind: "constant", doc: "Boolean false." },
  { name: "None", kind: "constant", doc: "Null value." },
];
