"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.MusicSeparateStemsRequestStemVariationId = void 0;
/** The id of the stem variation to use. */
exports.MusicSeparateStemsRequestStemVariationId = {
    TwoStemsV1: "two_stems_v1",
    SixStemsV1: "six_stems_v1",
};
