"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.NonStreamingOutputFormats = void 0;
exports.NonStreamingOutputFormats = {
    Wav8000: "wav_8000",
    Wav16000: "wav_16000",
    Wav22050: "wav_22050",
    Wav24000: "wav_24000",
    Wav32000: "wav_32000",
    Wav44100: "wav_44100",
    Wav48000: "wav_48000",
};
