"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.UuiTransferConfigProtocolDiscriminatorMode = void 0;
/** How to attach protocol_discriminator. 'prefix' prepends the octet to the hex payload (User-to-User=XX<hex>;encoding=hex). 'pd_parameter' sends it as a separate parameter (User-to-User=<hex>;pd=XX;encoding=hex). Ignored when protocol_discriminator is unset. */
exports.UuiTransferConfigProtocolDiscriminatorMode = {
    Prefix: "prefix",
    PdParameter: "pd_parameter",
};
