"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.ProductionsClient = void 0;
const BaseClient_1 = require("../../../../BaseClient");
const Client_1 = require("../resources/orders/client/Client");
class ProductionsClient {
    constructor(options = {}) {
        this._options = (0, BaseClient_1.normalizeClientOptions)(options);
    }
    get orders() {
        var _a;
        return ((_a = this._orders) !== null && _a !== void 0 ? _a : (this._orders = new Client_1.OrdersClient(this._options)));
    }
}
exports.ProductionsClient = ProductionsClient;
