package domain

import (
	"fmt"
	"html"
	"strings"
)

// ClickHouseNativeVersion is the upstream release haven runs as a host process:
// the newest 25.8 LTS patch, the series Altinity's 25.8 stable image (the
// container) is cut from, so the two differ by backports, not by series.
const ClickHouseNativeVersion = "25.8.33.6"

// ClickHouseNativeDir is the native server's directory under haven's home,
// apart from the container's, so the two never share data, config or a port.
const ClickHouseNativeDir = "clickhouse-native"

// PinnedArtifact is one pinned release download and the sha256 it must match.
// Member names the binary inside a tar.gz or .zip asset; empty means the
// asset is it.
type PinnedArtifact struct {
	URL    string
	SHA256 string
	Member string
}

// clickHouseNativeDigests are GitHub's recorded sha256 of each release asset
// (`gh api repos/ClickHouse/ClickHouse/releases`, field assets[].digest).
var clickHouseNativeDigests = map[string]struct{ asset, sha256 string }{
	"darwin/arm64": {"clickhouse-macos-aarch64", "9643585c035d939ba5c8cf57899235da8a2f1c2703d8fde99924db119659f198"},
	"darwin/amd64": {"clickhouse-macos", "b08dff345c8e1c89910be583146dc88790987619456fb4a6ea8961c949e08f0d"},
}

// ClickHouseNativeArtifactFor returns the pinned binary for a machine, or false
// where haven pins none (everything but macOS today).
func ClickHouseNativeArtifactFor(goos, goarch string) (PinnedArtifact, bool) {
	d, ok := clickHouseNativeDigests[goos+"/"+goarch]
	if !ok {
		return PinnedArtifact{}, false
	}
	url := fmt.Sprintf("https://github.com/ClickHouse/ClickHouse/releases/download/v%s-lts/%s", ClickHouseNativeVersion, d.asset)
	return PinnedArtifact{URL: url, SHA256: d.sha256}, true
}

// ClickHouseRuntime is where the shared ClickHouse runs.
type ClickHouseRuntime string

const (
	// ClickHouseRuntimeNative is the pinned upstream binary as a host process.
	ClickHouseRuntimeNative ClickHouseRuntime = "native"
	// ClickHouseRuntimeContainer is the Altinity image on the colima VM.
	ClickHouseRuntimeContainer ClickHouseRuntime = "container"
)

// ResolveClickHouseRuntime applies HAVEN_CH_RUNTIME, then the machine: native
// wherever a binary is pinned, the container elsewhere. Stating native on a
// machine with no pinned binary is an error, never a silent container.
func ResolveClickHouseRuntime(stated, goos, goarch string) (ClickHouseRuntime, error) {
	_, pinned := ClickHouseNativeArtifactFor(goos, goarch)
	switch strings.ToLower(strings.TrimSpace(stated)) {
	case "":
		if pinned {
			return ClickHouseRuntimeNative, nil
		}
		return ClickHouseRuntimeContainer, nil
	case "native", "host":
		if !pinned {
			return ClickHouseRuntimeContainer, fmt.Errorf("no native ClickHouse is pinned for %s/%s", goos, goarch)
		}
		return ClickHouseRuntimeNative, nil
	case "container", "docker", "colima":
		return ClickHouseRuntimeContainer, nil
	}
	return ClickHouseRuntimeContainer, fmt.Errorf("HAVEN_CH_RUNTIME=%q: want native or container", stated)
}

// PostgresHost is how this runtime's server reaches the Mac's Postgres for
// LangWatchQL's named collection: loopback natively, Lima's host route in colima.
func (r ClickHouseRuntime) PostgresHost() string {
	if r == ClickHouseRuntimeNative {
		return "127.0.0.1"
	}
	return ColimaHostAddress
}

// LWQLPostgresHost is the stack's recorded route, defaulting to colima's for a
// stack provisioned before the runtime was recorded on it.
func (s Stack) LWQLPostgresHost() string {
	if s.ClickHousePostgresHost == "" {
		return ColimaHostAddress
	}
	return s.ClickHousePostgresHost
}

// RenderClickHouseNativeServerConfig is the main config.xml a native server
// needs because no image supplies one. Tuning stays in RenderClickHouseConfig,
// written beside it into config.d exactly as the container mounts it.
func RenderClickHouseNativeServerConfig(home string, httpPort int) string {
	return fmt.Sprintf(clickHouseNativeServerTemplate, html.EscapeString(strings.TrimSuffix(home, "/")), httpPort)
}

// RenderClickHouseNativeUsersConfig is the users.xml the image would supply,
// with the container's local password; users.d adds ClickHouseUsersConfig.
func RenderClickHouseNativeUsersConfig() string {
	return fmt.Sprintf(clickHouseNativeUsersTemplate, html.EscapeString(ClickHousePassword))
}

// Only http_port is set, so the server opens no native, MySQL or PostgreSQL
// port. access_control_improvements copies the image's stock config.xml: the
// compiled defaults are laxer (system tables readable without a grant).
const clickHouseNativeServerTemplate = `<!-- generated by haven (thuishaven) — do not edit -->
<clickhouse>
    <listen_host>127.0.0.1</listen_host>
    <http_port>%[2]d</http_port>
    <path>%[1]s/data/</path>
    <tmp_path>%[1]s/data/tmp/</tmp_path>
    <user_files_path>%[1]s/data/user_files/</user_files_path>
    <format_schema_path>%[1]s/data/format_schemas/</format_schema_path>
    <user_directories>
        <users_xml><path>%[1]s/users.xml</path></users_xml>
        <local_directory><path>%[1]s/data/access/</path></local_directory>
    </user_directories>
    <logger>
        <level>information</level>
        <log>%[1]s/log/clickhouse-server.log</log>
        <errorlog>%[1]s/log/clickhouse-server.err.log</errorlog>
        <size>100M</size>
        <count>3</count>
    </logger>
    <timezone>UTC</timezone>
    <max_open_files>10240</max_open_files>
    <default_profile>default</default_profile>
    <default_database>default</default_database>
    <access_control_improvements>
        <users_without_row_policies_can_read_rows>true</users_without_row_policies_can_read_rows>
        <on_cluster_queries_require_cluster_grant>true</on_cluster_queries_require_cluster_grant>
        <select_from_system_db_requires_grant>true</select_from_system_db_requires_grant>
        <select_from_information_schema_requires_grant>true</select_from_information_schema_requires_grant>
        <settings_constraints_replace_previous>true</settings_constraints_replace_previous>
        <table_engines_require_grant>false</table_engines_require_grant>
        <role_cache_expiration_time_seconds>600</role_cache_expiration_time_seconds>
    </access_control_improvements>
</clickhouse>
`

const clickHouseNativeUsersTemplate = `<!-- generated by haven (thuishaven) — do not edit -->
<clickhouse>
    <profiles>
        <default/>
        <readonly><readonly>1</readonly></readonly>
    </profiles>
    <quotas>
        <default/>
    </quotas>
    <users>
        <default>
            <password>%s</password>
            <networks>
                <ip>127.0.0.1</ip>
                <ip>::1</ip>
            </networks>
            <profile>default</profile>
            <quota>default</quota>
        </default>
    </users>
</clickhouse>
`
