package domain

import (
	"fmt"
	"strings"
)

// ClickHouseService is the routed name for a stack's ClickHouse: it always
// resolves (clickhouse.<slug>.langwatch.localhost), pointing at the one shared
// managed clickhouse-server. Per-worktree isolation is by database, not server —
// so the hostname is always defined even when this worktree runs no CH of its
// own, and a "wrong migration count" is impossible because each worktree reads
// and writes only its own database.
const ClickHouseService = "clickhouse"

// DatabaseForSlug maps a slug to this worktree's isolated ClickHouse database on
// the shared server. Slugs use '-' (invalid in a CH identifier); databases use
// '_' and an "lw_" prefix so the name always starts with a letter and matches
// ClickHouse's identifier grammar (the app's goose runner validates the same).
func DatabaseForSlug(slug string) string {
	return "lw_" + strings.ReplaceAll(slug, "-", "_")
}

// ClickHouseContainer is the fixed container name for the shared managed
// server — a machine-wide singleton, same story as ObservabilityContainer: a
// second worktree finds this one and reuses it rather than standing up a rival.
const ClickHouseContainer = "langwatch-clickhouse"

// ClickHouseImage is Altinity's Stable Build: a well-managed, LTS-backported
// ClickHouse image (as opposed to upstream's own release cadence). Chosen over
// running clickhouse-server as a native host binary so every contributor's setup
// is identical regardless of what (if anything) they have brew-installed, and
// over the previous native-binary adapter so the memory ceiling is enforced two
// ways: ClickHouse's own <max_server_memory_usage> AND a hard Docker cgroup
// limit, so a runaway query is OOM-killed by the container rather than swelling
// into the host.
const ClickHouseImage = "altinity/clickhouse-server:25.8.16.10002.altinitystable"

// ClickHouseUser/ClickHousePassword are the fixed local-dev credentials for the
// managed container. Unlike the earlier native-binary adapter (which had its own
// users.xml and could leave the default user passwordless), the Altinity image's
// bootstrap entrypoint requires CLICKHOUSE_PASSWORD to be set or it rejects the
// default user outright. "langwatch" matches the password compose.dev.yml's own
// (now-legacy) clickhouse service already used, so nothing new to remember.
const (
	ClickHouseUser     = "default"
	ClickHousePassword = "langwatch"
)

// ClickHouseLimits bound what the managed server may take from the host. Proven
// numbers: the 1GiB experiment (880MiB internal cap) was too tight for
// LangWatch's read/background query load (UI + governance syncs) and the UI
// blanked when queries hit the cap. 1.5GiB container / 1.35GiB internal handles
// inserts + queries comfortably.
type ClickHouseLimits struct {
	ContainerMemoryMB int   // Docker --memory / --memory-swap (hard ceiling, OOM-kills rather than swells)
	MaxServerMemory   int64 // <max_server_memory_usage> — ClickHouse's own soft ceiling, under the container's
	MarkCacheSize     int64 // <mark_cache_size> — kept small on purpose; the rest are zeroed below
}

// DefaultClickHouseLimits is the proven-in-production tuning: internal cap at
// 90% of the container ceiling (leaves ClickHouse's own bookkeeping overhead
// room before the container's hard limit bites), a modest 64MiB mark cache, and
// — set directly in the config template, not here — uncompressed/mmap/compiled-
// expression caches all zeroed, since none of them pull their weight at this
// scale and idle RSS is the whole point.
func DefaultClickHouseLimits() ClickHouseLimits {
	const containerMB = 1536 // 1.5 GiB
	return ClickHouseLimits{
		ContainerMemoryMB: containerMB,
		MaxServerMemory:   int64(containerMB) * 9 / 10 * (1 << 20), // 1.35 GiB
		MarkCacheSize:     64 << 20,                                // 64 MiB
	}
}

// ClickHouseConfigFile is the config.d override haven mounts read-only into the
// container — additive to the image's own config.d, never replacing it.
const ClickHouseConfigFile = "zzz-thuis-memory.xml"

// RenderClickHouseConfig fills in the config.d memory-tuning override. "thuis" —
// Dutch for "home" — names this the same way thuishaven does: proven on a
// long-running low-RAM home instance before landing here.
func RenderClickHouseConfig(l ClickHouseLimits) string {
	return fmt.Sprintf(clickHouseConfigTemplate, l.MaxServerMemory, l.MarkCacheSize)
}

const clickHouseConfigTemplate = `<!-- generated by haven (thuishaven) — do not edit -->
<clickhouse>
    <max_server_memory_usage>%d</max_server_memory_usage>
    <mark_cache_size>%d</mark_cache_size>
    <uncompressed_cache_size>0</uncompressed_cache_size>
    <mmap_cache_size>0</mmap_cache_size>
    <compiled_expression_cache_size>0</compiled_expression_cache_size>
</clickhouse>
`
