package domain

import (
	"fmt"
	"strings"
)

// svc looks a service up by name; a zero value is fine for the string formatting
// below when a stack is partial.
func (s Stack) svc(name string) Service {
	for _, x := range s.Services {
		if x.Name == name {
			return x
		}
	}
	return Service{}
}

// OverlayEnv returns the KEY=VALUE lines that carry the resolved hostname URLs +
// ports. These are (a) written to langwatch/.env.portless — the overlay every TS
// entry point loads last with override:true so it beats anything pinned in .env —
// and (b) injected directly into each supervised child. Deriving them from the
// Stack (which already holds every URL/port) keeps this the single source of
// truth with no file round-trip.
func (s Stack) OverlayEnv() []string {
	app, api, gw, nlp := s.svc("app"), s.svc("api"), s.svc("gateway"), s.svc("nlp")
	return []string{
		"LANGWATCH_PORTLESS=1",
		"LANGWATCH_SLUG=" + s.Slug,
		fmt.Sprintf("LANGWATCH_APP_PORT=%d", app.Port),
		fmt.Sprintf("LANGWATCH_API_PORT=%d", api.Port),
		fmt.Sprintf("LANGWATCH_GATEWAY_PORT=%d", gw.Port),
		fmt.Sprintf("LANGWATCH_NLP_PORT=%d", nlp.Port),
		fmt.Sprintf("WORKER_METRICS_PORT=%d", s.WorkerMetricsPort),
		"BASE_HOST=" + app.URL,
		"NEXTAUTH_URL=" + app.URL,
		"LANGWATCH_ENDPOINT=" + app.URL,
		"LANGWATCH_API_URL=" + api.URL,
		"LANGWATCH_NLP_SERVICE=" + nlp.URL,
		"GATEWAY_CONTROL_PLANE_URL=" + api.URL,
		"LW_GATEWAY_BASE_URL=" + api.URL,
		"LW_GATEWAY_PUBLIC_URL=" + gw.URL,
		"LW_GATEWAY_INTERNAL_URL=" + gw.URL,
		fmt.Sprintf("REDIS_DB_INDEX=%d", s.RedisDB),
	}
}

// OverlayFile renders the .env.portless file body (header + OverlayEnv).
func (s Stack) OverlayFile() string {
	var b strings.Builder
	b.WriteString("# --- generated by haven (thuishaven) — do not edit ---\n")
	b.WriteString(fmt.Sprintf("# Portless hostname routing for the %q stack (worktree: %s).\n", s.Slug, s.WorktreeDir))
	b.WriteString("# Loaded last with override:true so these win over anything pinned in .env.\n")
	for _, line := range s.OverlayEnv() {
		b.WriteString(line)
		b.WriteByte('\n')
	}
	return b.String()
}
