package domain

import (
	"fmt"
	"strings"
)

// DefaultLocalAPIKey is the stable local dev project API key haven seeds and
// injects when none is pinned. It is intentionally fixed and well-known so any
// worktree, script, or AI agent authenticates with the same key locally — the
// "the API key is always the same locally" contract. It is a legacy sk-lw-* full
// project key, matched by exact lookup on Project.apiKey.
const DefaultLocalAPIKey = "sk-lw-local-development-key"

// svc looks a service up by name; a zero value is fine for the string formatting
// below when a stack is partial.
func (s Stack) svc(name string) Service {
	for _, x := range s.Services {
		if x.Name == name {
			return x
		}
	}
	return Service{}
}

// OverlayEnv returns the KEY=VALUE lines that carry the resolved hostname URLs +
// ports. These are (a) written to langwatch/.env.portless — the overlay every TS
// entry point loads last with override:true so it beats anything pinned in .env —
// and (b) injected directly into each supervised child. Deriving them from the
// Stack (which already holds every URL/port) keeps this the single source of
// truth with no file round-trip.
func (s Stack) OverlayEnv() []string {
	app, gw, nlp := s.svc("app"), s.svc("gateway"), s.svc("nlp")
	// The API is same-origin with the app: the browser (and any agent) uses one
	// URL, app.<slug>.../api, which Vite proxies to the API backend on loopback.
	// Server-to-server callers (Vite's /api proxy, the Go gateway's control-plane
	// client, langy) dial that loopback port directly — robust, no TLS/CA, no
	// second public hostname to confuse anyone.
	apiInternal := fmt.Sprintf("http://127.0.0.1:%d", s.APIPort)
	env := []string{
		"LANGWATCH_PORTLESS=1",
		"LANGWATCH_SLUG=" + s.Slug,
		fmt.Sprintf("LANGWATCH_APP_PORT=%d", app.Port),
		fmt.Sprintf("LANGWATCH_API_PORT=%d", s.APIPort),
		fmt.Sprintf("LANGWATCH_GATEWAY_PORT=%d", gw.Port),
		fmt.Sprintf("LANGWATCH_NLP_PORT=%d", nlp.Port),
		fmt.Sprintf("WORKER_METRICS_PORT=%d", s.WorkerMetricsPort),
		"BASE_HOST=" + app.URL,
		"NEXTAUTH_URL=" + app.URL,
		"LANGWATCH_ENDPOINT=" + app.URL,
		"LANGWATCH_API_URL=" + apiInternal,
		"LANGWATCH_NLP_SERVICE=" + nlp.URL,
		"GATEWAY_CONTROL_PLANE_URL=" + apiInternal,
		"LW_GATEWAY_BASE_URL=" + apiInternal,
		"LW_GATEWAY_PUBLIC_URL=" + gw.URL,
		"LW_GATEWAY_INTERNAL_URL=" + gw.URL,
		fmt.Sprintf("REDIS_DB_INDEX=%d", s.RedisDB),
	}
	// A stable local API key so the seed always mints the same credential and any
	// agent can authenticate without rediscovering it per worktree.
	if s.LocalAPIKey != "" {
		env = append(env, "LANGWATCH_API_KEY="+s.LocalAPIKey)
	}
	// haven manages one shared clickhouse-server; this stack gets its own database
	// on it. The app connects straight to loopback (native CH HTTP, no proxy) at
	// the per-slug database, so migration counts are always this worktree's own.
	if s.ClickHouseHTTPPort != 0 && s.ClickHouseDatabase != "" {
		env = append(env, fmt.Sprintf("CLICKHOUSE_URL=http://127.0.0.1:%d/%s", s.ClickHouseHTTPPort, s.ClickHouseDatabase))
	}
	env = append(env, s.observabilityEnv()...)
	return env
}

// observabilityEnv wires this stack into the shared LGTM collector — the whole
// point of haven owning the observability stack. Because haven already knows the
// slug, telemetry is tagged with it automatically: an agent debugging this
// worktree filters Grafana to langwatch.worktree="<slug>" and sees only its own
// logs, traces and metrics, even with a dozen worktrees sharing the collector.
//
// Emitted only when the stack is actually up, so a contributor who never starts
// it exports nothing and pays nothing. Console log level is deliberately NOT set
// here: the overlay overrides .env, and silently muting someone's terminal is not
// a decision haven gets to make. Set LOG_CONSOLE_LEVEL=warn in .env to get the
// quiet-terminal, full-detail-in-Grafana split.
func (s Stack) observabilityEnv() []string {
	if s.ObservabilityOTLPPort == 0 {
		return nil
	}
	otlp := fmt.Sprintf("http://127.0.0.1:%d", s.ObservabilityOTLPPort)
	return []string{
		"OTEL_EXPORTER_OTLP_ENDPOINT=" + otlp,   // TS: traces + logs + metrics
		"OTEL_DEBUG_COLLECTOR_ENDPOINT=" + otlp, // Go: dual-export, additive to the product trace path
		"PINO_OTEL_ENABLED=true",
		"OTEL_METRICS_ENABLED=true",
		"LOG_OTEL_LEVEL=debug",
		"OTEL_RESOURCE_ATTRIBUTES=" + ObservabilityWorktreeAttr + "=" + s.Slug,
	}
}

// OverlayFile renders the .env.portless file body (header + OverlayEnv).
func (s Stack) OverlayFile() string {
	var b strings.Builder
	b.WriteString("# --- generated by haven (thuishaven) — do not edit ---\n")
	b.WriteString(fmt.Sprintf("# Portless hostname routing for the %q stack (worktree: %s).\n", s.Slug, s.WorktreeDir))
	b.WriteString("# Loaded last with override:true so these win over anything pinned in .env.\n")
	for _, line := range s.OverlayEnv() {
		b.WriteString(line)
		b.WriteByte('\n')
	}
	return b.String()
}
