apiVersion: v2
name: langwatch
description: Helm chart for LangWatch application
type: application
appVersion: 3.1.0-prerelease.3
version: 3.1.0-prerelease.3
annotations:
  category: Observability
  keywords: ai,observability,monitoring,secrets
  maintainers: LangWatch Team
dependencies:
  - name: prometheus
    version: 25.27.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.chartManaged
  - name: clickhouse-serverless
    alias: clickhouse
    version: 0.2.0
    repository: file://../clickhouse-serverless
    condition: clickhouse.chartManaged
