# Production values file for LangWatch
# Copy and customize for your environment

global:
  env: production
  monitoring:
    enabled: true

app:
  replicaCount: 2
  resources:
    requests:
      cpu: 200m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 2Gi
  env:
    SKIP_ENV_VALIDATION: "false"
    DISABLE_PII_REDACTION: "false"
    BASE_HOST: "https://yourdomain.com"
    NEXTAUTH_URL: "https://yourdomain.com"
    IS_OPENSEARCH: "true"
    LANGWATCH_NLP_SERVICE: "http://langwatch-langwatch-nlp:5561"
    LANGEVALS_ENDPOINT: "http://langwatch-langevals:5562"

    # For env vars which contain secrets, omit them in the values file and set them as
    # kubernetes secrets. This is explained in more detail in the README.md file.
    # DATABASE_URL: "postgresql://user:@your-managed-postgres:5432/langwatch?sslmode=require"
    # REDIS_URL: "redis://:@your-managed-redis:6379/0"
    # ELASTICSEARCH_NODE_URL: "https://your-managed-opensearch:9200"

# External services
postgres:
  enabled: false

redis:
  enabled: false

opensearch:
  enabled: false

# Monitoring
prometheus:
  enabled: true
  storage:
    size: 10Gi
  retention: 30d

# CronJobs
cronjobs:
  enabled: true
  jobs:
    topicClustering:
      schedule: "0 2 * * *"
    alertTriggers:
      schedule: "*/5 * * * *"
    tracesRetentionCleanup:
      schedule: "0 3 * * *"

# Ingress (uncomment and configure)
ingress:
  enabled: false
  className: "nginx"
  hosts:
    - host: yourdomain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: langwatch-app
                port:
                  number: 5560
