# Production values file for LangWatch
# Copy and customize for your environment

global:
  env: production
  monitoring:
    enabled: true

app:
  replicaCount: 2
  resources:
    requests:
      cpu: 200m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 2Gi
  env:
    SKIP_ENV_VALIDATION: "false"
    DISABLE_PII_REDACTION: "false"
    BASE_HOST: "https://yourdomain.com"
    NEXTAUTH_URL: "https://yourdomain.com"
    DATABASE_URL: "postgresql://user:password@your-managed-postgres:5432/langwatch?sslmode=require"
    REDIS_URL: "redis://:password@your-managed-redis:6379/0"
    ELASTICSEARCH_NODE_URL: "https://your-managed-opensearch:9200"
    IS_OPENSEARCH: "true"
    LANGWATCH_NLP_SERVICE: "http://langwatch-langwatch-nlp:5561"
    LANGEVALS_ENDPOINT: "http://langwatch-langevals:5562"
    # SSO Configuration (uncomment and configure)
    # AZURE_AD_CLIENT_ID: "your-azure-client-id"
    # AZURE_AD_CLIENT_SECRET: "your-azure-client-secret"
    # NEXTAUTH_PROVIDERS: '[{"id":"azure-ad","name":"Azure AD","type":"oauth","clientId":"your-client-id","clientSecret":"your-client-secret","wellKnown":"https://login.microsoftonline.com/your-tenant-id/v2.0/.well-known/openid_configuration"}]'

# External services
postgres:
  enabled: false

redis:
  enabled: false

opensearch:
  enabled: false

# Monitoring
prometheus:
  enabled: true
  storage:
    size: 10Gi
  retention: 30d

# CronJobs
cronjobs:
  enabled: true
  jobs:
    topicClustering:
      schedule: "0 2 * * *"
    alertTriggers:
      schedule: "*/5 * * * *"
    tracesRetentionCleanup:
      schedule: "0 3 * * *"

# Ingress (uncomment and configure)
ingress:
  enabled: false
  className: "nginx"
  hosts:
    - host: yourdomain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: langwatch-app
                port:
                  number: 5560
