import { execFileSync } from "node:child_process";
import { mkdirSync, mkdtempSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { describe, expect, it } from "vitest";
import { changedSourceFiles, lintCommentBlocks } from "../src";

function lineComments(lines: number): string {
  return Array.from({ length: lines }, () => "// comment").join("\n");
}

function blockComment(lines: number): string {
  if (lines === 1) return "/* comment */";
  return ["/*", ...Array.from({ length: lines - 2 }, () => " * comment"), " */"].join(
    "\n",
  );
}

function writeFixture(root: string, file: string, source: string): void {
  const path = join(root, file);
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, `${source}\n`);
}

function git(root: string, ...arguments_: string[]): void {
  execFileSync("git", ["-C", root, ...arguments_], { stdio: "ignore" });
}

describe("oversized comment blocks", () => {
  it("keeps 3 lines quiet, warns at 4 lines (over 3), and errors at 6 lines (over 5)", () => {
    const root = mkdtempSync(join(tmpdir(), "comment-blocks-boundaries-"));
    writeFixture(root, "src/three.ts", lineComments(3));
    writeFixture(root, "src/four.ts", lineComments(4));
    writeFixture(root, "src/five.ts", blockComment(5));
    writeFixture(root, "src/six.ts", blockComment(6));

    const result = lintCommentBlocks(root);
    expect(result.reviews).toEqual(
      expect.arrayContaining([
        expect.objectContaining({ file: "src/four.ts", line: 1, lines: 4 }),
        expect.objectContaining({ file: "src/five.ts", line: 1, lines: 5 }),
      ]),
    );
    expect(result.reviews).not.toEqual(
      expect.arrayContaining([expect.objectContaining({ file: "src/three.ts" })]),
    );
    expect(result.violations).toMatchObject([
      {
        policy: "comment-block-size",
        file: join(root, "src/six.ts"),
        line: 1,
      },
    ]);
  });

  it("does not merge blocks separated by a blank line or count code-line comments", () => {
    const root = mkdtempSync(join(tmpdir(), "comment-blocks-contiguous-"));
    writeFixture(root, "src/separated.ts", `${lineComments(3)}\n\n${lineComments(3)}`);
    writeFixture(
      root,
      "src/code.ts",
      `${Array.from({ length: 6 }, () => "const value = 1; // comment").join("\n")}`,
    );

    expect(lintCommentBlocks(root)).toEqual({ reviews: [], violations: [] });
  });

  it("does not mistake a template tail for a block comment", () => {
    const root = mkdtempSync(join(tmpdir(), "comment-blocks-template-tail-"));
    writeFixture(
      root,
      "src/template-tail.ts",
      [
        'const value = "guard";',
        "const pattern = `${value}/*`;",
        ...Array.from({ length: 6 }, (_, index) => `const item${index} = ${index};`),
      ].join("\n"),
    );

    expect(lintCommentBlocks(root)).toEqual({ reviews: [], violations: [] });
  });

  it("checks committed branch changes, current changes, and untracked source only", () => {
    const root = mkdtempSync(join(tmpdir(), "comment-blocks-changed-files-"));
    git(root, "init", "--quiet", "--initial-branch=main");
    git(root, "config", "user.email", "test@example.com");
    git(root, "config", "user.name", "Architecture Lint Test");
    git(root, "config", "commit.gpgsign", "false");
    writeFixture(root, "src/base.ts", lineComments(6));
    git(root, "add", ".");
    git(root, "commit", "--quiet", "-m", "base");
    git(root, "checkout", "--quiet", "-b", "comment-blocks");

    writeFixture(root, "src/committed.ts", lineComments(6));
    git(root, "add", ".");
    git(root, "commit", "--quiet", "-m", "committed change");
    writeFixture(root, "src/current.ts", lineComments(6));
    writeFixture(root, "src/untracked.ts", lineComments(6));

    const files = changedSourceFiles(root);
    expect(files.map((file) => file.slice(root.length + 1))).toEqual([
      "src/committed.ts",
      "src/current.ts",
      "src/untracked.ts",
    ]);
    expect(lintCommentBlocks(root, { files }).violations).toHaveLength(3);
  });

  it("ignores licences, generated headers, generated files, and build output", () => {
    const root = mkdtempSync(join(tmpdir(), "comment-blocks-exclusions-"));
    writeFixture(
      root,
      "src/licensed.ts",
      `// SPDX-License-Identifier: Apache-2.0\n${lineComments(6)}`,
    );
    writeFixture(
      root,
      "src/copyright.ts",
      `/* Copyright 2026 LangWatch. Licensed under Apache-2.0. */\n${lineComments(6)}`,
    );
    writeFixture(
      root,
      "src/generated-header.ts",
      `// Code generated by test. DO NOT EDIT.\n${lineComments(6)}`,
    );
    writeFixture(root, "src/schema.generated.ts", lineComments(6));
    writeFixture(root, "vendor/vendor.ts", lineComments(6));
    writeFixture(root, "generated/generated.ts", lineComments(6));
    writeFixture(root, "build/build.ts", lineComments(6));

    expect(lintCommentBlocks(root)).toEqual({ reviews: [], violations: [] });
  });

  it("counts a JSDoc block toward the same thresholds as a plain block comment", () => {
    const root = mkdtempSync(join(tmpdir(), "comment-blocks-jsdoc-"));
    const jsdoc = [
      "/**",
      " * Line one of an explanation.",
      " * Line two of an explanation.",
      " * Line three of an explanation.",
      " */",
    ].join("\n");
    writeFixture(root, "src/jsdoc.ts", `${jsdoc}\nexport const value = 1;`);

    expect(lintCommentBlocks(root)).toEqual({
      reviews: [
        {
          category: "comment-blocks",
          file: "src/jsdoc.ts",
          line: 1,
          lines: 5,
          message: "Comment block has 5 lines and should receive review attention.",
        },
      ],
      violations: [],
    });
  });

  it("exempts a JSDoc block carrying a @scenario annotation regardless of length", () => {
    const root = mkdtempSync(join(tmpdir(), "comment-blocks-scenario-"));
    const jsdoc = [
      "/**",
      ' * @scenario "A definition map becomes a JSON Schema object"',
      " * Extra line one.",
      " * Extra line two.",
      " * Extra line three.",
      " * Extra line four.",
      " */",
    ].join("\n");
    writeFixture(root, "src/scenario.ts", `${jsdoc}\nit("works", () => {});`);

    expect(lintCommentBlocks(root)).toEqual({ reviews: [], violations: [] });
  });

  it("exempts a block that is only eslint/oxlint/@ts- directives", () => {
    const root = mkdtempSync(join(tmpdir(), "comment-blocks-directives-"));
    writeFixture(
      root,
      "src/directives.ts",
      [
        "// eslint-disable-next-line no-console",
        "// oxlint-disable-next-line no-unused-vars",
        "// @ts-expect-error legacy shape",
        "// eslint-disable-next-line max-len",
        "// oxlint-disable-next-line no-empty",
        "// @ts-ignore third-party types",
        "export const value = 1;",
      ].join("\n"),
    );

    expect(lintCommentBlocks(root)).toEqual({ reviews: [], violations: [] });
  });

  it("covers apps/ as a scanned source root, not only packages/", () => {
    const root = mkdtempSync(join(tmpdir(), "comment-blocks-apps-root-"));
    writeFixture(root, "apps/api/src/app/example.composition.ts", blockComment(6));

    const result = lintCommentBlocks(root);
    expect(result.violations).toMatchObject([
      {
        policy: "comment-block-size",
        file: join(root, "apps/api/src/app/example.composition.ts"),
        line: 1,
      },
    ]);
  });
});
