import type { AlertType } from "@langwatch/automation-contract";
import { Column, Container, Heading, Html, Img, Link, Row, Section } from "@react-email/components";
import { render } from "@react-email/render";
import { createElement, Fragment, type ReactNode } from "react";

/** One settled match, as a row in the digest. */
type DigestEntry = {
  traceId?: string | undefined;
  graphId?: string | undefined;
};

/**
 * How many matches one digest lists.
 *
 * A settlement window can flush hundreds of matches at a cap breach, and a mail
 * with hundreds of links is neither readable nor deliverable. The remaining
 * matches are still claimed, still counted and still visible in the product;
 * only the mail is truncated.
 */
const DIGEST_ROW_LIMIT = 10;

/**
 * The digest an automation sends when its author wrote no template of their
 * own — which is most automations.
 *
 * Written with `createElement` rather than JSX because the strict feature
 * layout admits no `.tsx` module and this package's TypeScript project builds
 * `.ts` only. The element TREE is what `render` turns into HTML, so this
 * produces the same bytes the application's JSX does.
 *
 * Nothing here reads configuration. `baseHost` arrives from the composition
 * root, and every link in the mail is built from it, so a deployment behind a
 * different origin sends links that resolve.
 */
export function renderTriggerDigestEmail(input: {
  triggerName: string;
  triggerType: AlertType | null;
  triggerMessage: string;
  projectSlug: string;
  baseHost: string;
  entries: DigestEntry[];
}): Promise<string> {
  const prefix = input.triggerType ? `(${input.triggerType}) ` : "";

  return render(
    createElement(
      Html,
      { lang: "en", dir: "ltr" },
      createElement(
        Container,
        {
          style: {
            border: "1px solid #F2F4F8",
            borderRadius: "10px",
            padding: "24px",
            paddingBottom: "12px",
          },
        },
        createElement(Img, {
          src: "https://app.langwatch.ai/images/logo-icon.png",
          alt: "LangWatch Logo",
          width: "36",
        }),
        createElement(Heading, { as: "h1" }, `${prefix}LangWatch Trigger`),
        createElement(Heading, { as: "h3" }, input.triggerName),
        createElement(
          "p",
          null,
          "This is an automated email generated by your configured triggers. Below, you will find the messages that initiated this action.",
        ),
        input.triggerMessage ? createElement("p", null, input.triggerMessage) : null,
        digestTable(input),
      ),
    ),
  );
}

function digestTable(input: {
  projectSlug: string;
  baseHost: string;
  entries: DigestEntry[];
}): ReactNode {
  return createElement(
    Section,
    null,
    createElement(
      Fragment,
      null,
      ...input.entries.slice(0, DIGEST_ROW_LIMIT).map((entry, index) =>
        createElement(Row, {
          key: index,
          children: createElement(Column, {
            children: createElement(Link, { href: linkFor(entry, input) }, textFor(entry)),
          }),
        }),
      ),
    ),
  );
}

/**
 * Where a row points.
 *
 * A graph automation's match is a threshold on a chart rather than one trace,
 * so it links to the chart. `#` is the deliberate ending for a match that
 * carries neither: a link that goes nowhere is better than one that resolves to
 * a trace page for an id the project does not hold.
 */
function linkFor(entry: DigestEntry, input: { projectSlug: string; baseHost: string }): string {
  if (entry.graphId) {
    return `${input.baseHost}/${input.projectSlug}/analytics/custom/${entry.graphId}`;
  }
  if (entry.traceId) {
    return `${input.baseHost}/${input.projectSlug}/traces/${entry.traceId}`;
  }

  return "#";
}

function textFor(entry: DigestEntry): string {
  if (entry.graphId) {
    return "View Graph";
  }

  return entry.traceId ?? "View";
}
