/**
 * The workflow module's application: what all five of its doors call. A caller
 * arrives as an argument, never read from a session or a request, so one
 * operation serves a browser session, an API key and a background job alike.
 */
import type { DatasetApi } from "@langwatch/dataset-contract";
import type { Evaluator, EvaluatorApi } from "@langwatch/evaluator-contract";
import type { AuthzPermission } from "@langwatch/authz-contract";
import {
  clearDsl,
  recursiveAlphabeticallySortedKeys,
  WorkflowApi,
  WorkflowExecutionFailedError,
  type ArchiveWorkflowCommand,
  type CopyStudioWorkflowCommand,
  type CopyWorkflowCommand,
  type CreateWorkflowCommand,
  type ExecuteWorkflowComponentInput,
  type PublishWorkflowCommand,
  type RunWorkflowCommand,
  type StudioClientEvent,
  type StudioServerEvent,
  type StudioWorkflow,
  type UpdateWorkflowCommand,
  type Workflow,
  type WorkflowCaller,
  type WorkflowCascadeArchive,
  type WorkflowCopiesRow,
  type WorkflowCopyWithPath,
  type WorkflowEvaluationRequest,
  type WorkflowEvaluationStarted,
  type WorkflowLineageRow,
  type WorkflowListRow,
  type WorkflowPublicationFlags,
  type WorkflowReference,
  type WorkflowRelatedEntities,
  type WorkflowRunAnswer,
  type WorkflowService,
  type WorkflowSourceRow,
  type WorkflowVersion,
  type WorkflowVersionHistoryEntry,
  type WorkflowVersionHistoryMode,
  type WorkflowWithVersion,
} from "@langwatch/workflow-contract";
import type { FeatureSetup } from "@langwatch/runtime-composition";
import { nanoid } from "nanoid";
import type {
  WorkflowAgentMappingPort,
  WorkflowRowPort,
  WorkflowStudioDslPort,
} from "../ports/workflow.port.ts";
import type { WorkflowStudioDispatchService } from "../services/workflow-studio-dispatch.service.ts";
import { WorkflowStudioCopyService } from "../services/workflow-studio-copy.service.ts";
import { WorkflowStudioVersionService } from "../services/workflow-studio-version.service.ts";

/** Whether one person may act on a project other than the scoped one. */
export interface WorkflowPermissionProbe {
  has(input: {
    userId: string;
    projectId: string;
    permission: AuthzPermission;
  }): Promise<boolean>;
  /**
   * The same probe for many projects at once. Bounded concurrency is the
   * process's concern - a workflow with many copies must not exhaust its
   * connection pool - so the cap lives with whoever owns the pool.
   */
  hasMany(input: {
    userId: string;
    projectIds: readonly string[];
    permission: AuthzPermission;
  }): Promise<ReadonlyMap<string, boolean>>;
}

/**
 * The reads a workflow's lineage and its archive cascade are made of: the
 * process's rows rather than this module's, since a copy names a project, a
 * team and an organization.
 */
export interface WorkflowLineageReads {
  listWithCopyLineage(input: {
    projectId: string;
  }): Promise<readonly WorkflowLineageRow[]>;
  findWorkflow(input: {
    workflowId: string;
    projectId: string;
  }): Promise<Readonly<{ projectId: string }> | null>;
  findCopiesWithPath(input: {
    workflowId: string;
    projectId: string;
  }): Promise<readonly WorkflowCopyWithPath[] | null>;
  findWorkflowWithSource(input: {
    workflowId: string;
    projectId: string;
  }): Promise<WorkflowSourceRow | null>;
  findWorkflowWithCopies(input: {
    workflowId: string;
    projectId: string;
  }): Promise<WorkflowCopiesRow | null>;
  /**
   * The latest version NUMBER of one workflow. Null when the workflow row is
   * gone; `version: null` when it exists but has no latest version.
   */
  findLatestVersionNumber(input: {
    workflowId: string;
    projectId: string;
  }): Promise<Readonly<{ version: string | null }> | null>;
  listAgents(input: {
    workflowId: string;
    projectId: string;
  }): Promise<readonly Readonly<{ id: string; name: string }>[]>;
  listMonitorsForEvaluators(input: {
    projectId: string;
    evaluatorIds: readonly string[];
  }): Promise<readonly Readonly<{ id: string; name: string; evaluatorId: string }>[]>;
  cascadeArchive(input: {
    projectId: string;
    workflowId: string;
    unarchive?: boolean;
  }): Promise<WorkflowCascadeArchive>;
}

/** The publication flags the Optimization Studio reads and writes. */
export interface WorkflowPublicationReads {
  findFlags(input: {
    workflowId: string;
    projectId: string;
  }): Promise<WorkflowPublicationFlags | null>;
  findVersion(input: {
    versionId: string;
    projectId: string;
  }): Promise<Readonly<Record<string, unknown>> | null>;
  setFlags(input: {
    workflowId: string;
    projectId: string;
    isComponent?: boolean;
    isEvaluator?: boolean;
  }): Promise<void>;
  listPublishedComponents(input: { projectId: string }): Promise<unknown>;
}

/** The model call behind an autogenerated commit message. */
export interface WorkflowCommitMessageWriter {
  generate(input: {
    projectId: string;
    previousDsl: string;
    nextDsl: string;
  }): Promise<string>;
}

/** Starting one evaluation run through the deployment's evaluations pipeline. */
export interface WorkflowEvaluationTrigger {
  trigger(input: WorkflowEvaluationRequest): Promise<WorkflowEvaluationStarted>;
}

/** One Monaco completion for the studio's code editor. */
export interface WorkflowCodeCompletions {
  complete(input: { projectId: string; body: unknown }): Promise<unknown>;
}

/** One streaming studio run, opened and read back event by event. */
export interface WorkflowStudioRuns {
  postEvent(input: {
    projectId: string;
    event: StudioClientEvent;
    onEvent: (event: StudioServerEvent) => void;
  }): Promise<void>;
}

/** Where a product signal and an unexpected failure go. */
export interface WorkflowSignals {
  workflowCreated(input: {
    userId: string;
    workflowCount: number;
    workflowId: string;
    projectId: string;
  }): void;
  failed(error: unknown, context: Readonly<{ projectId?: string }>): void;
}

/** What the process supplies this module beside its own graph. */
export interface WorkflowInfrastructure {
  /** Where a studio component executes; absent means nothing executes. */
  studioDispatch?: WorkflowStudioDispatchService;
  /** The ONE workflow graph service on this process. */
  workflows: WorkflowService;
  /** The evaluators a workflow is published as. */
  evaluators: EvaluatorApi;
  /** The dataset copies a Studio graph carries with it into another project. */
  datasets: DatasetApi;
  /** How a Studio graph is prepared before any version of it is written. */
  studioDsl: WorkflowStudioDslPort;
  /** The agent mappings a saved Studio graph refreshes, best effort. */
  agentMappings: WorkflowAgentMappingPort;
  /** The bare row a Studio copy lands in, before its first version exists. */
  workflowRows: WorkflowRowPort;
  permissions: WorkflowPermissionProbe;
  lineage: WorkflowLineageReads;
  publications: WorkflowPublicationReads;
  commitMessages: WorkflowCommitMessageWriter;
  evaluations: WorkflowEvaluationTrigger;
  codeCompletions: WorkflowCodeCompletions;
  studioRuns: WorkflowStudioRuns;
  signals: WorkflowSignals;
}

type WorkflowSetup = FeatureSetup<
  typeof WorkflowApp.dependencies,
  WorkflowInfrastructure,
  undefined
>;

/** The comparable text of a graph: local configuration stripped, keys sorted. */
function comparableDsl(dsl: StudioWorkflow): string {
  return JSON.stringify(recursiveAlphabeticallySortedKeys(clearDsl(dsl)), null, 2);
}

/** Every project id a workflow's copy lineage names, source and copies alike. */
function relatedProjectIdsOf(workflow: WorkflowLineageRow): readonly string[] {
  return [
    ...(workflow.copiedFrom ? [workflow.copiedFrom.projectId] : []),
    ...workflow.copiedWorkflows.map((copy) => copy.projectId),
  ];
}

export class WorkflowApp implements WorkflowApi {
  static readonly contract = WorkflowApi;
  static readonly dependencies = {} as const;

  static create(setup: WorkflowSetup): WorkflowApp {
    return new WorkflowApp(setup.infrastructure);
  }

  #infrastructure: WorkflowInfrastructure;
  #studioVersions: WorkflowStudioVersionService;
  #studioCopies: WorkflowStudioCopyService;

  private constructor(infrastructure: WorkflowInfrastructure) {
    this.#infrastructure = infrastructure;
    this.#studioVersions = WorkflowStudioVersionService.create({
      workflows: infrastructure.workflows,
      studioDsl: infrastructure.studioDsl,
      agentMappings: infrastructure.agentMappings,
    });
    this.#studioCopies = WorkflowStudioCopyService.create({
      datasets: infrastructure.datasets,
      rows: infrastructure.workflowRows,
    });
  }

  // -- the workflow itself ---------------------------------------------------

  async executeComponent(input: ExecuteWorkflowComponentInput) {
    const dispatch = this.#infrastructure.studioDispatch;

    if (!dispatch) throw new WorkflowExecutionFailedError();

    return dispatch.executeComponent(input);
  }

  /** Every non-archived workflow in the project. */
  list(input: { projectId: string }): Promise<Workflow[]> {
    return this.#infrastructure.workflows.list(input);
  }

  /** One workflow, optionally with its current version. */
  getById(input: {
    id: string;
    projectId: string;
    includeVersion?: boolean;
  }): Promise<WorkflowWithVersion> {
    return this.#infrastructure.workflows.getById(input);
  }

  /** Verifies that a workflow belongs to the requested project. */
  assertInProject(input: { workflowId: string; projectId: string }): Promise<void> {
    return this.#infrastructure.workflows.assertInProject(input);
  }

  listFields(input: { projectId: string; workflowIds: string[] }) {
    return this.#infrastructure.workflows.listFields(input);
  }

  listSummaries(input: { projectId: string; workflowIds: string[] }) {
    return this.#infrastructure.workflows.listSummaries(input);
  }

  archiveLinked(input: WorkflowReference) {
    return this.#infrastructure.workflows.archiveLinked(input);
  }

  deleteUncommitted(input: WorkflowReference) {
    return this.#infrastructure.workflows.deleteUncommitted(input);
  }

  /**
   * One studio event, resolved against the project it will run in: its
   * environment, its LiteLLM parameters and the datasets it names.
   */
  prepareStudioEvent(input: {
    event: StudioClientEvent;
    projectId: string;
  }): Promise<StudioClientEvent> {
    return this.#infrastructure.workflows.prepareStudioEvent(input);
  }

  /**
   * Creates a workflow and its first version, attributed to its caller, and
   * fires the product signal a project's new workflow raises. Attribution is
   * here because who wrote a version is a property of the act, not the door.
   */
  async create(
    input: Omit<CreateWorkflowCommand, "authorId">,
    by: WorkflowCaller,
  ): Promise<{ workflow: WorkflowWithVersion; version: WorkflowVersion }> {
    const created = await this.#infrastructure.workflows.create({ ...input, authorId: by.id });

    this.#announceCreated({ workflowId: created.workflow.id, projectId: input.projectId, by });

    return created;
  }

  /** Copies a workflow into another project, attributed to its caller. */
  copy(
    input: Omit<CopyWorkflowCommand, "authorId">,
    by: WorkflowCaller,
  ): Promise<{ workflow: WorkflowWithVersion; version: WorkflowVersion }> {
    return this.#infrastructure.workflows.copy({ ...input, authorId: by.id });
  }

  /** Changes a workflow's own metadata: its name, its icon, its description. */
  update(input: UpdateWorkflowCommand): Promise<Workflow> {
    return this.#infrastructure.workflows.update(input);
  }

  /** The version history of one workflow. */
  getVersionHistory(input: {
    workflowId: string;
    projectId: string;
    mode: WorkflowVersionHistoryMode;
  }): Promise<WorkflowVersionHistoryEntry[]> {
    return this.#infrastructure.workflows.getVersionHistory(input);
  }

  /** Makes a stored version current again. */
  restoreVersion(input: { versionId: string; projectId: string }): Promise<WorkflowVersion> {
    return this.#infrastructure.workflows.restoreVersion(input);
  }

  /** Publishes one version, attributed to the caller who asked for it. */
  publish(input: Omit<PublishWorkflowCommand, "actorId">, by: WorkflowCaller): Promise<Workflow> {
    return this.#infrastructure.workflows.publish({ ...input, actorId: by.id });
  }

  /** Withdraws the published version. */
  unpublish(input: { id: string; projectId: string }): Promise<Workflow> {
    return this.#infrastructure.workflows.unpublish(input);
  }

  /** Archives one workflow, or restores it when `unarchive` is set. */
  archive(input: ArchiveWorkflowCommand): Promise<Workflow> {
    return this.#infrastructure.workflows.archive(input);
  }

  /** Runs a workflow synchronously, on its published version unless one is named. */
  run(input: RunWorkflowCommand): Promise<WorkflowRunAnswer> {
    return this.#infrastructure.workflows.run(input);
  }

  /**
   * Runs the project's published workflow once, on the same service the public
   * run endpoint dispatches through.
   */
  runPublished(input: {
    workflowId: string;
    projectId: string;
    body: Readonly<Record<string, unknown>>;
  }): Promise<WorkflowRunAnswer> {
    return this.#infrastructure.workflows.run({
      workflowId: input.workflowId,
      projectId: input.projectId,
      inputs: { ...input.body },
    });
  }

  /** Starts one evaluation run of a committed version. */
  triggerEvaluation(input: WorkflowEvaluationRequest): Promise<WorkflowEvaluationStarted> {
    return this.#infrastructure.evaluations.trigger(input);
  }

  // -- the Studio's own save and copy ----------------------------------------

  /**
   * Prepares a Studio graph the way saving one does, without writing anything,
   * so what executes is the same graph a save would have persisted.
   */
  prepareStudioDsl(input: { projectId: string; dsl: StudioWorkflow }): Promise<StudioWorkflow> {
    return this.#studioVersions.prepareDsl(input);
  }

  /**
   * Writes a Studio graph as a version, attributed to the caller who asked for
   * it, and refreshes the agent mappings the new graph implies.
   */
  saveStudioVersion(
    input: {
      projectId: string;
      workflowId: string;
      dsl: StudioWorkflow;
      autoSaved: boolean;
      commitMessage: string;
      setAsLatestVersion?: boolean;
    },
    by: WorkflowCaller,
  ): Promise<WorkflowVersion> {
    return this.#studioVersions.saveOrCommit({ ...input, authorId: by.id });
  }

  /**
   * Copies a workflow into another project and answers the new row's id with
   * the graph rewritten to belong to it. The caller commits its first version.
   */
  copyStudioWorkflow(
    input: CopyStudioWorkflowCommand,
  ): Promise<{ workflowId: string; dsl: StudioWorkflow }> {
    return this.#studioCopies.copyWithDatasets(input);
  }

  completeCode(input: { projectId: string; body: unknown }): Promise<unknown> {
    return this.#infrastructure.codeCompletions.complete(input);
  }

  postStudioEvent(input: {
    projectId: string;
    event: StudioClientEvent;
    onEvent: (event: StudioServerEvent) => void;
  }): Promise<void> {
    return this.#infrastructure.studioRuns.postEvent(input);
  }

  reportStudioFailure(error: unknown, context: { projectId: string }): void {
    this.#infrastructure.signals.failed(error, context);
  }

  /**
   * A short commit message for the change between two graphs, both normalised
   * first - local configuration stripped, keys sorted - so a reordering never
   * reaches a model.
   */
  async generateCommitMessage(input: {
    projectId: string;
    prevDsl: StudioWorkflow;
    newDsl: StudioWorkflow;
  }): Promise<string> {
    const previousDsl = comparableDsl(input.prevDsl);
    const nextDsl = comparableDsl(input.newDsl);

    if (previousDsl === nextDsl) return "no changes";

    return await this.#infrastructure.commitMessages.generate({
      projectId: input.projectId,
      previousDsl,
      nextDsl,
    });
  }

  // -- the evaluator a published workflow is wrapped in -----------------------

  /** Every evaluator in the project. */
  listEvaluators(input: { projectId: string }): Promise<Evaluator[]> {
    return this.#infrastructure.evaluators.getAll(input);
  }

  /**
   * Create-or-rename rather than create: a workflow republished after a rename
   * must not leave the picker showing the old name, and a second evaluator for
   * one workflow would be two rows the picker cannot tell apart.
   */
  async linkEvaluatorToWorkflow(input: {
    workflowId: string;
    projectId: string;
    name: string;
  }): Promise<Evaluator> {
    const { workflowId, projectId, name } = input;
    const [existing] = await this.#infrastructure.evaluators.listByWorkflow({
      workflowId,
      projectId,
    });

    if (existing) {
      return this.#infrastructure.evaluators.update({
        id: existing.id,
        projectId,
        data: { name },
      });
    }

    return this.#infrastructure.evaluators.create({
      id: `evaluator_${nanoid()}`,
      projectId,
      name,
      type: "workflow",
      config: {},
      workflowId,
    });
  }

  /**
   * Nothing may keep an evaluator pointing at a workflow that no longer offers
   * itself as one. A workflow never published as an evaluator has nothing to
   * archive, which is a no-op rather than a refusal.
   */
  async unlinkEvaluatorFromWorkflow(input: {
    workflowId: string;
    projectId: string;
  }): Promise<void> {
    const [linked] = await this.#infrastructure.evaluators.listByWorkflow(input);

    if (!linked) return;

    await this.#infrastructure.evaluators.archive({
      id: linked.id,
      projectId: input.projectId,
    });
  }

  // -- what the caller may see elsewhere -------------------------------------

  hasProjectPermission(input: {
    userId: string;
    projectId: string;
    permission: AuthzPermission;
  }): Promise<boolean> {
    return this.#infrastructure.permissions.has(input);
  }

  // -- copy lineage, related entities and the archive cascade ----------------

  /**
   * The project's workflows, with copy lineage redacted to what the caller may
   * see: a source workflow in a project they cannot view is hidden entirely,
   * and the copy count only counts copies they can view.
   */
  async listWithCopyLineage(input: {
    projectId: string;
    viewerUserId: string;
  }): Promise<WorkflowListRow[]> {
    const workflows = await this.#infrastructure.lineage.listWithCopyLineage({
      projectId: input.projectId,
    });

    const relatedProjectIds = [...new Set(workflows.flatMap(relatedProjectIdsOf))];
    const probed = await this.#infrastructure.permissions.hasMany({
      userId: input.viewerUserId,
      projectIds: relatedProjectIds.filter((projectId) => projectId !== input.projectId),
      permission: "workflows:view",
    });
    const isVisible = (projectId: string) =>
      projectId === input.projectId || probed.get(projectId) === true;

    return workflows.map(({ copiedWorkflows, ...workflow }) => {
      const canSeeSource = workflow.copiedFrom !== null && isVisible(workflow.copiedFrom.projectId);

      return {
        ...workflow,
        copiedFromWorkflowId: canSeeSource ? workflow.copiedFromWorkflowId : null,
        copiedFrom: canSeeSource ? workflow.copiedFrom : null,
        _count: {
          copiedWorkflows: copiedWorkflows.filter((copy) => isVisible(copy.projectId)).length,
        },
      };
    });
  }

  findWorkflowOwner(input: {
    workflowId: string;
    projectId: string;
  }): Promise<Readonly<{ projectId: string }> | null> {
    return this.#infrastructure.lineage.findWorkflow(input);
  }

  findCopiesWithPath(input: {
    workflowId: string;
    projectId: string;
  }): Promise<readonly WorkflowCopyWithPath[] | null> {
    return this.#infrastructure.lineage.findCopiesWithPath(input);
  }

  findWorkflowWithSource(input: {
    workflowId: string;
    projectId: string;
  }): Promise<WorkflowSourceRow | null> {
    return this.#infrastructure.lineage.findWorkflowWithSource(input);
  }

  findWorkflowWithCopies(input: {
    workflowId: string;
    projectId: string;
  }): Promise<WorkflowCopiesRow | null> {
    return this.#infrastructure.lineage.findWorkflowWithCopies(input);
  }

  findLatestVersionNumber(input: {
    workflowId: string;
    projectId: string;
  }): Promise<Readonly<{ version: string | null }> | null> {
    return this.#infrastructure.lineage.findLatestVersionNumber(input);
  }

  /**
   * What archiving this workflow would take with it - the evaluators and
   * agents bound to it, and the monitors those evaluators back.
   */
  async getRelatedEntities(input: {
    workflowId: string;
    projectId: string;
  }): Promise<WorkflowRelatedEntities> {
    const evaluators = (await this.listEvaluators({ projectId: input.projectId }))
      .filter((evaluator) => evaluator.workflowId === input.workflowId)
      .map(({ id, name }) => ({ id, name }));

    // Copied out of the readonly views: the confirmation dialog these lists
    // feed types them as plain arrays, and a readonly element type would
    // narrow a client payload that is identical on the wire.
    const agents = [...(await this.#infrastructure.lineage.listAgents(input))];

    const evaluatorIds = evaluators.map((evaluator) => evaluator.id);
    const monitors =
      evaluatorIds.length > 0
        ? [
            ...(await this.#infrastructure.lineage.listMonitorsForEvaluators({
              projectId: input.projectId,
              evaluatorIds,
            })),
          ]
        : [];

    return { evaluators, agents, monitors };
  }

  /**
   * Archives the workflow and everything downstream of it in one transaction:
   * linked evaluators and agents are archived, and the monitors those
   * evaluators back are deleted outright.
   */
  cascadeArchive(input: {
    projectId: string;
    workflowId: string;
    unarchive?: boolean;
  }): Promise<WorkflowCascadeArchive> {
    return this.#infrastructure.lineage.cascadeArchive(input);
  }

  // -- the Optimization Studio's publication flags ---------------------------

  findWorkflowFlags(input: {
    workflowId: string;
    projectId: string;
  }): Promise<WorkflowPublicationFlags | null> {
    return this.#infrastructure.publications.findFlags(input);
  }

  findWorkflowVersionById(input: {
    versionId: string;
    projectId: string;
  }): Promise<Readonly<Record<string, unknown>> | null> {
    return this.#infrastructure.publications.findVersion(input);
  }

  setWorkflowFlags(input: {
    workflowId: string;
    projectId: string;
    isComponent?: boolean;
    isEvaluator?: boolean;
  }): Promise<void> {
    return this.#infrastructure.publications.setFlags(input);
  }

  listPublishedComponents(input: { projectId: string }): Promise<unknown> {
    return this.#infrastructure.publications.listPublishedComponents(input);
  }

  /**
   * Fire-and-forget: the count is read after the write landed, and a failure
   * to count must never fail the create that already succeeded.
   */
  #announceCreated(input: { workflowId: string; projectId: string; by: WorkflowCaller }): void {
    void this.#infrastructure.workflows
      .list({ projectId: input.projectId })
      .then((workflows) => {
        this.#infrastructure.signals.workflowCreated({
          userId: input.by.id,
          workflowCount: workflows.length,
          workflowId: input.workflowId,
          projectId: input.projectId,
        });
      })
      .catch((error: unknown) => {
        this.#infrastructure.signals.failed(error, { projectId: input.projectId });
      });
  }
}
