import { chromium } from "playwright";
const APP = process.env.APP_BASE;
const browser = await chromium.launch({ headless: true });
const ctx = await browser.newContext({ ignoreHTTPSErrors: true, viewport: { width: 1440, height: 900 } });
const p0 = await ctx.newPage();
await p0.goto(`${APP}/auth/signin`, { waitUntil: "domcontentloaded", timeout: 90000 });
await p0.locator('input[type="email"]').fill("admin@mail.langwatch.localhost");
await p0.locator('input[type="password"]').fill("LocalHavenAdmin!2026");
await p0.locator('button[type="submit"]').click();
await p0.waitForURL((u) => !u.pathname.startsWith("/auth/signin"), { timeout: 90000 });
await p0.close();
const page = await ctx.newPage();
page.on("console", (m) => console.log(`[console.${m.type()}]`, m.text().slice(0, 500)));
page.on("pageerror", (e) => console.log("[pageerror]", (e.stack ?? String(e)).slice(0, 900)));
page.on("requestfailed", (r) => console.log("[reqfail]", r.url().replace(APP, ""), r.failure()?.errorText));
const seen = []; page.on("response", (r) => { seen.push(`${r.status()} ${r.url().replace(APP, "").slice(0, 120)}`); });
await page.goto(`${APP}/settings/secrets`, { waitUntil: "domcontentloaded", timeout: 90000 });
await page.waitForTimeout(15000);
console.log("=== total responses", seen.length, "=== last 25 ===");
console.log(seen.slice(-25).join("\n"));
const html = await page.content();
console.log("\n=== #root innerHTML (first 1200) ===");
console.log(await page.locator("#root").innerHTML().catch(() => "(no #root)").then(h => h.slice(0,1200)));
console.log("\n=== html length ===", html.length);
await browser.close();
