import { chromium } from "playwright";
const APP = process.env.APP_BASE;
const b = await chromium.launch({ headless: true });
const ctx = await b.newContext({ ignoreHTTPSErrors: true, viewport: { width: 1600, height: 1000 } });
const p0 = await ctx.newPage();
await p0.goto(`${APP}/auth/signin`, { waitUntil: "domcontentloaded", timeout: 90000 });
await p0.locator('input[type="email"]').waitFor({ timeout: 60000 });
await p0.locator('input[type="email"]').fill("admin@mail.langwatch.localhost");
await p0.locator('input[type="password"]').fill("LocalHavenAdmin!2026");
await p0.locator('button[type="submit"]').click();
await p0.waitForURL((u) => !u.pathname.startsWith("/auth/signin"), { timeout: 90000 });
await p0.close();
const page = await ctx.newPage();
const seen = new Set();
page.on("request", (r) => {
  const u = r.url();
  if (!u.includes("analytics.getTimeseries")) return;
  const q = decodeURIComponent((u.split("?")[1] ?? "").replace(/^input=/, ""));
  if (seen.has(q)) return;
  seen.add(q);
  console.log("INPUT:", q);
});
await page.goto(`${APP}${process.env.ROUTE}`, { waitUntil: "domcontentloaded", timeout: 90000 });
await page.waitForTimeout(9000);
await b.close();
