import { chromium } from "playwright";
const APP = process.env.APP_BASE;
const browser = await chromium.launch({ headless: true });
const ctx = await browser.newContext({ ignoreHTTPSErrors: true });
const page = await ctx.newPage();
page.on("console", (m) => console.log(`[${m.type()}]`, m.text().slice(0, 600)));
page.on("pageerror", (e) => console.log("[pageerror]", (e.stack ?? String(e)).slice(0, 1500)));
page.on("response", (r) => { if (r.status() >= 400) console.log("[http]", r.status(), r.url().replace(APP, "").slice(0,140)); });
await page.goto(`${APP}/auth/signin`, { waitUntil: "domcontentloaded", timeout: 90000 });
await page.waitForTimeout(15000);
console.log("=== ROOT ===");
console.log((await page.locator("#root").innerHTML().catch(() => "(none)")).slice(0, 700));
await browser.close();
