/**
 * The execution half of {@link ApiTrpcCollaborators}: the three application
 * slices a run is dispatched through, and the three port groups the
 * `workflow.*`, `optimization.*`, `experiments.*` and `evaluations.*`
 * namespaces reach for.
 *
 * Four packaged surfaces are served from one composition, and they are one
 * composition because they are one graph:
 *
 *   workflow.*      the studio's own lifecycle — versions, copies, publication
 *   optimization.*  the studio's component and evaluator publication panel
 *   experiments.*   the wizard and the workbench
 *   evaluations.*   the evaluator inventory and one trace's re-score
 *
 * The workflow SERVICE is read by the evaluator service (a workflow published
 * as an evaluator), by the experiment service (a wizard experiment writes
 * workflow versions) and by the workflow application itself. Composing it more
 * than once would give this process two answers to "what is the current
 * version of this workflow", and the one that drifts is always the copy — so
 * it is built here once and handed out.
 *
 * A fifth thing is composed here and reached from outside tRPC: the workbench
 * RUN LOOP. The surfaces that start a run are REST routes rather than
 * procedures, but every collaborator a run needs — the Experiment service, the
 * workflow service, the dataset, prompt, agent and evaluator services, and the
 * `reportEvaluation` sender — is already in this scope, so the run is composed
 * beside them (`api-experiment-run.composition.ts`) rather than over a second
 * graph that could disagree with what the namespaces answer.
 *
 * ## The NLP engine is one address, and everything runs on it
 *
 * A Studio run, a code evaluator and the evaluator keep-alive all reach the
 * SAME engine through the SAME port. That is deliberate: a code evaluator is a
 * one-node Studio graph, and giving it a second dispatch path is what lets two
 * paths disagree about which trace an evaluation's spans belong to — the
 * orphan-trace failure the `traceparent` header exists to prevent. With no
 * engine address configured the port refuses by name, and the surfaces that do
 * not execute anything keep working.
 *
 * ## What arrives as an option, and why
 *
 * The MODEL GATEWAY still arrives as a required input rather than being built
 * here, and it is now built by the process rather than by a host: the six
 * ports `PostgresModelProviderAdapter` needs are composed in
 * `api-model-provider.composition.ts` over this process's own graph. It stays
 * an input because ONE gateway serves the whole process — the REST families,
 * the packaged namespaces and this half all read the same provider rows — and
 * a second composed here would be a second answer to which credential a
 * provider holds. A Studio node's model is resolved per run, so an absent
 * gateway still makes this whole half absent, which is a named absence rather
 * than a degradation: a workflow namespace mounted over a gateway that does
 * not exist would answer every run with an unattributable failure.
 *
 * The rest degrade FAIL-CLOSED, each with its own reason:
 *
 *   - `runEvaluationForTrace` reaches the trace read pipeline and the caller's
 *     content protections, neither of which this process composes. Absent, a
 *     re-score refuses by name rather than scoring against an empty trace.
 *   - `generateCommitMessage` reaches the model gateway behind the studio's
 *     autogenerated message. Absent, it refuses, and the studio's own text box
 *     is the answer.
 *   - `mappingsSchema` and `coerceMonitorMappings` are the TRACE-MAPPING
 *     registry's, and that registry now lives in a browser package. Server code
 *     may not value-import one, so the two default to a permissive parse and
 *     the narrowing they would have done is named here rather than silently
 *     lost.
 *   - `workflowCreated` and `trackEvaluationRan` are product signals. Absent,
 *     nothing is recorded — smaller, not wrong.
 *   - `captureException` defaults to this composition's own logger rather than
 *     the deployment's error sink.
 */
import { EventEmitter } from "node:events";
import type { ClickHouseClient } from "@clickhouse/client";
import { TupleParam } from "@clickhouse/client";
import type { AgentService } from "@langwatch/agent-contract";
import type { ApiKeyService } from "@langwatch/api-key-contract";
import type { EvaluatorService } from "@langwatch/evaluator-contract";
import { PostgresDatasetAdapter } from "@langwatch/dataset-server";
import type { DatasetService } from "@langwatch/dataset-contract";
import type { DatasetExperimentLookup } from "@langwatch/dataset-server";
import {
  AZURE_SAFETY_PROVIDER_KEY,
  type ReportEvaluationCommandData,
} from "@langwatch/evaluation-contract";
import {
  createEvaluationProcessingProducerPipeline,
  evaluatorUnavailability,
  type EvaluationRunOutcome,
} from "@langwatch/evaluation-server";
import {
  NlpEvaluatorCodeExecutionAdapter,
  PostgresEvaluatorAdapter,
  PrismaEvaluatorAuditLogAdapter,
} from "@langwatch/evaluator-server";
import type { EventSourcing } from "@langwatch/eventing";
import {
  ExperimentApp,
  ExperimentDspyRetentionPort,
  PostgresExperimentAdapter,
  workbenchStateSchema,
  type ExperimentBroadcast,
  type ExperimentTrpcPorts,
} from "@langwatch/experiment-server";
import { HandledError, NotFoundError } from "@langwatch/handled-error";
import type { ModelProviderService } from "@langwatch/model-provider-contract";
import { getProjectModelProviders } from "@langwatch/model-provider-server";
import type { MonitorService } from "@langwatch/monitor-contract";
import { PostgresMonitorAdapter } from "@langwatch/monitor-server";
import { createLogger, type Logger } from "@langwatch/observability";
import type { PrismaClient } from "@langwatch/prisma-client/generated";
import type { PromptService } from "@langwatch/prompt-contract";
import { PostgresPromptAdapter } from "@langwatch/prompt-server";
import type { RedisConnection } from "@langwatch/redis-client";
import {
  ContractWorkflowDslMigrationAdapter,
  HttpWorkflowNlpRuntimeAdapter,
  ModelProviderWorkflowStudioDslAdapter,
  PostgresWorkflowAdapter,
  PrismaWorkflowAgentMappingAdapter,
  PrismaWorkflowProjectEnvironmentAdapter,
  PrismaWorkflowRowAdapter,
  UnavailableWorkflowEnvironmentDecryptor,
  UnconfiguredWorkflowNlpRuntimeAdapter,
  WorkflowApp,
  WorkflowLlmParametersPort,
  type WorkflowEnvironmentDecryptor,
  type WorkflowLlmParameterResolution,
  type WorkflowNlpRuntimePort,
  type WorkflowOptimizationTrpcPorts,
  type WorkflowTrpcPorts,
} from "@langwatch/workflow-server";
import {
  WorkflowVersionRequiredError,
  type LLMConfig,
  type StudioWorkflow,
  type WorkflowService,
} from "@langwatch/workflow-contract";
import { nanoid } from "nanoid";
import type { ZodTypeAny } from "zod";
import { z } from "zod";
import type { EvaluationMountPorts } from "../features/evaluation/evaluation-trpc.mount";
import type { AnyApiTrpcCollaborators } from "../app-trpc/app-trpc.collaborators";
import type { ApiTrpcPortsContext } from "../app-trpc/app-trpc.context";
import {
  composeApiExperimentRun,
  composeApiExperimentRunCommands,
  type ApiExperimentRun,
  type ApiExperimentRunAbsenceReport,
} from "./api-experiment-run.composition";

/**
 * The retention floor a DSPy run read is bounded by when a project names no
 * policy of its own.
 *
 * The platform app's `PLATFORM_DEFAULT_RETENTION_DAYS`, stated for the same
 * reason the analytics half states it: the retention vertical has not moved,
 * and defaulting to something shorter would quietly truncate a run history on
 * a deployment that never changed a setting.
 */
const DEFAULT_RETENTION_DAYS = 49;

/** Everything the execution half is composed from. */
export type ApiExecutionCollaboratorsOptions = Readonly<{
  /** The one guarded connection every row read below runs on. */
  prisma: PrismaClient;
  /** Names this process in a refusal a stand-in raises. */
  processName: string;
  /**
   * The model gateway the studio resolves a node's model through.
   *
   * Required, and its absence is what makes this half absent — see the module
   * docblock.
   */
  modelProviders: ModelProviderService;
  /** The agent service this process already composes, for the wizard's references. */
  agents: AgentService;
  /** The application's own ClickHouse, or `null` where the process composed none. */
  resolveClickHouseClient: ((tenantId: string) => Promise<ClickHouseClient>) | null;
  /** Where the NLP engine answers; absent means nothing executes. */
  nlpServiceUrl: string | undefined;
  /** This deployment's public origin, for the studio's published-workflow run. */
  publicBaseUrl: string | undefined;
  /** The stored-secret cipher a project's run environment is decrypted with. */
  secretDecryptor: WorkflowEnvironmentDecryptor | undefined;
  /**
   * The producer-only eventing runtime the evaluation pipeline is registered
   * on, so a re-score reaches the same worker the ingestion path does.
   */
  eventing: EventSourcing | undefined;
  /**
   * The live-update channel a workbench cell is broadcast on. Absent means a
   * cell's result lands on the next read rather than as it happens.
   */
  broadcast?: ExperimentBroadcast;
  /** Scores one trace with one evaluator. Absent refuses by name. */
  runEvaluationForTrace?: NonNullable<
    EvaluationMountPorts<unknown, unknown>
  >["runEvaluationForTrace"];
  /** The model call behind the studio's autogenerated commit message. */
  generateCommitMessage?: (input: {
    projectId: string;
    previousDsl: string;
    nextDsl: string;
  }) => Promise<string>;
  /** The parser for a run's field mappings, when the deployment has the registry. */
  mappingsSchema?: ZodTypeAny;
  /** The canonicaliser for a monitor's stored mappings, same registry. */
  coerceMonitorMappings?: (mappings: unknown) => unknown;
  /** Product signal for a project's first workflow. */
  workflowCreated?: (input: {
    userId: string;
    workflowCount: number;
    workflowId: string;
    projectId: string;
  }) => void;
  /** Product signal for a completed evaluation run. */
  trackEvaluationRan?: (input: { userId: string; projectId: string }) => void;
  /** Where a fire-and-forget failure goes. */
  captureException?: (error: unknown) => void;
  /** The process environment, for the evaluator-install questions. */
  environment?: Readonly<Record<string, string | undefined>>;
  /**
   * The queue's Redis, where a run's abort flag and its progress both live.
   *
   * Absent means this process composes no RUN LOOP: it still mounts all four
   * namespaces and answers every read, and only starting a run refuses by
   * name. See `api-experiment-run.composition.ts` for why the progress store
   * is the thing that decides it.
   */
  redis?: RedisConnection | null;
  /**
   * The API-key service a run mints its sandbox credential through. Absent
   * means a run lends the code it executes no key and every row does its own
   * work, which is what a failed mint already means.
   */
  apiKeys?: ApiKeyService;
  /** Names the run loop's own absences at boot rather than leaving them inferred. */
  experimentRunReport?: ApiExperimentRunAbsenceReport;
}>;

/** The three application slices and the three port groups, composed together. */
export type ApiExecutionCollaborators = Readonly<{
  /** For `ctx.app.workflows`. */
  workflows: WorkflowApp;
  /** For `ctx.app.experiments`. */
  experiments: ExperimentApp;
  /** For `ctx.app.evaluations`. */
  evaluations: Readonly<{ reportEvaluation(data: never): Promise<unknown> }>;
  /** The `workflows` entry of {@link ApiTrpcCollaborators}. */
  workflowPorts: Readonly<{
    lifecycle: Partial<WorkflowTrpcPorts>;
    optimization: Partial<WorkflowOptimizationTrpcPorts<never, never>>;
  }>;
  /** The `experiments` entry. */
  experimentPorts: Partial<ExperimentTrpcPorts<unknown>>;
  /** The `evaluations` entry. */
  evaluationPorts: EvaluationMountPorts<unknown, unknown>;
  /** The evaluator service the workflow application publishes evaluators through. */
  evaluators: EvaluatorService;
  /**
   * The monitor service an experiment upserts its own monitor through.
   *
   * Published rather than kept private for the same reason the dataset service
   * is: the `monitors.*` surface answers from this ONE service, and a second
   * one over the same table would let the wizard's list disagree with what an
   * experiment just created.
   */
  monitors: MonitorService;
  /**
   * The dataset service the workflow and experiment applications read rows
   * through.
   *
   * Published rather than kept private because `dataset.*`, `datasetRecord.*`
   * and `batchRecord.*` answer from the SAME service: a project's rows are one
   * set, and a second connection-level service over them would be a second
   * answer to what a dataset contains.
   */
  datasets: DatasetService;
  /**
   * The experiment lookup a dataset resolves a borrowed name through, as the
   * dataset application asks for it.
   */
  experimentLookup: DatasetExperimentLookup;
  /**
   * The workbench RUN LOOP, over the same graph the four namespaces answer
   * from.
   *
   * Published rather than kept private because the surfaces that START a run
   * are REST routes, not tRPC procedures: `POST /api/experiments/execute`
   * streams one, `POST /api/experiments/{slug}/run` polls one, and
   * `POST /api/workflows/{id}/evaluate` triggers one. All three take this, and
   * they take THIS one so a run dispatches through the same studio, prices
   * against the same rate table and reports onto the same pipeline the
   * namespaces beside them already use.
   */
  experimentRun: ApiExperimentRun;
}>;

/**
 * A mapping state nobody narrowed.
 *
 * The registry that decides which sources a mapping may name moved into a
 * BROWSER package with the trace UI, and no server module may value-import
 * one. So this parses the shape and not the vocabulary: the mapping travels to
 * the evaluator exactly as the client sent it, which is what the platform app
 * did before the registry existed and is strictly what a permissive parse
 * means. The narrowing returns with the trace vertical.
 */
const permissiveMappingsSchema = z
  .object({
    mapping: z.record(z.string(), z.unknown()).default({}),
    expansions: z.array(z.string()).default([]),
  })
  .passthrough()
  .nullable();

/** The same shape, coerced rather than parsed, for a stored monitor row. */
const permissiveCoerceMonitorMappings = (mappings: unknown): unknown => {
  if (typeof mappings !== "object" || mappings === null || Array.isArray(mappings)) {
    return { mapping: {}, expansions: [] };
  }
  if (!("mapping" in mappings)) return { mapping: {}, expansions: [] };
  const parsed = permissiveMappingsSchema.safeParse(mappings);
  return parsed.success && parsed.data ? parsed.data : { mapping: {}, expansions: [] };
};

/**
 * The slug an experiment is saved under, as every slugged resource derives it.
 *
 * The three punctuation classes are replaced BEFORE the slug library runs,
 * because `strict` drops them silently and two names differing only by a colon
 * would otherwise collide on one slug.
 */
const slugify = (value: string): string =>
  value
    .replaceAll(/[:?&_]/g, "-")
    .normalize("NFKD")
    .replace(/[̀-ͯ]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");

/** Composes the execution half from this process's graph. */
export function composeApiExecutionCollaborators(
  options: ApiExecutionCollaboratorsOptions,
): ApiExecutionCollaborators {
  const logger = createLogger("langwatch:api:execution");
  const environment = options.environment ?? process.env;

  const nlpRuntime: WorkflowNlpRuntimePort = options.nlpServiceUrl
    ? HttpWorkflowNlpRuntimeAdapter.create({ serviceUrl: options.nlpServiceUrl })
    : UnconfiguredWorkflowNlpRuntimeAdapter.create();

  const datasets: DatasetService = PostgresDatasetAdapter.create({
    database: options.prisma,
  }).build();

  const workflows: WorkflowService = PostgresWorkflowAdapter.create({
    database: options.prisma,
    datasets,
    modelProviders: options.modelProviders,
    nlpRuntime,
    projectEnvironment: PrismaWorkflowProjectEnvironmentAdapter.create({
      database: options.prisma,
      encryption: options.secretDecryptor ?? UnavailableWorkflowEnvironmentDecryptor.create(),
    }),
    llmParameters: ApiWorkflowLlmParametersAdapter.create({
      modelProviders: options.modelProviders,
    }),
    dslMigration: ContractWorkflowDslMigrationAdapter.create(),
  });

  const evaluators: EvaluatorService = PostgresEvaluatorAdapter.create({
    database: options.prisma,
    workflows,
    auditLog: PrismaEvaluatorAuditLogAdapter.create(options.prisma),
    // The engine dispatches a code evaluator through the SAME runtime a Studio
    // run uses, which is the point: one path, one trace.
    codeExecution: NlpEvaluatorCodeExecutionAdapter.create(nlpRuntime),
    generateId: () => nanoid(),
  });

  const workflowApp = WorkflowApp.create({
    workflows,
    evaluators,
    datasets,
    studioDsl: ModelProviderWorkflowStudioDslAdapter.create({
      modelProviders: options.modelProviders,
    }),
    agentMappings: PrismaWorkflowAgentMappingAdapter.create({ database: options.prisma }),
    workflowRows: PrismaWorkflowRowAdapter.create({ database: options.prisma }),
  });

  const monitors = PostgresMonitorAdapter.create({
    database: options.prisma,
    evaluators,
    generateId: () => `monitor_${nanoid()}`,
  });

  // The run-history dispatchers, from a PRODUCER-only registration of the same
  // packaged definition the worker drains. Composed BEFORE the Experiment
  // service because the service is what validates and sends on them.
  const experimentRunCommands = composeApiExperimentRunCommands({
    eventing: options.eventing,
    processName: options.processName,
  });

  // Built once and handed to both the experiment application's reference set
  // and the run loop's data load: a prompt handle a run resolves and one the
  // workbench read resolves have to be the same version, and two services over
  // the same rows are two answers to which.
  const prompts: PromptService = PostgresPromptAdapter.create({
    database: options.prisma,
    modelProvider: options.modelProviders,
  }).build();

  const experiments = PostgresExperimentAdapter.create({
    database: options.prisma,
    // The adapter's own contract: `null` is a deployment without ClickHouse,
    // and its repository answers the refusal rather than this composition
    // guessing at one.
    resolveClickHouseClient: async (projectId) =>
      options.resolveClickHouseClient ? await options.resolveClickHouseClient(projectId) : null,
    tupleParam: (values) => new TupleParam(values),
    dspyRetention: FixedExperimentDspyRetention.create(DEFAULT_RETENTION_DAYS),
    runHistoryTelemetry: LoggedExperimentRunHistoryTelemetry.create(logger),
    slugify,
    newId: () => nanoid(8),
    references: {
      prompts,
      agents: options.agents,
      evaluators,
      workflows,
      dataset: datasets,
    },
    // The run's history, written through this process's own producer-only
    // registration. Absent only where the process composed no command queue,
    // and then the packaged `UnavailableExperimentExecutionAdapter` refuses by
    // name — which is what stops a run at its first cell rather than letting
    // it produce a history with a hole at the front.
    ...(experimentRunCommands ? { execution: experimentRunCommands } : {}),
    // Still no `updates`: this process broadcasts no cell, so a workbench cell
    // lands on the next read rather than as it happens. That is the packaged
    // no-op's documented shape, not a gap this composition is papering over.
  });

  const experimentApp = ExperimentApp.create({
    experiments,
    workflows,
    dataset: datasets,
    monitors,
    broadcast: options.broadcast ?? NO_BROADCAST,
  });

  const reportEvaluation = composeReportEvaluation({
    eventing: options.eventing,
    processName: options.processName,
  });

  // The run loop, over the SAME six services composed above. It is built here
  // rather than in the production root because everything it needs except a
  // Redis connection and the API-key service is already in this scope, and a
  // second Experiment service, workflow service or dataset service built for a
  // run would be a second answer to what an experiment holds.
  const experimentRun = composeApiExperimentRun({
    prisma: options.prisma,
    processName: options.processName,
    modelProviders: options.modelProviders,
    nlpServiceUrl: options.nlpServiceUrl,
    publicBaseUrl: options.publicBaseUrl,
    redis: options.redis,
    experiments,
    workflows,
    reportEvaluation,
    datasets,
    prompts,
    agents: options.agents,
    evaluators,
    apiKeys: options.apiKeys,
    ...(options.experimentRunReport ? { report: options.experimentRunReport } : {}),
  });

  const mappingsSchema = options.mappingsSchema ?? permissiveMappingsSchema;
  const captureException =
    options.captureException ??
    ((error: unknown) => logger.error({ error }, "workflow surface reported a failure"));

  return {
    workflows: workflowApp,
    experiments: experimentApp,
    evaluations: { reportEvaluation: reportEvaluation as (data: never) => Promise<unknown> },
    evaluators,
    monitors,
    datasets,
    experimentLookup: experiments,
    experimentRun,

    workflowPorts: {
      lifecycle: {
        prepareDsl: (_ctx, input) => workflowApp.prepareStudioDsl(input),
        saveWorkflowVersion: (ctx, input) =>
          workflowApp.saveStudioVersion(input, { id: actorId(ctx) }),
        generateCommitMessage: async (_ctx, input) => {
          if (!options.generateCommitMessage) {
            throw new ExecutionCapabilityUnavailableError(
              "model gateway, so it cannot write a commit message for you",
            );
          }
          return await options.generateCommitMessage(input);
        },
        workflowCreated: (_ctx, input) => options.workflowCreated?.(input),
        captureException,
      },
      optimization: {
        /**
         * The studio's chat panel runs the project's published workflow over
         * the SAME public run endpoint an external caller uses, authenticated
         * as the project.
         *
         * Deliberately an outbound call rather than an in-process one: what
         * the panel exercises is what a customer's integration exercises, so a
         * break in the public path is visible in the studio rather than only
         * in a customer's logs.
         */
        runPublishedWorkflow: async (_ctx, input) => {
          if (!options.publicBaseUrl) {
            throw new ExecutionCapabilityUnavailableError(
              "public base URL, so the studio cannot call its own workflow endpoint",
            );
          }
          const project = await options.prisma.project.findFirst({
            where: { id: input.projectId },
            select: { apiKey: true },
          });
          const response = await fetch(
            `${options.publicBaseUrl.replace(/\/$/, "")}/api/workflows/${input.workflowId}/run`,
            {
              method: "POST",
              body: JSON.stringify(input.body),
              headers: {
                "Content-Type": "application/json",
                ...(project?.apiKey ? { "x-auth-token": project.apiKey } : {}),
              },
            },
          );
          return await response.json();
        },
      },
    },

    experimentPorts: {
      workbenchStateSchema: workbenchStateSchema as never,
      slugify,
      saveWorkflowVersion: (ctx, input) =>
        workflowApp.saveStudioVersion(input, { id: actorId(ctx) }),
      /**
       * A copy whose SOURCE has no version cannot be copied, and the studio
       * renders that as "not found" rather than as a failure of the copy.
       * The refusal is the feature's; translating it for this transport is
       * this process's, which is why it is caught here and nowhere deeper.
       */
      copyWorkflowWithDatasets: async (_ctx, input) => {
        try {
          return await workflowApp.copyStudioWorkflow(input);
        } catch (error) {
          if (error instanceof WorkflowVersionRequiredError) {
            throw new NotFoundError("workflow_version_not_found", "Workflow version", input.workflow.id);
          }
          throw error;
        }
      },
      coerceMonitorMappings: options.coerceMonitorMappings ?? permissiveCoerceMonitorMappings,
      upsertExperimentMonitor: async (_ctx, { projectId, experimentId, monitor }) =>
        await monitors.upsertForExperiment({
          projectId,
          experimentId,
          name: monitor.name,
          checkType: monitor.checkType,
          slug: monitor.slug,
          preconditions: monitor.preconditions,
          parameters: monitor.parameters,
          mappings: monitor.mappings,
          sample: monitor.sample,
          enabled: monitor.enabled,
          executionMode: monitor.executionMode,
        } as never),
    },

    evaluationPorts: {
      mappingsSchema: mappingsSchema as never,

      /**
       * Azure Content Safety credentials come solely from the project's
       * `azure_safety` model provider. There is no `process.env` fallback, so
       * an unconfigured provider deterministically resolves to null and the
       * package reports every Azure variable as missing.
       *
       * Spec: specs/evaluators/azure-safety-byok-gating.feature.
       */
      tryResolveAzureSafetyEnv: async (_ctx, input) => {
        const providers = await getProjectModelProviders(
          options.modelProviders,
          input.projectId,
        );
        const provider = providers[AZURE_SAFETY_PROVIDER_KEY];
        if (!provider?.enabled) return null;

        const endpoint = provider.customKeys?.AZURE_CONTENT_SAFETY_ENDPOINT;
        const key = provider.customKeys?.AZURE_CONTENT_SAFETY_KEY;
        if (typeof endpoint !== "string" || endpoint.trim() === "") return null;
        if (typeof key !== "string" || key.trim() === "") return null;

        return {
          AZURE_CONTENT_SAFETY_ENDPOINT: endpoint,
          AZURE_CONTENT_SAFETY_KEY: key,
        };
      },

      evaluatorUnavailability: (input) =>
        evaluatorUnavailability({ evaluatorType: input.evaluatorType, environment }),

      missingEnvironmentVariables: (envVars) =>
        [...envVars].filter((name) => !environment[name]),

      runEvaluationForTrace: async (ctx, input) => {
        if (!options.runEvaluationForTrace) {
          throw new ExecutionCapabilityUnavailableError(
            "trace read pipeline, so it cannot score a trace on demand",
          );
        }
        return (await options.runEvaluationForTrace(ctx, input)) as EvaluationRunOutcome;
      },

      trackEvaluationRan: (input) => options.trackEvaluationRan?.(input),

      /**
       * One liveness probe at the evaluator backend.
       *
       * The platform app sent this down the engine's STREAMING route, which is
       * the per-project Lambda path this process does not carry. Same engine,
       * same process warmed; a probe that is not answered warmed nothing,
       * which is why the failure is swallowed rather than raised.
       */
      sendKeepAliveProbe: async (_ctx, input) => {
        if (!(nlpRuntime instanceof HttpWorkflowNlpRuntimeAdapter)) return;
        try {
          await nlpRuntime.probe({ projectId: input.projectId });
        } catch (error) {
          logger.debug({ error, projectId: input.projectId }, "evaluator keep-alive probe failed");
        }
      },
    } as EvaluationMountPorts<unknown, unknown>,
  };
}

/**
 * Registers the `evaluation_processing` pipeline as a PRODUCER and hands back
 * its `reportEvaluation` sender.
 *
 * The SAME packaged definition the worker installs — nothing here forks it,
 * because the routing triple every job carries is derived from the pipeline
 * and command names, and two descriptions of one event stream drift into jobs
 * the worker cannot route. Registration is passive: this process starts no
 * consumer loop and owns no event log.
 *
 * With no eventing runtime the command refuses by name rather than resolving.
 * A re-score that silently reported nothing would leave the customer looking
 * at a result the analytics never received.
 */
function composeReportEvaluation(input: {
  eventing: EventSourcing | undefined;
  processName: string;
}): (data: ReportEvaluationCommandData) => Promise<unknown> {
  if (!input.eventing) {
    return () =>
      Promise.reject(
        new ExecutionCapabilityUnavailableError(
          "command queue, so it cannot report an evaluation to the processing pipeline",
        ),
      );
  }

  const registered = input.eventing.register(
    createEvaluationProcessingProducerPipeline({ processName: input.processName }),
  );
  const sender = (registered.commands as Record<string, unknown>).reportEvaluation;
  if (!isSender(sender)) {
    throw new Error(
      "The evaluation_processing registration produced no \"reportEvaluation\" command sender; the pipeline was registered incompletely.",
    );
  }
  return (data) => sender.send(data);
}

/** The one shape a command dispatcher has, checked rather than asserted. */
type CommandSender = { send(data: unknown): Promise<unknown> };
const isSender = (value: unknown): value is CommandSender =>
  typeof value === "object" &&
  value !== null &&
  typeof (value as CommandSender).send === "function";

/**
 * A capability this deployment did not compose, reported to the caller.
 *
 * A handled error rather than a bare throw: the boundary serialises its code,
 * which is what a client keys its own copy off, and every one of these is a
 * DEPLOYMENT gap an operator can act on rather than a customer mistake.
 */
class ExecutionCapabilityUnavailableError extends HandledError {
  declare readonly code: "service_unavailable";

  constructor(capability: string) {
    super("service_unavailable", `This deployment has no ${capability}.`, {
      httpStatus: 503,
      fault: "platform",
    });
    this.name = "ExecutionCapabilityUnavailableError";
  }
}

/** The caller of one request, as the ports above read it. */
const actorId = (ctx: unknown): string => (ctx as ApiTrpcPortsContext).actor().id;

/** A deployment with no live-update channel: a workbench cell lands on read. */
const NO_BROADCAST: ExperimentBroadcast = (() => {
  const emitters = new Map<string, EventEmitter>();
  return {
    getTenantEmitter: (projectId: string) => {
      const existing = emitters.get(projectId);
      if (existing) return existing;
      const emitter = new EventEmitter();
      emitters.set(projectId, emitter);
      return emitter;
    },
    cleanupTenantEmitter: (projectId: string) => {
      emitters.delete(projectId);
    },
  };
})();

/**
 * The LiteLLM parameters one Studio run executes each of its models with.
 *
 * Lives in this process rather than in `@langwatch/workflow-server` because it
 * is a CROSS-FEATURE bridge: it reads the model-provider vertical's legacy
 * execution shape, and a feature server package may not depend on another
 * feature's server package. The composition root is where two features meet.
 *
 * The three-way answer per model is the platform app's and is preserved: a
 * provider the project never configured, one configured but switched off, and
 * one that is on and hands back prepared credentials. The studio renders those
 * three differently, so collapsing any two changes what a person is told about
 * why their run will not start. The provider rows themselves never leave here.
 */
class ApiWorkflowLlmParametersAdapter extends WorkflowLlmParametersPort {
  static create(input: {
    modelProviders: ModelProviderService;
  }): ApiWorkflowLlmParametersAdapter {
    return new ApiWorkflowLlmParametersAdapter(input.modelProviders);
  }

  private constructor(private readonly modelProviders: ModelProviderService) {
    super();
  }

  async resolve(input: {
    projectId: string;
    models: readonly LLMConfig["model"][];
  }): Promise<readonly WorkflowLlmParameterResolution[]> {
    const providers = await getProjectModelProviders(this.modelProviders, input.projectId);

    return await Promise.all(
      input.models.map(async (model) => {
        const provider = model.split("/")[0]!;
        const modelProvider = providers[provider];
        if (!modelProvider) {
          return { model, provider, configured: false, enabled: false };
        }
        if (!modelProvider.enabled) {
          return { model, provider, configured: true, enabled: false };
        }
        return {
          model,
          provider,
          configured: true,
          enabled: true,
          litellmParams: await this.modelProviders.prepareExecution({
            model,
            projectId: input.projectId,
          }),
        };
      }),
    );
  }
}

/**
 * The DSPy retention floor, fixed for this process.
 *
 * The data-retention vertical has not moved, so a per-project policy cannot be
 * resolved here. The deployment default is used for every project — which is
 * the answer for every project that never set one, and a longer window than
 * the floor for the few that did.
 */
class FixedExperimentDspyRetention extends ExperimentDspyRetentionPort {
  static create(days: number): FixedExperimentDspyRetention {
    return new FixedExperimentDspyRetention(days);
  }

  private constructor(private readonly days: number) {
    super();
  }

  getTraceRetentionDays(_tenantId: string): Promise<number> {
    return Promise.resolve(this.days);
  }
}

/**
 * Run-history telemetry, as this process reports it.
 *
 * The trace wrapper is a pass-through: this process's tracer wraps the REQUEST,
 * and a second span per run-history read would only restate the request it is
 * already inside. The three log lines are kept, because each names a condition
 * an operator acts on.
 */
class LoggedExperimentRunHistoryTelemetry {
  static create(logger: Pick<Logger, "warn" | "error">): LoggedExperimentRunHistoryTelemetry {
    return new LoggedExperimentRunHistoryTelemetry(logger);
  }

  private constructor(private readonly logger: Pick<Logger, "warn" | "error">) {}

  trace<T>(
    _input: { name: string; attributes: Record<string, string | number> },
    operation: () => Promise<T>,
  ): Promise<T> {
    return operation();
  }

  warnOldRuns(input: {
    projectId: string;
    oldestRunAgeDays: number;
    runCount: number;
    occurredAtBufferHours: number;
  }): void {
    this.logger.warn(input, "experiment run history reached far back in time");
  }

  error(
    input: { projectId: string; experimentId?: string; runId?: string; error: unknown },
    message: string,
  ): void {
    this.logger.error(input, message);
  }

  warn(input: { projectId: string; error: unknown }, message: string): void {
    this.logger.warn(input, message);
  }
}

/**
 * Folds the execution half into a collaborator set the process assembled from
 * its other halves.
 *
 * A function rather than a spread at the call site, for the reason the
 * analytics fold gives: the record is all-or-nothing, so a set that is
 * `undefined` stays `undefined` and an execution half that failed to compose
 * must not leave four namespaces answering with whatever was there before. It
 * composes with the other halves' own folds rather than competing with them —
 * each fills the entries it owns and passes the rest through untouched.
 */
export function withApiExecutionCollaborators(
  base: AnyApiTrpcCollaborators | undefined,
  execution: ApiExecutionCollaborators | undefined,
): AnyApiTrpcCollaborators | undefined {
  if (!base || !execution) return base;
  return {
    ...base,
    workflows: execution.workflowPorts,
    experiments: execution.experimentPorts,
    evaluations: execution.evaluationPorts,
    application: {
      ...base.application,
      workflows: execution.workflows,
      experiments: execution.experiments,
      evaluations: execution.evaluations,
    },
  } as AnyApiTrpcCollaborators;
}
