/** Generated from modules/catalogue.json. Do not edit by hand. */
/** Run `pnpm generate:modules` to rewrite it. */

/**
 * What each installed module's App declared it reads, in name order.
 *
 * Boot builds exactly this union, plus whatever each module's chosen
 * repository tier requires, and refuses by module and member when this
 * process cannot supply one.
 */
export const processModuleMembers = {
  agent: ["publicBaseUrl"],
  analytics: ["clickhouse", "clickhouseAdmin", "databaseTarget", "prisma", "publicBaseUrl", "rateLimiter"],
  annotation: [],
  "api-key": ["redis"],
  "audit-log": [],
  auth: ["isSaas", "nodeEnvironment", "publicBaseUrl"],
  authz: ["prisma", "redis"],
  automation: ["encryption", "logger", "publicBaseUrl"],
  "coding-agent": [],
  dashboard: ["publicBaseUrl"],
  "data-privacy": ["nodeEnvironment"],
  "data-retention": ["clickhouse", "nodeEnvironment", "redis"],
  dataset: ["objectStorage", "publicBaseUrl"],
  entitlement: ["isSaas", "logger", "processName"],
  evaluation: ["objectStorage"],
  evaluator: ["publicBaseUrl"],
  experiment: ["clickhouse", "isSaas", "logger", "prisma", "processName", "publicBaseUrl", "redis"],
  "feature-flag": [],
  gateway: ["clickhouse", "encryption", "prisma", "publicBaseUrl", "redis"],
  github: [],
  "hosted-mcp": ["encryption", "publicBaseUrl", "redis"],
  identity: ["encryption", "eventing", "isSaas", "prisma", "publicBaseUrl", "rateLimiter"],
  "instant-eval": ["nodeEnvironment", "redis"],
  langy: ["publicBaseUrl"],
  log: ["clickhouse"],
  metric: ["clickhouse"],
  "model-provider": ["nlpServiceUrl", "redis"],
  monitor: ["publicBaseUrl"],
  notification: ["outboundProxy", "publicBaseUrl"],
  onboarding: [],
  ops: ["clickhouse", "eventing", "isSaas", "logger", "nodeEnvironment", "prisma", "processName", "publicBaseUrl", "redis", "serviceVersion"],
  organization: ["encryption", "logger", "prisma", "processName", "publicBaseUrl", "redis"],
  "platform-health": ["publicBaseUrl"],
  presence: ["logger", "redis"],
  project: ["encryption", "logger"],
  prompt: ["logger", "publicBaseUrl", "rateLimiter"],
  role: ["prisma"],
  rum: ["logger", "telemetryExporter"],
  "sample-agents": ["logger", "publicBaseUrl"],
  scenario: ["clickhouse", "encryption", "isSaas", "nlpCodeBlockTimeoutSeconds", "nlpServiceUrl", "nodeEnvironment", "publicBaseUrl", "rateLimiter", "rawSocketPort", "redis"],
  secret: ["encryption"],
  share: ["redis"],
  slack: [],
  "stored-object": ["clickhouse", "encryption", "isSaas", "logger", "objectStorage", "publicBaseUrl", "rateLimiter"],
  suite: ["clickhouse", "publicBaseUrl", "redis"],
  topic: [],
  trace: ["clickhouse", "logger", "processName", "publicBaseUrl", "rateLimiter", "redis"],
  user: ["prisma", "publicBaseUrl", "redis"],
  webhook: ["isSaas", "outboundProxy", "rateLimiter"],
  workflow: ["encryption", "nlpCodeBlockTimeoutSeconds", "nlpServiceUrl", "prisma", "publicBaseUrl"],
  billing: ["isSaas", "nodeEnvironment", "publicBaseUrl"],
  "demo-data": [],
  "enterprise-gateway": ["isSaas"],
  "enterprise-ops": [],
  governance: ["encryption", "isSaas", "publicBaseUrl", "rateLimiter"],
  licensing: ["encryption", "isSaas", "logger", "prisma", "rateLimiter", "serviceVersion"],
  "managed-provider": [],
  nurturing: ["idempotency"],
  saas: ["isSaas"],
  scim: ["eventing"],
  sso: ["isSaas", "logger", "publicBaseUrl"],
} as const;
