/** Generated from modules/catalogue.json. Do not edit by hand. */
/** Run `pnpm generate:modules` to rewrite it. */

/**
 * What each installed module's App declared it reads, in name order.
 *
 * Boot builds exactly this union, plus whatever each module's chosen
 * repository tier requires, and refuses by module and member when this
 * process cannot supply one.
 */
export const serverModuleMembers = {
  agent: ["publicBaseUrl", "redis"],
  analytics: ["clickhouse", "langwatchQl", "publicBaseUrl", "rateLimiter"],
  annotation: [],
  "api-key": [],
  "audit-log": [],
  auth: ["isSaas", "nodeEnvironment", "publicBaseUrl"],
  authz: ["prisma", "redis"],
  automation: ["encryption", "isSaas", "logger", "mail", "prisma", "publicBaseUrl", "redis"],
  "coding-agent": [],
  dashboard: ["publicBaseUrl"],
  "data-privacy": ["dataPrivacy", "nodeEnvironment"],
  "data-retention": ["clickhouse", "nodeEnvironment"],
  dataset: ["content", "objectStorage", "publicBaseUrl", "queue"],
  entitlement: ["logger"],
  evaluation: ["objectStorage"],
  evaluator: ["prisma", "publicBaseUrl"],
  experiment: ["clickhouse", "logger", "prisma", "redis"],
  "feature-flag": [],
  gateway: [
    "clickhouse",
    "elevenLabsWebhook",
    "encryption",
    "gatewayInternalProtocol",
    "prisma",
    "publicBaseUrl",
  ],
  github: ["secrets"],
  "hosted-mcp": ["encryption", "publicBaseUrl", "redis"],
  identity: ["encryption", "eventing", "prisma", "rateLimiter"],
  "instant-eval": ["connectJudge", "redis"],
  langy: ["publicBaseUrl"],
  log: ["clickhouse"],
  metric: ["clickhouse"],
  "model-provider": ["redis"],
  monitor: ["monitor"],
  notification: [],
  onboarding: [],
  ops: [
    "adminEmails",
    "clickhouse",
    "eventing",
    "isSaas",
    "logger",
    "nodeEnvironment",
    "prisma",
    "processName",
    "publicBaseUrl",
    "redis",
    "serviceVersion",
  ],
  organization: ["encryption", "logger", "prisma", "redis"],
  "platform-health": ["publicBaseUrl", "secrets"],
  presence: ["logger", "redis"],
  project: ["encryption", "logger"],
  prompt: ["logger", "publicBaseUrl", "rateLimiter"],
  role: ["prisma"],
  scenario: [
    "clickhouse",
    "encryption",
    "idempotency",
    "isSaas",
    "nlpServiceUrl",
    "nodeEnvironment",
    "publicBaseUrl",
    "rateLimiter",
  ],
  secret: ["encryption"],
  share: ["redis"],
  "stored-object": [
    "clickhouse",
    "encryption",
    "isSaas",
    "logger",
    "objectStorage",
    "publicBaseUrl",
    "rateLimiter",
  ],
  suite: ["clickhouse", "publicBaseUrl", "redis"],
  topic: [],
  trace: ["clickhouse", "logger", "processName", "publicBaseUrl", "rateLimiter", "redis"],
  user: ["prisma", "redis"],
  webhook: ["isSaas", "rateLimiter", "redis"],
  workflow: ["encryption", "prisma"],
  billing: ["isSaas", "mail", "nodeEnvironment", "publicBaseUrl"],
  governance: ["encryption", "prisma"],
  licensing: ["logger", "prisma"],
  "managed-provider": [],
  saas: ["isSaas"],
  scim: [],
  sso: ["isSaas", "logger", "publicBaseUrl"],
} as const;
