-- Index the predicate the Langy session-key reaper sweeps on.
--
-- The reaper runs hourly (langy_maintenance pipeline) with:
--   WHERE "name" = 'Langy session' AND "revokedAt" IS NULL AND "expiresAt" <= now
-- and ApiKey carried indexes only on userId / organizationId / lookupId /
-- ingestSourceType / ingestionTemplateId. So every tick was a sequential scan
-- of the whole table — which grows monotonically, because reaped keys are
-- stamped with revokedAt rather than deleted.
--
-- PARTIAL, on the un-revoked rows only. `name` is NOT the selective column here:
-- one session key is minted per Langy chat turn and never deleted, so
-- 'Langy session' becomes the DOMINANT name in the table over time. What is
-- selective is `revokedAt IS NULL` — the reaper's own working set, which stays
-- roughly the size of the live-key population while the table grows without
-- bound. Putting that in the index PREDICATE rather than a leading column keeps
-- the index small permanently: reaped rows leave it instead of accumulating in
-- it. The remaining columns are the equality (`name`) then the range
-- (`expiresAt`), which is the correct leftmost-prefix order for the sweep.
--
-- Prisma cannot express a partial index, so this index is defined HERE and
-- deliberately absent from schema.prisma. Verified against this repo's Prisma
-- (5.7.1): `migrate diff` does not read index predicates, and with no `@@index`
-- declared it reports an empty diff against a database holding this index — so
-- there is no drift and no recreate. Declaring the `@@index` instead WOULD
-- drift (Prisma emits a CREATE INDEX for the non-partial form).
--
-- NOT built CONCURRENTLY: Prisma runs migrations inside a transaction and this
-- repo has no non-transactional migration setup (see
-- 20260426150000_drop_redundant_audit_log_org_index, which hit the same wall).
-- A plain CREATE INDEX takes a SHARE lock on ApiKey: reads keep running, WRITES
-- BLOCK for the whole build. That is not hypothetical traffic — `ApiKeyService
-- .markUsed` fires a fire-and-forget `apiKey.update({ lastUsedAt })` after every
-- successful API-key authorization, including trace ingest (collector.ts,
-- otel.ts), and `apiKey.create` runs on every Langy session-key mint. All of
-- them stall until the index is built. On a large deployment, build it by hand
-- with CREATE INDEX CONCURRENTLY first (same name, same definition) and this
-- becomes a no-op via IF NOT EXISTS.
CREATE INDEX IF NOT EXISTS "ApiKey_name_expiresAt_unrevoked_idx"
  ON "ApiKey"("name", "expiresAt")
  WHERE "revokedAt" IS NULL;
