// @langwatch/api/access -- the three access decisions both transports call.
// Neither runtime decides anything here itself: `decide` is the one check, and
// the permission vocabulary it reads belongs to `@langwatch/authz-contract`.

export {
  AccessWiringError,
  AuthenticationRequiredError,
  anyAuthenticated,
  assertRouteScopePermission,
  declareAccessMiddleware,
  decide,
  decideEntitlement,
  deferredScope,
  optionalCredential,
  publicRoute,
  routeScopeOf,
  SCOPE_INPUT_FIELDS,
  securityRequirement,
  sharedGrantTiers,
  type AccessActor,
  type AccessDecision,
  type AccessDeclaration,
  type AccessDenialPort,
  type ApiEntitlement,
  type AuthenticatedRouteAccess,
  type AuthorizePort,
  type Caller,
  type Credential,
  type DeferredScopeAccess,
  type EntitlementsPort,
  type OptionalCredentialAccess,
  type PermissionAllDeclaration,
  type PublicRouteAccess,
  type RouteAccess,
} from "./access.ts";
