"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.ShareOptionResponseModelType = void 0;
/** The type of the principal: user, group, or service account (under 'key'). */
exports.ShareOptionResponseModelType = {
    User: "user",
    Group: "group",
    Key: "key",
};
