"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.Currency = void 0;
exports.Currency = {
    Usd: "usd",
    Eur: "eur",
    Inr: "inr",
    Pln: "pln",
};
