MINIMUM_SUBTOPICS_PER_TOPIC = 1
MINIMUM_TRACES_PER_TOPIC = 5
COPHENETIC_DISTANCES_FOR_TOPICS = 4
COPHENETIC_DISTANCES_FOR_SUBTOPICS = 2

MINIMUM_UNASSIGNED_TRACES_TO_CREATE_NEW_TOPIC = 100
MINIMUM_UNASSIGNED_TRACES_TO_CREATE_NEW_SUBTOPIC = 50
