"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.ResourceAccessInfoAccessSource = void 0;
exports.ResourceAccessInfoAccessSource = {
    Creator: "creator",
    Explicit: "explicit",
    WorkspaceAdmin: "workspace_admin",
    WorkspaceDefault: "workspace_default",
};
