/**
 * The generated OpenAPI description of the LangWatch REST API, narrowed once
 * for every route that serves it.
 *
 * The document is the build artifact `src/app/api/openapiLangWatch.json`,
 * regenerated by `pnpm run task generateOpenAPISpec`. It is imported rather
 * than read from disk per request so the file resolves through the module
 * graph and cannot go missing at runtime in a deployment that only ships
 * compiled output.
 *
 * The typed shape of the import is a 1.8 MB object literal that no caller
 * benefits from. Narrowing it here keeps that type out of every handler's
 * inference, and out of every module that touches a router serving it.
 */
import openapiJson from "../../app/api/openapiLangWatch.json";

export const apiDocument = openapiJson as unknown as Record<string, unknown>;
