"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.SamplesClient = void 0;
const BaseClient_1 = require("../../../../../../BaseClient");
const Client_1 = require("../resources/audio/client/Client");
class SamplesClient {
    constructor(options = {}) {
        this._options = (0, BaseClient_1.normalizeClientOptions)(options);
    }
    get audio() {
        var _a;
        return ((_a = this._audio) !== null && _a !== void 0 ? _a : (this._audio = new Client_1.AudioClient(this._options)));
    }
}
exports.SamplesClient = SamplesClient;
