"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.BucketingStatus = void 0;
exports.BucketingStatus = {
    Pending: "pending",
    Completed: "completed",
    Failed: "failed",
};
