"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.WebhookToolApiSchemaConfigInputContentType = void 0;
/** Content type for the request body. Only applies to POST/PUT/PATCH requests. */
exports.WebhookToolApiSchemaConfigInputContentType = {
    ApplicationJson: "application/json",
    ApplicationXWwwFormUrlencoded: "application/x-www-form-urlencoded",
};
