// SPDX-License-Identifier: LicenseRef-LangWatch-Enterprise

/**
 * @vitest-environment node
 *
 * The Genie adapter's sweep — pagination, identity resolution, the watermark,
 * budget-cut resume, and sign-in — driven through `runOnce` against a real
 * fixture HTTP workspace.
 *
 * No database, no event-sourcing runtime: every claim here is about the
 * adapter's own output (`events`, `cursor`), the same boundary the sibling
 * `databricks-genie-warehouse-cost.integration.test.ts` file tests at. What
 * happens to that output once it reaches the OCSF projection is somebody
 * else's test.
 *
 * Most of what is asserted below is about NOT LOSING DATA — pagination that
 * stops early, a watermark that steps over unread history, one forbidden
 * space discarding five good ones. Those failures are silent by construction:
 * the run reports success and the missing records are simply never mentioned
 * again. They only exist as tests.
 */

import http from "http";
import type { AddressInfo } from "net";
import { afterEach, describe, expect, it } from "vitest";

import type { NormalizedPullEvent, PullResult } from "@langwatch/enterprise-governance-contract";
import { FetchHttpPort } from "../../__tests__/support/puller-test-ports";
import {
  DATABRICKS_GENIE_ADAPTER_ID,
  type DatabricksGeniePullConfig,
  DatabricksGeniePuller,
} from "../databricks-genie-puller.adapter";

/** Mirrors the adapter's own constant; asserted against, not imported by it. */
const WATERMARK_LAG_MS = 5 * 60 * 1000;

function decodeCursor(cursor: string | null): {
  sinceMs: number;
  spaceId: string | null;
  conversationId: string | null;
  sweepHadGap: boolean;
  spaceSetFingerprint: string | null;
  sweepStartedAtMs: number | null;
} {
  if (!cursor) throw new Error("expected a cursor");
  return JSON.parse(cursor);
}

/** The adapter's `extra` block for one event. */
function extensionOf(event: NormalizedPullEvent): Record<string, unknown> {
  return (event.extra ?? {}) as Record<string, unknown>;
}

function sqlAttachment(id: string, query: string, rowCount: number) {
  return {
    attachment_id: id,
    query: {
      query,
      description: "generated by genie",
      statement_id: `stmt-${id}`,
      query_result_metadata: { row_count: rowCount },
    },
  };
}

function message(params: {
  id: string;
  conversationId: string;
  spaceId: string;
  userId: number;
  content: string;
  createdMs: number;
  sql: string;
}) {
  return {
    message_id: params.id,
    conversation_id: params.conversationId,
    space_id: params.spaceId,
    user_id: params.userId,
    content: params.content,
    status: "COMPLETED",
    created_timestamp: params.createdMs,
    attachments: [
      { attachment_id: `txt-${params.id}`, text: { content: "Here you go." } },
      sqlAttachment(params.id, params.sql, 5),
    ],
  };
}

/** Two users: one carrying an IdP object id, one provisioned without. */
const USERS: Record<string, Record<string, string | null>> = {
  "700000000000001": {
    id: "700000000000001",
    userName: "dana.hoffman@acme.test",
    externalId: "11111111-2222-3333-4444-555555555555",
    displayName: "Dana Hoffman",
  },
  "700000000000002": {
    id: "700000000000002",
    userName: "priya.nair@acme.test",
    externalId: null,
    displayName: "Priya Nair",
  },
};

/** Nobody the directory knows — every SCIM lookup for this id 404s. */
const DELETED_USER_ID = 799_999_999_999_999;

const SPACE_TITLES: Record<string, string> = {
  "space-alpha": "ACME Revenue Analyst",
  "space-beta": "ACME Trip Analytics",
  "space-forbidden": "ACME Restricted",
  "space-loop": "ACME Broken Pagination",
  "space-orphan": "ACME Departed Analyst",
};

/**
 * A fixture Genie workspace.
 *
 * Built per suite rather than shared, because some scenarios mutate it
 * mid-sweep and one of them 403s — state leaking between them would make the
 * failures mean the wrong thing.
 */
function createFixtureWorkspace(options: { betaAgeMs?: number } = {}) {
  const now = Date.now();
  const alphaMs = now - 60 * 60 * 1000;
  const betaMs = now - (options.betaAgeMs ?? 30 * 60 * 1000);

  const conversations: Record<
    string,
    Array<{ conversation_id: string; title: string; created_timestamp: number }>
  > = {
    "space-alpha": [
      { conversation_id: "conv-alpha-1", title: "Top products", created_timestamp: alphaMs },
      { conversation_id: "conv-alpha-2", title: "Revenue by region", created_timestamp: alphaMs },
    ],
    "space-beta": [
      { conversation_id: "conv-beta-1", title: "Trip distance", created_timestamp: betaMs },
    ],
    "space-forbidden": [],
    "space-loop": [],
    "space-orphan": [
      {
        conversation_id: "conv-orphan-1",
        title: "Questions from a departed analyst",
        created_timestamp: alphaMs,
      },
    ],
  };

  const messages: Record<string, Array<ReturnType<typeof message>>> = {
    "conv-alpha-1": [
      message({
        id: "msg-alpha-1",
        conversationId: "conv-alpha-1",
        spaceId: "space-alpha",
        userId: 700_000_000_000_001,
        content: "What are the top 5 products by quantity sold?",
        createdMs: alphaMs,
        sql: "SELECT `product`, SUM(`quantity`) AS qty\nFROM `acme`.`sales`.`orders`\nGROUP BY `product`\nORDER BY qty DESC\nLIMIT 5",
      }),
    ],
    "conv-alpha-2": [
      message({
        id: "msg-alpha-2",
        conversationId: "conv-alpha-2",
        spaceId: "space-alpha",
        userId: 700_000_000_000_001,
        content: "Revenue by region last quarter?",
        createdMs: alphaMs,
        sql: "SELECT `region`, SUM(`revenue`) FROM `acme`.`sales`.`orders` GROUP BY `region`",
      }),
      message({
        id: "msg-alpha-3",
        conversationId: "conv-alpha-2",
        spaceId: "space-alpha",
        userId: 700_000_000_000_002,
        content: "And the quarter before that?",
        createdMs: alphaMs + 1_000,
        sql: "SELECT `region`, SUM(`revenue`) FROM `acme`.`sales`.`orders` WHERE `quarter` = 'Q3' GROUP BY `region`",
      }),
    ],
    "conv-orphan-1": [1, 2, 3].map((n) =>
      message({
        id: `msg-orphan-${n}`,
        conversationId: "conv-orphan-1",
        spaceId: "space-orphan",
        userId: DELETED_USER_ID,
        content: `Question ${n} from an account that no longer exists`,
        createdMs: alphaMs + n,
        sql: "SELECT 1",
      }),
    ),
    "conv-beta-1": [
      message({
        id: "msg-beta-1",
        conversationId: "conv-beta-1",
        spaceId: "space-beta",
        userId: 700_000_000_000_002,
        content: "What was the average trip distance by pickup zip code?",
        createdMs: betaMs,
        sql: "SELECT `pickup_zip`, AVG(`trip_distance`) AS avg_distance\nFROM `samples`.`nyctaxi`.`trips`\nGROUP BY `pickup_zip`",
      }),
    ],
  };

  return { conversations, messages, alphaMs, betaMs };
}

type FixtureWorkspace = ReturnType<typeof createFixtureWorkspace>;

/**
 * Serves the fixture workspace over real HTTP, with the pagination, the 403
 * and the broken page token the adapter has to survive.
 */
async function startFixtureServer(params: {
  workspace: FixtureWorkspace;
  onBeforeSpace?: (spaceId: string) => void;
  onMessages?: (conversationId: string) => Promise<void> | void;
  onScim?: (userId: string) => number | undefined;
  oauth?: {
    accessToken?: string;
    status?: number;
    body?: unknown;
    hang?: boolean;
  };
}): Promise<{
  baseUrl: string;
  conversationRequests: string[];
  requestCounts: Map<string, number>;
  oauthBasic: string[];
  bearersSeen: string[];
  close: () => Promise<void>;
}> {
  const { workspace } = params;
  const conversationRequests: string[] = [];
  const requestCounts = new Map<string, number>();
  const oauthBasic: string[] = [];
  const bearersSeen: string[] = [];
  const CONVERSATION_PAGE = 1;
  const MESSAGE_PAGE = 1;

  const server = http.createServer((req, res) => {
    handle(req, res).catch(() => {
      if (!res.headersSent) {
        res.statusCode = 500;
        res.end("{}");
      }
    });
  });

  async function handle(req: http.IncomingMessage, res: http.ServerResponse): Promise<void> {
    const url = new URL(req.url ?? "/", "http://localhost");
    const token = url.searchParams.get("page_token");
    requestCounts.set(url.pathname, (requestCounts.get(url.pathname) ?? 0) + 1);
    res.setHeader("content-type", "application/json");
    res.statusCode = 200;
    const send = (body: unknown) => res.end(JSON.stringify(body));

    if (url.pathname === "/oidc/v1/token") {
      const oauth = params.oauth;
      if (!oauth) {
        res.statusCode = 404;
        send({ error: "no token endpoint" });
        return;
      }
      const header = req.headers.authorization ?? "";
      const basic = /^Basic (.+)$/.exec(header);
      if (basic) {
        oauthBasic.push(Buffer.from(basic[1]!, "base64").toString("utf8"));
      }
      if (oauth.hang) return;
      if (oauth.status && oauth.status !== 200) {
        res.statusCode = oauth.status;
        send({ error: "invalid_client", error_description: "refused" });
        return;
      }
      send(
        oauth.body ?? {
          access_token: oauth.accessToken ?? "minted-token",
          token_type: "Bearer",
          expires_in: 3600,
        },
      );
      return;
    }

    const bearer = /^Bearer (.+)$/.exec(req.headers.authorization ?? "");
    if (bearer) bearersSeen.push(bearer[1]!);

    if (url.pathname === "/api/2.0/genie/spaces") {
      const ids = Object.keys(SPACE_TITLES);
      send({
        spaces: ids.map((space_id) => ({ space_id, title: SPACE_TITLES[space_id] ?? null })),
        next_page_token: null,
      });
      return;
    }

    const conversations = /^\/api\/2\.0\/genie\/spaces\/([^/]+)\/conversations$/.exec(url.pathname);
    if (conversations) {
      const spaceId = conversations[1]!;
      params.onBeforeSpace?.(spaceId);
      conversationRequests.push(url.search);

      if (spaceId === "space-forbidden") {
        res.statusCode = 403;
        send({ error_code: "PERMISSION_DENIED", message: "no access" });
        return;
      }
      if (spaceId === "space-loop") {
        send({ conversations: [], next_page_token: token ?? "stuck" });
        return;
      }
      if (url.searchParams.get("include_all") !== "true") {
        send({ conversations: [], next_page_token: null });
        return;
      }

      const all = workspace.conversations[spaceId] ?? [];
      const offset = token ? Number(token) : 0;
      const slice = all.slice(offset, offset + CONVERSATION_PAGE);
      const next = offset + CONVERSATION_PAGE;
      send({
        conversations: slice,
        next_page_token: next < all.length ? String(next) : null,
      });
      return;
    }

    const messages = /^\/api\/2\.0\/genie\/spaces\/[^/]+\/conversations\/([^/]+)\/messages$/.exec(
      url.pathname,
    );
    if (messages) {
      await params.onMessages?.(messages[1]!);
      const all = workspace.messages[messages[1]!] ?? [];
      const offset = token ? Number(token) : 0;
      const slice = all.slice(offset, offset + MESSAGE_PAGE);
      const next = offset + MESSAGE_PAGE;
      send({
        messages: slice,
        next_page_token: next < all.length ? String(next) : null,
      });
      return;
    }

    const scim = /^\/api\/2\.0\/preview\/scim\/v2\/Users\/([^/]+)$/.exec(url.pathname);
    if (scim) {
      const forced = params.onScim?.(scim[1]!);
      if (forced !== undefined) {
        res.statusCode = forced;
        send({ error: `forced ${forced}` });
        return;
      }
      const user = USERS[scim[1]!];
      if (!user) {
        res.statusCode = 404;
        send({ error: "not found" });
        return;
      }
      send(user);
      return;
    }

    res.statusCode = 404;
    send({ error: `unrouted ${url.pathname}` });
  }

  await new Promise<void>((resolve) => server.listen(0, "127.0.0.1", resolve));
  return {
    baseUrl: `http://127.0.0.1:${(server.address() as AddressInfo).port}`,
    conversationRequests,
    requestCounts,
    oauthBasic,
    bearersSeen,
    close: () => new Promise<void>((resolve) => server.close(() => resolve())),
  };
}

function genieConfig(params: {
  baseUrl: string;
  spaceIds: string[];
  startingAt: string;
  credentials?: Record<string, string>;
}): DatabricksGeniePullConfig {
  return DatabricksGeniePuller.create(new FetchHttpPort()).validateConfig({
    adapter: DATABRICKS_GENIE_ADAPTER_ID,
    workspaceUrl: params.baseUrl,
    spaceIds: params.spaceIds,
    startingAt: params.startingAt,
    schedule: "*/15 * * * *",
    credentials: params.credentials ?? { token: "fixture-token" },
  });
}

let closers: Array<() => Promise<void>> = [];
afterEach(async () => {
  await Promise.all(closers.map((close) => close()));
  closers = [];
});

async function sweep(params: {
  workspace: FixtureWorkspace;
  spaceIds: string[];
  startingAt?: string;
  fixtureOptions?: Omit<Parameters<typeof startFixtureServer>[0], "workspace">;
}): Promise<{
  outcome: PullResult;
  fixture: Awaited<ReturnType<typeof startFixtureServer>>;
}> {
  const fixture = await startFixtureServer({
    workspace: params.workspace,
    ...params.fixtureOptions,
  });
  closers.push(fixture.close);
  const adapter = DatabricksGeniePuller.create(new FetchHttpPort());
  const config = genieConfig({
    baseUrl: fixture.baseUrl,
    spaceIds: params.spaceIds,
    startingAt: params.startingAt ?? "2020-01-01T00:00:00.000Z",
  });
  const outcome = await adapter.runOnce(
    { cursor: null, credentials: { token: "fixture-token" } },
    config,
  );
  return { outcome, fixture };
}

describe("given a Genie workspace the credential can fully read", () => {
  async function sweepOk() {
    const workspace = createFixtureWorkspace();
    return sweep({ workspace, spaceIds: ["space-alpha", "space-beta"] });
  }

  /** @scenario "Every page of every list is read" */
  it("reads every page of every list, not just the first", async () => {
    const { outcome } = await sweepOk();
    expect(outcome.events.map((e) => e.source_event_id).sort()).toEqual(
      ["msg-alpha-1", "msg-alpha-2", "msg-alpha-3", "msg-beta-1"].sort(),
    );
  });

  /** @scenario "One record per question, carrying the question and the SQL" */
  it("carries the question and the SQL it generated", async () => {
    const { outcome } = await sweepOk();
    const alpha = outcome.events.find((e) => e.source_event_id === "msg-alpha-1")!;
    const extra = extensionOf(alpha);

    expect(alpha.action).toBe("genie_query");
    expect(alpha.target).toBe("ACME Revenue Analyst");
    expect(extra.question).toBe("What are the top 5 products by quantity sold?");
    expect(extra.generatedSql).toContain("`acme`.`sales`.`orders`");
    expect(extra.statementId).toBe("stmt-msg-alpha-1");
    expect(extra.rowCount).toBe(5);
  });

  /** @scenario "Every user's activity is captured, not just the caller's" */
  it("asks for every user's conversations, not just the caller's", async () => {
    const { fixture } = await sweepOk();
    expect(fixture.conversationRequests.length).toBeGreaterThan(0);
    for (const search of fixture.conversationRequests) {
      expect(search).toContain("include_all=true");
    }
  });

  /** @scenario "Identity resolves to the directory's object id when it has one" */
  it("keys a record on the IdP object id when the directory has one", async () => {
    const { outcome } = await sweepOk();
    const withObjectId = extensionOf(
      outcome.events.find((e) => e.source_event_id === "msg-alpha-1")!,
    );
    expect(withObjectId.actorKey).toBe("11111111-2222-3333-4444-555555555555");
    expect(withObjectId.actorEmail).toBe("dana.hoffman@acme.test");
  });

  /** @scenario "Identity falls back to the login when there is no object id" */
  it("keys a record on the login when the directory has no object id", async () => {
    const { outcome } = await sweepOk();
    const event = outcome.events.find((e) => e.source_event_id === "msg-beta-1")!;
    const withoutObjectId = extensionOf(event);

    expect(withoutObjectId.actorExternalId).toBe("");
    expect(withoutObjectId.actorKey).toBe("priya.nair@acme.test");
    expect(event.actor).toBe("priya.nair@acme.test");
  });

  it("anchors the watermark to when the sweep began, not to the newest message", async () => {
    const workspace = createFixtureWorkspace();
    const { outcome } = await sweep({ workspace, spaceIds: ["space-alpha", "space-beta"] });
    const cursor = decodeCursor(outcome.cursor);
    expect(cursor.sinceMs).toBeGreaterThan(workspace.betaMs);
    expect(cursor.sinceMs).toBeLessThanOrEqual(Date.now() - WATERMARK_LAG_MS);
    expect(cursor.spaceId).toBeNull();
  });
});

describe("given someone asks a question while a sweep is running", () => {
  async function sweepTwiceWithLateInjection() {
    const workspace = createFixtureWorkspace({ betaAgeMs: 10_000 });
    let injected = false;
    const fixture = await startFixtureServer({
      workspace,
      onBeforeSpace: (spaceId) => {
        if (spaceId !== "space-beta" || injected) return;
        injected = true;
        workspace.messages["conv-alpha-1"]!.push(
          message({
            id: "msg-alpha-late",
            conversationId: "conv-alpha-1",
            spaceId: "space-alpha",
            userId: 700_000_000_000_001,
            content: "Asked while the sweep was already past this space",
            createdMs: workspace.betaMs - 2_000,
            sql: "SELECT 1",
          }),
        );
      },
    });
    closers.push(fixture.close);
    const adapter = DatabricksGeniePuller.create(new FetchHttpPort());
    const config = genieConfig({
      baseUrl: fixture.baseUrl,
      spaceIds: ["space-alpha", "space-beta"],
      startingAt: "2020-01-01T00:00:00.000Z",
    });

    const first = await adapter.runOnce(
      { cursor: null, credentials: { token: "fixture-token" } },
      config,
    );
    const second = await adapter.runOnce(
      { cursor: first.cursor, credentials: { token: "fixture-token" } },
      config,
    );

    const injectedMsg = workspace.messages["conv-alpha-1"]!.find(
      (m) => m.message_id === "msg-alpha-late",
    )!;
    const newestSeen = Math.max(
      ...Object.values(workspace.messages)
        .flat()
        .filter((m) => m.message_id !== "msg-alpha-late")
        .map((m) => m.created_timestamp),
    );
    // The property that gives this scenario its teeth: the injected message
    // must be OLDER than the newest message the first sweep saw, or a
    // max-seen watermark would have caught it too and the scenario would
    // prove nothing.
    expect(injectedMsg.created_timestamp).toBeLessThan(newestSeen);

    return { first, second };
  }

  /** @scenario "Activity during a sweep is caught by the next one" */
  it("records the question the first sweep raced past", async () => {
    const { first, second } = await sweepTwiceWithLateInjection();
    expect(first.events.map((e) => e.source_event_id)).not.toContain("msg-alpha-late");
    expect(second.events.map((e) => e.source_event_id)).toContain("msg-alpha-late");
  }, 60_000);

  /** @scenario "A re-read message is recorded once" */
  it("keeps a message read by both sweeps as a single record", async () => {
    const { second } = await sweepTwiceWithLateInjection();
    // The lag window means the second run deliberately re-reads part of the
    // first's window; the adapter itself emits it once per run it is read in,
    // and de-duplication across runs is the sink's job (see
    // fold-read-back-store.feature). Within THIS run's output it appears once.
    const reRead = second.events.filter((e) => e.source_event_id === "msg-beta-1");
    expect(reRead).toHaveLength(1);
  }, 60_000);
});

describe("given one space the credential cannot read", () => {
  /** @scenario "One unreadable space does not discard the others" */
  it("still records everything the readable spaces held", async () => {
    const workspace = createFixtureWorkspace();
    const { outcome } = await sweep({
      workspace,
      spaceIds: ["space-alpha", "space-forbidden", "space-beta"],
    });
    expect(outcome.events.map((e) => e.source_event_id).sort()).toEqual(
      ["msg-alpha-1", "msg-alpha-2", "msg-alpha-3", "msg-beta-1"].sort(),
    );
  });

  /** @scenario "The watermark never moves past data that was not fetched" */
  it("holds the watermark, so nothing behind the failure is skipped", async () => {
    const workspace = createFixtureWorkspace();
    const { outcome } = await sweep({
      workspace,
      spaceIds: ["space-alpha", "space-forbidden", "space-beta"],
    });
    const cursor = decodeCursor(outcome.cursor);
    expect(cursor.sinceMs).toBe(Date.parse("2020-01-01T00:00:00.000Z"));
  });
});

describe("given a list endpoint whose page token never advances", () => {
  /** @scenario "Pagination that does not advance is refused" */
  it("refuses rather than re-reading the same page until the budget dies", async () => {
    const workspace = createFixtureWorkspace();
    const fixture = await startFixtureServer({ workspace });
    closers.push(fixture.close);
    const adapter = DatabricksGeniePuller.create(new FetchHttpPort(), { maxRequests: 5 });
    const config = genieConfig({
      baseUrl: fixture.baseUrl,
      spaceIds: ["space-loop"],
      startingAt: "2020-01-01T00:00:00.000Z",
    });
    const outcome = await adapter.runOnce(
      { cursor: null, credentials: { token: "fixture-token" } },
      config,
    );

    const requests =
      fixture.requestCounts.get("/api/2.0/genie/spaces/space-loop/conversations") ?? 0;
    expect(requests).toBeGreaterThan(0);
    expect(requests).toBeLessThan(5);

    expect(outcome.events).toHaveLength(0);
    expect(decodeCursor(outcome.cursor).sinceMs).toBe(Date.parse("2020-01-01T00:00:00.000Z"));
  }, 60_000);
});

describe("given messages by an author the directory no longer has", () => {
  /** @scenario "An author the directory no longer has is looked up once" */
  it("asks the directory once, and still records every question", async () => {
    const workspace = createFixtureWorkspace();
    const { outcome, fixture } = await sweep({ workspace, spaceIds: ["space-orphan"] });

    const lookups =
      fixture.requestCounts.get(`/api/2.0/preview/scim/v2/Users/${DELETED_USER_ID}`) ?? 0;
    expect(lookups).toBe(1);

    expect(outcome.events).toHaveLength(3);
    for (const event of outcome.events) {
      expect(extensionOf(event).question).not.toBe("");
      expect(event.actor).toBe("");
    }
  });
});

describe("given a sweep too large for one run's budget", () => {
  /** @scenario "A sweep cut short by its budget resumes where it stopped" */
  it("anchors the watermark to the FIRST run's start, not the last one's", async () => {
    const workspace = createFixtureWorkspace();
    const fixture = await startFixtureServer({ workspace });
    closers.push(fixture.close);
    const adapter = DatabricksGeniePuller.create(new FetchHttpPort());
    const config = genieConfig({
      baseUrl: fixture.baseUrl,
      spaceIds: ["space-alpha", "space-beta"],
      startingAt: "2020-01-01T00:00:00.000Z",
    });
    const credentials = { token: "fixture-token" };

    const beforeFirstRun = Date.now();
    const first = await adapter.runOnce(
      { cursor: null, credentials, deadlineMs: Date.now() - 1 },
      config,
    );
    const afterFirstRun = Date.now();

    const truncated = decodeCursor(first.cursor);
    expect(truncated.spaceId).toBe("space-alpha");
    expect(truncated.sweepStartedAtMs).not.toBeNull();
    expect(truncated.sinceMs).toBe(Date.parse("2020-01-01T00:00:00.000Z"));

    await new Promise((resolve) => setTimeout(resolve, 1_500));

    const beforeSecondRun = Date.now();
    const second = await adapter.runOnce({ cursor: first.cursor, credentials }, config);
    const done = decodeCursor(second.cursor);

    expect(done.sinceMs).toBeGreaterThanOrEqual(beforeFirstRun - WATERMARK_LAG_MS);
    expect(done.sinceMs).toBeLessThanOrEqual(afterFirstRun - WATERMARK_LAG_MS);
    expect(done.sinceMs).toBeLessThan(beforeSecondRun - WATERMARK_LAG_MS);

    expect(done.spaceId).toBeNull();
    expect(done.sweepStartedAtMs).toBeNull();
  }, 60_000);

  /** @scenario "A sweep cut short by its budget resumes where it stopped" */
  it("resumes at the cut space and loses no message from its tail", async () => {
    const workspace = createFixtureWorkspace();
    let slowedOnce = false;
    const fixture = await startFixtureServer({
      workspace,
      onMessages: async (conversationId) => {
        if (conversationId === "conv-alpha-1" && !slowedOnce) {
          slowedOnce = true;
          await new Promise((resolve) => setTimeout(resolve, 1_500));
        }
      },
    });
    closers.push(fixture.close);

    const adapter = DatabricksGeniePuller.create(new FetchHttpPort());
    const config = genieConfig({
      baseUrl: fixture.baseUrl,
      spaceIds: ["space-alpha", "space-beta"],
      startingAt: "2020-01-01T00:00:00.000Z",
    });
    const credentials = { token: "fixture-token" };

    const first = await adapter.runOnce(
      { cursor: null, credentials, deadlineMs: Date.now() + 800 },
      config,
    );
    const firstCursor = decodeCursor(first.cursor);

    expect(firstCursor.spaceId).toBe("space-alpha");
    expect(firstCursor.sinceMs).toBe(Date.parse("2020-01-01T00:00:00.000Z"));

    const second = await adapter.runOnce({ cursor: first.cursor, credentials }, config);
    const secondCursor = decodeCursor(second.cursor);

    const emitted = new Set([...first.events, ...second.events].map((e) => e.source_event_id));
    for (const id of ["msg-alpha-1", "msg-alpha-2", "msg-alpha-3", "msg-beta-1"]) {
      expect(emitted).toContain(id);
    }
    expect(secondCursor.spaceId).toBeNull();
    expect(secondCursor.sweepStartedAtMs).toBeNull();
  }, 60_000);
});

describe("given the directory fails while the sweep is running", () => {
  /** @scenario "A directory outage does not strip authors off the rest of the run" */
  it("asks the directory again rather than reusing the failure", async () => {
    const workspace = createFixtureWorkspace();
    const flakyUserId = "700000000000001";
    let lookups = 0;

    const fixture = await startFixtureServer({
      workspace,
      onScim: (userId) => {
        if (userId !== flakyUserId) return undefined;
        lookups += 1;
        return lookups === 1 ? 503 : undefined;
      },
    });
    closers.push(fixture.close);

    const adapter = DatabricksGeniePuller.create(new FetchHttpPort());
    const config = genieConfig({
      baseUrl: fixture.baseUrl,
      spaceIds: ["space-alpha"],
      startingAt: "2020-01-01T00:00:00.000Z",
    });

    const result = await adapter.runOnce(
      { cursor: null, credentials: { token: "fixture-token" } },
      config,
    );

    const byId = new Map(result.events.map((event) => [event.source_event_id, event]));
    const duringOutage = byId.get("msg-alpha-1");
    const afterOutage = byId.get("msg-alpha-2");
    expect(duringOutage).toBeDefined();
    expect(afterOutage).toBeDefined();

    expect(lookups).toBeGreaterThanOrEqual(2);
    expect(String(extensionOf(duringOutage!).actorEmail ?? "")).toBe("");
    expect(String(extensionOf(afterOutage!).actorEmail ?? "")).toBe("dana.hoffman@acme.test");
  }, 60_000);
});

// ---------------------------------------------------------------------------
// A source can sign in for itself, so a schedule outlives a pasted token.
// ---------------------------------------------------------------------------

describe("given a source that signs in with a service principal", () => {
  async function runWithServicePrincipal() {
    const workspace = createFixtureWorkspace();
    const fixture = await startFixtureServer({
      workspace,
      oauth: { accessToken: "minted-token" },
    });
    closers.push(fixture.close);
    const adapter = DatabricksGeniePuller.create(new FetchHttpPort());
    const credentials = { clientId: "sp-client-id", clientSecret: "sp-client-secret" };
    const config = genieConfig({
      baseUrl: fixture.baseUrl,
      spaceIds: ["space-alpha", "space-beta"],
      startingAt: "2020-01-01T00:00:00.000Z",
      credentials,
    });
    const outcome = await adapter.runOnce({ cursor: null, credentials }, config);
    return { outcome, fixture };
  }

  /** @scenario "A source given a client id and secret signs in for itself" */
  it("asks the workspace for a token with the client id and secret", async () => {
    const { fixture } = await runWithServicePrincipal();
    expect(fixture.oauthBasic).toEqual(["sp-client-id:sp-client-secret"]);
  });

  /** @scenario "Signing in happens once a run, not once a request" */
  it("signs in once a run, not once a request", async () => {
    const { fixture } = await runWithServicePrincipal();
    expect(fixture.requestCounts.get("/oidc/v1/token")).toBe(1);
    expect(fixture.requestCounts.get("/api/2.0/genie/spaces") ?? 0).toBeGreaterThan(0);
    expect(new Set(fixture.bearersSeen)).toEqual(new Set(["minted-token"]));
  });
});

describe("given a source holding a pasted token", () => {
  /** @scenario "A pasted token is still honoured" */
  it("does not ask the workspace for a token", async () => {
    const workspace = createFixtureWorkspace();
    // No `oauth` block at all: a sign-in would 404 and be impossible to miss.
    const fixture = await startFixtureServer({ workspace });
    closers.push(fixture.close);
    const adapter = DatabricksGeniePuller.create(new FetchHttpPort());
    const config = genieConfig({
      baseUrl: fixture.baseUrl,
      spaceIds: ["space-alpha"],
      startingAt: "2020-01-01T00:00:00.000Z",
    });
    await adapter.runOnce({ cursor: null, credentials: { token: "fixture-token" } }, config);
    expect(fixture.requestCounts.get("/oidc/v1/token")).toBeUndefined();
    expect(new Set(fixture.bearersSeen)).toEqual(new Set(["fixture-token"]));
  });

  /** @scenario "A pasted token wins over a client secret" */
  it("prefers a pasted token over a client secret", async () => {
    const workspace = createFixtureWorkspace();
    const fixture = await startFixtureServer({ workspace });
    closers.push(fixture.close);
    const adapter = DatabricksGeniePuller.create(new FetchHttpPort());
    const config = genieConfig({
      baseUrl: fixture.baseUrl,
      spaceIds: ["space-alpha"],
      startingAt: "2020-01-01T00:00:00.000Z",
    });
    await adapter.runOnce(
      {
        cursor: null,
        credentials: {
          token: "fixture-token",
          clientId: "sp-client-id",
          clientSecret: "sp-client-secret",
        },
      },
      config,
    );
    expect(fixture.requestCounts.get("/oidc/v1/token")).toBeUndefined();
  });
});

describe("given a source that cannot sign in", () => {
  /** Runs one sweep, returning the error the run threw (if any). */
  async function runWith(params: {
    credentials: Record<string, string>;
    oauth?: Parameters<typeof startFixtureServer>[0]["oauth"];
  }): Promise<{ error: Error | null; elapsedMs: number }> {
    const workspace = createFixtureWorkspace();
    const fixture = await startFixtureServer({ workspace, oauth: params.oauth });
    closers.push(fixture.close);
    const adapter = DatabricksGeniePuller.create(new FetchHttpPort());
    const config = genieConfig({
      baseUrl: fixture.baseUrl,
      spaceIds: ["space-alpha"],
      startingAt: "2020-01-01T00:00:00.000Z",
      credentials: params.credentials,
    });
    const startedAt = performance.now();
    let error: Error | null = null;
    try {
      await adapter.runOnce({ cursor: null, credentials: params.credentials }, config);
    } catch (caught) {
      error = caught as Error;
    }
    return { error, elapsedMs: performance.now() - startedAt };
  }

  /** @scenario "A source with no way to sign in says so" */
  it("fails naming what it needs when given neither a token nor a secret", async () => {
    const { error } = await runWith({ credentials: {} });
    expect(error).not.toBeNull();
    expect(error?.message).toMatch(/token/i);
    expect(error?.message).toMatch(/client/i);
  });

  /** @scenario "Credentials the workspace rejects fail the run rather than emptying it" */
  it("fails the run when the workspace refuses the credentials", async () => {
    const { error } = await runWith({
      credentials: { clientId: "sp-client-id", clientSecret: "wrong" },
      oauth: { status: 401 },
    });
    expect(error).not.toBeNull();
    expect(error?.message).toMatch(/sign|token|auth/i);
  });

  /** @scenario "A refused sign-in does not put the secret in the reason" */
  it("does not put the client secret in the reason", async () => {
    const { error } = await runWith({
      credentials: { clientId: "sp-client-id", clientSecret: "super-secret-value" },
      oauth: { status: 401 },
    });
    expect(error).not.toBeNull();
    expect(JSON.stringify(error, Object.getOwnPropertyNames(error))).not.toContain(
      "super-secret-value",
    );
  });

  /** @scenario "A sign-in answered with no token fails the run" */
  it("fails when the sign-in is answered without a token", async () => {
    const { error } = await runWith({
      credentials: { clientId: "sp-client-id", clientSecret: "sp-secret" },
      oauth: { body: { message: "hello from a captive portal" } },
    });
    expect(error).not.toBeNull();
  });

  /** @scenario "A sign-in that hangs does not consume the whole run" */
  it("abandons a hanging sign-in well before the run's own deadline", async () => {
    const { error, elapsedMs } = await runWith({
      credentials: { clientId: "sp-client-id", clientSecret: "sp-secret" },
      oauth: { hang: true },
    });
    expect(error).not.toBeNull();
    expect(elapsedMs).toBeLessThan(60_000);
  }, 65_000);
});
