"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.CrawlStatus = void 0;
exports.CrawlStatus = {
    Queued: "queued",
    Processing: "processing",
    Succeeded: "succeeded",
    Failed: "failed",
    Skipped: "skipped",
    Cancelled: "cancelled",
};
