"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.ConversationFeedbackType = void 0;
exports.ConversationFeedbackType = {
    Thumbs: "thumbs",
    Rating: "rating",
};
