"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.TextToDialogueWebsocketApplyTextNormalizationEnum = void 0;
/** Text normalization mode for the WebSocket session. This endpoint defaults to `'off'` when omitted. */
exports.TextToDialogueWebsocketApplyTextNormalizationEnum = {
    On: "on",
    Off: "off",
};
