"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.InvoiceResponsePaymentIntentStatussesItem = void 0;
exports.InvoiceResponsePaymentIntentStatussesItem = {
    Canceled: "canceled",
    Processing: "processing",
    RequiresAction: "requires_action",
    RequiresCapture: "requires_capture",
    RequiresConfirmation: "requires_confirmation",
    RequiresPaymentMethod: "requires_payment_method",
    Succeeded: "succeeded",
};
