const fs = require("fs");
const path = require("path");

const processIncludes = (schemaContent, basePath) => {
  return schemaContent.replace(/@include "([^"]+)"/g, (_, includePath) => {
    const fullPath = path.join(basePath, includePath);
    return fs.readFileSync(fullPath, "utf8");
  });
};

const processExtends = (schemaContent) => {
  const extendMatches = [
    ...schemaContent.matchAll(/@extends\nmodel (\w+) \{([\s\S]*?)\}/g),
  ];

  for (const match of extendMatches) {
    const [extendBlock, modelName, fieldsToAdd] = match;
    const modelRegex = new RegExp(`(model ${modelName} \\{[\\s\\S]*?\\})`, "g");

    schemaContent = schemaContent.replace(extendBlock, ""); // Remove the @extends block
    schemaContent = schemaContent.replace(modelRegex, (modelMatch) => {
      return `${modelMatch.replace("}", "").trim()}\n  ${fieldsToAdd}}`;
    });
  }

  return schemaContent;
};

const processSchema = (templatePath) => {
  const basePath = path.dirname(templatePath);
  let schemaContent = fs.readFileSync(templatePath, "utf8");

  schemaContent =
    "// This file was auto-generated by generate-schema.js, don't change it by hand, change schema.saas.prisma instead\n\n" +
    schemaContent;

  schemaContent = processIncludes(schemaContent, basePath);
  schemaContent = processExtends(schemaContent);

  return schemaContent;
};

const outputPath = `${__dirname}/schema.prisma`;
const templatePath = `${__dirname}/schema.saas.prisma`;

const processedSchema = processSchema(templatePath);
fs.writeFileSync(outputPath, processedSchema);
console.log(`Processed schema written to ${outputPath}`);
