/**
 * @langwatch/identity-contract — the isomorphic identity core (ADR-101,
 * ADR-115). Both sides import it verbatim, so it reads and writes nothing —
 * just the vocabulary, shapes, reducer and refusal errors both must agree on.
 */
export {
  type BackfillDiff,
  type BackfillIdentifierRow,
  backfillParityDiffs,
  type ExpectedIdentifier,
  identifierStateSatisfies,
  orphanedIdentifierRows,
} from "./backfill.ts";
export {
  CONNECTION_ACTIVATED_EVENT_TYPE,
  CONNECTION_DISCARDED_EVENT_TYPE,
  CONNECTION_ARRIVAL_POLICY_SET_EVENT_TYPE,
  CONNECTION_REGISTERED_EVENT_TYPE,
  CONNECTION_RESUMED_EVENT_TYPE,
  CONNECTION_SUSPENDED_EVENT_TYPE,
  CONNECTION_TORN_DOWN_EVENT_TYPE,
  compareConnectionRouting,
  type ConnectionRoutingComparison,
  type ConnectionRoutingFacts,
  connectionActivatedPayloadSchema,
  connectionDiscardedPayloadSchema,
  connectionRegisteredPayloadSchema,
  connectionResumedPayloadSchema,
  connectionSuspendedPayloadSchema,
  connectionTornDownPayloadSchema,
  DOMAIN_CLAIM_APPROVED_EVENT_TYPE,
  DOMAIN_CLAIM_REJECTED_EVENT_TYPE,
  DOMAIN_CLAIMED_EVENT_TYPE,
  DOMAIN_ATTESTED_EVENT_TYPE,
  DOMAIN_WITHDRAWN_EVENT_TYPE,
  DOMAIN_PROOF_LAPSED_EVENT_TYPE,
  DOMAIN_PROOF_RECOVERED_EVENT_TYPE,
  DOMAIN_PROOF_WAVERED_EVENT_TYPE,
  DOMAIN_VERIFIED_EVENT_TYPE,
  domainAttestedPayloadSchema,
  domainClaimApprovedPayloadSchema,
  domainClaimRejectedPayloadSchema,
  domainClaimedPayloadSchema,
  domainProofLapsedPayloadSchema,
  domainProofRecoveredPayloadSchema,
  domainProofWaveredPayloadSchema,
  domainVerifiedPayloadSchema,
  domainWithdrawnPayloadSchema,
  emptySsoConnection,
  isSsoArrivalPolicy,
  isSsoPublishedProofChannel,
  verificationHasExpired,
  reduceSsoConnection,
  routingFactsOf,
  routingStateOf,
  DEFAULT_SSO_ARRIVAL_POLICY,
  SSO_ARRIVAL_POLICIES,
  SSO_CONNECTION_EVENT_TYPES,
  SSO_CONNECTION_EVENT_VERSION_LATEST,
  SSO_CONNECTION_SOURCES,
  SSO_CONNECTION_STATES,
  SSO_MIGRATION_PHASES,
  SSO_MIGRATION_ROUTES,
  CONNECTION_RENAMED_EVENT_TYPE,
  connectionRenamedPayloadSchema,
  REPLACEMENT_CONNECTION_REGISTERED_EVENT_TYPE,
  replacementConnectionRegisteredPayloadSchema,
  MIGRATION_ROUTE_SELECTED_EVENT_TYPE,
  migrationRouteSelectedPayloadSchema,
  MIGRATION_FINALIZATION_STARTED_EVENT_TYPE,
  migrationFinalizationStartedPayloadSchema,
  MIGRATION_FINALIZED_EVENT_TYPE,
  migrationFinalizedPayloadSchema,
  ssoMigrationRouteOf,
  ssoDomainVerificationSchema,
  ssoMigrationPhaseSchema,
  ssoMigrationRouteSchema,
  type SsoMigrationPhase,
  type SsoMigrationRoute,
  SSO_CONNECTION_TYPES,
  SSO_DOMAIN_PROOF_STATES,
  SSO_DOMAIN_CLAIM_AUTHORITIES,
  SSO_PUBLISHED_PROOF_CHANNELS,
  SSO_VERIFICATION_CEREMONY_METHODS,
  SSO_VERIFICATION_METHODS,
  type SsoArrivalPolicy,
  type SsoConnectionEventType,
  type SsoConnectionFact,
  type SsoConnectionFactInput,
  type SsoConnectionLifecycleState,
  type SsoConnectionSource,
  type SsoConnectionState,
  type SsoConnectionType,
  type SsoDomainProofState,
  type SsoDomainVerification,
  type SsoIdpMetadata,
  type SsoDomainClaim,
  type SsoDomainClaimAuthority,
  type SsoPublishedProofChannel,
  type SsoVerificationCeremonyMethod,
  type SsoVerificationMethod,
  connectionArrivalPolicySetPayloadSchema,
  ssoArrivalPolicySchema,
  ssoConnectionFactInputSchema,
  ssoConnectionSourceSchema,
  ssoConnectionStateSchema,
  ssoConnectionTypeSchema,
  ssoDomainProofStateSchema,
  ssoIdpMetadataSchema,
  ssoDomainClaimAuthoritySchema,
  ssoDomainClaimSchema,
  ssoPublishedProofChannelSchema,
  ssoVerificationCeremonyMethodSchema,
  ssoVerificationMethodSchema,
  TEARDOWN_REQUESTED_EVENT_TYPE,
  teardownRequestedPayloadSchema,
  VERIFICATION_REQUESTED_EVENT_TYPE,
  verificationRequestedPayloadSchema,
} from "./connection.ts";
export {
  type SsoArrivingUser,
  type SsoAssertionDecision,
  type SsoAssertionRefusal,
  type SsoAssertionRefusalReason,
  NOT_A_TEST_ARRIVAL,
  type SsoTestArrivalStanding,
} from "./sso-admission.ts";
export { SSO_CREDENTIAL_KINDS, type SsoCredentialKind } from "./sso-credential.ts";
export {
  parseSamlIdpConfig,
  type SsoIdpRegistration,
  ssoIdpRegistrationSchema,
  type SsoOidcRegistration,
  ssoOidcRegistrationSchema,
  type SsoSamlIdpConfig,
  ssoSamlIdpConfigSchema,
  type SsoSamlRegistration,
  ssoSamlRegistrationSchema,
} from "./sso-idp-registration.ts";
export {
  isSealedProviderConfig,
  sealedProviderConfigCipher,
  type SsoProviderConfigCipher,
} from "./sso-provider-config.ts";
export {
  type SsoConnectionRemoval,
  type SsoSetupCommand,
  type SsoSetupConnectionView,
  type SsoSetupDomainClaimView,
  type SsoSetupDomainProofView,
  type SsoSetupGoLiveView,
  type SsoSetupRecordView,
  type SsoSetupView,
} from "./sso-setup.ts";
export {
  type SsoMigrationAccountLinkDecision,
  type SsoMigrationAuthenticationDecision,
  type SsoMigrationAuthenticationRefusalCode,
  type SsoMigrationBlockerView,
  type SsoMigrationConnectionRef,
  type SsoMigrationLinkRefusalCode,
  type SsoMigrationScimStatus,
  type SsoMigrationStragglerView,
  type SsoMigrationView,
} from "./sso-migration.ts";
export {
  isConfiguredLegacySsoRoute,
  isSsoConnectionInSetup,
  lapsedDomainsOf,
  looksLikeSsoConnectionId,
  type QualifiableConnection,
  qualifySsoDomainOwnership,
  type SsoDomainOwnershipQualification,
  ssoDomainStanding,
  ssoDomainVouchesForNewPeople,
} from "./sso-domain-ownership.ts";
export {
  SSO_DNS_PROOF_TTL_MS,
  SSO_DNS_RECORD_NAME,
  SSO_DNS_RECORD_TYPE,
  SSO_DNS_REPROOF_GRACE_MS,
  SSO_VERIFICATION_FILE_PATH,
  type SelfServeActor,
  type SelfServeDnsRecordLocation,
  type SelfServeIssuedDnsRecord,
  type SsoDomainReproofOutcome,
  ssoDnsRecordName,
  ssoDomainRecordLocation,
  ssoVerificationFileUrl,
} from "./sso-domain-proof.ts";
export {
  ACTIVATE_CONNECTION_COMMAND_TYPE,
  APPROVE_DOMAIN_CLAIM_COMMAND_TYPE,
  ATTEST_DOMAIN_COMMAND_TYPE,
  type ActivateConnectionCommandData,
  activateConnectionCommandDataSchema,
  type ApproveDomainClaimCommandData,
  approveDomainClaimCommandDataSchema,
  type AttestDomainCommandData,
  attestDomainCommandDataSchema,
  CLAIM_DOMAIN_COMMAND_TYPE,
  COMPLETE_TEARDOWN_COMMAND_TYPE,
  type ClaimDomainCommandData,
  claimDomainCommandDataSchema,
  type CompleteTeardownCommandData,
  completeTeardownCommandDataSchema,
  DISCARD_CONNECTION_COMMAND_TYPE,
  type DiscardConnectionCommandData,
  discardConnectionCommandDataSchema,
  GRANDFATHER_CONNECTION_COMMAND_TYPE,
  type GrandfatherConnectionCommandData,
  grandfatherConnectionCommandDataSchema,
  RECORD_DOMAIN_PROOF_ABSENT_COMMAND_TYPE,
  RECORD_DOMAIN_PROOF_PRESENT_COMMAND_TYPE,
  REGISTER_CONNECTION_COMMAND_TYPE,
  REJECT_DOMAIN_CLAIM_COMMAND_TYPE,
  REQUEST_TEARDOWN_COMMAND_TYPE,
  REQUEST_VERIFICATION_COMMAND_TYPE,
  RESUME_CONNECTION_COMMAND_TYPE,
  type RecordDomainProofAbsentCommandData,
  recordDomainProofAbsentCommandDataSchema,
  type RecordDomainProofPresentCommandData,
  recordDomainProofPresentCommandDataSchema,
  type RegisterConnectionCommandData,
  registerConnectionCommandDataSchema,
  REGISTER_REPLACEMENT_CONNECTION_COMMAND_TYPE,
  type RegisterReplacementConnectionCommandData,
  registerReplacementConnectionCommandDataSchema,
  RENAME_CONNECTION_COMMAND_TYPE,
  type RenameConnectionCommandData,
  renameConnectionCommandDataSchema,
  SELECT_MIGRATION_ROUTE_COMMAND_TYPE,
  type SelectMigrationRouteCommandData,
  selectMigrationRouteCommandDataSchema,
  BEGIN_MIGRATION_FINALIZATION_COMMAND_TYPE,
  type BeginMigrationFinalizationCommandData,
  beginMigrationFinalizationCommandDataSchema,
  FINALIZE_MIGRATION_COMMAND_TYPE,
  type FinalizeMigrationCommandData,
  finalizeMigrationCommandDataSchema,
  type RejectDomainClaimCommandData,
  rejectDomainClaimCommandDataSchema,
  type RequestTeardownCommandData,
  requestTeardownCommandDataSchema,
  type RequestVerificationCommandData,
  requestVerificationCommandDataSchema,
  type ResumeConnectionCommandData,
  resumeConnectionCommandDataSchema,
  SET_ARRIVAL_POLICY_COMMAND_TYPE,
  SSO_CONNECTION_COMMAND_TYPES,
  SUSPEND_CONNECTION_COMMAND_TYPE,
  type SetArrivalPolicyCommandData,
  setArrivalPolicyCommandDataSchema,
  type SsoConnectionCommand,
  type SsoConnectionCommandType,
  type SuspendConnectionCommandData,
  suspendConnectionCommandDataSchema,
  VERIFY_DOMAIN_COMMAND_TYPE,
  type VerifyDomainCommandData,
  verifyDomainCommandDataSchema,
  WITHDRAW_DOMAIN_COMMAND_TYPE,
  type WithdrawDomainCommandData,
  withdrawDomainCommandDataSchema,
} from "./connection-commands.ts";
export {
  IdentityCapabilityUnavailableError,
  IdentityCommandRefusedError,
  IdentityDetachStrandsUserError,
  IdentityEmailInUseError,
  IdentityIdentifierNotFoundError,
  IdentityIdentifierNotVerifiableError,
  IdentityMfaBackupCodesExhaustedError,
  IdentityMfaCodeInvalidError,
  IdentityEngineUnavailableError,
  IdentityMfaEnrollmentExpiredError,
  IdentityMfaEnrollmentRequiredError,
  IdentityMfaLockedOutError,
  IdentityMfaRequiredByOrganizationError,
  IdentityPasskeyCeremonyFailedError,
  IdentityPasskeyNotRecognizedError,
  IdentityPrimaryMustDemoteFirstError,
  IdentityPrimaryRequiresVerifiedError,
  IDENTITY_UNSUPPORTED_STORAGE_QUERY_CODE,
  IdentityUnsupportedStorageQueryError,
  IdentityVerificationExpiredError,
  IdentityVerificationInvalidError,
  IdentityVerificationNotSettledError,
  JoinAutoConnectionAdmitsError,
  JoinAutoDomainUnprovenError,
  JoinAutoNotLicensedError,
  JoinPolicyNotLicensedError,
  JoinNotAvailableError,
  JoinRequestAlreadyPendingError,
  JoinRequestNotFoundError,
  JoinRequestNotPendingError,
  JoinRequestRefusedError,
  JoinRequestThrottledError,
  MfaCommandRefusedError,
  PasskeyCommandRefusedError,
  SsoBreakGlassExpiryOutOfRangeError,
  SsoBreakGlassHolderIneligibleError,
  SsoBreakGlassLastWayInError,
  SsoConnectionActivationBlockedError,
  SsoConnectionAlreadyRegisteredError,
  SsoConnectionCommandRefusedError,
  SsoConnectionDomainTakenError,
  SsoDomainClaimThrottledError,
  SsoDomainNotEligibleError,
  SsoAssertionRefusedError,
  SsoAssertionWithoutAddressError,
  SsoCertificateInvalidError,
  SsoCredentialsRequiredError,
  SsoConnectionInvalidTransitionError,
  SsoConnectionNotFoundError,
  SsoConnectionOperatorActRequiredError,
  SsoConnectionStringEditRetiredError,
  SsoConnectionTeardownStrandsUsersError,
  SsoMigrationFinalizationBlockedError,
  SsoDomainClaimPendingError,
  SsoDomainLookupFailedError,
  SsoDomainNotVerifiedError,
  SsoDomainProofExpiredError,
  SsoDomainProofLapsedError,
  SsoDomainProofNotFoundError,
  SsoIssuerUnreachableError,
  SsoSamlMetadataInvalidError,
  SsoSamlNotSelfServeError,
  SsoSetupAddressMismatchError,
  SsoSignInRefusedError,
  ScimSyncNotFoundError,
  SsoTestArrivalCannotCreateOrganizationError,
} from "./identity.errors.ts";
export {
  BREAK_GLASS_MAX_WINDOW_DAYS,
  BREAK_GLASS_MAX_WINDOW_MS,
  BREAK_GLASS_WARNING_DAYS,
  type BreakGlassBinding,
  type BreakGlassCandidateView,
  type BreakGlassGrantView,
  breakGlassDaysRemaining,
  breakGlassExpiryIsAllowed,
  breakGlassIsLive,
  type BreakGlassWarningDay,
  breakGlassWarningsDue,
} from "./break-glass.ts";
export {
  SSO_CONNECTION_HISTORY_LIMIT,
  type OrganizationSsoConnection,
  type SsoConnectionHistoryEntryView,
} from "./sso-connection-history.ts";
export { IdentityEmailService } from "./identity-email.service.ts";
export {
  coarseColleagueCount,
  DEFAULT_DOMAIN_JOIN_SETTING,
  DOMAIN_JOIN_SETTINGS,
  type DomainJoinSetting,
  isPublicEmailDomain,
  JOIN_REQUEST_VERIFIED_MEMBER_THRESHOLD,
  type JoinCandidateOrganization,
  type JoinLookupDecision,
  type JoinLookupInput,
  type JoinOffer,
  extractJoinDomain,
  organizationAdmitsDomain,
  organizationAdmitsDomainAutomatically,
  PUBLIC_EMAIL_DOMAINS,
  resolveJoinLookup,
} from "./join-matching.ts";
export {
  DOMAIN_AUTO_JOIN_POLICY_ID,
  emptyJoinRequest,
  isPendingJoinRequest,
  JOIN_APPROVED_EVENT_TYPE,
  JOIN_EXPIRED_EVENT_TYPE,
  JOIN_MATCH_KINDS,
  JOIN_REJECTED_EVENT_TYPE,
  JOIN_REQUEST_EVENT_TYPES,
  JOIN_REQUEST_EVENT_VERSION_LATEST,
  JOIN_REQUEST_STATES,
  JOIN_REQUESTED_EVENT_TYPE,
  JOIN_RESOLVER_TYPES,
  JOIN_WITHDRAWAL_CAUSES,
  JOIN_WITHDRAWN_EVENT_TYPE,
  type JoinApprovedPayload,
  type JoinExpiredPayload,
  type JoinMatchKind,
  type JoinRejectedPayload,
  type JoinRequestAggregateState,
  type JoinRequestEventType,
  type JoinRequestFact,
  type JoinRequestFactInput,
  type JoinRequestState,
  type JoinRequestedPayload,
  type JoinResolver,
  type JoinResolverType,
  type JoinWithdrawalCause,
  type JoinWithdrawnPayload,
  joinApprovedPayloadSchema,
  joinExpiredPayloadSchema,
  joinMatchKindSchema,
  joinRejectedPayloadSchema,
  joinRequestFactInputSchema,
  joinRequestStateSchema,
  joinRequestedPayloadSchema,
  joinResolverSchema,
  joinResolverTypeSchema,
  joinWithdrawalCauseSchema,
  joinWithdrawnPayloadSchema,
  reduceJoinRequest,
} from "./join-request.ts";
export {
  APPROVE_JOIN_COMMAND_TYPE,
  type ApproveJoinCommandData,
  approveJoinCommandDataSchema,
  EXPIRE_JOIN_COMMAND_TYPE,
  type ExpireJoinCommandData,
  expireJoinCommandDataSchema,
  JOIN_REQUEST_COMMAND_TYPES,
  type JoinRequestCommand,
  type JoinRequestCommandType,
  REJECT_JOIN_COMMAND_TYPE,
  REQUEST_JOIN_COMMAND_TYPE,
  type RejectJoinCommandData,
  type RequestJoinCommandData,
  rejectJoinCommandDataSchema,
  requestJoinCommandDataSchema,
  WITHDRAW_JOIN_COMMAND_TYPE,
  type WithdrawJoinCommandData,
  withdrawJoinCommandDataSchema,
} from "./join-request-commands.ts";
export {
  ATTACH_IDENTIFIER_COMMAND_TYPE,
  type AttachIdentifierCommandData,
  attachIdentifierCommandDataSchema,
  DETACH_IDENTIFIER_COMMAND_TYPE,
  type DetachIdentifierCommandData,
  detachIdentifierCommandDataSchema,
  ERASE_USER_COMMAND_TYPE,
  emptyIdentityHeads,
  type EraseUserCommandData,
  eraseUserCommandDataSchema,
  IDENTIFIER_ATTACHED_EVENT_TYPE,
  IDENTIFIER_DEAD_ENDED_EVENT_TYPE,
  IDENTIFIER_DETACHED_EVENT_TYPE,
  IDENTIFIER_VERIFIED_EVENT_TYPE,
  IDENTITY_COMMAND_TYPES,
  IDENTITY_EVENT_TYPES,
  IDENTITY_EVENT_VERSION_LATEST,
  type IdentifierFact,
  type IdentityCommand,
  type IdentityCommandType,
  type IdentityEventType,
  type IdentityFact,
  type IdentityFactInput,
  type IdentityFactInputOf,
  type IdentityFactOf,
  type IdentityHeads,
  identifierAttachedPayloadSchema,
  identifierDeadEndedPayloadSchema,
  identifierDetachedPayloadSchema,
  identifierVerifiedPayloadSchema,
  identifierFactInputSchema,
  LINK_PROPOSED_EVENT_TYPE,
  type LinkProposalReason,
  linkProposalReasonSchema,
  linkProposedPayloadSchema,
  MARK_PRIMARY_COMMAND_TYPE,
  type MarkPrimaryCommandData,
  markPrimaryCommandDataSchema,
  PRIMARY_CHANGED_EVENT_TYPE,
  primaryChangedPayloadSchema,
  PROPOSE_LINK_COMMAND_TYPE,
  type ProposeLinkCommandData,
  proposeLinkCommandDataSchema,
  USER_ERASED_EVENT_TYPE,
  userErasedPayloadSchema,
  VERIFY_IDENTIFIER_COMMAND_TYPE,
  type VerifyIdentifierCommandData,
  verifyIdentifierCommandDataSchema,
} from "./facts.ts";
export {
  extractIdentifierDomain,
  normalizeDomain,
  normalizeIdentifierValue,
} from "./identifier.ts";
export {
  type IdentifierHead,
  type IdentityStream,
  identityStreamsFor,
  primaryChangeFacts,
  reduceIdentifier,
  userErasureFacts,
} from "./identifier-aggregate.ts";
export { type MatchableEmail, matchableEmailsOf } from "./matchable-emails.ts";
export {
  BACKUP_CODE_CONSUMED_EVENT_TYPE,
  BACKUP_CODES_REGENERATED_EVENT_TYPE,
  backupCodeConsumedPayloadSchema,
  backupCodesRegeneratedPayloadSchema,
  canProveSecondFactor,
  CONFIRM_MFA_COMMAND_TYPE,
  CONSUME_BACKUP_CODE_COMMAND_TYPE,
  type ConfirmMfaCommandData,
  confirmMfaCommandDataSchema,
  type ConsumeBackupCodeCommandData,
  consumeBackupCodeCommandDataSchema,
  DISABLE_MFA_COMMAND_TYPE,
  type DisableMfaCommandData,
  disableMfaCommandDataSchema,
  ENROLL_MFA_COMMAND_TYPE,
  EXPIRE_MFA_ENROLLMENT_COMMAND_TYPE,
  emptyMfaEnrollment,
  type EnrollMfaCommandData,
  enrollMfaCommandDataSchema,
  type ExpireMfaEnrollmentCommandData,
  expireMfaEnrollmentCommandDataSchema,
  MFA_COMMAND_TYPES,
  MFA_CONFIRMED_EVENT_TYPE,
  MFA_DISABLED_EVENT_TYPE,
  MFA_ENROLLED_EVENT_TYPE,
  MFA_ENROLLMENT_EXPIRED_EVENT_TYPE,
  MFA_ENROLLMENT_STATES,
  MFA_EVENT_TYPES,
  MFA_EVENT_VERSION_LATEST,
  MFA_VERIFICATION_FAILED_EVENT_TYPE,
  type MfaCommand,
  type MfaCommandType,
  type MfaDisableVia,
  type MfaEnrollmentLifecycleState,
  type MfaEnrollmentState,
  type MfaEventType,
  type MfaFact,
  type MfaFactInput,
  type MfaFactOf,
  type MfaMethod,
  mfaConfirmedPayloadSchema,
  mfaDisableViaSchema,
  mfaDisabledPayloadSchema,
  mfaEnrolledPayloadSchema,
  mfaEnrollmentExpiredPayloadSchema,
  mfaFactInputSchema,
  mfaMethodSchema,
  mfaVerificationFailedPayloadSchema,
  REGENERATE_BACKUP_CODES_COMMAND_TYPE,
  RECORD_MFA_VERIFICATION_FAILURE_COMMAND_TYPE,
  type RecordMfaVerificationFailureCommandData,
  recordMfaVerificationFailureCommandDataSchema,
  type RegenerateBackupCodesCommandData,
  regenerateBackupCodesCommandDataSchema,
  reduceMfaEnrollment,
  remainingBackupCodes,
} from "./mfa.ts";
export {
  AMR_VALUES,
  type Amr,
  amrSchema,
  assertsSecondFactor,
  connectionAssertsSecondFactor,
  isAmr,
  isMfaChallengeMethod,
  MFA_CHALLENGE_METHODS,
  type MfaChallengeMethod,
  PASSWORD_AMR,
  PHISHING_RESISTANT_AMR,
  recordedNothing,
  SECOND_FACTOR_AMR_VALUES,
  satisfiesOrganizationMfaRequirement,
  type SecondFactorEvidence,
  type SecondFactorSatisfaction,
  secondFactorsIn,
  signInProvedSecondFactor,
  TOTP_AMR,
} from "./mfa-condition.ts";
export {
  deriveSessionAmr,
  localFactorsForPath,
  signedInWithFor,
  signInMethodLabelFor,
  signInProviderForPath,
  type SignedInWith,
  type SignInPathReading,
} from "./session-claims.ts";
export {
  PASSWORD_MAXIMUM_BYTES,
  PASSWORD_MINIMUM_LENGTH,
  PASSWORD_REQUIREMENTS_HINT,
  describePasswordProblem,
} from "./password-policy.ts";
export { pickPrimaryEmail } from "./primary-email.ts";
export {
  LOCAL_METHOD_SET,
  PASSKEY_METHOD,
  PASSWORD_METHOD,
  SignInMethodPolicyService,
  type SignInMethodPolicyInputs,
  type SignInMethodPolicyResolver,
} from "./signin-method-policy.ts";
export { reduceIdentity } from "./reduce.ts";
export {
  emptyScimSync,
  pickRetiredLetter,
  reduceScimSync,
  SCIM_APPLY_FAILED_EVENT_TYPE,
  SCIM_APPLY_OPS,
  SCIM_APPLY_RECOVERED_EVENT_TYPE,
  SCIM_APPLY_RETIRED_EVENT_TYPE,
  SCIM_GROUP_MAPPED_EVENT_TYPE,
  SCIM_REVOKE_CAUSES,
  SCIM_SYNC_EVENT_TYPES,
  SCIM_SYNC_EVENT_VERSION_LATEST,
  SCIM_SYNC_STATES,
  SCIM_TOKEN_ISSUED_EVENT_TYPE,
  SCIM_TOKEN_REVOKED_EVENT_TYPE,
  SCIM_APPLY_REDRIVEN_EVENT_TYPE,
  SCIM_USER_OPS,
  SCIM_USER_PUSHED_EVENT_TYPE,
  type ScimApplyOp,
  type ScimRevokeCause,
  type ScimSyncEventType,
  type ScimSyncFact,
  type ScimSyncFactInput,
  type ScimSyncFailure,
  type ScimSyncLifecycleState,
  type ScimSyncState,
  type ScimUserOp,
  scimApplyFailedPayloadSchema,
  scimApplyOpSchema,
  scimApplyRecoveredPayloadSchema,
  scimApplyRetiredPayloadSchema,
  scimGroupMappedPayloadSchema,
  scimRevokeCauseSchema,
  scimSyncFactInputSchema,
  scimSyncIdFor,
  scimSyncStateSchema,
  scimTokenIssuedPayloadSchema,
  scimTokenRevokedPayloadSchema,
  scimApplyRedrivenPayloadSchema,
  scimUserOpSchema,
  scimUserPushedPayloadSchema,
} from "./scim-sync.ts";
export {
  ISSUE_SCIM_TOKEN_COMMAND_TYPE,
  type IssueScimTokenCommandData,
  issueScimTokenCommandDataSchema,
  RECORD_SCIM_APPLY_FAILURE_COMMAND_TYPE,
  RECORD_SCIM_GROUP_MAPPING_COMMAND_TYPE,
  RECORD_SCIM_USER_PUSH_COMMAND_TYPE,
  REDRIVE_SCIM_APPLY_COMMAND_TYPE,
  REVOKE_SCIM_SYNC_COMMAND_TYPE,
  type RecordScimApplyFailureCommandData,
  type RedriveScimApplyCommandData,
  redriveScimApplyCommandDataSchema,
  type RecordScimGroupMappingCommandData,
  type RecordScimUserPushCommandData,
  type RevokeScimSyncCommandData,
  recordScimApplyFailureCommandDataSchema,
  recordScimGroupMappingCommandDataSchema,
  recordScimUserPushCommandDataSchema,
  revokeScimSyncCommandDataSchema,
  SCIM_SYNC_COMMAND_TYPES,
  type ScimSyncCommand,
  type ScimSyncCommandType,
} from "./scim-sync-commands.ts";

export {
  type AccountSignInMethods,
  compareToLegacy,
  isLocalSignInMethod,
  legacyProviderOf,
  rankAccountMethods,
  isOrganizationManagedDecision,
  type RoutableConnection,
  type RoutingDecision,
  type RoutingIdentifier,
  type RoutingInput,
  routeSignIn,
  routesToOrganizationConnection,
  routingDecisionSchema,
  routingIdentifierOf,
  SIGNIN_METHOD_KINDS,
  SIGNIN_ROUTING_OUTCOMES,
  SIGNIN_ROUTING_REASON_CODES,
  signInMethodSchema,
  SSO_CONNECTION_ROUTING_STATES,
  type ShadowComparison,
  type SignInMethod,
  type SignInMethodKind,
  type SignInMethodPolicy,
  type SignInRoutingOutcome,
  type SignInRoutingReasonCode,
  type SsoConnectionRoutingState,
} from "./signin-routing.ts";
export {
  arrivalStateForProvider,
  IDENTIFIER_LIFECYCLE_STATES,
  IDENTIFIER_PROVIDERS,
  LIVE_IDENTIFIER_STATES,
  type IdentifierArrivalState,
  type IdentifierLifecycleState,
  type IdentifierProvider,
  type IdentityActor,
  identifierArrivalStateSchema,
  identifierProviderFor,
  identifierProviderSchema,
  identityActorSchema,
  isLiveIdentifierState,
  type VerificationMethod,
  verificationMethodSchema,
} from "./vocabulary.ts";
/**
 * The four pipelines' framework identity (ADR-101, ADR-115, ADR-117): the
 * pipeline name and aggregate type every event stamps. Wire schemas that
 * extend these with the eventing envelope stay in `@langwatch/identity-process`.
 */
export { IDENTITY_PIPELINE_NAME, USER_IDENTITY_AGGREGATE_TYPE } from "./identity-events.ts";
export { JOIN_REQUEST_AGGREGATE_TYPE, JOIN_REQUEST_PIPELINE_NAME } from "./join-request-events.ts";
export { SCIM_SYNC_AGGREGATE_TYPE, SCIM_SYNC_PIPELINE_NAME } from "./scim-sync-events.ts";
export {
  SSO_CONNECTION_AGGREGATE_TYPE,
  SSO_CONNECTION_PIPELINE_NAME,
} from "./sso-connection-events.ts";
export * from "./signin-callback.errors.ts";
export {
  domainClaimRetryAfterSeconds,
  isClaimableSsoDomain,
  SSO_DOMAIN_CLAIM_WINDOW_MS,
  SSO_DOMAIN_CLAIMS_PER_WINDOW,
} from "./sso-domain-claims.ts";
export * from "./identity.api.ts";
export * from "./identity-lookup.ts";
export * from "./identity.config.ts";
