"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.OrderState = void 0;
exports.OrderState = {
    Open: "open",
    Submitted: "submitted",
    Paid: "paid",
    Accepted: "accepted",
    Rejected: "rejected",
    Done: "done",
};
