"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.ToolType = void 0;
exports.ToolType = {
    System: "system",
    Webhook: "webhook",
    Client: "client",
    Mcp: "mcp",
    Workflow: "workflow",
    ApiIntegrationWebhook: "api_integration_webhook",
    ApiIntegrationMcp: "api_integration_mcp",
    Smb: "smb",
};
