import { DEFAULT_DATASET_NAME } from "../../components/datasets/DatasetTable";
import type { End, Entry, Evaluator, Retriever, Workflow } from "../types/dsl";

export const simpleRagTemplate: Workflow = {
  spec_version: "1.3",
  name: "Simple RAG",
  icon: "🧩",
  description:
    "Query transformation, vector database search and answer generation",
  version: "1.0",
  default_llm: {
    model: "openai/gpt-4o-mini",
    temperature: 0,
    max_tokens: 8192,
  },
  enable_tracing: true,
  nodes: [
    {
      id: "entry",
      type: "entry",
      position: { x: 0, y: 0 },
      deletable: false,
      data: {
        name: "Entry",
        outputs: [
          { identifier: "question", type: "str" },
          { identifier: "gold_answer", type: "str" },
        ],
        entry_selection: "random",
        train_size: 0.8,
        test_size: 0.2,
        seed: 42,
        dataset: {
          name: DEFAULT_DATASET_NAME,
          inline: {
            records: {
              question: [
                "Are both Cangzhou and Qionghai in the Hebei province of China?",
                "Who conducts the draft in which Marc-Andre Fleury was drafted to the Vegas Golden Knights for the 2017-18 season?",
                "The Wings entered a new era, following the retirement of which Canadian retired professional ice hockey player and current general manager of the Tampa Bay Lightning of the National Hockey League (NHL)?",
                "What river is near the Crichton Collegiate Church?",
                "In the 10th Century A.D. Ealhswith had a son called Æthelweard by which English king?",
                "The Newark Airport Exchange is at the northern edge of an airport that is operated by whom?",
                "Where did an event take place resulting in a win during a domestic double due to the action of a Peruvian footballer known for his goal scoring ability?",
                "Are both Chico Municipal Airport and William R. Fairchild International Airport in California?",
                "In which Maine county is Fort Pownall located?",
                "Which 90s rock band has more recently reformed, Gene or The Afghan Whigs?",
                'What year did the mountain known in Italian as "Monte Vesuvio", erupt?',
                "Is the 72nd field brigade part of the oldest or newest established field army?",
                "Was Stanislaw Kiszka paid for his services by the Royal Treasury?",
                "Which film director is younger, Del Lord or Wang Xiaoshuai?",
                "Lord North Street has a resident in which former Conservative MP who received an 18-month prison sentence for perjury in 1999?",
                "What is the name of this region of Italy, referring to the medieval March of Ancona and nearby marches of Camerino and Fermo, where the comune Pollenza is located?",
                "William Hughes Miller was born in a city with how many inhabitants ?",
                "What do students do at the school of New York University where Meleko Mokgosi is an artist and assistant professor?",
                "What is the nationality of the chef and restaurateur featured in Restaurant: Impossible?",
                "What American actor plays an East side drug lord who prefers peaceful solutions to business disputes when possible?",
                "What city is 11 miles north of the birthplace of actor Toby Sawyer?",
                "Who was born first, Tony Kaye or Deepa Mehta?",
                "What is the English translation of the name of the store that Macy's replaced in Boise Town Square?",
                "Who did Lizzette Reynolds fire to make her notable in November 2007?",
                'What was the name of the man, who was billed by the coiner of the phrase "There\'s a sucker born every minute" as "Boy Lightning Calculator"?',
                "Which battle was fought for a shorter period of time, the Battle of the Ch'ongch'on River, or the Meuse-Argonne Offensive?",
                "What cricketeer active 1974–1993 had a strong performance in the tour by the Australian cricket team in England in 1981?",
                "What is the present post of the head coach of the 1982 NC State Wolfpack football team ?",
                'Which Scottish actor sang "Come What May"?',
                "Where have Ivan Bella and Frank De Winne both traveled?",
                "The original work by Anton Chekhov involving a disillusioned schoolmaster, which inspired a later play by this British playwright, was written specifically for whom?",
                "Are Roswell International Air Center and Pago Pago International Airport both located in the mainland US?",
                "Untold: The Greatest Sports Stories Never Told was hosted by a sportscaster commonly referred to as what ?",
                "Are Walt Disney and Sacro GRA both documentry films?",
                "What is the Palestinian Islamic organization that governs th small territory on the eastern coast of the Mediterranean Sea that was captured by Israel during the 1967 Six-Day War?",
                "What album did the song of which Taylor Swift premiered the music video of during the pre-show of the 2015 MTV Video Music Awards come from?",
                "Which is considered a genus level classification, Apera or Gunnera manicata?",
                "Do The Drums and Pussy Galore play music of similar genres?",
                "What is the post-nominal abbreviation for the university where the Banded Mongoose Research Project is based?",
                "Are both Benjamin Christensen and Len Wiseman directors?",
                "Steven Cuitlahuac Melendez and Disney are connected by what American animator?",
                "Shark Creek is located on this river which is in the northern rivers district?",
                "Who was the producer of the 2016 animated film about an amnesiac fish?",
                "Who purchased the team Michael Schumacher raced for in the 1995 Monaco Grand Prix in 2000?",
                "Fredrick Law Olmsted was an American landscape architect, journalist, social critic and public administrator that designed what neighborhood in Trenton, New Jersey?",
                "Gordon Warnecke worked alongside the former senator for which political party on Young Toscanini?",
                "André Zucca was a French photographer who worked with a German propaganda magazine published by what Nazi organization?",
                "Both Bill Ponsford and Bill Woodfull played what?",
                " Suzana S. Drobnjaković Ponti acted in a film loosely based on a book by who?",
                "In what city was the Election Law Journal founded?",
                "Who was a producer who produced albums for both rock bands Juke Karten and Thirty Seconds to Mars?",
                "Are both the University of Chicago and Syracuse University public universities? ",
                "In what region was Eddy Mazzoleni born?",
                "Who edited the 1990 American romantic comedy film directed by Garry Marshall?",
                "Burrs Country Park railway station is what stop on the railway line that runs between Heywood and Rawtenstall",
                'At which university did this American writer, lawyer, actor, and commentator on political and economic issues, who appeared in the 1993 comedy-drama film "Me and the Kid" get a law degree?',
                "The first person to interpret Relational quantum mechanics has worked in what countries? ",
                "How many seasons did, the Guard with a FG% around .420, play in the NBA ?",
                "Jorge Miramón plays for the team that is in what autonomous country?",
                "Which Big East champion began his NBA career with the Celtics in 2007?",
                "What genre do The Gaslight Anthem and Seaweed share?",
                "What was the 2010 population of the birthplace of Gerard Piel?",
                "Folk dances from Thessaly include this popular dance, which is a mixture of the slow and fast rhythms of hasapiko and which other dance?",
                "Elisabeth Hasselbeck the former host of The Look for Less graduated from what College?",
                "Which has more species Nothoscordum or Calypso bulbosa?",
                "Do both Central Illinois Regional Airport and Idaho Falls Regional Airport serve two cities each?",
                "How much is spent on the type of whiskey that 1792 Whiskey is in the United States?",
                "Rex Reed appeared in the film Myra Breckinridge, in addition to being known as what?",
                "What is being built both at 3 Hudson Boulevard and 520 Park Avenue?",
                "Who has published more works, Melissa Bank  or Alan Moore?",
                'What footballer is a striker for İstanbul Başakşehir and endorsed the song "Skelewu"?',
                "What country does Lex Gabinia and Pompey have in common?",
                "What was the full name of the author that memorialized Susan Bertie through her single volume of poems?",
                "George Ho Ho-chi's father was known as what?",
                "Which of these is in the Apiaceae family, Ostrowskia or Selinum?",
                "For what contribution did Simon van der Meer won the that is given by he Royal Swedish Academy of Sciences?",
                'Which character, an elder sister, was played by Melissa Sue Anderson in the NBC series "Little House on the Prairie"?',
                "Juwan Howard was part of the Michigan team that had four participants in what 1991 exhibition?",
                "In 2007, which network aired the eleventh season of the animated television series created by Trey Parker and Matt Stone?",
                "The coach of the 2017 Houston Texans coached which team from 2012 to 2013?",
                "The Black Halo features a guest appearance by a Dutch symphonic metal band, that was founded by who?",
                "The score for Frankie and Johnny was composed by a composer who has won what collection of four awards?",
              ],
              gold_answer: [
                "no",
                "National Hockey League",
                "Steve Yzerman",
                "the River Tyne",
                "King Alfred the Great",
                "Port Authority of New York and New Jersey",
                "Bundesliga",
                "no",
                "Waldo County, Maine",
                "The Afghan Whigs",
                "79 AD",
                "the oldest",
                "not",
                "Del Lord",
                "Jonathan William Patrick Aitken",
                "Marche",
                "7,402 at the 2010 census",
                "design their own interdisciplinary program",
                "English",
                "Robert F. Chew",
                "Manchester",
                "Deepa Mehta",
                "the good market",
                "Christine Comer",
                "William Street Hutchings",
                "Battle of the Ch'ongch'on River",
                "Ian Botham",
                "defensive assistant at Florida Atlantic",
                "Ewan McGregor",
                "space",
                "Maria Yermolova",
                "no",
                "the voice of basketball",
                "yes",
                "Hamas",
                "1989",
                "Apera",
                "no",
                "Exon",
                "yes",
                "Bill Melendez",
                "Clarence River",
                "Pixar",
                "Renault",
                "Cadwalader Heights",
                '"Forza Italia" party.',
                "the Wehrmacht",
                "cricketer",
                "Danny Wallace",
                "Portland",
                "Brian Virtue",
                "no",
                "Lombardy, northern Italy",
                "Raja Raymond Gosnell",
                "seventh",
                "Yale Law School",
                "Italy, the United States and since 2000, in France",
                "14 seasons",
                "Catalonia",
                "Jeff Green",
                "rock",
                "17,121",
                "hasaposerviko",
                "Boston College",
                "Nothoscordum",
                "no",
                "about $2.7 billion",
                "an American film critic",
                "an American skyscraper under construction",
                "Alan Moore",
                "Sheyi Emmanuel Adebayor",
                "Rome",
                "Emilia Lanier",
                "the grand old man of Hong Kong",
                "Selinum",
                "CERN",
                "Mary Ingalls",
                "1991 McDonald's All-American Game",
                "Comedy Central",
                "Penn State",
                "Mark Jansen",
                "EGOT",
              ],
            },
            columnTypes: [
              { name: "question", type: "string" },
              { name: "gold_answer", type: "string" },
            ],
          },
        },
      } satisfies Entry,
    },
    {
      id: "generate_query",
      type: "signature",
      position: { x: 300, y: 30 },
      data: {
        name: "GenerateQuery",
        parameters: [
          {
            identifier: "llm",
            type: "llm",
            value: undefined,
          },
          {
            identifier: "prompting_technique",
            type: "prompting_technique",
            value: undefined,
          },
          {
            identifier: "instructions",
            type: "str",
            value:
              "given the question, generate a short wikipedia search query to find info about it",
          },
          {
            identifier: "demonstrations",
            type: "dataset",
            value: undefined,
          },
        ],
        inputs: [{ identifier: "question", type: "str" }],
        outputs: [{ identifier: "query", type: "str" }],
      },
    },
    {
      id: "col_bert_v2",
      type: "retriever",
      position: { x: 600, y: 30 },
      data: {
        cls: "ColBERTv2",
        name: "ColBERTv2",
        parameters: [
          {
            identifier: "k",
            desc: "Number of contexts to retrieve",
            type: "int",
            value: 3,
          },
          {
            identifier: "url",
            desc: "URL of the ColBERTv2 index",
            type: "str",
            value: "http://20.102.90.50:2017/wiki17_abstracts",
          },
        ],
        inputs: [
          {
            identifier: "query",
            type: "str",
          },
        ],
        outputs: [
          {
            identifier: "contexts",
            type: "list[str]",
          },
        ],
      } satisfies Retriever,
    },
    {
      id: "generate_answer",
      type: "signature",
      position: { x: 900, y: 10 },
      data: {
        name: "GenerateAnswer",
        parameters: [
          {
            identifier: "llm",
            type: "llm",
            value: undefined,
          },
          {
            identifier: "prompting_technique",
            type: "prompting_technique",
            value: undefined,
          },
          {
            identifier: "instructions",
            type: "str",
            value: undefined,
          },
          {
            identifier: "demonstrations",
            type: "dataset",
            value: undefined,
          },
        ],
        inputs: [
          { identifier: "question", type: "str" },
          { identifier: "contexts", type: "list[str]" },
        ],
        outputs: [{ identifier: "answer", type: "str" }],
      },
    },
    {
      id: "exact_match",
      type: "evaluator",
      position: { x: 1200, y: 130 },
      data: {
        name: "ExactMatch",
        cls: "ExactMatchEvaluator",
        inputs: [
          { identifier: "output", type: "str" },
          { identifier: "expected_output", type: "str" },
        ],
        outputs: [
          { identifier: "passed", type: "bool" },
          { identifier: "score", type: "float" },
        ],
      } satisfies Evaluator,
    },
    {
      id: "end",
      type: "end",
      position: { x: 1200, y: -80 },
      deletable: false,
      data: {
        name: "End",
        inputs: [{ identifier: "output", type: "str" }],
      } satisfies End,
    },
  ] satisfies Workflow["nodes"],
  edges: [
    {
      id: "e0-1",
      source: "entry",
      sourceHandle: "outputs.question",
      target: "generate_query",
      targetHandle: "inputs.question",
      type: "default",
    },
    {
      id: "e1-2-1",
      source: "generate_query",
      sourceHandle: "outputs.query",
      target: "col_bert_v2",
      targetHandle: "inputs.query",
      type: "default",
    },
    {
      id: "e1-2-2",
      source: "col_bert_v2",
      sourceHandle: "outputs.contexts",
      target: "generate_answer",
      targetHandle: "inputs.contexts",
      type: "default",
    },
    {
      id: "e2-3",
      source: "entry",
      sourceHandle: "outputs.question",
      target: "generate_answer",
      targetHandle: "inputs.question",
      type: "default",
    },
    {
      id: "e3-4",
      source: "generate_answer",
      sourceHandle: "outputs.answer",
      target: "end",
      targetHandle: "inputs.output",
      type: "default",
    },
    {
      id: "e4-5",
      source: "entry",
      sourceHandle: "outputs.gold_answer",
      target: "exact_match",
      targetHandle: "inputs.expected_output",
      type: "default",
    },
    {
      id: "e5-6",
      source: "generate_answer",
      sourceHandle: "outputs.answer",
      target: "exact_match",
      targetHandle: "inputs.output",
      type: "default",
    },
  ],
  state: {},
};
