"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.LockReason = void 0;
exports.LockReason = {
    TrialEnded: "trial_ended",
    SubscriptionDowngrade: "subscription_downgrade",
    ExposedPublicly: "exposed_publicly",
    SelfDisabled: "self_disabled",
};
