"use strict";
// This file was auto-generated by Fern from our API Definition.
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.ApiIntegrationWebhookOverrides = void 0;
const core = __importStar(require("../../core"));
const ApiIntegrationWebhookOverridesRequestHeadersValue_1 = require("./ApiIntegrationWebhookOverridesRequestHeadersValue");
const ApiIntegrationWebhookOverridesSchemaOverridesValue_1 = require("./ApiIntegrationWebhookOverridesSchemaOverridesValue");
const ResponseFilterMode_1 = require("./ResponseFilterMode");
exports.ApiIntegrationWebhookOverrides = core.serialization.object({
    schemaOverrides: core.serialization.property("schema_overrides", core.serialization
        .record(core.serialization.string(), ApiIntegrationWebhookOverridesSchemaOverridesValue_1.ApiIntegrationWebhookOverridesSchemaOverridesValue.optional())
        .optional()),
    requestHeaders: core.serialization.property("request_headers", core.serialization
        .record(core.serialization.string(), ApiIntegrationWebhookOverridesRequestHeadersValue_1.ApiIntegrationWebhookOverridesRequestHeadersValue.optional())
        .optional()),
    responseFilterMode: core.serialization.property("response_filter_mode", ResponseFilterMode_1.ResponseFilterMode.optional()),
    responseFilters: core.serialization.property("response_filters", core.serialization.list(core.serialization.string()).optional()),
});
