"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.TurnModel = void 0;
/** Version of the turn detection model to use. */
exports.TurnModel = {
    TurnV2: "turn_v2",
    TurnV3: "turn_v3",
};
