"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.ProjectExtendedResponseFiction = void 0;
exports.ProjectExtendedResponseFiction = {
    Fiction: "fiction",
    NonFiction: "non-fiction",
};
