"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.DubbingProjectResponseStatus = void 0;
/** Lifecycle status of the project: 'preparing'/'processing' while it transcribes, 'ready' once transcription is done, or 'failed'. */
exports.DubbingProjectResponseStatus = {
    Queued: "queued",
    Preparing: "preparing",
    Processing: "processing",
    Ready: "ready",
    Failed: "failed",
};
