"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.ReviewResponseModelReviewStatus = void 0;
exports.ReviewResponseModelReviewStatus = {
    Approved: "approved",
    EditsRequired: "edits_required",
    Rejected: "rejected",
};
