/**
 * The generated OpenAPI description of the LangWatch REST API, prepared once
 * for every route that serves it.
 *
 * The document is the build artifact `apps/api/src/features/discovery/openapi-document.json`,
 * regenerated by `pnpm run task generateOpenAPISpec`. It is imported rather
 * than read from disk per request so the file resolves through the module
 * graph and cannot go missing at runtime in a deployment that only ships
 * compiled output.
 *
 * The typed shape of the import is a 1.8 MB object literal that no caller
 * benefits from. Narrowing it here keeps that type out of every handler's
 * inference, and out of every module that touches a router serving it.
 *
 * WHY THE BYTES ARE PRECOMPUTED. Three routes serve this document, and each
 * was calling `c.json(apiDocument)` — a full `JSON.stringify` of a 5.8 MB
 * object graph on every request, measured at 2.8 ms and 1.3 MB of garbage per
 * hit. The result is identical every time, because the source is a build
 * artifact: it cannot change while the process is running. So it is serialised
 * once here, and the routes write bytes.
 *
 * That leaves the parsed object resident as well as the bytes. The RPC
 * catalogues no longer read it — the per-service ones are derived from the
 * services' own registrations, the root index from the mounted route tables —
 * but an ESM JSON import is held by the module registry regardless, and the
 * export stays because the alternative is not importing the JSON at all,
 * which trades the resolution guarantee above for the saving. Not worth it.
 */
import { createHash } from "node:crypto";

import openapiJson from "./openapi-document.json" with { type: "json" };

export const apiDocument = openapiJson as unknown as Record<string, unknown>;

/**
 * The document as it goes on the wire, serialised once at module load.
 *
 * A `Buffer` rather than a string: it is what the socket wants, so writing it
 * skips the UTF-8 encode a string body pays on every response, and
 * `Content-Length` is its `byteLength` rather than a second pass over the text.
 */
export const apiDocumentBytes: Uint8Array<ArrayBuffer> = Buffer.from(
  JSON.stringify(apiDocument),
  "utf8",
);

/**
 * A strong ETag over those exact bytes.
 *
 * Discovery is the one surface an agent polls speculatively — it fetches the
 * description to find out whether anything changed — so a conditional request
 * answering 304 with no body is the difference between 688 KB and ~200 bytes.
 * The tag is derived from the content rather than from a version or a build
 * stamp, so two replicas serving the same artifact agree, and a redeploy that
 * did not change the document does not invalidate anyone's cache.
 */
export const apiDocumentETag = `"${createHash("sha256")
  .update(apiDocumentBytes)
  .digest("base64url")
  .slice(0, 27)}"`;
