/**
 * The studio's autogenerated commit message for one graph change: a plain-text completion, since
 * function tools with a reasoning effort are rejected for the gpt-5 family on the chat proxy.
 * specs/model-providers/missing-model-popup.feature.
 */
import type { ModelProviderApi } from "@langwatch/model-provider-contract";
import { createPatch } from "diff";

import {
  WORKFLOW_COMMIT_MESSAGE_FEATURE_KEY,
  WORKFLOW_COMMIT_MESSAGE_PATCH_FILE,
  WORKFLOW_COMMIT_MESSAGE_PATCH_LABELS,
  workflowCommitMessagePrompt,
} from "../rules/workflow-commit-message.rules.ts";

export class WorkflowCommitMessageService {
  static create(options: {
    modelProviders: Pick<ModelProviderApi, "generateText">;
  }): WorkflowCommitMessageService {
    return new WorkflowCommitMessageService(options.modelProviders);
  }

  readonly #modelProviders: Pick<ModelProviderApi, "generateText">;

  private constructor(modelProviders: Pick<ModelProviderApi, "generateText">) {
    this.#modelProviders = modelProviders;
  }

  /**
   * The message for the change between two already-normalised graphs. The
   * caller decides they differ; this one only describes how.
   */
  async generate(input: {
    projectId: string;
    previousDsl: string;
    nextDsl: string;
  }): Promise<string> {
    const prompt = workflowCommitMessagePrompt({
      previousDsl: input.previousDsl,
      diff: createPatch(
        WORKFLOW_COMMIT_MESSAGE_PATCH_FILE,
        input.previousDsl,
        input.nextDsl,
        WORKFLOW_COMMIT_MESSAGE_PATCH_LABELS.previous,
        WORKFLOW_COMMIT_MESSAGE_PATCH_LABELS.next,
      ),
    });

    const completion = await this.#modelProviders.generateText({
      projectId: input.projectId,
      featureKey: WORKFLOW_COMMIT_MESSAGE_FEATURE_KEY,
      system: prompt.system,
      messages: [{ role: "user", content: prompt.user }],
      reasoningEffort: "low",
    });

    return completion.text.trim();
  }
}
