"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.ReferencedToolCommonModelType = void 0;
/** The type of the tool */
exports.ReferencedToolCommonModelType = {
    System: "system",
    Webhook: "webhook",
    Client: "client",
    Workflow: "workflow",
    ApiIntegrationWebhook: "api_integration_webhook",
    Mcp: "mcp",
    Code: "code",
};
