{{- if .Values.postgresql.chartManaged }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgresql
  labels:
    {{- include "langwatch.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  type: ClusterIP
  ports:
    - name: tcp-postgresql
      port: 5432
      targetPort: postgresql
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-postgresql
    app.kubernetes.io/instance: {{ .Release.Name }}
---
# Headless service for StatefulSet DNS
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgresql-hl
  labels:
    {{- include "langwatch.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: tcp-postgresql
      port: 5432
      targetPort: postgresql
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-postgresql
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
