"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.ExternalSyncJobTrigger = void 0;
exports.ExternalSyncJobTrigger = {
    OnDemand: "on_demand",
    OnConnect: "on_connect",
    Auto: "auto",
};
