// @langwatch/api/trpc -- the typed tRPC root, the one execution path a declared
// procedure runs, and the policy spine a process builds its `procedure` from.
// Runtime dependencies remain injected; the framework and error vocabularies are
// exported from their own entrypoints.

export {
  bindTrpcFact,
  bindTrpcHeader,
  browserSessionFact,
  callerAddressFact,
  createTrpcErrorFormatter,
  createTrpcHandlerBinding,
  createTrpcRuntime,
  defineTrpcFact,
  defineTrpcRouter,
  parseGovernedOutput,
  resolveTrustedHandlerArguments,
  TrpcHandlerBinding,
  TrpcRootDefinition,
  type ApiHandlerAdapter,
  type TrpcAccess,
  type TrpcAnonymousHandlerArguments,
  type TrpcBuildableProcedure,
  type TrpcContractHandlerArguments,
  type TrpcContractProcedures,
  type TrpcErrorCausePayload,
  type TrpcFact,
  type TrpcFactBinding,
  type TrpcFeatureApiWitness,
  type TrpcHandlerActor,
  type TrpcMountOptions,
  type TrpcProceduresNotImplemented,
  type TrpcProcedureFactory,
  type TrpcProcedureRequest,
  type TrpcRoot,
  type TrpcRouterAccess,
  type TrpcRouterBuilder,
  type TrpcRouterDeclaration,
  type TrpcRouterImplementation,
  type TrpcRouterMount,
  type TrpcRuntime,
  type TrpcRuntimeAuditEntry,
  type TrpcRuntimeContext,
  type TrpcRuntimePorts,
  type TrpcRuntimeRequest,
} from "./runtime.ts";

export {
  auditScopeIds,
  callerTraceContext,
  deriveAuditTarget,
  handleTrpcCallLogging,
  isAuditLogExempt,
  isSilencedCall,
  recordTrpcCall,
  redactAuditArgs,
  resetSlowCallThrottle,
  resolveSlowCallBudgetMs,
  TrpcFailureTraceIds,
  trpcFailureTraceIds,
} from "./audit.ts";

export {
  createDeclaredAuthzMiddlewares,
  createIsPublicProcedure,
  createPermissionProcedureBuilder,
  createScopeLineageGuard,
  createTrpcRuntimePolicy,
  type PendingPermissionProcedureBuilder,
  type TrpcActor,
  type TrpcActorPort,
  type TrpcAuditEntry,
  type TrpcAudit,
  type TrpcAuthenticatedMiddlewareContext,
  type TrpcAuthorizationDecisions,
  type TrpcAuthorizationDenial,
  type TrpcAuthorization,
  type TrpcCauseTranslation,
  type TrpcCheckMiddleware,
  type TrpcContextOnlyCheckParams,
  type TrpcContextOnlyDeclaredCheck,
  type TrpcDeclaredAuthzContext,
  type TrpcDeclaredAuthzMiddlewares,
  type TrpcDeclaredAuthzMembers,
  type TrpcDeclaredCheck,
  type TrpcDeclaredCheckParams,
  type TrpcErrorReporting,
  type TrpcIdentity,
  type TrpcMiddlewareContext,
  type TrpcOrganizationRole,
  type TrpcPolicyChainMiddlewares,
  type TrpcPolicyContext,
  type TrpcRequestHeaders,
  type TrpcRequestLike,
  type TrpcResponseLike,
  type TrpcRuntimePolicyMembers,
  type TrpcTranslatedCause,
} from "./policy.ts";

export type { ApiHandlerArguments } from "../handler-arguments.ts";
