/**
 * The application's REST boundary, owned by the API process. The kit itself no longer
 * lives here.
 */
export {
  type AccessPolicy,
  anyAuthenticated,
  apiKeyPermission,
  type CredentialClass,
  credentialClassFor,
  describeAccessPolicy,
  type HandlerCredential,
  handlerManagedAuth,
  internalSecret,
  isApiKeyReachable,
  policyPermissions,
  publicEndpoint,
  requires,
  requiresOnProject,
  requiresOnTeam,
} from "@langwatch/api";

export {
  type ApiErrorBody,
  type ApiErrorEnvelope,
  API_ERROR_TYPE_BY_STATUS,
  allRegisteredRoutes,
  apiErrorBody,
  apiErrorSchema,
  apiErrorType,
  type AppRestBroadcast,
  type AppRestManagementAuditPort,
  type AppRestOrganizationVariables,
  type AppRestProjectVariables,
  type AppRestRbacVocabulary,
  type AppRestSecurity,
  type AppRestSecurityPorts,
  BadRequestError,
  badRequestSchema,
  baseResponses,
  buildStandardSuccessResponse,
  canonicalBaseResponses,
  canonicalConflictResponses,
  canonicalUnprocessableResponses,
  coerceToEpoch,
  conflictResponses,
  conflictSchema,
  createAppRestSecurity,
  createCanonicalFamilyErrorHandler,
  createFamilyErrorHandler,
  documentedPathOf,
  emitManagementAudit,
  errorSchema,
  FALLBACK_API_ERROR_TYPE,
  familyFromBasePath,
  type FieldViolation,
  flexibleDateSchema,
  ForbiddenError,
  getRoutePolicy,
  HttpError,
  IDEMPOTENCY_KEY_HEADER,
  IDEMPOTENT_REPLAY_HEADER,
  type IdempotentHandlerResult,
  type IdempotentOutcome,
  type IdempotentRunner,
  idempotencyKeyParameter,
  idempotentJson,
  idempotentReplayHeaders,
  InternalServerError,
  isHttpMethod,
  jsonResponse,
  managementActor,
  MANAGEMENT_API_VERSION,
  MAX_KEY_LENGTH,
  MIN_KEY_LENGTH,
  type MountableRestApp,
  NotFoundError,
  PersonalProjectKeyRequiredError,
  PersonalUsageKeyMismatchError,
  type PlatformUrlBuilder,
  rateLimitedResponse,
  readIdempotencyKey,
  type RegisteredRoute,
  registerRoutePolicy,
  RequestValidationError,
  requestTraceIds,
  resolvePersonalCaller,
  type RestApiVersionedFamily,
  type RouteResponse,
  safeMediaType,
  sanitizeFilenameSegment,
  SecuredApp,
  type SecuredVerbs,
  type SecurityRequirement,
  securityForCredentialClass,
  STORED_OBJECT_RESPONSE_BASE_HEADERS,
  successSchema,
  UnauthorizedError,
  unauthorizedSchema,
  UnprocessableEntityError,
  validator,
  type VersionedEndpointMeta,
} from "@langwatch/api/rest";
