import { Ksuid, Instance, getEnvironment } from "@langwatch/ksuid";
import { createHash } from "crypto";
import { EventUtils } from "../../../library";
import type { SpanReceivedEvent } from "../schemas/events";

/**
 * Generates a deterministic span record ID from a SpanReceivedEvent.
 * This ensures that replaying events produces the same IDs for idempotency,
 * while maintaining K-sortability by span start time.
 *
 * The ID is generated by:
 * 1. Validating the tenant ID
 * 2. Hashing the combination of tenantId, traceId, and spanId
 * 3. Using the hash to create deterministic KSUID components
 * 4. Using the span's timestamp for K-sortability
 *
 * @param event - The SpanReceivedEvent containing span data
 * @returns A deterministic KSUID string for the span record
 *
 * @example
 * ```typescript
 * const recordId = generateDeterministicSpanRecordId(spanReceivedEvent);
 * // Always returns the same ID for the same event
 * ```
 */
function generateDeterministicSpanRecordId(event: SpanReceivedEvent): string {
  return generateDeterministicSpanRecordIdFromData(
    String(event.tenantId),
    event.data.spanData.traceId,
    event.data.spanData.spanId,
    event.data.spanData.startTimeUnixMs,
  );
}

/**
 * Generates a deterministic span record ID from raw span data.
 * This is a fallback for repository operations where the full event is not available.
 * Event handlers should use generateDeterministicSpanRecordId(event) instead.
 *
 * @param tenantId - The tenant ID
 * @param traceId - The OpenTelemetry trace ID
 * @param spanId - The OpenTelemetry span ID
 * @param timestampMs - The span start timestamp in milliseconds
 * @returns A deterministic KSUID string for the span record
 */
function generateDeterministicSpanRecordIdFromData(
  tenantId: string,
  traceId: string,
  spanId: string,
  timestampMs: number,
): string {
  EventUtils.validateTenantId(
    { tenantId },
    "generateDeterministicSpanRecordIdFromData",
  );

  // Create a deterministic hash from tenantId + traceId + spanId
  const hash = createHash("sha256")
    .update(`${tenantId}:${traceId}:${spanId}`)
    .digest();

  // Use first 8 bytes of hash as instance identifier
  const instanceIdentifier = new Uint8Array(hash.subarray(0, 8));

  // Create a deterministic instance using RANDOM scheme
  const instance = new Instance(Instance.schemes.RANDOM, instanceIdentifier);

  // Convert milliseconds to seconds for KSUID timestamp
  const timestampSeconds = Math.floor(timestampMs / 1000);

  // Use sequence 0 for deterministic generation
  const sequenceId = 0;

  // Create KSUID with deterministic components
  const ksuid = new Ksuid(
    getEnvironment(),
    "span",
    timestampSeconds,
    instance,
    sequenceId,
  );

  return ksuid.toString();
}

/**
 * Generates a deterministic trace summary ID from a SpanReceivedEvent.
 * This ensures that replaying events produces the same IDs for idempotency,
 * while maintaining K-sortability by trace start time.
 *
 * The ID is generated by:
 * 1. Validating the tenant ID
 * 2. Hashing the combination of tenantId and traceId
 * 3. Using the hash to create deterministic KSUID components
 * 4. Using the trace's first span timestamp for K-sortability
 *
 * @param event - The SpanReceivedEvent containing trace data
 * @returns A deterministic KSUID string for the trace summary
 *
 * @example
 * ```typescript
 * const traceummaryId = generateDeterministicTraceSummaryId(spanReceivedEvent);
 * // Always returns the same ID for the same event
 * ```
 */
function generateDeterministicTraceSummaryId(event: SpanReceivedEvent): string {
  return generateDeterministicTraceSummaryIdFromData(
    String(event.tenantId),
    event.data.spanData.traceId,
    event.data.spanData.startTimeUnixMs,
  );
}

/**
 * Generates a deterministic trace summary ID from raw trace data.
 * This is a fallback for repository operations where the full event is not available.
 * Event handlers should use generateDeterministicTraceSummaryId(event) instead.
 *
 * @param tenantId - The tenant ID
 * @param traceId - The OpenTelemetry trace ID
 * @param timestampMs - The trace's first span start timestamp in milliseconds
 * @returns A deterministic KSUID string for the trace summary
 *
 * @example
 * ```typescript
 * const traceummaryId = generateDeterministicTraceSummaryIdFromData(tenantId, traceId, timestampMs);
 * // Always returns the same ID for the same inputs
 * ```
 */
function generateDeterministicTraceSummaryIdFromData(
  tenantId: string,
  traceId: string,
  timestampMs: number,
): string {
  EventUtils.validateTenantId(
    { tenantId },
    "generateDeterministicTraceSummaryIdFromData",
  );

  // Create a deterministic hash from tenantId + traceId + spanId
  const hash = createHash("sha256").update(`${tenantId}:${traceId}`).digest();

  // Use first 8 bytes of hash as instance identifier
  const instanceIdentifier = new Uint8Array(hash.subarray(0, 8));

  // Create a deterministic instance using RANDOM scheme
  const instance = new Instance(Instance.schemes.RANDOM, instanceIdentifier);

  // Convert milliseconds to seconds for KSUID timestamp
  const timestampSeconds = Math.floor(timestampMs / 1000);

  // Use sequence 0 for deterministic generation
  const sequenceId = 0;

  // Create KSUID with deterministic components
  const ksuid = new Ksuid(
    getEnvironment(),
    "tracesummary",
    timestampSeconds,
    instance,
    sequenceId,
  );

  return ksuid.toString();
}

export {
  generateDeterministicSpanRecordId,
  generateDeterministicSpanRecordIdFromData,
  generateDeterministicTraceSummaryId,
  generateDeterministicTraceSummaryIdFromData,
};

export const IdUtils = {
  generateDeterministicSpanRecordId,
  generateDeterministicSpanRecordIdFromData,
  generateDeterministicTraceSummaryId,
  generateDeterministicTraceSummaryIdFromData,
} as const;
