export interface CodingAgentSessionDisplay {
  traceIds: string[];
  costUsd: number;
  modelCalls: number;
  toolCalls: number;
  subAgents: number;
  filesTouched: string[];
  steps: [string, number, boolean][];
  toolCounts: Record<string, number>;
  toolDurationMs: Record<string, number>;
  models: string[];
  mcpServers: string[];
  mcpTools: string[];
  skills: string[];
  subAgentTypes: string[];
  slashCommands: string[];
  cacheReadTokens: number;
  cacheCreationTokens: number;
  cacheRebuildCount: number;
  largestCacheRebuildTokens: number;
  peakContextTokens: number;
  compactions: number;
  compactionTokensBefore: number;
  compactionTokensAfter: number;
  modelCallMs: number;
  toolMs: number;
  ttftMsTotal: number;
  ttftSamples: number;
  blockedOnUserMs: number;
  retryMs: number;
  linesAdded: number;
  linesRemoved: number;
  commits: number;
  pullRequests: number;
  editsAccepted: number;
  editsRejected: number;
  languagesEdited: string[];
  truncated: boolean;
  rateLimited: number;
  retriesExhausted: number;
  toolsDenied: number;
  hooksBlocked: number;
  failedTools: number;
  errorTypes: Record<string, number>;
  refusals: number;
  refusalCategories: string[];
  permissionChanges: number;
  permissionMode: string;
}
