FROM python:3.11-slim

WORKDIR /usr/src/app

RUN pip install poetry
RUN pip install --target . awslambdaric

COPY poetry.toml poetry.lock pyproject.toml .
RUN poetry install

COPY . .

EXPOSE 8080

ENTRYPOINT [ "/usr/local/bin/poetry", "run", "python", "-m", "awslambdaric" ]
CMD [ "langwatch_nlp.main.handler" ]
