FROM python:3.11-slim

WORKDIR /usr/src/app

RUN pip install uv

COPY .python-version uv.lock pyproject.toml .
RUN uv sync

RUN uv pip install awslambdaric

COPY . .

# Preload for faster subsequent startups
RUN PYTHONPATH=. uv run python langwatch_nlp/main.py

ENV RUNNING_IN_DOCKER=true

EXPOSE 8080

ENTRYPOINT [ "uv", "--no-cache", "run", "python", "-m", "awslambdaric" ]
CMD [ "langwatch_nlp.main.handler" ]
