FROM python:3.12-slim-bookworm
COPY --from=public.ecr.aws/awsguru/aws-lambda-adapter:0.8.4 /lambda-adapter /opt/extensions/lambda-adapter

WORKDIR /usr/src/app

RUN pip install uv

COPY .python-version uv.lock pyproject.toml .
RUN uv sync

COPY . .

# Preload for faster subsequent startups
RUN PYTHONPATH=. uv run python langwatch_nlp/main.py

ENV RUNNING_IN_DOCKER=true

EXPOSE 8080

CMD uv --no-cache run uvicorn langwatch_nlp.main:app --host 0.0.0.0 --port 8080 --timeout-keep-alive 4500