"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.UpdateOAuth2JwtRequestTokenResponseField = void 0;
exports.UpdateOAuth2JwtRequestTokenResponseField = {
    AccessToken: "access_token",
    IdToken: "id_token",
};
