// Generated from prisma/schema.prisma by scripts/generate-table-catalogue.mjs.
export const prismaTableCatalogue = {
  "Account": "Account",
  "AccountCredential": "AccountCredential",
  "Session": "Session",
  "User": "User",
  "VerificationToken": "VerificationToken",
  "Identifier": "Identifier",
  "IdentifierReservation": "IdentifierReservation",
  "IdentityProjectionCursor": "IdentityProjectionCursor",
  "TwoFactor": "TwoFactor",
  "Passkey": "Passkey",
  "MfaEnrollment": "MfaEnrollment",
  "SsoConnection": "SsoConnection",
  "JoinRequest": "JoinRequest",
  "TeamUser": "TeamUser",
  "OrganizationUser": "OrganizationUser",
  "Team": "Team",
  "Organization": "Organization",
  "ScimToken": "ScimToken",
  "ScimExternalId": "ScimExternalId",
  "ScimSyncState": "ScimSyncState",
  "Project": "Project",
  "Department": "Department",
  "PlatformToolPolicy": "PlatformToolPolicy",
  "OrganizationInvite": "OrganizationInvite",
  "Monitor": "Monitor",
  "Cost": "Cost",
  "Topic": "Topic",
  "Dataset": "Dataset",
  "DatasetRecord": "DatasetRecord",
  "Dashboard": "Dashboard",
  "SavedView": "SavedView",
  "CustomGraph": "CustomGraph",
  "BatchEvaluation": "BatchEvaluation",
  "Trigger": "Trigger",
  "WebhookEndpoint": "WebhookEndpoint",
  "WebhookEndpointDelivery": "WebhookEndpointDelivery",
  "Experiment": "Experiment",
  "ExperimentVersion": "ExperimentVersion",
  "Annotation": "Annotation",
  "ModelProvider": "ModelProvider",
  "ModelProviderScope": "ModelProviderScope",
  "ModelDefaultConfig": "ModelDefaultConfig",
  "ModelDefaultConfigScope": "ModelDefaultConfigScope",
  "GithubInstallation": "GithubInstallation",
  "GithubPullRequest": "GithubPullRequest",
  "GithubBranchPullRequestCheck": "GithubBranchPullRequestCheck",
  "LangyConversationProjection": "LangyConversationProjection",
  "LangyTurnRequest": "LangyTurnRequest",
  "LangyActiveTurn": "LangyActiveTurn",
  "LangyConversationTurnProjection": "LangyConversationTurnProjection",
  "LangyMessageProjection": "LangyMessageProjection",
  "ProjectSecret": "ProjectSecret",
  "TriggerSent": "TriggerSent",
  "EmailSuppression": "EmailSuppression",
  "AnnotationScore": "AnnotationScore",
  "AnnotationQueue": "AnnotationQueue",
  "AnnotationQueueMembers": "AnnotationQueueMembers",
  "AnnotationQueueScores": "AnnotationQueueScores",
  "AnnotationQueueItem": "AnnotationQueueItem",
  "ShareLink": "ShareLink",
  "PinnedTrace": "PinnedTrace",
  "TraceEditOverlay": "TraceEditOverlay",
  "RetentionPolicy": "RetentionPolicy",
  "DataPrivacyPolicy": "DataPrivacyPolicy",
  "CustomLLMModelCost": "CustomLLMModelCost",
  "Workflow": "Workflow",
  "WorkflowVersion": "WorkflowVersion",
  "AuditLog": "AuditLog",
  "LlmPromptConfig": "LlmPromptConfig",
  "LlmPromptConfigVersion": "LlmPromptConfigVersion",
  "PromptTagAssignment": "PromptTagAssignment",
  "PromptTag": "PromptTag",
  "Analytics": "Analytics",
  "CustomRole": "CustomRole",
  "Notification": "Notification",
  "Agent": "Agent",
  "Evaluator": "Evaluator",
  "Scenario": "Scenario",
  "ScenarioVersion": "ScenarioVersion",
  "SimulationSuite": "SimulationSuite",
  "Subscription": "Subscription",
  "Invoice": "Invoice",
  "InvoiceItem": "InvoiceItem",
  "Group": "Group",
  "GroupMembership": "GroupMembership",
  "RoleBinding": "RoleBinding",
  "Grant": "Grant",
  "GrantUsage": "GrantUsage",
  "Role": "Role",
  "ApiKey": "ApiKey",
  "BillingMeterCheckpoint": "BillingMeterCheckpoint",
  "VirtualKey": "VirtualKey",
  "VirtualKeyScope": "VirtualKeyScope",
  "RoutingPolicy": "RoutingPolicy",
  "RoutingPolicyScope": "RoutingPolicyScope",
  "GatewayGuardrail": "GatewayGuardrail",
  "IngestionSource": "IngestionSource",
  "AnomalyRule": "AnomalyRule",
  "AnomalyAlert": "AnomalyAlert",
  "AiToolEntry": "AiToolEntry",
  "AiToolEntryTeam": "AiToolEntryTeam",
  "AiToolEntryDepartment": "AiToolEntryDepartment",
  "IngestionTemplate": "IngestionTemplate",
  "GatewayBudget": "GatewayBudget",
  "GatewayBudgetBucketBoundary": "GatewayBudgetBucketBoundary",
  "GatewayBudgetLedger": "GatewayBudgetLedger",
  "GatewayChangeEvent": "GatewayChangeEvent",
  "GatewayCacheRule": "GatewayCacheRule",
  "FeatureFlag": "FeatureFlag",
  "FeatureFlagExperimentSetting": "FeatureFlagExperimentSetting",
  "ProcessManagerInstance": "ProcessManagerInstance",
  "ProcessManagerInbox": "ProcessManagerInbox",
  "ProcessManagerOutbox": "ProcessManagerOutbox",
  "ProcessManagerOutboxAttempt": "ProcessManagerOutboxAttempt",
  "TopicClusteringRunProjection": "TopicClusteringRunProjection",
  "TopicModelProjection": "TopicModelProjection",
  "TopicClusteringRunHistoryProjection": "TopicClusteringRunHistoryProjection",
  "IngestionPullRunProjection": "IngestionPullRunProjection",
  "ScheduledJob": "ScheduledJob",
  "BugReport": "BugReport",
  "IdempotencyReceipt": "IdempotencyReceipt",
  "GatewayRealtimeSession": "GatewayRealtimeSession",
  "SystemMigrationTenantState": "SystemMigrationTenantState",
  "SystemMigrationEnrollment": "SystemMigrationEnrollment",
  "StoredObject": "StoredObject"
} as const;

export const prismaModelFieldCatalogue = {
  "Account": [
    "id",
    "userId",
    "type",
    "provider",
    "issuer",
    "providerAccountId",
    "refresh_token",
    "access_token",
    "expires_at",
    "ext_expires_in",
    "token_type",
    "scope",
    "id_token",
    "session_state",
    "password",
    "user",
    "createdAt",
    "updatedAt"
  ],
  "AccountCredential": [
    "id",
    "userId",
    "user",
    "provider",
    "password",
    "accessToken",
    "refreshToken",
    "idToken",
    "accessTokenExpiresAt",
    "refreshTokenExpiresAt",
    "scope",
    "createdAt",
    "updatedAt"
  ],
  "Session": [
    "id",
    "sessionToken",
    "userId",
    "expires",
    "user",
    "impersonating",
    "ipAddress",
    "userAgent",
    "identifierId",
    "amr",
    "createdAt",
    "updatedAt"
  ],
  "User": [
    "id",
    "name",
    "email",
    "emailVerified",
    "image",
    "pendingSsoSetup",
    "userHashKey",
    "twoFactorEnabled",
    "accounts",
    "accountCredentials",
    "sessions",
    "twoFactors",
    "passkeys",
    "teamMemberships",
    "orgMemberships",
    "createdAt",
    "updatedAt",
    "lastLoginAt",
    "deactivatedAt",
    "lastHomePath",
    "tracesExplorerTourDismissedAt",
    "langyCodeAccessPreference",
    "passkeyNudgeDismissedAt",
    "Annotation",
    "shareLinks",
    "Workflow",
    "WorkflowVersion",
    "annotationQueues",
    "assignedQueueItems",
    "createdQueueItems",
    "llmPromptConfigVersions",
    "scenarios",
    "inviteRequests",
    "secretsCreated",
    "secretsUpdated",
    "savedViews",
    "versionTagsCreated",
    "versionTagsUpdated",
    "promptTagsCreated",
    "promptTagsUpdated",
    "groupMemberships",
    "roleBindings",
    "scimExternalIds",
    "apiKeys",
    "gatewayBudgetsCreated",
    "principalVirtualKeys",
    "personalTeams",
    "personalProjects",
    "routingPoliciesCreated",
    "routingPoliciesUpdated",
    "gatewayGuardrailsCreated",
    "gatewayGuardrailsUpdated",
    "ingestionSourcesCreated",
    "anomalyRulesCreated",
    "pinnedTraces",
    "traceEditOverlaysCreated",
    "traceEditOverlaysUpdated"
  ],
  "VerificationToken": [
    "id",
    "identifier",
    "token",
    "expires",
    "createdAt",
    "updatedAt"
  ],
  "Identifier": [
    "id",
    "userId",
    "provider",
    "value",
    "domain",
    "identifierHash",
    "accountId",
    "providerId",
    "issuer",
    "providerAccountId",
    "state",
    "connectionId",
    "verifiedAt",
    "attachedAt",
    "detachedAt",
    "createdAt",
    "updatedAt"
  ],
  "IdentifierReservation": [
    "normalizedValue",
    "userId",
    "identifierId",
    "commandId",
    "createdAt"
  ],
  "IdentityProjectionCursor": [
    "userId",
    "lastEventId",
    "acceptedAt",
    "occurredAt",
    "projectionVersion",
    "createdAt",
    "updatedAt"
  ],
  "TwoFactor": [
    "id",
    "userId",
    "user",
    "secret",
    "backupCodes",
    "verified",
    "failedVerificationCount",
    "lockedUntil",
    "createdAt",
    "updatedAt"
  ],
  "Passkey": [
    "id",
    "name",
    "publicKey",
    "userId",
    "user",
    "credentialID",
    "counter",
    "deviceType",
    "backedUp",
    "transports",
    "aaguid",
    "createdAt",
    "updatedAt"
  ],
  "MfaEnrollment": [
    "userId",
    "enrollmentId",
    "method",
    "state",
    "enrolledAt",
    "confirmedAt",
    "expiredAt",
    "disabledAt",
    "disabledVia",
    "backupCodeCount",
    "consumedBackupCodeIndexes",
    "failedCount",
    "occurredAt",
    "lastEventId",
    "acceptedAt",
    "projectionVersion",
    "createdAt",
    "updatedAt"
  ],
  "SsoConnection": [
    "id",
    "organizationId",
    "type",
    "state",
    "claimedDomains",
    "approvedDomains",
    "verifiedDomains",
    "domainVerifications",
    "pendingVerification",
    "idpMetadata",
    "allowsJit",
    "source",
    "testLoginAccountId",
    "rejection",
    "createdBy",
    "tearDownAfter",
    "occurredAt",
    "lastEventId",
    "acceptedAt",
    "projectionVersion",
    "createdAt",
    "updatedAt"
  ],
  "JoinRequest": [
    "id",
    "userId",
    "organizationId",
    "domain",
    "state",
    "matchedVia",
    "expiresAt",
    "resolvedAt",
    "resolvedByType",
    "resolvedById",
    "withdrawalCause",
    "occurredAt",
    "lastEventId",
    "acceptedAt",
    "projectionVersion",
    "createdAt",
    "updatedAt"
  ],
  "TeamUser": [
    "userId",
    "teamId",
    "role",
    "assignedRoleId",
    "assignedRole",
    "user",
    "team",
    "createdAt",
    "updatedAt"
  ],
  "OrganizationUser": [
    "userId",
    "organizationId",
    "role",
    "user",
    "organization",
    "createdAt",
    "updatedAt",
    "departmentId",
    "disabledAt"
  ],
  "Team": [
    "id",
    "name",
    "slug",
    "members",
    "organizationId",
    "organization",
    "projects",
    "createdAt",
    "updatedAt",
    "archivedAt",
    "isPersonal",
    "ownerUserId",
    "ownerUser",
    "ingestionSources",
    "aiToolEntryTeams",
    "departmentId"
  ],
  "Organization": [
    "id",
    "name",
    "phoneNumber",
    "slug",
    "members",
    "teams",
    "webhookEndpoints",
    "createdAt",
    "updatedAt",
    "OrganizationInvite",
    "usageSpendingMaxLimit",
    "maxSessionDurationDays",
    "mfaRequired",
    "signupData",
    "signedDPA",
    "elasticsearchNodeUrl",
    "elasticsearchApiKey",
    "useCustomElasticsearch",
    "s3Endpoint",
    "s3AccessKeyId",
    "s3SecretAccessKey",
    "s3Bucket",
    "useCustomS3",
    "sentPlanLimitAlert",
    "ssoDomain",
    "ssoProvider",
    "domainJoin",
    "joinDomains",
    "presenceEnabled",
    "traceSharingEnabled",
    "supportContact",
    "primaryIntent",
    "promoCode",
    "stripeCustomerId",
    "currency",
    "pricingModel",
    "CustomRoles",
    "notifications",
    "subscriptions",
    "scimTokens",
    "promptTags",
    "groups",
    "roleBindings",
    "apiKeys",
    "license",
    "licenseExpiresAt",
    "licenseLastValidatedAt",
    "gatewayChangeEvents",
    "routingPolicies",
    "ingestionSources",
    "anomalyRules",
    "anomalyAlerts",
    "aiToolEntries",
    "ingestionTemplates",
    "githubInstallations",
    "githubPullRequests",
    "githubBranchPrChecks"
  ],
  "ScimToken": [
    "id",
    "organizationId",
    "organization",
    "connectionId",
    "hashedToken",
    "description",
    "createdAt",
    "lastUsedAt"
  ],
  "ScimExternalId": [
    "id",
    "connectionId",
    "externalId",
    "userId",
    "user",
    "createdAt",
    "updatedAt"
  ],
  "ScimSyncState": [
    "id",
    "connectionId",
    "organizationId",
    "state",
    "lastPushedAt",
    "lastFailure",
    "deadLetters",
    "revokedCause",
    "occurredAt",
    "lastEventId",
    "acceptedAt",
    "projectionVersion",
    "createdAt",
    "updatedAt"
  ],
  "Project": [
    "id",
    "name",
    "slug",
    "apiKey",
    "lwqlKey",
    "teamId",
    "team",
    "language",
    "framework",
    "kind",
    "firstMessage",
    "integrated",
    "createdAt",
    "updatedAt",
    "userLinkTemplate",
    "checks",
    "costs",
    "topics",
    "datasets",
    "datasetRecords",
    "customGraphs",
    "dashboards",
    "batchEvaluations",
    "traceSharingEnabled",
    "presenceEnabled",
    "triggers",
    "experiments",
    "annotations",
    "projectSecrets",
    "TriggerSent",
    "webhookDeliveries",
    "annotationScores",
    "shareLinks",
    "workflows",
    "WorkflowVersion",
    "AnnotationQueue",
    "AnnotationQueueItem",
    "s3Endpoint",
    "s3AccessKeyId",
    "s3SecretAccessKey",
    "s3Bucket",
    "llmPromptConfigs",
    "analytics",
    "archivedAt",
    "notifications",
    "agents",
    "evaluators",
    "scenarios",
    "suiteConfigurations",
    "savedViews",
    "gatewayGuardrails",
    "gatewayChangeEvents",
    "pinnedTraces",
    "traceEditOverlays",
    "emailSuppressions",
    "isPersonal",
    "ownerUserId",
    "ownerUser",
    "personalFeatures",
    "departmentId",
    "langyEgressAllowlist",
    "lastCodingAgentSessionAt",
    "lastCodingAgentPullRequestAt"
  ],
  "Department": [
    "id",
    "organizationId",
    "name",
    "createdAt",
    "updatedAt",
    "archivedAt"
  ],
  "PlatformToolPolicy": [
    "id",
    "organizationId",
    "toolSlug",
    "allowVk",
    "allowOtelDirect",
    "createdAt",
    "updatedAt"
  ],
  "OrganizationInvite": [
    "id",
    "email",
    "inviteCode",
    "expiration",
    "status",
    "organizationId",
    "organization",
    "teamIds",
    "teamAssignments",
    "role",
    "requestedBy",
    "requestedByUser",
    "subscriptionId",
    "acceptedByUserId",
    "acceptedViaIdentifierId",
    "createdAt",
    "updatedAt"
  ],
  "Monitor": [
    "id",
    "projectId",
    "project",
    "experimentId",
    "experiment",
    "evaluatorId",
    "evaluator",
    "checkType",
    "name",
    "slug",
    "executionMode",
    "enabled",
    "preconditions",
    "parameters",
    "mappings",
    "sample",
    "level",
    "threadIdleTimeout",
    "createdAt",
    "updatedAt"
  ],
  "Cost": [
    "id",
    "projectId",
    "project",
    "costType",
    "costName",
    "referenceType",
    "referenceId",
    "amount",
    "currency",
    "createdAt",
    "updatedAt",
    "extraInfo"
  ],
  "Topic": [
    "id",
    "projectId",
    "project",
    "name",
    "parentId",
    "parent",
    "subtopics",
    "embeddings_model",
    "centroid",
    "p95Distance",
    "automaticallyGenerated",
    "lastEventId",
    "createdAt",
    "updatedAt"
  ],
  "Dataset": [
    "id",
    "projectId",
    "project",
    "name",
    "slug",
    "columnTypes",
    "createdAt",
    "updatedAt",
    "archivedAt",
    "datasetRecords",
    "batchEvaluations",
    "mapping",
    "useS3",
    "s3RecordCount",
    "contentLayout",
    "status",
    "statusError",
    "stagingKey",
    "uploadFilename",
    "rowCount",
    "sizeBytes",
    "chunkCount",
    "chunkOffsets"
  ],
  "DatasetRecord": [
    "id",
    "datasetId",
    "dataset",
    "projectId",
    "project",
    "entry",
    "createdAt",
    "updatedAt"
  ],
  "Dashboard": [
    "id",
    "projectId",
    "project",
    "name",
    "order",
    "createdAt",
    "updatedAt",
    "graphs"
  ],
  "SavedView": [
    "id",
    "projectId",
    "project",
    "userId",
    "user",
    "name",
    "filters",
    "query",
    "period",
    "order",
    "kind",
    "createdAt",
    "updatedAt"
  ],
  "CustomGraph": [
    "id",
    "projectId",
    "project",
    "name",
    "graph",
    "filters",
    "kind",
    "createdAt",
    "updatedAt",
    "dashboardId",
    "dashboard",
    "gridColumn",
    "gridRow",
    "colSpan",
    "rowSpan",
    "trigger",
    "TriggerSent"
  ],
  "BatchEvaluation": [
    "id",
    "experimentId",
    "experiment",
    "projectId",
    "project",
    "data",
    "status",
    "score",
    "label",
    "passed",
    "details",
    "cost",
    "datasetSlug",
    "datasetId",
    "dataset",
    "evaluation",
    "createdAt",
    "updatedAt"
  ],
  "Trigger": [
    "id",
    "name",
    "projectId",
    "project",
    "action",
    "triggerKind",
    "actionParams",
    "filters",
    "filterQuery",
    "lastRunAt",
    "createdAt",
    "updatedAt",
    "active",
    "pausedReason",
    "pausedAt",
    "message",
    "deleted",
    "alertType",
    "slackTemplateType",
    "slackTemplate",
    "emailSubjectTemplate",
    "emailBodyTemplate",
    "notificationCadence",
    "traceDebounceMs",
    "TriggerSent",
    "webhookDeliveries",
    "customGraphId",
    "customGraph"
  ],
  "WebhookEndpoint": [
    "id",
    "organizationId",
    "organization",
    "destinationKind",
    "url",
    "sqsQueueUrl",
    "sqsRoleArn",
    "sqsExternalId",
    "sqsAccessKeyId",
    "sqsSecretAccessKeyEncrypted",
    "secretEncrypted",
    "previousSecretEncrypted",
    "previousSecretExpiresAt",
    "enabledEvents",
    "status",
    "disabledReason",
    "disabledAt",
    "failingSince",
    "maxBatchSize",
    "maxBatchDelayMs",
    "maxInFlight",
    "lastSuccessAt",
    "lastFailureAt",
    "archivedAt",
    "createdAt",
    "updatedAt",
    "deliveries"
  ],
  "WebhookEndpointDelivery": [
    "id",
    "channel",
    "organizationId",
    "endpointId",
    "endpoint",
    "projectId",
    "project",
    "triggerId",
    "trigger",
    "dispatchId",
    "attempt",
    "eventCount",
    "responseStatus",
    "latencyMs",
    "error",
    "response",
    "outcome",
    "firedAt",
    "createdAt"
  ],
  "Experiment": [
    "id",
    "name",
    "type",
    "slug",
    "projectId",
    "project",
    "workflowId",
    "workflow",
    "createdAt",
    "updatedAt",
    "archivedAt",
    "batchEvaluations",
    "workbenchState",
    "monitor",
    "workbenchVersion"
  ],
  "ExperimentVersion": [
    "id",
    "experimentId",
    "projectId",
    "version",
    "counterVersion",
    "autoSaved",
    "commitMessage",
    "authorId",
    "authorLabel",
    "runId",
    "state",
    "schemaVersion",
    "createdAt",
    "updatedAt"
  ],
  "Annotation": [
    "id",
    "projectId",
    "project",
    "traceId",
    "comment",
    "isThumbsUp",
    "userId",
    "user",
    "createdAt",
    "updatedAt",
    "email",
    "scoreOptions",
    "expectedOutput",
    "anchorKind",
    "anchorId",
    "anchorPath"
  ],
  "ModelProvider": [
    "id",
    "name",
    "provider",
    "routingHandle",
    "enabled",
    "customKeys",
    "extraHeaders",
    "customModels",
    "customEmbeddingsModels",
    "deploymentMapping",
    "rateLimitRpm",
    "rateLimitTpm",
    "rateLimitRpd",
    "rotationPolicy",
    "providerConfig",
    "fallbackPriorityGlobal",
    "langySkipPermissionsModels",
    "healthStatus",
    "circuitOpenedAt",
    "lastHealthCheckAt",
    "disabledAt",
    "createdAt",
    "updatedAt",
    "scopes",
    "organizationId"
  ],
  "ModelProviderScope": [
    "id",
    "modelProviderId",
    "modelProvider",
    "scopeType",
    "scopeId",
    "createdAt"
  ],
  "ModelDefaultConfig": [
    "id",
    "config",
    "authorId",
    "createdAt",
    "updatedAt",
    "scopes",
    "organizationId"
  ],
  "ModelDefaultConfigScope": [
    "id",
    "configId",
    "config",
    "scopeType",
    "scopeId",
    "createdAt"
  ],
  "GithubInstallation": [
    "id",
    "installationId",
    "organizationId",
    "organization",
    "accountLogin",
    "accountType",
    "accountId",
    "repositorySelection",
    "repositories",
    "suspendedAt",
    "createdAt",
    "updatedAt"
  ],
  "GithubPullRequest": [
    "id",
    "organizationId",
    "organization",
    "repositoryHost",
    "repositoryFullName",
    "headBranch",
    "prNumber",
    "htmlUrl",
    "title",
    "state",
    "isDraft",
    "authorLogin",
    "prCreatedAt",
    "prClosedAt",
    "prMergedAt",
    "prUpdatedAt",
    "mappedAt",
    "lastCheckedAt",
    "createdAt",
    "updatedAt"
  ],
  "GithubBranchPullRequestCheck": [
    "id",
    "organizationId",
    "organization",
    "repositoryHost",
    "repositoryFullName",
    "headBranch",
    "lastCheckedAt",
    "prCount",
    "notFoundAt",
    "recheckAfter",
    "attempts",
    "lastRequestedAt",
    "createdAt",
    "updatedAt"
  ],
  "LangyConversationProjection": [
    "id",
    "projectId",
    "ConversationId",
    "UserId",
    "Title",
    "TitleSource",
    "Status",
    "IsShared",
    "SharedAt",
    "SharedById",
    "MessageCount",
    "LastActivityAt",
    "CurrentTurnId",
    "LastError",
    "LastModel",
    "PendingHandoffToken",
    "PendingHandoffTurnId",
    "RunToken",
    "ArchivedAt",
    "CreatedAt",
    "UpdatedAt",
    "OccurredAt",
    "AcceptedAt",
    "LastEventId",
    "ProjectionVersion"
  ],
  "LangyTurnRequest": [
    "id",
    "projectId",
    "userId",
    "requestId",
    "conversationId",
    "turnId",
    "status",
    "leaseOwner",
    "leaseExpiresAt",
    "createdAt",
    "updatedAt"
  ],
  "LangyActiveTurn": [
    "id",
    "projectId",
    "conversationId",
    "turnId",
    "requestId",
    "userId",
    "status",
    "leaseOwner",
    "leaseExpiresAt",
    "createdAt",
    "updatedAt"
  ],
  "LangyConversationTurnProjection": [
    "id",
    "projectId",
    "ConversationId",
    "TurnId",
    "Status",
    "QuestionParts",
    "AnswerParts",
    "ToolCalls",
    "Plan",
    "Error",
    "StartedAt",
    "EndedAt",
    "CreatedAt",
    "UpdatedAt",
    "OccurredAt",
    "AcceptedAt",
    "LastEventId",
    "ProjectionVersion"
  ],
  "LangyMessageProjection": [
    "id",
    "projectId",
    "ConversationId",
    "MessageId",
    "Role",
    "Parts",
    "SourceEventId",
    "OccurredAt",
    "AcceptedAt",
    "CreatedAt",
    "UpdatedAt"
  ],
  "ProjectSecret": [
    "id",
    "projectId",
    "project",
    "name",
    "encryptedValue",
    "createdById",
    "createdBy",
    "updatedById",
    "updatedBy",
    "createdAt",
    "updatedAt"
  ],
  "TriggerSent": [
    "id",
    "triggerId",
    "traceId",
    "customGraphId",
    "customGraph",
    "projectId",
    "project",
    "trigger",
    "resolvedAt",
    "openIncidentKey",
    "createdAt",
    "updatedAt"
  ],
  "EmailSuppression": [
    "id",
    "projectId",
    "project",
    "email",
    "triggerId",
    "reason",
    "createdAt"
  ],
  "AnnotationScore": [
    "id",
    "name",
    "projectId",
    "project",
    "createdAt",
    "updatedAt",
    "deletedAt",
    "description",
    "active",
    "dataType",
    "options",
    "defaultValue",
    "global",
    "AnnotationQueueScores"
  ],
  "AnnotationQueue": [
    "id",
    "name",
    "slug",
    "projectId",
    "description",
    "project",
    "members",
    "createdAt",
    "updatedAt",
    "AnnotationQueueScores",
    "AnnotationQueueItems"
  ],
  "AnnotationQueueMembers": [
    "annotationQueueId",
    "userId",
    "user",
    "annotationQueue"
  ],
  "AnnotationQueueScores": [
    "annotationQueueId",
    "annotationScoreId",
    "annotationScore",
    "annotationQueue"
  ],
  "AnnotationQueueItem": [
    "id",
    "annotationQueueId",
    "annotationQueue",
    "userId",
    "user",
    "createdAt",
    "updatedAt",
    "createdByUserId",
    "createdByUser",
    "traceId",
    "projectId",
    "doneAt",
    "markedForDatasetAt",
    "project"
  ],
  "ShareLink": [
    "id",
    "token",
    "resourceType",
    "resourceId",
    "threadId",
    "projectId",
    "project",
    "userId",
    "user",
    "visibility",
    "expiresAt",
    "maxViews",
    "viewCount",
    "createdAt",
    "updatedAt"
  ],
  "PinnedTrace": [
    "id",
    "projectId",
    "project",
    "traceId",
    "userId",
    "user",
    "source",
    "reason",
    "createdAt"
  ],
  "TraceEditOverlay": [
    "id",
    "projectId",
    "project",
    "traceId",
    "patch",
    "createdById",
    "createdBy",
    "updatedById",
    "updatedBy",
    "createdAt",
    "updatedAt"
  ],
  "RetentionPolicy": [
    "id",
    "organizationId",
    "scopeType",
    "scopeId",
    "category",
    "retentionDays",
    "createdAt",
    "updatedAt"
  ],
  "DataPrivacyPolicy": [
    "id",
    "organizationId",
    "scopeType",
    "scopeId",
    "personalOnly",
    "config",
    "createdAt",
    "updatedAt"
  ],
  "CustomLLMModelCost": [
    "id",
    "organizationId",
    "scopeType",
    "scopeId",
    "projectId",
    "model",
    "regex",
    "inputCostPerToken",
    "outputCostPerToken",
    "cacheReadCostPerToken",
    "cacheCreationCostPerToken",
    "cacheCreation1hCostPerToken",
    "createdAt",
    "updatedAt"
  ],
  "Workflow": [
    "id",
    "projectId",
    "project",
    "name",
    "icon",
    "description",
    "createdAt",
    "updatedAt",
    "latestVersionId",
    "latestVersion",
    "currentVersionId",
    "currentVersion",
    "versions",
    "publishedId",
    "publishedById",
    "publishedBy",
    "archivedAt",
    "experiments",
    "isEvaluator",
    "isComponent",
    "copiedFromWorkflowId",
    "copiedFrom",
    "copiedWorkflows",
    "agents",
    "evaluators"
  ],
  "WorkflowVersion": [
    "id",
    "version",
    "commitMessage",
    "authorId",
    "author",
    "projectId",
    "project",
    "workflowId",
    "workflow",
    "parentId",
    "parent",
    "children",
    "autoSaved",
    "createdAt",
    "updatedAt",
    "dsl",
    "WorkflowAsLatestVersion",
    "WorkflowAsCurrentVersion"
  ],
  "AuditLog": [
    "id",
    "createdAt",
    "userId",
    "projectId",
    "organizationId",
    "action",
    "args",
    "error",
    "ipAddress",
    "userAgent",
    "metadata",
    "targetKind",
    "targetId",
    "before",
    "after"
  ],
  "LlmPromptConfig": [
    "id",
    "handle",
    "name",
    "projectId",
    "project",
    "createdAt",
    "updatedAt",
    "deletedAt",
    "organizationId",
    "scope",
    "copiedFromPromptId",
    "copiedFrom",
    "copiedPrompts",
    "versions",
    "versionTags"
  ],
  "LlmPromptConfigVersion": [
    "id",
    "version",
    "commitMessage",
    "authorId",
    "author",
    "configId",
    "config",
    "configData",
    "schemaVersion",
    "runtimeParameters",
    "createdAt",
    "projectId",
    "versionTags"
  ],
  "PromptTagAssignment": [
    "id",
    "configId",
    "config",
    "versionId",
    "version",
    "tagId",
    "promptTag",
    "projectId",
    "createdAt",
    "updatedAt",
    "createdById",
    "createdBy",
    "updatedById",
    "updatedBy"
  ],
  "PromptTag": [
    "id",
    "organizationId",
    "organization",
    "name",
    "assignments",
    "createdAt",
    "updatedAt",
    "createdById",
    "createdBy",
    "updatedById",
    "updatedBy"
  ],
  "Analytics": [
    "id",
    "projectId",
    "project",
    "key",
    "value",
    "numericValue",
    "stringValue",
    "boolValue",
    "createdAt"
  ],
  "CustomRole": [
    "id",
    "organizationId",
    "organization",
    "name",
    "description",
    "permissions",
    "kind",
    "createdAt",
    "updatedAt",
    "assignedUsers",
    "roleBindings"
  ],
  "Notification": [
    "id",
    "organizationId",
    "organization",
    "projectId",
    "project",
    "metadata",
    "createdAt",
    "updatedAt",
    "sentAt"
  ],
  "Agent": [
    "id",
    "projectId",
    "project",
    "name",
    "type",
    "config",
    "workflowId",
    "workflow",
    "copiedFromAgentId",
    "copiedFrom",
    "copiedAgents",
    "environment",
    "ownerUserId",
    "hostLabel",
    "identityKey",
    "lastSeenAt",
    "archivedAt",
    "createdAt",
    "updatedAt"
  ],
  "Evaluator": [
    "id",
    "projectId",
    "project",
    "name",
    "slug",
    "type",
    "config",
    "workflowId",
    "workflow",
    "copiedFromEvaluatorId",
    "copiedFrom",
    "copiedEvaluators",
    "monitors",
    "gatewayGuardrails",
    "archivedAt",
    "createdAt",
    "updatedAt"
  ],
  "Scenario": [
    "id",
    "projectId",
    "project",
    "name",
    "situation",
    "criteria",
    "labels",
    "parameters",
    "simulatorModel",
    "judgeModel",
    "maxTurns",
    "minTurns",
    "testSuiteId",
    "testSuite",
    "version",
    "versions",
    "lastUpdatedById",
    "lastUpdatedBy",
    "archivedAt",
    "createdAt",
    "updatedAt"
  ],
  "ScenarioVersion": [
    "id",
    "scenarioId",
    "scenario",
    "projectId",
    "version",
    "authorId",
    "authorLabel",
    "changeDescription",
    "snapshot",
    "schemaVersion",
    "createdAt"
  ],
  "SimulationSuite": [
    "id",
    "projectId",
    "project",
    "name",
    "slug",
    "description",
    "scenarioIds",
    "targets",
    "repeatCount",
    "labels",
    "simulatorModel",
    "judgeModel",
    "kind",
    "scope",
    "testSuiteScenarios",
    "archivedAt",
    "createdAt",
    "updatedAt"
  ],
  "Subscription": [
    "id",
    "organizationId",
    "plan",
    "stripeSubscriptionId",
    "status",
    "startDate",
    "endDate",
    "lastPaymentFailedDate",
    "createdAt",
    "updatedAt",
    "maxMembers",
    "maxProjects",
    "maxMessagesPerMonth",
    "maxWorkflows",
    "maxRetentionDays",
    "maxMembersLite",
    "maxTeams",
    "maxPrompts",
    "maxEvaluators",
    "maxScenarios",
    "maxAgents",
    "maxExperiments",
    "maxOnlineEvaluations",
    "maxDatasets",
    "maxDashboards",
    "maxCustomGraphs",
    "maxAutomations",
    "organization",
    "invoices"
  ],
  "Invoice": [
    "id",
    "subscriptionId",
    "totalAmount",
    "currency",
    "dueDate",
    "paid",
    "createdAt",
    "updatedAt",
    "subscription",
    "lineItems"
  ],
  "InvoiceItem": [
    "id",
    "invoiceId",
    "description",
    "amount",
    "createdAt",
    "updatedAt",
    "invoice"
  ],
  "Group": [
    "id",
    "organizationId",
    "organization",
    "name",
    "slug",
    "externalId",
    "scimSource",
    "scimConnectionId",
    "members",
    "roleBindings",
    "createdAt",
    "updatedAt"
  ],
  "GroupMembership": [
    "userId",
    "groupId",
    "user",
    "group",
    "createdAt"
  ],
  "RoleBinding": [
    "id",
    "organizationId",
    "organization",
    "userId",
    "user",
    "groupId",
    "group",
    "apiKeyId",
    "apiKey",
    "role",
    "customRoleId",
    "customRole",
    "scopeType",
    "scopeId",
    "createdAt",
    "updatedAt"
  ],
  "Grant": [
    "id",
    "organizationId",
    "principalType",
    "principalId",
    "roleKey",
    "legacyRole",
    "source",
    "scopeType",
    "scopeId",
    "token",
    "permission",
    "resourceKind",
    "projectId",
    "createdByUserId",
    "expiresAt",
    "maxViews",
    "occurredAt",
    "createdAt",
    "updatedAt",
    "revokedAt",
    "revokedReason"
  ],
  "GrantUsage": [
    "grantId",
    "organizationId",
    "projectId",
    "viewCount",
    "lastViewedAt",
    "createdAt",
    "updatedAt"
  ],
  "Role": [
    "id",
    "organizationId",
    "name",
    "description",
    "permissions",
    "kind",
    "occurredAt",
    "createdAt",
    "updatedAt",
    "deletedAt"
  ],
  "ApiKey": [
    "id",
    "name",
    "description",
    "lookupId",
    "hashedSecret",
    "permissionMode",
    "userId",
    "user",
    "createdByUserId",
    "organizationId",
    "organization",
    "roleBindings",
    "expiresAt",
    "lastUsedAt",
    "revokedAt",
    "revocationCause",
    "ingestSourceType",
    "ingestionTemplateId",
    "createdByDeviceLabel",
    "createdAt",
    "updatedAt"
  ],
  "BillingMeterCheckpoint": [
    "id",
    "organizationId",
    "billingMonth",
    "lastReportedTotal",
    "pendingReportedTotal",
    "consecutiveFailures",
    "updatedAt"
  ],
  "VirtualKey": [
    "id",
    "organizationId",
    "name",
    "description",
    "status",
    "purpose",
    "externalId",
    "metadata",
    "disabledAt",
    "disabledReason",
    "expiresAt",
    "hashedSecret",
    "displayPrefix",
    "principalUserId",
    "principalUser",
    "traceProjectId",
    "config",
    "revision",
    "previousHashedSecret",
    "previousSecretValidUntil",
    "revokedAt",
    "revokedById",
    "createdAt",
    "updatedAt",
    "createdById",
    "lastUsedAt",
    "scopes",
    "ledgerEntries",
    "routingPolicyId",
    "routingPolicy",
    "routingMode"
  ],
  "VirtualKeyScope": [
    "id",
    "virtualKeyId",
    "virtualKey",
    "scopeType",
    "scopeId",
    "createdAt"
  ],
  "RoutingPolicy": [
    "id",
    "organizationId",
    "organization",
    "name",
    "description",
    "modelProviderIds",
    "modelAliases",
    "defaultModel",
    "policyRules",
    "isDefault",
    "createdAt",
    "updatedAt",
    "createdById",
    "createdBy",
    "updatedById",
    "updatedBy",
    "virtualKeys",
    "scopes"
  ],
  "RoutingPolicyScope": [
    "id",
    "routingPolicyId",
    "routingPolicy",
    "scopeType",
    "scopeId",
    "createdAt"
  ],
  "GatewayGuardrail": [
    "id",
    "projectId",
    "project",
    "name",
    "description",
    "evaluatorId",
    "evaluator",
    "direction",
    "failureMode",
    "archivedAt",
    "createdAt",
    "updatedAt",
    "createdById",
    "createdBy",
    "updatedById",
    "updatedBy"
  ],
  "IngestionSource": [
    "id",
    "organizationId",
    "organization",
    "teamId",
    "team",
    "sourceType",
    "name",
    "description",
    "ingestSecretHash",
    "parserConfig",
    "pollerCursor",
    "errorCount",
    "pullSchedule",
    "status",
    "traceProjectId",
    "lastEventAt",
    "archivedAt",
    "createdAt",
    "updatedAt",
    "createdById",
    "createdBy"
  ],
  "AnomalyRule": [
    "id",
    "organizationId",
    "organization",
    "scope",
    "scopeId",
    "name",
    "description",
    "severity",
    "ruleType",
    "thresholdConfig",
    "destinationConfig",
    "status",
    "archivedAt",
    "createdAt",
    "updatedAt",
    "createdById",
    "createdBy",
    "alerts"
  ],
  "AnomalyAlert": [
    "id",
    "organizationId",
    "organization",
    "ruleId",
    "rule",
    "severity",
    "ruleName",
    "ruleType",
    "triggerWindowStart",
    "triggerWindowEnd",
    "triggerSpendUsd",
    "triggerEventCount",
    "detail",
    "state",
    "destinationStatus",
    "detectedAt",
    "acknowledgedAt",
    "resolvedAt"
  ],
  "AiToolEntry": [
    "id",
    "organizationId",
    "organization",
    "scope",
    "scopeId",
    "type",
    "displayName",
    "slug",
    "iconKey",
    "iconAsset",
    "order",
    "enabled",
    "config",
    "archivedAt",
    "createdAt",
    "updatedAt",
    "createdById",
    "updatedById",
    "teams",
    "departments"
  ],
  "AiToolEntryTeam": [
    "id",
    "entryId",
    "teamId",
    "entry",
    "team"
  ],
  "AiToolEntryDepartment": [
    "id",
    "entryId",
    "departmentId",
    "entry"
  ],
  "IngestionTemplate": [
    "id",
    "organizationId",
    "organization",
    "slug",
    "sourceType",
    "displayName",
    "description",
    "iconAsset",
    "credentialSchema",
    "ottlRules",
    "platformPublished",
    "enabled",
    "archivedAt",
    "createdAt",
    "updatedAt",
    "createdById",
    "updatedById"
  ],
  "GatewayBudget": [
    "id",
    "organizationId",
    "scopeType",
    "scopeId",
    "providerKey",
    "name",
    "description",
    "window",
    "limitUsd",
    "onBreach",
    "timezone",
    "externalId",
    "metadata",
    "spentUsd",
    "currentPeriodStartedAt",
    "resetsAt",
    "lastResetAt",
    "cycleAnchorAt",
    "archivedAt",
    "createdAt",
    "updatedAt",
    "createdById",
    "createdBy",
    "ledgerEntries",
    "bucketBoundaries",
    "managedByVirtualKeyId"
  ],
  "GatewayBudgetBucketBoundary": [
    "id",
    "organizationId",
    "budgetId",
    "budget",
    "bucketScopeId",
    "periodStartedAt",
    "createdAt",
    "updatedAt"
  ],
  "GatewayBudgetLedger": [
    "id",
    "budgetId",
    "budget",
    "virtualKeyId",
    "virtualKey",
    "modelProviderId",
    "providerKey",
    "gatewayRequestId",
    "amountUsd",
    "tokensInput",
    "tokensOutput",
    "tokensCacheRead",
    "tokensCacheWrite",
    "model",
    "durationMs",
    "status",
    "occurredAt"
  ],
  "GatewayChangeEvent": [
    "revision",
    "organizationId",
    "organization",
    "kind",
    "virtualKeyId",
    "budgetId",
    "modelProviderId",
    "projectId",
    "project",
    "payload",
    "createdAt"
  ],
  "GatewayCacheRule": [
    "id",
    "organizationId",
    "name",
    "description",
    "priority",
    "enabled",
    "matchers",
    "action",
    "modeEnum",
    "archivedAt",
    "createdAt",
    "updatedAt",
    "createdById"
  ],
  "FeatureFlag": [
    "key",
    "enabled",
    "rules",
    "lastEditedBy",
    "createdAt",
    "updatedAt"
  ],
  "FeatureFlagExperimentSetting": [
    "flagKey",
    "subjectType",
    "subjectId",
    "enabled",
    "changedByUserId",
    "createdAt",
    "updatedAt"
  ],
  "ProcessManagerInstance": [
    "id",
    "processName",
    "projectId",
    "processKey",
    "tenantId",
    "userId",
    "state",
    "revision",
    "nextWakeAt",
    "updatedAt"
  ],
  "ProcessManagerInbox": [
    "id",
    "processName",
    "projectId",
    "processKey",
    "tenantId",
    "sourceEventId",
    "sourceEventKey",
    "consumedAt"
  ],
  "ProcessManagerOutbox": [
    "id",
    "processName",
    "projectId",
    "processKey",
    "tenantId",
    "userId",
    "messageKey",
    "intentType",
    "payload",
    "traceCarrier",
    "sourceEventId",
    "status",
    "attempts",
    "nextAttemptAt",
    "leasedUntil",
    "leaseToken",
    "dispatchedAt",
    "createdAt",
    "updatedAt",
    "attemptLog"
  ],
  "ProcessManagerOutboxAttempt": [
    "id",
    "outboxId",
    "projectId",
    "attempt",
    "occurredAt",
    "outcome",
    "errorType",
    "errorMessage",
    "retryAfterMs",
    "outbox"
  ],
  "TopicClusteringRunProjection": [
    "id",
    "projectId",
    "LastRequestedAt",
    "LastRequestTrigger",
    "LastRunAt",
    "LastRunOutcome",
    "LastRunMode",
    "LastRunSkippedReason",
    "LastRunError",
    "LastRunErrorCode",
    "LastRunErrorUserActionable",
    "LastRunTracesProcessed",
    "LastRunTopicsCount",
    "LastRunSubtopicsCount",
    "LastRunPages",
    "InProgressRunId",
    "InProgressTraces",
    "InProgressPages",
    "InProgressStartedAt",
    "CreatedAt",
    "UpdatedAt",
    "OccurredAt",
    "AcceptedAt",
    "LastEventId",
    "ProjectionVersion"
  ],
  "TopicModelProjection": [
    "id",
    "projectId",
    "CreatedAt",
    "UpdatedAt",
    "OccurredAt",
    "AcceptedAt",
    "LastEventId",
    "ProjectionVersion"
  ],
  "TopicClusteringRunHistoryProjection": [
    "id",
    "projectId",
    "Runs",
    "CreatedAt",
    "UpdatedAt",
    "OccurredAt",
    "AcceptedAt",
    "LastEventId",
    "ProjectionVersion"
  ],
  "IngestionPullRunProjection": [
    "id",
    "sourceId",
    "projectId",
    "Enabled",
    "Cron",
    "Cursor",
    "LastRunAt",
    "LastRunOutcome",
    "LastRunEventCount",
    "LastRunError",
    "LastRunErrorCode",
    "ConsecutiveErrors",
    "LastRunScheduledFor",
    "CreatedAt",
    "UpdatedAt",
    "OccurredAt",
    "AcceptedAt",
    "LastEventId",
    "ProjectionVersion"
  ],
  "ScheduledJob": [
    "id",
    "projectId",
    "targetType",
    "targetId",
    "cron",
    "timezone",
    "nextRunAt",
    "lastSlot",
    "currentSlot",
    "attempts",
    "lastError",
    "active",
    "createdAt",
    "updatedAt"
  ],
  "BugReport": [
    "id",
    "createdAt",
    "source",
    "kind",
    "title",
    "summary",
    "sessionData",
    "sessionTruncated",
    "agent",
    "contactEmail",
    "cliVersion",
    "linkedProjectId",
    "metadata"
  ],
  "IdempotencyReceipt": [
    "id",
    "scopeId",
    "key",
    "claimId",
    "requestFingerprint",
    "responseStatus",
    "responseBody",
    "createdAt",
    "heartbeatAt",
    "expiresAt"
  ],
  "GatewayRealtimeSession": [
    "id",
    "projectId",
    "organizationId",
    "virtualKeyId",
    "modelProviderId",
    "vendor",
    "agentId",
    "model",
    "requestedModel",
    "vendorConversationId",
    "status",
    "mintedAt",
    "closedAt",
    "closeReason",
    "traceId",
    "vendorCostRaw",
    "createdAt",
    "updatedAt"
  ],
  "SystemMigrationTenantState": [
    "migrationName",
    "tenantId",
    "status",
    "report",
    "occurredAt",
    "createdAt",
    "updatedAt"
  ],
  "SystemMigrationEnrollment": [
    "organizationId",
    "migrationName",
    "enrolledByUserId",
    "createdAt"
  ],
  "StoredObject": [
    "tenantId",
    "id",
    "status",
    "purpose",
    "ownerKind",
    "ownerId",
    "filename",
    "sha256",
    "sizeBytes",
    "mediaType",
    "mediaTypeVerified",
    "storageProvider",
    "storageDestinationId",
    "storageProviderRelativeId",
    "generation",
    "audiences",
    "expiresAt",
    "availableAt",
    "deletedAt",
    "source",
    "legacyFingerprint",
    "createdAt",
    "updatedAt"
  ]
} as const;

export const prismaRelationCatalogue = {
  "Account": {
    "user": "User"
  },
  "AccountCredential": {
    "user": "User"
  },
  "Session": {
    "user": "User"
  },
  "User": {
    "accounts": "Account",
    "accountCredentials": "AccountCredential",
    "sessions": "Session",
    "twoFactors": "TwoFactor",
    "passkeys": "Passkey",
    "teamMemberships": "TeamUser",
    "orgMemberships": "OrganizationUser",
    "Annotation": "Annotation",
    "shareLinks": "ShareLink",
    "Workflow": "Workflow",
    "WorkflowVersion": "WorkflowVersion",
    "annotationQueues": "AnnotationQueueMembers",
    "assignedQueueItems": "AnnotationQueueItem",
    "createdQueueItems": "AnnotationQueueItem",
    "llmPromptConfigVersions": "LlmPromptConfigVersion",
    "scenarios": "Scenario",
    "inviteRequests": "OrganizationInvite",
    "secretsCreated": "ProjectSecret",
    "secretsUpdated": "ProjectSecret",
    "savedViews": "SavedView",
    "versionTagsCreated": "PromptTagAssignment",
    "versionTagsUpdated": "PromptTagAssignment",
    "promptTagsCreated": "PromptTag",
    "promptTagsUpdated": "PromptTag",
    "groupMemberships": "GroupMembership",
    "roleBindings": "RoleBinding",
    "scimExternalIds": "ScimExternalId",
    "apiKeys": "ApiKey",
    "gatewayBudgetsCreated": "GatewayBudget",
    "principalVirtualKeys": "VirtualKey",
    "personalTeams": "Team",
    "personalProjects": "Project",
    "routingPoliciesCreated": "RoutingPolicy",
    "routingPoliciesUpdated": "RoutingPolicy",
    "gatewayGuardrailsCreated": "GatewayGuardrail",
    "gatewayGuardrailsUpdated": "GatewayGuardrail",
    "ingestionSourcesCreated": "IngestionSource",
    "anomalyRulesCreated": "AnomalyRule",
    "pinnedTraces": "PinnedTrace",
    "traceEditOverlaysCreated": "TraceEditOverlay",
    "traceEditOverlaysUpdated": "TraceEditOverlay"
  },
  "VerificationToken": {},
  "Identifier": {},
  "IdentifierReservation": {},
  "IdentityProjectionCursor": {},
  "TwoFactor": {
    "user": "User"
  },
  "Passkey": {
    "user": "User"
  },
  "MfaEnrollment": {},
  "SsoConnection": {},
  "JoinRequest": {},
  "TeamUser": {
    "assignedRole": "CustomRole",
    "user": "User",
    "team": "Team"
  },
  "OrganizationUser": {
    "user": "User",
    "organization": "Organization"
  },
  "Team": {
    "members": "TeamUser",
    "organization": "Organization",
    "projects": "Project",
    "ownerUser": "User",
    "ingestionSources": "IngestionSource",
    "aiToolEntryTeams": "AiToolEntryTeam"
  },
  "Organization": {
    "members": "OrganizationUser",
    "teams": "Team",
    "webhookEndpoints": "WebhookEndpoint",
    "OrganizationInvite": "OrganizationInvite",
    "CustomRoles": "CustomRole",
    "notifications": "Notification",
    "subscriptions": "Subscription",
    "scimTokens": "ScimToken",
    "promptTags": "PromptTag",
    "groups": "Group",
    "roleBindings": "RoleBinding",
    "apiKeys": "ApiKey",
    "gatewayChangeEvents": "GatewayChangeEvent",
    "routingPolicies": "RoutingPolicy",
    "ingestionSources": "IngestionSource",
    "anomalyRules": "AnomalyRule",
    "anomalyAlerts": "AnomalyAlert",
    "aiToolEntries": "AiToolEntry",
    "ingestionTemplates": "IngestionTemplate",
    "githubInstallations": "GithubInstallation",
    "githubPullRequests": "GithubPullRequest",
    "githubBranchPrChecks": "GithubBranchPullRequestCheck"
  },
  "ScimToken": {
    "organization": "Organization"
  },
  "ScimExternalId": {
    "user": "User"
  },
  "ScimSyncState": {},
  "Project": {
    "team": "Team",
    "checks": "Monitor",
    "costs": "Cost",
    "topics": "Topic",
    "datasets": "Dataset",
    "datasetRecords": "DatasetRecord",
    "customGraphs": "CustomGraph",
    "dashboards": "Dashboard",
    "batchEvaluations": "BatchEvaluation",
    "triggers": "Trigger",
    "experiments": "Experiment",
    "annotations": "Annotation",
    "projectSecrets": "ProjectSecret",
    "TriggerSent": "TriggerSent",
    "webhookDeliveries": "WebhookEndpointDelivery",
    "annotationScores": "AnnotationScore",
    "shareLinks": "ShareLink",
    "workflows": "Workflow",
    "WorkflowVersion": "WorkflowVersion",
    "AnnotationQueue": "AnnotationQueue",
    "AnnotationQueueItem": "AnnotationQueueItem",
    "llmPromptConfigs": "LlmPromptConfig",
    "analytics": "Analytics",
    "notifications": "Notification",
    "agents": "Agent",
    "evaluators": "Evaluator",
    "scenarios": "Scenario",
    "suiteConfigurations": "SimulationSuite",
    "savedViews": "SavedView",
    "gatewayGuardrails": "GatewayGuardrail",
    "gatewayChangeEvents": "GatewayChangeEvent",
    "pinnedTraces": "PinnedTrace",
    "traceEditOverlays": "TraceEditOverlay",
    "emailSuppressions": "EmailSuppression",
    "ownerUser": "User"
  },
  "Department": {},
  "PlatformToolPolicy": {},
  "OrganizationInvite": {
    "organization": "Organization",
    "requestedByUser": "User"
  },
  "Monitor": {
    "project": "Project",
    "experiment": "Experiment",
    "evaluator": "Evaluator"
  },
  "Cost": {
    "project": "Project"
  },
  "Topic": {
    "project": "Project",
    "parent": "Topic",
    "subtopics": "Topic"
  },
  "Dataset": {
    "project": "Project",
    "datasetRecords": "DatasetRecord",
    "batchEvaluations": "BatchEvaluation"
  },
  "DatasetRecord": {
    "dataset": "Dataset",
    "project": "Project"
  },
  "Dashboard": {
    "project": "Project",
    "graphs": "CustomGraph"
  },
  "SavedView": {
    "project": "Project",
    "user": "User"
  },
  "CustomGraph": {
    "project": "Project",
    "dashboard": "Dashboard",
    "trigger": "Trigger",
    "TriggerSent": "TriggerSent"
  },
  "BatchEvaluation": {
    "experiment": "Experiment",
    "project": "Project",
    "dataset": "Dataset"
  },
  "Trigger": {
    "project": "Project",
    "TriggerSent": "TriggerSent",
    "webhookDeliveries": "WebhookEndpointDelivery",
    "customGraph": "CustomGraph"
  },
  "WebhookEndpoint": {
    "organization": "Organization",
    "deliveries": "WebhookEndpointDelivery"
  },
  "WebhookEndpointDelivery": {
    "endpoint": "WebhookEndpoint",
    "project": "Project",
    "trigger": "Trigger"
  },
  "Experiment": {
    "project": "Project",
    "workflow": "Workflow",
    "batchEvaluations": "BatchEvaluation",
    "monitor": "Monitor"
  },
  "ExperimentVersion": {},
  "Annotation": {
    "project": "Project",
    "user": "User"
  },
  "ModelProvider": {
    "scopes": "ModelProviderScope"
  },
  "ModelProviderScope": {
    "modelProvider": "ModelProvider"
  },
  "ModelDefaultConfig": {
    "scopes": "ModelDefaultConfigScope"
  },
  "ModelDefaultConfigScope": {
    "config": "ModelDefaultConfig"
  },
  "GithubInstallation": {
    "organization": "Organization"
  },
  "GithubPullRequest": {
    "organization": "Organization"
  },
  "GithubBranchPullRequestCheck": {
    "organization": "Organization"
  },
  "LangyConversationProjection": {},
  "LangyTurnRequest": {},
  "LangyActiveTurn": {},
  "LangyConversationTurnProjection": {},
  "LangyMessageProjection": {},
  "ProjectSecret": {
    "project": "Project",
    "createdBy": "User",
    "updatedBy": "User"
  },
  "TriggerSent": {
    "customGraph": "CustomGraph",
    "project": "Project",
    "trigger": "Trigger"
  },
  "EmailSuppression": {
    "project": "Project"
  },
  "AnnotationScore": {
    "project": "Project",
    "AnnotationQueueScores": "AnnotationQueueScores"
  },
  "AnnotationQueue": {
    "project": "Project",
    "members": "AnnotationQueueMembers",
    "AnnotationQueueScores": "AnnotationQueueScores",
    "AnnotationQueueItems": "AnnotationQueueItem"
  },
  "AnnotationQueueMembers": {
    "user": "User",
    "annotationQueue": "AnnotationQueue"
  },
  "AnnotationQueueScores": {
    "annotationScore": "AnnotationScore",
    "annotationQueue": "AnnotationQueue"
  },
  "AnnotationQueueItem": {
    "annotationQueue": "AnnotationQueue",
    "user": "User",
    "createdByUser": "User",
    "project": "Project"
  },
  "ShareLink": {
    "project": "Project",
    "user": "User"
  },
  "PinnedTrace": {
    "project": "Project",
    "user": "User"
  },
  "TraceEditOverlay": {
    "project": "Project",
    "createdBy": "User",
    "updatedBy": "User"
  },
  "RetentionPolicy": {},
  "DataPrivacyPolicy": {},
  "CustomLLMModelCost": {},
  "Workflow": {
    "project": "Project",
    "latestVersion": "WorkflowVersion",
    "currentVersion": "WorkflowVersion",
    "versions": "WorkflowVersion",
    "publishedBy": "User",
    "experiments": "Experiment",
    "copiedFrom": "Workflow",
    "copiedWorkflows": "Workflow",
    "agents": "Agent",
    "evaluators": "Evaluator"
  },
  "WorkflowVersion": {
    "author": "User",
    "project": "Project",
    "workflow": "Workflow",
    "parent": "WorkflowVersion",
    "children": "WorkflowVersion",
    "WorkflowAsLatestVersion": "Workflow",
    "WorkflowAsCurrentVersion": "Workflow"
  },
  "AuditLog": {},
  "LlmPromptConfig": {
    "project": "Project",
    "copiedFrom": "LlmPromptConfig",
    "copiedPrompts": "LlmPromptConfig",
    "versions": "LlmPromptConfigVersion",
    "versionTags": "PromptTagAssignment"
  },
  "LlmPromptConfigVersion": {
    "author": "User",
    "config": "LlmPromptConfig",
    "versionTags": "PromptTagAssignment"
  },
  "PromptTagAssignment": {
    "config": "LlmPromptConfig",
    "version": "LlmPromptConfigVersion",
    "promptTag": "PromptTag",
    "createdBy": "User",
    "updatedBy": "User"
  },
  "PromptTag": {
    "organization": "Organization",
    "assignments": "PromptTagAssignment",
    "createdBy": "User",
    "updatedBy": "User"
  },
  "Analytics": {
    "project": "Project"
  },
  "CustomRole": {
    "organization": "Organization",
    "assignedUsers": "TeamUser",
    "roleBindings": "RoleBinding"
  },
  "Notification": {
    "organization": "Organization",
    "project": "Project"
  },
  "Agent": {
    "project": "Project",
    "workflow": "Workflow",
    "copiedFrom": "Agent",
    "copiedAgents": "Agent"
  },
  "Evaluator": {
    "project": "Project",
    "workflow": "Workflow",
    "copiedFrom": "Evaluator",
    "copiedEvaluators": "Evaluator",
    "monitors": "Monitor",
    "gatewayGuardrails": "GatewayGuardrail"
  },
  "Scenario": {
    "project": "Project",
    "testSuite": "SimulationSuite",
    "versions": "ScenarioVersion",
    "lastUpdatedBy": "User"
  },
  "ScenarioVersion": {
    "scenario": "Scenario"
  },
  "SimulationSuite": {
    "project": "Project",
    "testSuiteScenarios": "Scenario"
  },
  "Subscription": {
    "organization": "Organization",
    "invoices": "Invoice"
  },
  "Invoice": {
    "subscription": "Subscription",
    "lineItems": "InvoiceItem"
  },
  "InvoiceItem": {
    "invoice": "Invoice"
  },
  "Group": {
    "organization": "Organization",
    "members": "GroupMembership",
    "roleBindings": "RoleBinding"
  },
  "GroupMembership": {
    "user": "User",
    "group": "Group"
  },
  "RoleBinding": {
    "organization": "Organization",
    "user": "User",
    "group": "Group",
    "apiKey": "ApiKey",
    "customRole": "CustomRole"
  },
  "Grant": {},
  "GrantUsage": {},
  "Role": {},
  "ApiKey": {
    "user": "User",
    "organization": "Organization",
    "roleBindings": "RoleBinding"
  },
  "BillingMeterCheckpoint": {},
  "VirtualKey": {
    "principalUser": "User",
    "scopes": "VirtualKeyScope",
    "ledgerEntries": "GatewayBudgetLedger",
    "routingPolicy": "RoutingPolicy"
  },
  "VirtualKeyScope": {
    "virtualKey": "VirtualKey"
  },
  "RoutingPolicy": {
    "organization": "Organization",
    "createdBy": "User",
    "updatedBy": "User",
    "virtualKeys": "VirtualKey",
    "scopes": "RoutingPolicyScope"
  },
  "RoutingPolicyScope": {
    "routingPolicy": "RoutingPolicy"
  },
  "GatewayGuardrail": {
    "project": "Project",
    "evaluator": "Evaluator",
    "createdBy": "User",
    "updatedBy": "User"
  },
  "IngestionSource": {
    "organization": "Organization",
    "team": "Team",
    "createdBy": "User"
  },
  "AnomalyRule": {
    "organization": "Organization",
    "createdBy": "User",
    "alerts": "AnomalyAlert"
  },
  "AnomalyAlert": {
    "organization": "Organization",
    "rule": "AnomalyRule"
  },
  "AiToolEntry": {
    "organization": "Organization",
    "teams": "AiToolEntryTeam",
    "departments": "AiToolEntryDepartment"
  },
  "AiToolEntryTeam": {
    "entry": "AiToolEntry",
    "team": "Team"
  },
  "AiToolEntryDepartment": {
    "entry": "AiToolEntry"
  },
  "IngestionTemplate": {
    "organization": "Organization"
  },
  "GatewayBudget": {
    "createdBy": "User",
    "ledgerEntries": "GatewayBudgetLedger",
    "bucketBoundaries": "GatewayBudgetBucketBoundary"
  },
  "GatewayBudgetBucketBoundary": {
    "budget": "GatewayBudget"
  },
  "GatewayBudgetLedger": {
    "budget": "GatewayBudget",
    "virtualKey": "VirtualKey"
  },
  "GatewayChangeEvent": {
    "organization": "Organization",
    "project": "Project"
  },
  "GatewayCacheRule": {},
  "FeatureFlag": {},
  "FeatureFlagExperimentSetting": {},
  "ProcessManagerInstance": {},
  "ProcessManagerInbox": {},
  "ProcessManagerOutbox": {
    "attemptLog": "ProcessManagerOutboxAttempt"
  },
  "ProcessManagerOutboxAttempt": {
    "outbox": "ProcessManagerOutbox"
  },
  "TopicClusteringRunProjection": {},
  "TopicModelProjection": {},
  "TopicClusteringRunHistoryProjection": {},
  "IngestionPullRunProjection": {},
  "ScheduledJob": {},
  "BugReport": {},
  "IdempotencyReceipt": {},
  "GatewayRealtimeSession": {},
  "SystemMigrationTenantState": {},
  "SystemMigrationEnrollment": {},
  "StoredObject": {}
} as const;

export type PrismaTableModel = keyof typeof prismaTableCatalogue;
