"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.CaptionStyleModelTextWeight = void 0;
exports.CaptionStyleModelTextWeight = {
    Normal: "normal",
    Bold: "bold",
    NineHundred: "900",
};
