packages:
  - .
  - "saas-src/*"
  - "packages/*"

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - bcrypt
  - bufferutil
  - core-js
  - cpu-features
  - esbuild
  - msgpackr-extract
  - prisma
  - protobufjs
  - sharp
  - ssh2
