packages:
  - .
  - "saas-src/*"
  - "packages/*"

overrides:
  pino: ^10.3.0
  pino-pretty: ^13.0.0
  thread-stream: ^4.0.0
  prettier: ^3.8.1

packageExtensions:
  bullmq-otel:
    dependencies:
      tslib: "^2.6.0"

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - bcrypt
  - bufferutil
  - core-js
  - cpu-features
  - esbuild
  - msgpackr-extract
  - prisma
  - protobufjs
  - sharp
  - ssh2
