#!/bin/bash

set -e

# Tracer types are Zod-first in the platform: the schemas in types.ts are the
# source of truth and the TypeScript types are inferred with z.infer. Copy the
# module verbatim — the SDK reuses both the schemas and the types directly, so
# there is no schema-generation (ts-to-zod) step anymore.
cp ../langwatch/src/server/tracer/types.ts src/internal/generated/types/tracer.ts

# Copy filter types (only filterFieldsEnum is needed by the SDK)
mkdir -p src/internal/generated/filters
node -e "
const fs = require('fs');
const src = fs.readFileSync('../langwatch/src/server/filters/types.ts', 'utf8');
// Extract only the zod import and filterFieldsEnum definition
const lines = src.split('\n');
const out = [];
let inEnum = false;
for (const line of lines) {
  if (line.match(/^import.*from ['\"]zod['\"]/)) { out.push(line); continue; }
  if (line.match(/export const filterFieldsEnum/)) { inEnum = true; }
  if (inEnum) { out.push(line); }
  if (inEnum && line.includes(']);')) { inEnum = false; }
  if (line.match(/export type FilterField/)) { out.push(line); }
}
fs.writeFileSync('src/internal/generated/filters/types.ts', out.join('\n') + '\n');
"

# Evaluations types are already Zod-first (schemas defined with z.*); copy verbatim.
cp ../langwatch/src/server/evaluations/types.ts src/internal/generated/types/evaluations.ts

# Evaluator catalog + settings schemas are Zod-first (generated from langevals);
# copy verbatim — no ts-to-zod step.
cp ../langevals/ts-integration/evaluators.generated.ts src/internal/generated/types/evaluators.generated.ts

# Default prompt model — derive the newest plain `openai/gpt-<major>.<minor>`
# flagship from the same llmModels.json the platform reads, so `langwatch
# prompt create` and the platform stay in lock-step without a hand-edited
# constant that drifts every time the registry advances.
mkdir -p src/internal/generated/cli
node -e "
const fs = require('fs');
const path = require('path');
const registry = require('../langwatch/src/server/modelProviders/llmModels.json');
const pattern = /^([a-z0-9_-]+)\/([a-z]+)-(\d+)\.(\d+)\$/;
let best = null;
let bestVersion = [-1, -1];
for (const model of Object.values(registry.models)) {
  if (model.provider !== 'openai' || model.mode !== 'chat') continue;
  const m = pattern.exec(model.id);
  if (!m) continue;
  const v = [Number(m[3]), Number(m[4])];
  if (v[0] > bestVersion[0] || (v[0] === bestVersion[0] && v[1] > bestVersion[1])) {
    bestVersion = v;
    best = model.id;
  }
}
if (!best) {
  console.error('No openai chat flagship found in llmModels.json');
  process.exit(1);
}
const out = 'src/internal/generated/cli/default-prompt-model.generated.ts';
fs.writeFileSync(out,
  '// Generated by copy-types.sh from langwatch/src/server/modelProviders/llmModels.json\n' +
  '// Do not edit by hand — re-runs on every SDK install/build.\n' +
  'export const DEFAULT_PROMPT_MODEL = ' + JSON.stringify(best) + ';\n'
);
console.log('Wrote ' + out + ' (DEFAULT_PROMPT_MODEL=' + best + ')');
"

# Feature map — embed the canonical information architecture (feature-map.json
# at the repo root) so the CLI's machine-readable catalog (`langwatch
# commands`, `langwatch help-tree`) is built from the same source of truth as
# the platform, not a hand-maintained parallel registry. Only the shape the
# CLI reads is typed (id/name + surfaces.code cli/hints/skill) — everything
# else passes through as data, so additive map edits never break the codegen.
node -e "
const fs = require('fs');
const map = require('../feature-map.json');
const out = 'src/internal/generated/cli/feature-map.generated.ts';
fs.writeFileSync(out,
  '// Generated by copy-types.sh from feature-map.json (repo root)\n' +
  '// Do not edit by hand — re-runs on every SDK install/build.\n' +
  '\n' +
  '/** The slice of a feature-map entry the CLI catalog reads. */\n' +
  'export interface GeneratedFeature {\n' +
  '  id: string;\n' +
  '  name: string;\n' +
  '  description?: string;\n' +
  '  children?: GeneratedFeature[];\n' +
  '  surfaces?: {\n' +
  '    code?: {\n' +
  '      cli?: string[] | null;\n' +
  '      /** Optional per-command usage examples, keyed by the same command string as \`cli\`. */\n' +
  '      hints?: Record<string, string> | null;\n' +
  '      skill?: string | null;\n' +
  '    } | null;\n' +
  '  } | null;\n' +
  '}\n' +
  '\n' +
  'export const FEATURE_MAP = ' +
  JSON.stringify(map, null, 2) +
  // The literal carries the whole map (sdk/platform/api/docs surfaces,
  // produces/consumes, meta) while the type is only the slice the CLI reads —
  // asserted, not annotated, so additive map edits never break the codegen.
  ' as unknown as { features: GeneratedFeature[] };\n'
);
console.log('Wrote ' + out + ' (' + map.features.length + ' top-level features)');
"

# Skills bundle — embed the published agent skills (the curated FEATURE_SKILLS
# + auto-discovered recipes) so `langwatch skills list/get/install/…` needs no
# runtime files and works identically in the tsup dist and the bun single
# binary. Bodies are the COMMITTED skills/_compiled/native/<slug>/SKILL.md
# renders (same inlineMdx output the public publisher ships — no
# re-implementation to drift); metadata comes from the canonical sources.
# Pure node, no workspace deps — see scripts/generate-skills-bundle.mjs.
node scripts/generate-skills-bundle.mjs
