#!/bin/bash

set -e

# Copy tracer types (Zod-first — schemas are already in the file)
cp ../langwatch/src/server/tracer/types.ts src/internal/generated/types/tracer.ts

# Copy filter types (only filterFieldsEnum is needed by the SDK)
mkdir -p src/internal/generated/filters
node -e "
const fs = require('fs');
const src = fs.readFileSync('../langwatch/src/server/filters/types.ts', 'utf8');
// Extract only the zod import and filterFieldsEnum definition
const lines = src.split('\n');
const out = [];
let inEnum = false;
for (const line of lines) {
  if (line.match(/^import.*from ['\"]zod['\"]/)) { out.push(line); continue; }
  if (line.match(/export const filterFieldsEnum/)) { inEnum = true; }
  if (inEnum) { out.push(line); }
  if (inEnum && line.includes(']);')) { inEnum = false; }
  if (line.match(/export type FilterField/)) { out.push(line); }
}
fs.writeFileSync('src/internal/generated/filters/types.ts', out.join('\n') + '\n');
"

# Copy evaluations types (Zod-first)
cp ../langwatch/src/server/evaluations/types.ts src/internal/generated/types/evaluations.ts
# Fix import path from ../tracer/types to ./tracer
if [[ "$OSTYPE" == "darwin"* ]]; then
  sed -i '' 's/\.\.\/tracer\/types/\.\/tracer/g' src/internal/generated/types/evaluations.ts
else
  sed -i 's/\.\.\/tracer\/types/\.\/tracer/g' src/internal/generated/types/evaluations.ts
fi

# Copy evaluators generated (Zod schemas are already in the file)
cp ../langevals/ts-integration/evaluators.generated.ts src/internal/generated/types/evaluators.generated.ts
# Default prompt model — derive the newest plain `openai/gpt-<major>.<minor>`
# flagship from the same llmModels.json the platform reads, so `langwatch
# prompt create` and the platform stay in lock-step without a hand-edited
# constant that drifts every time the registry advances.
mkdir -p src/internal/generated/cli
node -e "
const fs = require('fs');
const path = require('path');
const registry = require('../langwatch/src/server/modelProviders/llmModels.json');
const pattern = /^([a-z0-9_-]+)\/([a-z]+)-(\d+)\.(\d+)\$/;
let best = null;
let bestVersion = [-1, -1];
for (const model of Object.values(registry.models)) {
  if (model.provider !== 'openai' || model.mode !== 'chat') continue;
  const m = pattern.exec(model.id);
  if (!m) continue;
  const v = [Number(m[3]), Number(m[4])];
  if (v[0] > bestVersion[0] || (v[0] === bestVersion[0] && v[1] > bestVersion[1])) {
    bestVersion = v;
    best = model.id;
  }
}
if (!best) {
  console.error('No openai chat flagship found in llmModels.json');
  process.exit(1);
}
const out = 'src/internal/generated/cli/default-prompt-model.generated.ts';
fs.writeFileSync(out,
  '// Generated by copy-types.sh from langwatch/src/server/modelProviders/llmModels.json\n' +
  '// Do not edit by hand — re-runs on every SDK install/build.\n' +
  'export const DEFAULT_PROMPT_MODEL = ' + JSON.stringify(best) + ';\n'
);
console.log('Wrote ' + out + ' (DEFAULT_PROMPT_MODEL=' + best + ')');
"
