import { defineConfig } from "tsup";
import packageJson from "./package.json";

// The card/domain-error contract is a source-only workspace package and a
// devDependency, so it must be inlined rather than left as an import the
// published `langwatch` tarball could never resolve. The pattern covers every
// subpath the CLI takes (`/cards`, `/cards/handled-error`), not just the one
// spelled here — a plain string would match a single specifier and silently
// leave the others external.
const noExternal = [/^@langwatch\/langy(\/|$)/];

// `__CLI_VERSION__` is a bare identifier in src/cli/program.ts.
const define = {
  __CLI_VERSION__: JSON.stringify(packageJson.version),
};

export default defineConfig([
  {
    // Library entries — the published SDK surface (`langwatch`,
    // `langwatch/observability`, …). Dual format + dts, exactly as before.
    //
    // NOTE: no `clean` here — tsup builds the configs of this array
    // CONCURRENTLY, so a clean in either would race the other build's output.
    // The `build` script rm -rf's dist before invoking tsup instead.
    entry: [
      "src/index.ts",
      "src/observability-sdk/index.ts",
      "src/observability-sdk/setup/node/index.ts",
      "src/observability-sdk/instrumentation/langchain/index.ts",
    ],
    splitting: true,
    clean: false,
    format: ["cjs", "esm"],
    dts: true,
    sourcemap: true,
    noExternal,
    define,
  },
  {
    // CLI entry — only ever RUN as CJS (package.json `bin` →
    // ./dist/cli/index.js), never imported as a library, so the ESM copy, the
    // dts and the sourcemaps were pure tarball weight. Built as a SEPARATE
    // config object, not another entry above: entries in one build share
    // chunks, and a CJS-only entry must not share chunks with dual-format
    // library entries (an ESM-only shared chunk would break `require`).
    //
    // `splitting: false` inlines the lazy command chunks into the single
    // file — dynamic `import()` calls keep their lazy semantics (esbuild
    // wraps them in promises), which is what keeps command modules and the
    // lazy js-yaml load off the cold-start path.
    // Object-form entry pins the output path: with a single string entry
    // tsup would take src/cli as the outbase and emit dist/index.js,
    // clobbering the library's main entry.
    //
    // The bundle emits as cli/bundle.js; `onSuccess` then writes the real
    // cli/index.js as a tiny stub that enables Node's compile cache BEFORE
    // the 600KB bundle is even parsed, and only then requires it. Enabling
    // the cache from inside the bundle (src/cli/compileCache.ts) comes too
    // late for the bundle's own ~10ms compile — V8 compiles the entry file
    // before its first statement runs — so the entry must be a file that is
    // not the bundle. The in-bundle enable stays as belt and braces for the
    // Bun binary (which compiles src/cli/index.ts directly) and for anyone
    // executing bundle.js straight.
    entry: { "cli/bundle": "src/cli/index.ts" },
    splitting: false,
    clean: false,
    format: ["cjs"],
    minify: true,
    dts: false,
    // Minified WITHOUT a sourcemap, every user-reported stack trace reads
    // `at t (bundle.js:1:284119)` and is unresolvable even for us. So the map
    // is generated — but it is excluded from the published tarball via
    // package.json `files` (`!dist/cli/*.map`), which keeps the npm weight win
    // the minify+no-dts decision above was after. Node only reads maps under
    // `--enable-source-maps`, so shipping the reference without the map costs
    // nothing at runtime.
    //
    // To decode a trace from a released version: check out that tag, run
    // `pnpm build`, and use the local dist/cli/bundle.js.map — esbuild output
    // is deterministic for a given input, so it matches what shipped.
    sourcemap: true,
    noExternal,
    define,
    onSuccess: async () => {
      const { chmodSync, writeFileSync } = await import("node:fs");
      const stub = `#!/usr/bin/env node
// Generated by tsup.config.ts (onSuccess). Enables the V8 compile cache
// before the bundle below is parsed — see src/cli/compileCache.ts — then
// hands over. Keep this file tiny: anything added here is paid at boot.
"use strict";
try {
  require("node:module").enableCompileCache?.();
} catch {
  // A compile cache is an optimisation, never a reason to fail a boot.
}
require("./bundle.js");
`;
      writeFileSync("dist/cli/index.js", stub);
      chmodSync("dist/cli/index.js", 0o755);
    },
  },
]);
