"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.TokensClient = void 0;
const BaseClient_1 = require("../../../../BaseClient");
const Client_1 = require("../resources/singleUse/client/Client");
class TokensClient {
    constructor(options = {}) {
        this._options = (0, BaseClient_1.normalizeClientOptions)(options);
    }
    get singleUse() {
        var _a;
        return ((_a = this._singleUse) !== null && _a !== void 0 ? _a : (this._singleUse = new Client_1.SingleUseClient(this._options)));
    }
}
exports.TokensClient = TokensClient;
