"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.SampleConfigDbModelParentType = void 0;
exports.SampleConfigDbModelParentType = {
    Read: "read",
    Collection: "collection",
};
