// The registry: every rule now lives in `@langwatch/oxlint-rules`, built with
// `defineRule` so the message shape, the per-file classification, and the
// fixture-tree test harness are shared instead of hand-rolled per rule. This
// file only wires the rule objects into the plugin oxlint loads.

import {
  apiContextServicesRule,
  awaitedReturnChainRule,
  bannedLegacyNamesRule,
  bannedTestModelNamesRule,
  noInlineDynamicImportRule,
  noPortVocabularyRule,
  booleanWallRule,
  boundaryRule,
  cognitiveComplexityRule,
  commentBlockSizeRule,
  conditionShapeRule,
  legacyMonolithPathRule,
  conditionalTypeDepthRule,
  danglingBarrelExportRule,
  emptyCatchRule,
  environmentBoundariesRule,
  fallibleResultNamingRule,
  emDashInCopyRule,
  jsxFromHookRule,
  designSystemExportCollisionRule,
  zodInternalsRule,
  sharedSetupIsAHookRule,
  prismaCountInListQueryRule,
  unitTestDoesNotRenderRule,
  noTryPrefixRule,
  positionalParameterListRule,
  returnAwaitOutsideTryRule,
  featureModuleClassesRule,
  featureSourceFilenameRule,
  featureSourceLayoutRule,
  featureSourceSubjectRule,
  featureSideHoldsNoAppRule,
  handledErrorOutsideContractRule,
  layerClassRule,
  noAliasReexportRule,
  noBootHookOutsideGuardRule,
  noLoggerSpyRule,
  noPrototypeStubRule,
  noRawErrorOutputRule,
  noRuntimeReflectionRule,
  transportMiddlewareIsAGateRule,
  logicalStatementSpacingRule,
  maxStatementsPerLineRule,
  moduleAppOnlyAcrossPackagesRule,
  namespaceClassRule,
  unboundedLoopRule,
  idGenerationOriginRule,
  idempotencyKeyIsStableRule,
  noRawHonoMountRule,
  overloadByLiteralRule,
  planLiteralsRule,
  prismaContainmentRule,
  schemaOutsideContractRule,
  restSchemaFromOwnContractRule,
  restDeclaresInputOutputRule,
  restHandlerThrowsRule,
  restDeclaresItsAnswerRule,
  restPathParamIsSemanticRule,
  restNoErrorHandlerOverrideRule,
  secretsThroughSourceRule,
  serviceClassesRule,
  channelTakesOnlyItsClientRule,
  clickhouseContainmentRule,
  redisContainmentRule,
  refusalIsAHandledErrorRule,
  repositoryTakesOnlyItsStoreRule,
  serviceDoesNotOpenAChannelRule,
  serviceDependenciesRule,
  serviceLoadsItsOwnConfigRule,
  serviceMemberSpacingRule,
  serviceQualityRule,
  standInCastRule,
  temporalOnlyRule,
  testDescriptionIsAnActionRule,
  transportImportsARepositoryRule,
  typedPrismaSeamRule,
  typeOnlyValueImportRule,
  webImportsServerShapedValueRule,
  zodObjectCompositionRule,
} from "@langwatch/oxlint-rules";

export const rules = {
  "api-context-services": apiContextServicesRule,
  "comment-block-size": commentBlockSizeRule,
  "conditional-type-depth": conditionalTypeDepthRule,
  "fallible-result-naming": fallibleResultNamingRule,
  "em-dash-in-copy": emDashInCopyRule,
  "jsx-from-hook": jsxFromHookRule,
  "design-system-export-collision": designSystemExportCollisionRule,
  "zod-internals": zodInternalsRule,
  "shared-setup-is-a-hook": sharedSetupIsAHookRule,
  "prisma-count-in-list-query": prismaCountInListQueryRule,
  "unit-test-does-not-render": unitTestDoesNotRenderRule,
  "no-try-prefix": noTryPrefixRule,
  "positional-parameter-list": positionalParameterListRule,
  "return-await-outside-try": returnAwaitOutsideTryRule,
  "feature-source-filename": featureSourceFilenameRule,
  "feature-source-layout": featureSourceLayoutRule,
  "feature-source-subject": featureSourceSubjectRule,
  "handled-error-outside-contract": handledErrorOutsideContractRule,
  "layer-class": layerClassRule,
  "no-raw-hono-mount": noRawHonoMountRule,
  "overload-by-literal": overloadByLiteralRule,
  "plan-literals": planLiteralsRule,
  "prisma-containment": prismaContainmentRule,
  "schema-outside-contract": schemaOutsideContractRule,

  "rest-schema-from-own-contract": restSchemaFromOwnContractRule,

  "rest-declares-input-output": restDeclaresInputOutputRule,

  "rest-handler-throws": restHandlerThrowsRule,

  "rest-declares-its-answer": restDeclaresItsAnswerRule,

  "rest-path-param-is-semantic": restPathParamIsSemanticRule,

  "rest-no-error-handler-override": restNoErrorHandlerOverrideRule,
  "service-loads-its-own-config": serviceLoadsItsOwnConfigRule,
  "temporal-only": temporalOnlyRule,
  "typed-prisma-seam": typedPrismaSeamRule,
  "cognitive-complexity": cognitiveComplexityRule,
  "condition-shape": conditionShapeRule,
  "legacy-monolith-path": legacyMonolithPathRule,
  "environment-boundaries": environmentBoundariesRule,
  "package-boundaries": boundaryRule,
  "feature-module-classes": featureModuleClassesRule,
  "service-classes": serviceClassesRule,
  "service-quality": serviceQualityRule,
  "max-statements-per-line": maxStatementsPerLineRule,
  "namespace-class": namespaceClassRule,
  "unbounded-loop": unboundedLoopRule,
  "id-generation-origin": idGenerationOriginRule,
  "idempotency-key-is-stable": idempotencyKeyIsStableRule,
  "service-member-spacing": serviceMemberSpacingRule,
  "service-dependencies": serviceDependenciesRule,
  "secrets-through-source": secretsThroughSourceRule,
  "logical-statement-spacing": logicalStatementSpacingRule,
  "boolean-wall": booleanWallRule,
  "awaited-return-chain": awaitedReturnChainRule,
  "web-imports-server-shaped-value": webImportsServerShapedValueRule,
  "zod-object-composition": zodObjectCompositionRule,
  "banned-legacy-names": bannedLegacyNamesRule,
  "no-port-vocabulary": noPortVocabularyRule,
  "module-app-only-across-packages": moduleAppOnlyAcrossPackagesRule,
  "feature-side-holds-no-app": featureSideHoldsNoAppRule,
  "no-alias-reexport": noAliasReexportRule,
  "no-boot-hook-outside-guard": noBootHookOutsideGuardRule,
  "no-logger-spy": noLoggerSpyRule,
  "no-prototype-stub": noPrototypeStubRule,
  "no-raw-error-output": noRawErrorOutputRule,
  "no-runtime-reflection": noRuntimeReflectionRule,
  "channel-takes-only-its-client": channelTakesOnlyItsClientRule,
  "clickhouse-containment": clickhouseContainmentRule,
  "redis-containment": redisContainmentRule,
  "refusal-is-a-handled-error": refusalIsAHandledErrorRule,
  "repository-takes-only-its-store": repositoryTakesOnlyItsStoreRule,
  "service-does-not-open-a-channel": serviceDoesNotOpenAChannelRule,
  "transport-middleware-is-a-gate": transportMiddlewareIsAGateRule,
  "type-only-value-import": typeOnlyValueImportRule,
  "dangling-barrel-export": danglingBarrelExportRule,
  "empty-catch": emptyCatchRule,
  "stand-in-cast": standInCastRule,
  "transport-imports-a-repository": transportImportsARepositoryRule,
  "banned-test-model-names": bannedTestModelNamesRule,
  "no-inline-dynamic-import": noInlineDynamicImportRule,
  "test-description-is-an-action": testDescriptionIsAnActionRule,
};

// "nested-ternary" (superseded by the built-in no-nested-ternary) and
// "runtime-undefined" (superseded by the built-in no-undefined) are gone from
// this registry - ADR-135/ADR-140's class-A migration. Each built-in is
// configured directly in oxlint.architecture.jsonc, beside this file.

export default {
  meta: { name: "eslint-plugin-langwatch", version: "0.1.0" },
  rules,
};
