package devscripts

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"slices"
	"sort"
	"strings"

	"github.com/langwatch/langwatch/tools/internal/jsonc"
)

const (
	groupSolution = "dev/tsconfig.web-declarations.json"
	rootSolution  = "tsconfig.json"
)

var (
	checkRoots      = []string{"tsconfig.json", "tsconfig.test.json", "tsconfig.tests.json", "tsconfig.type-tests.json"}
	packagesHeader  = regexp.MustCompile(`^packages:\s*$`)
	globEntry       = regexp.MustCompile(`^\s+-\s+["']?([^"'#\s]+)["']?\s*$`)
	contractBuild   = regexp.MustCompile(`^modules/[^/]+/contract/tsconfig\.build\.json$`)
	indentPattern   = regexp.MustCompile(`\n([ \t]+)\S`)
	openingPattern  = regexp.MustCompile(`[\[{]\s*$`)
	blankIndent     = regexp.MustCompile(`^[ \t]*$`)
	trailingSpace   = regexp.MustCompile(`\s*$`)
	buildSolutionTS = strings.Join([]string{
		"// The build solution: the module contracts, in one project graph, so their",
		"// declarations are emitted by a single `tsc -b` instead of one compiler",
		"// process per package. `pnpm build:types` runs it.",
		"//",
		"// Generated by `pnpm sync:references` (tools/devscripts). Do not edit: add a",
		"// package to the workspace and re-run `pnpm sync:references`.",
	}, "\n")
)

// WorkspaceMember is one pnpm workspace package.
type WorkspaceMember struct {
	Name, Directory               string
	Dependencies, DevDependencies []string
	Checks                        bool
}

// Project is one tsconfig and the references it should carry.
type Project struct {
	File       string
	References []string
	Undeduced  []string
	// Current is the references the file carries today, normalised.
	Current []string
}

func readConfig(path string) map[string]any {
	data, err := os.ReadFile(path)
	if err != nil {
		return map[string]any{}
	}
	return jsonc.Read(string(data))
}

func referencePaths(config map[string]any, key string) []string {
	list, _ := config[key].([]any)
	out := []string{}
	for _, entry := range list {
		if object, ok := entry.(map[string]any); ok {
			if path, ok := object["path"].(string); ok {
				out = append(out, path)
			}
		}
	}
	return out
}

func workspaceGlobs(root string) []string {
	data, err := os.ReadFile(filepath.Join(root, "pnpm-workspace.yaml"))
	if err != nil {
		return nil
	}
	var globs []string
	inside := false
	for _, line := range strings.Split(string(data), "\n") {
		if packagesHeader.MatchString(line) {
			inside = true
			continue
		}
		if inside && line != "" && !strings.ContainsAny(line[:1], " \t\r\n\f\v") {
			break
		}
		if match := globEntry.FindStringSubmatch(line); inside && match != nil {
			globs = append(globs, match[1])
		}
	}
	return globs
}

func isDir(path string) bool {
	info, err := os.Stat(path)
	return err == nil && info.IsDir()
}

func expandGlob(root, pattern string) []string {
	directories := []string{root}
	for _, segment := range strings.Split(pattern, "/") {
		var next []string
		for _, directory := range directories {
			if segment != "*" {
				if candidate := filepath.Join(directory, segment); isDir(candidate) {
					next = append(next, candidate)
				}
				continue
			}
			entries, _ := os.ReadDir(directory)
			for _, entry := range entries {
				name := entry.Name()
				if entry.IsDir() && !strings.HasPrefix(name, ".") && name != "node_modules" {
					next = append(next, filepath.Join(directory, name))
				}
			}
		}
		directories = next
	}
	return directories
}

func workspaceNames(deps any) []string {
	names := []string{}
	object, _ := deps.(map[string]any)
	for name, rangeValue := range object {
		if text, _ := rangeValue.(string); strings.HasPrefix(text, "workspace:") {
			names = append(names, name)
		}
	}
	sort.Strings(names)
	return names
}

// ReadWorkspaceMembers lists the pnpm workspace packages, ordered by name.
func ReadWorkspaceMembers(root string) ([]WorkspaceMember, error) {
	byName := map[string]WorkspaceMember{}
	for _, pattern := range workspaceGlobs(root) {
		for _, directory := range expandGlob(root, pattern) {
			data, err := os.ReadFile(filepath.Join(directory, "package.json"))
			if err != nil {
				continue
			}
			var manifest struct {
				Name            string         `json:"name"`
				Dependencies    any            `json:"dependencies"`
				DevDependencies any            `json:"devDependencies"`
				Scripts         map[string]any `json:"scripts"`
			}
			if err := json.Unmarshal(data, &manifest); err != nil {
				return nil, fmt.Errorf("%s: %w", filepath.Join(directory, "package.json"), err)
			}
			if manifest.Name == "" {
				continue
			}
			_, checks := manifest.Scripts["typecheck"].(string)
			byName[manifest.Name] = WorkspaceMember{
				manifest.Name, directory,
				workspaceNames(manifest.Dependencies), workspaceNames(manifest.DevDependencies), checks,
			}
		}
	}
	members := make([]WorkspaceMember, 0, len(byName))
	for _, member := range byName {
		members = append(members, member)
	}
	sort.Slice(members, func(i, j int) bool { return members[i].Name < members[j].Name })
	return members, nil
}

func groupMemberDirectories(root string) map[string]bool {
	solution := filepath.Join(root, groupSolution)
	set := map[string]bool{}
	if !exists(solution) {
		return set
	}
	group, _ := readConfig(solution)["langwatchDeclarationGroup"].(map[string]any)
	entries, _ := group["members"].([]any)
	for _, entry := range entries {
		object, _ := entry.(map[string]any)
		if directory, _ := object["directory"].(string); directory != "" {
			set[resolvePath(filepath.Dir(solution), directory)] = true
		}
	}
	return set
}

func resolvePath(base, path string) string {
	if filepath.IsAbs(path) {
		return filepath.Clean(path)
	}
	return filepath.Join(base, path)
}

func relativeReference(from, target string) string {
	rel, err := filepath.Rel(from, target)
	if err != nil {
		return target
	}
	return filepath.ToSlash(rel)
}

func normalise(reference string) string { return strings.TrimPrefix(reference, "./") }

func unique(items []string) []string {
	seen := map[string]bool{}
	out := []string{}
	for _, item := range items {
		if !seen[item] {
			seen[item] = true
			out = append(out, item)
		}
	}
	return out
}

// producerFile (cached by producer) is the project a consumer references for this package's
// declarations, or "" when it has none.
func (d *deriver) producer(directory string) string {
	if cached, ok := d.producers[directory]; ok {
		return cached
	}
	producer := d.producerFile(directory)
	d.producers[directory] = producer
	return producer
}

func (d *deriver) config(path string) map[string]any {
	if cached, ok := d.configs[path]; ok {
		return cached
	}
	config := readConfig(path)
	d.configs[path] = config
	return config
}

func (d *deriver) producerFile(directory string) string {
	build := filepath.Join(directory, "tsconfig.build.json")
	if !exists(build) {
		return ""
	}
	options, _ := d.config(build)["compilerOptions"].(map[string]any)
	if declaration, ok := options["declaration"].(bool); !ok || declaration {
		return build
	}
	if declarations := filepath.Join(directory, "tsconfig.declarations.json"); exists(declarations) {
		return declarations
	}
	return ""
}

func checkRootsOf(directory string) []string {
	base := filepath.Join(directory, "tsconfig.test.json")
	if !exists(base) {
		base = filepath.Join(directory, "tsconfig.json")
	}
	var out []string
	for _, file := range []string{base, filepath.Join(directory, "tsconfig.tests.json"), filepath.Join(directory, "tsconfig.type-tests.json")} {
		if exists(file) {
			out = append(out, file)
		}
	}
	return out
}

type cycleWalk struct {
	edges   map[string][]string
	dropped map[string]bool
	done    map[string]bool
	onPath  map[string]bool
	path    []string
}

func (w *cycleWalk) find(node string) []string {
	if w.onPath[node] {
		start := slices.Index(w.path, node)
		return append(slices.Clone(w.path[start:]), node)
	}
	if w.done[node] {
		return nil
	}
	w.path = append(w.path, node)
	w.onPath[node] = true
	for _, next := range w.edges[node] {
		if w.dropped[node+"\n"+next] {
			continue
		}
		if cycle := w.find(next); cycle != nil {
			return cycle
		}
	}
	w.path = w.path[:len(w.path)-1]
	delete(w.onPath, node)
	w.done[node] = true
	return nil
}

func firstCycle(edges map[string][]string, dropped map[string]bool) []string {
	walk := &cycleWalk{edges: edges, dropped: dropped, done: map[string]bool{}, onPath: map[string]bool{}}
	nodes := make([]string, 0, len(edges))
	for node := range edges {
		nodes = append(nodes, node)
	}
	sort.Strings(nodes)
	for _, node := range nodes {
		if cycle := walk.find(node); cycle != nil {
			return cycle
		}
	}
	return nil
}

// droppedEdges removes one edge per cycle: the first whose removal leaves
// the graph acyclic.
func droppedEdges(edges map[string][]string) map[string]bool {
	dropped := map[string]bool{}
	for cycle := firstCycle(edges, dropped); cycle != nil; cycle = firstCycle(edges, dropped) {
		candidates := []string{}
		for i, node := range cycle[:len(cycle)-1] {
			candidates = append(candidates, node+"\n"+cycle[i+1])
		}
		chosen := candidates[0]
		for _, candidate := range candidates {
			trial := map[string]bool{candidate: true}
			for edge := range dropped {
				trial[edge] = true
			}
			if firstCycle(edges, trial) == nil {
				chosen = candidate
				break
			}
		}
		dropped[chosen] = true
	}
	return dropped
}

type deriver struct {
	root, group  string
	members      []WorkspaceMember
	byName       map[string]WorkspaceMember
	groupMembers map[string]bool
	configs      map[string]map[string]any
	producers    map[string]string
}

func (d *deriver) targetsFor(names []string) []string {
	out := []string{}
	for _, name := range names {
		member, ok := d.byName[name]
		if !ok {
			continue
		}
		producer := d.producer(member.Directory)
		if producer == "" {
			continue
		}
		if d.groupMembers[member.Directory] {
			producer = d.group
		}
		out = append(out, producer)
	}
	return out
}

func (d *deriver) buildEdges() map[string][]string {
	edges := map[string][]string{d.group: {}}
	if exists(d.group) {
		for _, path := range referencePaths(d.config(d.group), "references") {
			edges[d.group] = append(edges[d.group], resolvePath(filepath.Dir(d.group), path))
		}
	}
	for _, member := range d.members {
		producer := d.producer(member.Directory)
		if producer == "" {
			continue
		}
		targets := []string{d.group}
		if !d.groupMembers[member.Directory] {
			targets = d.targetsFor(member.Dependencies)
		}
		kept := []string{}
		for _, edge := range unique(targets) {
			if edge != producer {
				kept = append(kept, edge)
			}
		}
		edges[producer] = kept
	}
	return edges
}

type kind struct {
	file    string
	targets []string
}

func (d *deriver) derivedProject(k kind) []Project {
	if !exists(k.file) {
		return nil
	}
	config := d.config(k.file)
	derived := []string{}
	for _, target := range k.targets {
		if target != k.file {
			derived = append(derived, relativeReference(filepath.Dir(k.file), target))
		}
	}
	for _, extra := range referencePaths(config, "langwatchExtraReferences") {
		derived = append(derived, normalise(extra))
	}
	references := unique(derived)
	undeduced, current := []string{}, currentReferences(config)
	for _, entry := range current {
		if !slices.Contains(references, entry) {
			undeduced = append(undeduced, entry)
		}
	}
	return []Project{{File: k.file, References: references, Undeduced: undeduced, Current: current}}
}

func (d *deriver) rootSolutionProject() []Project {
	solution := filepath.Join(d.root, rootSolution)
	if !exists(solution) {
		return nil
	}
	config := readConfig(solution)
	derived := []string{}
	for _, member := range d.members {
		if !member.Checks {
			continue
		}
		for _, file := range checkRootsOf(member.Directory) {
			derived = append(derived, relativeReference(d.root, file))
		}
	}
	for _, extra := range referencePaths(config, "langwatchExtraReferences") {
		derived = append(derived, normalise(extra))
	}
	return []Project{{File: solution, References: unique(derived), Undeduced: []string{}, Current: currentReferences(config)}}
}

func currentReferences(config map[string]any) []string {
	current := []string{}
	for _, entry := range referencePaths(config, "references") {
		current = append(current, normalise(entry))
	}
	return current
}

func (d *deriver) kinds(member WorkspaceMember, isGroup bool, own string, buildTargets, dependencyTargets, consumerTargets []string) []kind {
	build := filepath.Join(member.Directory, "tsconfig.build.json")
	var out []kind
	if own == build || isGroup {
		out = append(out, kind{build, unique(buildTargets)})
	}
	for _, name := range checkRoots {
		out = append(out, kind{filepath.Join(member.Directory, name), consumerTargets})
	}
	if own != "" && own != build && !isGroup {
		targets := []string{}
		for _, target := range dependencyTargets {
			if target != own {
				targets = append(targets, target)
			}
		}
		out = append(out, kind{own, targets})
	}
	return out
}

// DeriveProjects computes every tsconfig's references from the workspace.
func DeriveProjects(root string, members []WorkspaceMember) []Project {
	d := &deriver{root: root, group: filepath.Join(root, groupSolution), members: members,
		byName: map[string]WorkspaceMember{}, groupMembers: groupMemberDirectories(root),
		configs: map[string]map[string]any{}, producers: map[string]string{}}
	for _, member := range members {
		d.byName[member.Name] = member
	}
	dropped := droppedEdges(d.buildEdges())
	var projects []Project
	for _, member := range members {
		isGroup := d.groupMembers[member.Directory]
		own := d.group
		if !isGroup {
			own = d.producer(member.Directory)
		}
		buildTargets := []string{d.group}
		if !isGroup {
			buildTargets = d.targetsFor(member.Dependencies)
		}
		kept := []string{}
		for _, target := range buildTargets {
			if !dropped[d.producer(member.Directory)+"\n"+target] {
				kept = append(kept, target)
			}
		}
		dependencyTargets := unique(append(d.targetsFor(member.Dependencies), d.targetsFor(member.DevDependencies)...))
		consumerTargets := dependencyTargets
		if own != "" {
			consumerTargets = unique(append([]string{own}, dependencyTargets...))
		}
		for _, k := range d.kinds(member, isGroup, own, kept, dependencyTargets, consumerTargets) {
			projects = append(projects, d.derivedProject(k)...)
		}
	}
	return append(projects, d.rootSolutionProject()...)
}

func indentUnitOf(text string) string {
	if match := indentPattern.FindStringSubmatch(text); match != nil {
		return match[1]
	}
	return "  "
}

func lineIndentAt(text string, position int) string {
	start := strings.LastIndex(text[:position+1], "\n") + 1
	if line := text[start:position]; blankIndent.MatchString(line) {
		return line
	}
	return ""
}

func renderArray(references []string, indent, unit string) string {
	if len(references) == 0 {
		return "[]"
	}
	entries := make([]string, len(references))
	for i, path := range references {
		entries[i] = indent + unit + "{\n" + indent + unit + unit + "\"path\": " + jsQuote(path) + "\n" + indent + unit + "}"
	}
	return "[\n" + strings.Join(entries, ",\n") + "\n" + indent + "]"
}

// RenderReferences replaces only the references array, keeping every other byte.
func RenderReferences(text string, references []string) string {
	unit := indentUnitOf(text)
	if keyStart, valueStart, valueEnd, ok := jsonc.ReferencesSpan(text); ok {
		indent := lineIndentAt(text, keyStart)
		return text[:valueStart] + renderArray(references, indent, unit) + text[valueEnd:]
	}
	closing := strings.LastIndex(text, "}")
	if len(references) == 0 || closing < 0 {
		return text
	}
	body := trailingSpace.ReplaceAllString(text[:closing], "")
	insertion := unit + "\"references\": " + renderArray(references, unit, unit)
	separator := ","
	if openingPattern.MatchString(body) {
		separator = ""
	}
	return body + separator + "\n" + insertion + "\n" + text[closing:]
}

func unifiedDiff(path, before, after string) string {
	left, right := strings.Split(before, "\n"), strings.Split(after, "\n")
	lines := []string{"--- a/" + path, "+++ b/" + path}
	start := 0
	for start < len(left) && start < len(right) && left[start] == right[start] {
		start++
	}
	end := 0
	for end < len(left)-start && end < len(right)-start && left[len(left)-1-end] == right[len(right)-1-end] {
		end++
	}
	removed, added := left[start:len(left)-end], right[start:len(right)-end]
	lines = append(lines, fmt.Sprintf("@@ -%d,%d +%d,%d @@", start+1, len(removed), start+1, len(added)))
	for _, line := range removed {
		lines = append(lines, "-"+line)
	}
	for _, line := range added {
		lines = append(lines, "+"+line)
	}
	return strings.Join(lines, "\n")
}

func renderBuildSolution(root string, projects []Project) string {
	paths := []string{}
	for _, project := range projects {
		if rel := relativeReference(root, project.File); contractBuild.MatchString(rel) {
			paths = append(paths, rel)
		}
	}
	sort.Strings(paths)
	references := []any{}
	for _, path := range paths {
		references = append(references, Object{{"path", path}})
	}
	body := stringifyJS(Object{{"files", []any{}}, {"references", references}})
	return buildSolutionTS + "\n" + body + "\n"
}

type changedFile struct{ path, before, after string }

func runSyncReferences(root string, args []string, stdout, stderr io.Writer) int {
	write := slices.Contains(args, "--write")
	members, err := ReadWorkspaceMembers(root)
	if err != nil {
		fmt.Fprintln(stderr, "sync-references:", err)
		return 1
	}
	projects := DeriveProjects(root, members)
	var changed []changedFile
	var undeducible []string
	for _, project := range projects {
		path := relativeReference(root, project.File)
		data, err := os.ReadFile(project.File)
		if err != nil {
			fmt.Fprintln(stderr, "sync-references:", err)
			return 1
		}
		before := string(data)
		after := RenderReferences(before, project.References)
		for _, entry := range project.Undeduced {
			undeducible = append(undeducible, fmt.Sprintf("Undeducible reference in %s: %s. Keep it under langwatchExtraReferences.", path, entry))
		}
		if before == after {
			continue
		}
		changed = append(changed, changedFile{path, before, after})
		if write {
			if err := os.WriteFile(project.File, []byte(after), 0o644); err != nil {
				fmt.Fprintln(stderr, "sync-references:", err)
				return 1
			}
		}
	}
	solutionPath := filepath.Join(root, "tsconfig.build.json")
	solution := renderBuildSolution(root, projects)
	existing, _ := os.ReadFile(solutionPath)
	if string(existing) != solution {
		changed = append(changed, changedFile{"tsconfig.build.json", string(existing), solution})
		if write {
			if err := os.WriteFile(solutionPath, []byte(solution), 0o644); err != nil {
				fmt.Fprintln(stderr, "sync-references:", err)
				return 1
			}
		}
	}
	if write {
		fmt.Fprintf(stdout, "Wrote %d of %d tsconfig files.\n", len(changed), len(projects))
	} else {
		for _, file := range changed {
			fmt.Fprintf(stdout, "%s\n\n", unifiedDiff(file.path, file.before, file.after))
		}
	}
	for _, line := range undeducible {
		fmt.Fprintln(stdout, line)
	}
	fmt.Fprintf(stdout, "%d of %d tsconfig files differ; %d undeducible entries.\n", len(changed), len(projects), len(undeducible))
	if !write && (len(changed) > 0 || len(undeducible) > 0) {
		return 1
	}
	return 0
}
