/**
 * The capabilities the packaged tRPC record reaches that this process cannot
 * build for itself yet — enumerated, so "what is left" is a type rather than a
 * memory.
 *
 * `AppTrpcFeaturePorts` is the full list of what the twenty-two namespaces need
 * from their host. This is that list MINUS everything the API process now
 * answers out of its own composition: its Prisma connection, its audit sink,
 * its AuthZ service, and the several dozen row reads those three make possible.
 * What remains is not a leftover — every entry names a real capability with a
 * real owner, and the owner is a service no package holds today:
 *
 *   - the analytics input schemas and the filter catalogue, which are the
 *     deployment's and are shared with the REST analytics body;
 *   - the LangWatchQL workbench: its rollout gate, its statement executor and
 *     the tenant capability a restricted statement runs as;
 *   - the trace pipeline — reading a trace's content, resolving which ids a
 *     project holds, and the two annotation commands;
 *   - the sign-in ceremony, the sign-up ceremony and the invitation mailer;
 *   - the evaluator inventory, the evaluation runner and the NLP keep-alive;
 *   - the model gateway behind an autogenerated commit message;
 *   - the Enterprise governance surfaces, the billing store and the
 *     deployment's marketing notifications.
 *
 * A process that has none of them composes no record and says so by name; a
 * process that has them mounts all twenty-two. Nothing in between, and nothing
 * silently degraded — see {@link ApiTrpcCollaboratorsAbsence}.
 */
import type { AnnotationTrpcPorts } from "@langwatch/annotation-server";
import type { AuthApp } from "@langwatch/auth-server";
import type { DataPrivacyTrpcPorts } from "@langwatch/data-privacy-server";
import type { ExperimentTrpcPorts } from "@langwatch/experiment-server";
import type { BugReportTrpcPorts } from "@langwatch/ops-server";
import type { EmailSuppressionTrpcPorts } from "@langwatch/automation-server";
import type {
  GroupTrpcPorts,
  JoinRequestTrpcPorts,
  OnboardingTrpcPorts,
  OrganizationTrpcPorts,
} from "@langwatch/organization-server";
import type { IntegrationsChecksTrpcPorts } from "@langwatch/project-server";
import type { IdentityTrpcPorts, UserTrpcPorts } from "@langwatch/user-server";
import type { WorkflowOptimizationTrpcPorts, WorkflowTrpcPorts } from "@langwatch/workflow-server";
import type { ZodTypeAny } from "zod";
import type { EvaluationMountPorts } from "../features/evaluation/evaluation-trpc.mount";
import type { ApiTrpcFeatureApplication } from "./app-trpc.context";
import type { CodingAgentTrpcPorts } from "@langwatch/coding-agent-server";
import type { OpsTrpcPorts } from "@langwatch/ops-server";
import type { AuthzPermission } from "@langwatch/authz-contract";
import type { AppTrpcDeclaredCheck } from "./app-trpc.policy-kit";
import type { AutomationMountPorts } from "../features/automation/automation-trpc.mount";
import type { EnterpriseTrpcMountPorts } from "../features/enterprise/enterprise-trpc.mount";
import type {
  ProjectTrpcChecks,
  ProjectTrpcMountPorts,
} from "../features/project/project-trpc.mount";
import type { HttpProxyTrpcPorts } from "@langwatch/agent-server";
import type { SavedViewTrpcPorts } from "@langwatch/dashboard-server";
import type { CostTrpcPorts, LimitsTrpcPorts } from "@langwatch/entitlement-server";
import type {
  LlmModelCostTrpcPorts,
  ModelProviderTrpcPorts,
  TranslateTrpcPorts,
} from "@langwatch/model-provider-server";
import type { TraceLegacyFilterInput, TraceLegacyListInput } from "@langwatch/trace-contract";
import type {
  SharedTraceTrpcPorts,
  SpansTrpcPorts,
  TraceEditOverlayTrpcPorts,
  TraceEditOverlayVisibilityWindow,
  TracesTrpcPorts,
  TracesV2TrpcPorts,
} from "@langwatch/trace-server";
import type { ModelProviderTrpcChecks } from "../features/model-provider/model-provider-trpc.mount";

/**
 * The `user.*` entries this process answers from its own Prisma connection:
 * the user rows behind the /me screens, the organization membership probe and
 * the first-project slug. Every one of them is a row read with a project or
 * user id already in hand, which is why they moved with the connection rather
 * than staying behind a port.
 *
 * The five that used to be here and are not any more — `rotatePassword`,
 * `tryFindAuth0DatabaseAccount`, `listLinkedAccounts` and `unlinkAccount`, and
 * the credential read and write the first replaced — are reads of `Account`,
 * the table the stored password hash lives on. They now reach the user
 * feature's own `UserCredentialService` and arrive as collaborators, which is
 * what the second half of this module's contract is for.
 */
type ApiOwnedUserPorts =
  | "emailIsTaken"
  | "isOrganizationMember"
  | "tryGetOrganizationName"
  | "tryGetUserContact"
  | "tryFindFirstProjectSlug";

/** The `workflow.*` entries this process answers from Prisma and its AuthZ service. */
type ApiOwnedWorkflowPorts =
  | "hasProjectPermission"
  | "hasProjectPermissions"
  | "listWorkflowsWithCopyLineage"
  | "tryFindWorkflow"
  | "tryFindCopiesWithPath"
  | "tryFindWorkflowWithSource"
  | "tryFindWorkflowWithCopies"
  | "tryFindLatestVersionNumber"
  | "listAgentsForWorkflow"
  | "listMonitorsForEvaluators"
  | "cascadeArchiveWorkflow";

/** The `optimization.*` entries that are row reads and one flag write. */
type ApiOwnedOptimizationPorts =
  | "tryGetWorkflow"
  | "tryGetWorkflowVersion"
  | "setWorkflowFlags"
  | "listPublishedComponents";

/** The `experiments.*` entries that are row reads or an AuthZ probe. */
type ApiOwnedExperimentPorts =
  | "probeProjectPermission"
  | "createWorkflow"
  | "tryFindWorkflow"
  | "resolveAuthorNames";

/** The `annotation.*` entries answered by the packaged Postgres adapter and AuthZ. */
type ApiOwnedAnnotationPorts = "queues" | "probeProjectPermission" | "toQueueSlug";

export type ApiTrpcCollaborators<
  TBugReport,
  TBugReportPage,
  TCheckStatus,
  TMappingsIn,
  TMappingsOut,
  TPrivacyRule,
  TPrivacySnapshot,
  TSignUpDataSchema extends ZodTypeAny,
  TWorkbenchState,
  TListInput extends TraceLegacyListInput = TraceLegacyListInput,
  TListInputRaw = unknown,
  TFilterInput extends TraceLegacyFilterInput = TraceLegacyFilterInput,
  TFilterInputRaw = unknown,
  TPrecondition = unknown,
  TProtections extends TraceEditOverlayVisibilityWindow = TraceEditOverlayVisibilityWindow,
  TMetadata = unknown,
  TMetadataRaw = unknown,
  TSavedView = unknown,
  TSpendRollup = unknown,
  TApiKeyValidation = unknown,
  TStoredKeyValidation = unknown,
> = Readonly<{
  /**
   * The application slices every packaged surface reads off `ctx.app`.
   *
   * They arrive whole rather than one per feature: a request carries ONE
   * application, and a process that could hand a different `annotations` to
   * the annotation surface than to the queueing behind it would have two.
   */
  application: ApiTrpcFeatureApplication;

  /** Everything an annotation needs from the TRACE side, and nothing else. */
  annotation: Omit<AnnotationTrpcPorts, ApiOwnedAnnotationPorts>;

  /** The composed auth application both signed-out doors answer from. */
  auth: AuthApp;



  /** The support inbox itself; the audit trail beside it is this process's. */
  bugReports: Omit<BugReportTrpcPorts<TBugReportPage, TBugReport>, "recordAudit">;

  dataPrivacy: DataPrivacyTrpcPorts<TPrivacySnapshot, TPrivacyRule>;

  evaluations: EvaluationMountPorts<TMappingsIn, TMappingsOut>;


  experiments: Omit<ExperimentTrpcPorts<TWorkbenchState>, ApiOwnedExperimentPorts>;

  group: GroupTrpcPorts;


  identity: IdentityTrpcPorts;

  integrationsChecks: IntegrationsChecksTrpcPorts<TCheckStatus>;

  joinRequests: Omit<JoinRequestTrpcPorts, "listUserNames">;

  onboarding: OnboardingTrpcPorts<TSignUpDataSchema>;




  /** The legacy grid's two shared input schemas, the precondition engine, the span digest and redactions. */
  traces: TracesTrpcPorts<TListInput, TListInputRaw, TFilterInput, TFilterInputRaw, TPrecondition>;
  /** Everything the explorer reads that is another vertical's. */
  tracesV2: Omit<TracesV2TrpcPorts<TMetadata, TMetadataRaw>, "queryTranslation">;
  /** The caller's read-time redactions, for the waterfall and the studio span. */
  spans: SpansTrpcPorts;
  /** The same redactions, plus the two rules a correction is carried through. */
  traceEditOverlay: TraceEditOverlayTrpcPorts<TProtections>;
  /** The anonymous read's own four capabilities. */
  sharedTrace: SharedTraceTrpcPorts;
  /** The stored filter sets, generic in the row shape the explorer renders. */
  savedViews: SavedViewTrpcPorts<TSavedView>;
  /** The organization's spend, rolled up per project. */
  costs: CostTrpcPorts<TSpendRollup>;
  /** The cost rule's regex safety gate, the model registry's ceilings and the live span preview. */
  llmModelCost: LlmModelCostTrpcPorts;
  /** The outbound credential probes, the Codex device flow and the audit trail. */
  modelProvider: ModelProviderTrpcPorts<TApiKeyValidation, TStoredKeyValidation>;
  /** The two data-dependent gates the provider surface needs, already built. */
  modelProviderChecks: ModelProviderTrpcChecks;
  /** The application's provider-failure policy behind one model call. */
  translate: TranslateTrpcPorts;
  /** The studio's event dispatch, and the agent test's own trace write. */
  httpProxy: HttpProxyTrpcPorts;
  /** The usage reading and the approaching-limit notifier, over the billing store. */
  limits: LimitsTrpcPorts;

  /** The forty-six answers `organization.*` needs from this deployment. */
  organization: OrganizationTrpcPorts<TSignUpDataSchema>;
  /** The audit-log read's own `kind: "custom"` check, already built. */
  organizationAuditLogCheck: unknown;
  /** The six answers `project.*` needs. */
  project: ProjectTrpcMountPorts;
  /** `project.create`'s custom tier resolution and the trace-sharing demand. */
  projectChecks: ProjectTrpcChecks;
  /** What one viewer may see of one project's captured content and spend. */
  codingAgents: CodingAgentTrpcPorts;
  /** The three answers the automation transport reaches beyond automation's own. */
  automation: AutomationMountPorts;
  /** The unsubscribe pair's client address, its throttle and its audit trail. */
  emailSuppression: EmailSuppressionTrpcPorts;
  /** The SCIM plan gate, and the back office's connection ledger with its trail. */
  enterprise: EnterpriseTrpcMountPorts;

  /**
   * The retention policy: who may write an override at a scope, which values
   * that scope's plan may persist, who may switch retention off, and the two
   * RBAC-filtered reads the settings page renders.
   */
  /** The monitor surface's precondition parser, comparison window and evaluator replication. */

  user: Omit<UserTrpcPorts, ApiOwnedUserPorts>;

  workflows: Readonly<{
    lifecycle: Omit<WorkflowTrpcPorts, ApiOwnedWorkflowPorts>;
    optimization: Pick<
      WorkflowOptimizationTrpcPorts<never, never>,
      Exclude<keyof WorkflowOptimizationTrpcPorts<never, never>, ApiOwnedOptimizationPorts>
    >;
  }>;
}>;

/**
 * Reports the composition decision a missing collaborator set would otherwise
 * hide.
 *
 * One reason today and it is deliberately not a list of the individual
 * capabilities: they are one graph. A deployment holding the trace pipeline
 * but not the sign-in ceremony cannot serve `frontDoor`, and a record with
 * `frontDoor` missing is not a smaller record — it is a product a person
 * cannot sign in to. The absence is stated once, at the level a deployment can
 * actually act on.
 */
export abstract class ApiTrpcCollaboratorsAbsence {
  abstract absent(reason: "no-collaborators" | "no-database"): void;
}
