/**
 * The capabilities the packaged tRPC record reaches that this process cannot
 * build for itself yet — enumerated, so "what is left" is a type rather than a
 * memory.
 *
 * `AppTrpcFeaturePorts` is the full list of what the twenty-two namespaces need
 * from their host. This is that list MINUS everything the API process now
 * answers out of its own composition: its Prisma connection, its audit sink,
 * its AuthZ service, and the several dozen row reads those three make possible.
 * What remains is not a leftover — every entry names a real capability with a
 * real owner, and the owner is a service no package holds today:
 *
 *   - the analytics input schemas and the filter catalogue, which are the
 *     deployment's and are shared with the REST analytics body;
 *   - the LangWatchQL workbench: its rollout gate, its statement executor and
 *     the tenant capability a restricted statement runs as;
 *   - the trace pipeline — reading a trace's content, resolving which ids a
 *     project holds, and the two annotation commands;
 *   - the sign-in ceremony, the sign-up ceremony and the invitation mailer;
 *   - the evaluator inventory, the evaluation runner and the NLP keep-alive;
 *   - the model gateway behind an autogenerated commit message;
 *   - the Enterprise governance surfaces, the billing store and the
 *     deployment's marketing notifications.
 *
 * A process that has none of them composes no record and says so by name; a
 * process that has them mounts all twenty-two. Nothing in between, and nothing
 * silently degraded — see {@link ApiTrpcCollaboratorsAbsence}.
 */
import type { AnalyticsReadInput, AnalyticsTimeseriesInput } from "@langwatch/analytics-contract";
import type { AnalyticsTrpcPorts, LangWatchQLTrpcPorts } from "@langwatch/analytics-server";
import type { AnnotationTrpcPorts } from "@langwatch/annotation-server";
import type { AuthApp } from "@langwatch/auth-server";
import type { SavedWorkbenchChartTrpcPorts, GraphTrpcPorts } from "@langwatch/dashboard-server";
import type { DataPrivacyTrpcPorts } from "@langwatch/data-privacy-server";
import type { ExperimentTrpcPorts } from "@langwatch/experiment-server";
import type { BugReportTrpcPorts } from "@langwatch/ops-server";
import type {
  GroupTrpcPorts,
  JoinRequestTrpcPorts,
  OnboardingTrpcPorts,
} from "@langwatch/organization-server";
import type { IntegrationsChecksTrpcPorts } from "@langwatch/project-server";
import type { IdentityTrpcPorts, UserTrpcPorts } from "@langwatch/user-server";
import type {
  WorkflowOptimizationTrpcPorts,
  WorkflowTrpcPorts,
} from "@langwatch/workflow-server";
import type { ZodTypeAny } from "zod";
import type { EvaluationMountPorts } from "../features/evaluation/evaluation-trpc.mount";
import type { ApiTrpcFeatureApplication } from "./app-trpc.context";

/**
 * The `user.*` entries this process answers from its own Prisma connection:
 * the account rows behind the /me screens, the credential and Auth0 lookups,
 * the organization membership probe and the first-project slug. Every one of
 * them is a row read with a project or user id already in hand, which is why
 * they moved with the connection rather than staying behind a port.
 */
type ApiOwnedUserPorts =
  | "tryFindCredentialAccount"
  | "writeCredentialPassword"
  | "tryFindAuth0DatabaseAccount"
  | "emailIsTaken"
  | "listLinkedAccounts"
  | "unlinkAccount"
  | "isOrganizationMember"
  | "tryGetOrganizationName"
  | "tryGetUserContact"
  | "tryFindFirstProjectSlug";

/** The `workflow.*` entries this process answers from Prisma and its AuthZ service. */
type ApiOwnedWorkflowPorts =
  | "hasProjectPermission"
  | "hasProjectPermissions"
  | "listWorkflowsWithCopyLineage"
  | "tryFindWorkflow"
  | "tryFindCopiesWithPath"
  | "tryFindWorkflowWithSource"
  | "tryFindWorkflowWithCopies"
  | "tryFindLatestVersionNumber"
  | "listAgentsForWorkflow"
  | "listMonitorsForEvaluators"
  | "cascadeArchiveWorkflow";

/** The `optimization.*` entries that are row reads and one flag write. */
type ApiOwnedOptimizationPorts =
  | "tryGetWorkflow"
  | "tryGetWorkflowVersion"
  | "setWorkflowFlags"
  | "listPublishedComponents";

/** The `experiments.*` entries that are row reads or an AuthZ probe. */
type ApiOwnedExperimentPorts =
  | "probeProjectPermission"
  | "createWorkflow"
  | "tryFindWorkflow"
  | "resolveAuthorNames";

/** The `annotation.*` entries answered by the packaged Postgres adapter and AuthZ. */
type ApiOwnedAnnotationPorts = "queues" | "probeProjectPermission" | "toQueueSlug";

export type ApiTrpcCollaborators<
  TBugReport,
  TBugReportPage,
  TCheckStatus,
  TFilterField extends string,
  TMappingsIn,
  TMappingsOut,
  TPrivacyRule,
  TPrivacySnapshot,
  TReadInput extends AnalyticsReadInput,
  TSignUpDataSchema extends ZodTypeAny,
  TTimeseriesInput extends AnalyticsTimeseriesInput,
  TWorkbenchState,
  TTimeseriesInputWire = unknown,
  TReadInputWire = unknown,
> = Readonly<{
  /**
   * The application slices every packaged surface reads off `ctx.app`.
   *
   * They arrive whole rather than one per feature: a request carries ONE
   * application, and a process that could hand a different `annotations` to
   * the annotation surface than to the queueing behind it would have two.
   */
  application: ApiTrpcFeatureApplication;

  /** The charted reads, the workbench, and the saved workbench charts. */
  analytics: Readonly<{
    reads: AnalyticsTrpcPorts<
      TTimeseriesInput,
      TReadInput,
      TFilterField,
      TTimeseriesInputWire,
      TReadInputWire
    >;
    workbench: LangWatchQLTrpcPorts;
    savedCharts: SavedWorkbenchChartTrpcPorts;
  }>;

  /** Everything an annotation needs from the TRACE side, and nothing else. */
  annotation: Omit<AnnotationTrpcPorts, ApiOwnedAnnotationPorts>;

  /** The composed auth application both signed-out doors answer from. */
  auth: AuthApp;

  /** The support inbox itself; the audit trail beside it is this process's. */
  bugReports: Omit<BugReportTrpcPorts<TBugReportPage, TBugReport>, "recordAudit">;

  dataPrivacy: DataPrivacyTrpcPorts<TPrivacySnapshot, TPrivacyRule>;

  evaluations: EvaluationMountPorts<TMappingsIn, TMappingsOut>;

  experiments: Omit<ExperimentTrpcPorts<TWorkbenchState>, ApiOwnedExperimentPorts>;

  graphs: GraphTrpcPorts<TFilterField>;

  group: GroupTrpcPorts;

  identity: IdentityTrpcPorts;

  integrationsChecks: IntegrationsChecksTrpcPorts<TCheckStatus>;

  joinRequests: Omit<JoinRequestTrpcPorts, "listUserNames">;

  onboarding: OnboardingTrpcPorts<TSignUpDataSchema>;

  user: Omit<UserTrpcPorts, ApiOwnedUserPorts>;

  workflows: Readonly<{
    lifecycle: Omit<WorkflowTrpcPorts, ApiOwnedWorkflowPorts>;
    optimization: Pick<
      WorkflowOptimizationTrpcPorts<never, never>,
      Exclude<keyof WorkflowOptimizationTrpcPorts<never, never>, ApiOwnedOptimizationPorts>
    >;
  }>;
}>;

/**
 * Reports the composition decision a missing collaborator set would otherwise
 * hide.
 *
 * One reason today and it is deliberately not a list of the individual
 * capabilities: they are one graph. A deployment holding the trace pipeline
 * but not the sign-in ceremony cannot serve `frontDoor`, and a record with
 * `frontDoor` missing is not a smaller record — it is a product a person
 * cannot sign in to. The absence is stated once, at the level a deployment can
 * actually act on.
 */
export abstract class ApiTrpcCollaboratorsAbsence {
  abstract absent(reason: "no-collaborators" | "no-database"): void;
}

/**
 * The collaborator set with its type parameters erased, for the composition
 * root.
 *
 * The parameters exist so a CLIENT sees the concrete return types the ports
 * answer with. The composition root publishes no client type — the record it
 * builds is handed to the application as a `TRPCRouterRecord` — so carrying
 * fourteen parameters through it would buy nothing and would make every
 * deployment shape restate them. A host that wants the derived types calls
 * {@link ApiTrpcFeaturesComposition.tryCompose} directly.
 */
export type AnyApiTrpcCollaborators = ApiTrpcCollaborators<
  unknown,
  unknown,
  unknown,
  string,
  unknown,
  unknown,
  unknown,
  unknown,
  AnalyticsReadInput,
  ZodTypeAny,
  AnalyticsTimeseriesInput,
  unknown,
  unknown,
  unknown
>;
