/**
 * Every widget the library defines: the question it answers, who it is for and what it needs.
 * Generated from the dashboards library draft on 2026-10-06; edit here from now on.
 */

import type { AgentKind, CatalogueScope, Persona, QuestionType } from "./catalogue-labels.ts";

/** built: code exists; ready: today's data; logic: new query code; feature: waits for LangWatch. */
export type CatalogueBuild = "built" | "ready" | "logic" | "feature";

export interface CatalogueWidget {
  readonly id: string;
  /** Where the design came from: our PR, Rogerio's prototype, or proposed by the library. */
  readonly origin: "pr" | "prototype" | "proposed";
  readonly question: string;
  readonly title: string;
  readonly why: string;
  readonly questionId: string;
  readonly alsoAnswers: readonly string[];
  readonly questionType: QuestionType;
  readonly personas: readonly Persona[];
  readonly agentKinds: readonly AgentKind[];
  /** Each entry is one requirement; its keys are alternatives, any one of which will do. */
  readonly requirements: readonly (readonly string[])[];
  readonly build: CatalogueBuild;
  readonly scope: CatalogueScope;
}

export const CATALOGUE_WIDGETS: readonly CatalogueWidget[] = [
  {
    id: "traffic",
    origin: "pr",
    question: "How much work did my agent handle?",
    title: "How much traffic did my agent handle?",
    why: "Traces per bucket, with the period total and the busiest and quietest buckets.",
    questionId: "used",
    alsoAnswers: [],
    questionType: "happened",
    personas: ["product", "ops"],
    agentKinds: ["support-bot", "rag", "voice", "extraction", "tools-agent", "generative"],
    requirements: [["traces"]],
    build: "built",
    scope: "project",
  },
  {
    id: "satisfaction-shift",
    origin: "pr",
    question: "Did user satisfaction with my agent shift?",
    title: "Did user satisfaction shift?",
    why: "Average of LangWatch's derived satisfaction score per bucket, against the period before.",
    questionId: "happy",
    alsoAnswers: [],
    questionType: "changed",
    personas: ["product", "ops"],
    agentKinds: ["support-bot", "rag", "voice", "tools-agent"],
    requirements: [["satscore"]],
    build: "built",
    scope: "project",
  },
  {
    id: "token-drift",
    origin: "pr",
    question: "Is my agent's token use drifting up?",
    title: "Is token usage drifting up?",
    why: "Prompt and completion tokens per bucket, and how far the total moved first to last.",
    questionId: "spend",
    alsoAnswers: ["change"],
    questionType: "changed",
    personas: ["eng", "finance"],
    agentKinds: ["support-bot", "rag", "voice", "extraction", "tools-agent", "generative"],
    requirements: [["tokens"]],
    build: "built",
    scope: "project",
  },
  {
    id: "conversation-length",
    origin: "pr",
    question: "Are conversations with my agent getting longer?",
    title: "Are conversations getting longer?",
    why: "Average traces per conversation in each bucket, and its change first to last.",
    questionId: "depth",
    alsoAnswers: [],
    questionType: "changed",
    personas: ["product"],
    agentKinds: ["support-bot", "rag", "voice", "tools-agent"],
    requirements: [["thread"]],
    build: "built",
    scope: "project",
  },
  {
    id: "latency-slo",
    origin: "pr",
    question: "Which periods were slower than usual for my agent?",
    title: "Is p95 latency above target?",
    why: "Slowest-5% latency per bucket against the period's own figure, counting the buckets well above it. There is no target setting yet.",
    questionId: "fast",
    alsoAnswers: [],
    questionType: "line",
    personas: ["eng", "ops"],
    agentKinds: ["support-bot", "rag", "voice", "extraction", "tools-agent", "generative"],
    requirements: [["traces"]],
    build: "built",
    scope: "project",
  },
  {
    id: "error-rate",
    origin: "pr",
    question: "Are more of my agent's traces ending in an error?",
    title: "Are more of my traces ending in an error?",
    why: "Share of traces ending in an error per bucket, with the latest and first rates.",
    questionId: "failing",
    alsoAnswers: [],
    questionType: "changed",
    personas: ["eng", "ops"],
    agentKinds: ["support-bot", "rag", "voice", "extraction", "tools-agent", "generative"],
    requirements: [["errors"]],
    build: "built",
    scope: "project",
  },
  {
    id: "latency-spread",
    origin: "pr",
    question: "How far apart are my agent's typical and slowest responses?",
    title: "How far apart are typical and slowest responses?",
    why: "Typical, slow and slowest-1% latency for the period and per bucket, and how long the tail is.",
    questionId: "fast",
    alsoAnswers: [],
    questionType: "compare",
    personas: ["eng"],
    agentKinds: ["support-bot", "rag", "voice", "extraction", "tools-agent", "generative"],
    requirements: [["traces"]],
    build: "built",
    scope: "project",
  },
  {
    id: "spend",
    origin: "pr",
    question: "What is my agent spending?",
    title: "What are my agents spending?",
    why: "Spend per bucket, the period total and the most expensive bucket.",
    questionId: "spend",
    alsoAnswers: [],
    questionType: "happened",
    personas: ["finance", "eng", "leader"],
    agentKinds: ["support-bot", "rag", "voice", "extraction", "tools-agent", "generative"],
    requirements: [["cost"]],
    build: "built",
    scope: "project",
  },
  {
    id: "top-models",
    origin: "pr",
    question: "Which models do my traces use most?",
    title: "Which models do my traces use most?",
    why: "The ten models most traces use, with their share of all traces and their cost.",
    questionId: "spend",
    alsoAnswers: ["less"],
    questionType: "matters",
    personas: ["eng", "prompt"],
    agentKinds: ["support-bot", "rag", "voice", "extraction", "tools-agent", "generative"],
    requirements: [["model"]],
    build: "built",
    scope: "project",
  },
  {
    id: "lowest-passing-evaluators",
    origin: "pr",
    question: "Which evaluators fail most?",
    title: "Lowest-passing evaluators",
    why: "The five evaluators with the lowest pass rate, with their run counts.",
    questionId: "answers",
    alsoAnswers: [],
    questionType: "matters",
    personas: ["qa", "expert"],
    agentKinds: ["support-bot", "rag", "voice", "extraction", "tools-agent", "generative"],
    requirements: [["evals"]],
    build: "built",
    scope: "project",
  },
  {
    id: "scenarios",
    origin: "pr",
    question: "Does my agent keep passing its test scenarios?",
    title: "What are my scenarios telling me?",
    why: "Share of scenario runs the judge passed, for the period and bucket by bucket.",
    questionId: "tests",
    alsoAnswers: [],
    questionType: "changed",
    personas: ["qa", "eng"],
    agentKinds: ["support-bot", "rag", "voice", "extraction", "tools-agent", "generative"],
    requirements: [["scenarios"]],
    build: "built",
    scope: "project",
  },
  {
    id: "topics",
    origin: "pr",
    question: "What do users ask my agent about most?",
    title: "What are users asking about most?",
    why: "The ten topics with the most traces, their share, and the topic that grew most.",
    questionId: "asking",
    alsoAnswers: [],
    questionType: "matters",
    personas: ["product", "ops", "expert"],
    agentKinds: ["support-bot", "rag", "voice", "tools-agent"],
    requirements: [["topics"]],
    build: "built",
    scope: "project",
  },
  {
    id: "slowest-models",
    origin: "pr",
    question: "Which model makes my agent slowest?",
    title: "Improve latency: slowest models",
    why: "The five models whose traces have the slowest-5% latency.",
    questionId: "fast",
    alsoAnswers: ["less"],
    questionType: "compare",
    personas: ["eng", "prompt"],
    agentKinds: ["support-bot", "rag", "voice", "extraction", "tools-agent", "generative"],
    requirements: [["model"]],
    build: "built",
    scope: "project",
  },
  {
    id: "thumbs-down",
    origin: "pr",
    question: "Which of my agent's answers did reviewers mark down?",
    title: "Improve responses: thumbs-down traces",
    why: "Share of reviewer thumbs down, then the latest traces marked down. The widget reads reviewer annotations, not end-user feedback; the PR label says otherwise.",
    questionId: "answers",
    alsoAnswers: ["testset"],
    questionType: "matters",
    personas: ["expert", "qa"],
    agentKinds: ["support-bot", "rag", "voice", "extraction", "tools-agent", "generative"],
    requirements: [["annotations"]],
    build: "built",
    scope: "project",
  },
  {
    id: "lowest-scores",
    origin: "pr",
    question: "Which of my agent's answers scored worst?",
    title: "Improve responses: lowest-scoring evaluations",
    why: "The eight evaluation results with the lowest score, each linked to its trace.",
    questionId: "answers",
    alsoAnswers: ["testset"],
    questionType: "why",
    personas: ["expert", "qa"],
    agentKinds: ["support-bot", "rag", "voice", "extraction", "tools-agent", "generative"],
    requirements: [["evals"]],
    build: "built",
    scope: "project",
  },
  {
    id: "evaluation-coverage",
    origin: "pr",
    question: "How much of my traffic is evaluated?",
    title: "Set up evaluations: coverage per evaluator",
    why: "What each evaluator runs on, its pass rate, and the share of traces evaluated at all.",
    questionId: "answers",
    alsoAnswers: ["judges"],
    questionType: "matters",
    personas: ["qa"],
    agentKinds: ["support-bot", "rag", "voice", "extraction", "tools-agent", "generative"],
    requirements: [["evals"]],
    build: "built",
    scope: "project",
  },
  {
    id: "fd-throughput",
    origin: "pr",
    question: "How much did my agent handle, how fast, and with how many errors?",
    title: "Throughput, latency & errors",
    why: "Traces per bucket as bars, slowest-5% latency as a line and the error rate as a ribbon.",
    questionId: "used",
    alsoAnswers: ["fast", "failing"],
    questionType: "happened",
    personas: ["eng", "ops"],
    agentKinds: ["support-bot", "rag", "voice", "extraction", "tools-agent", "generative"],
    requirements: [["traces"]],
    build: "built",
    scope: "project",
  },
  {
    id: "fd-cost-efficiency",
    origin: "pr",
    question: "What does each successful trace of my agent cost?",
    title: "Cost efficiency",
    why: "Cost per successful trace, tokens in and out, and the five models that cost the most.",
    questionId: "spend",
    alsoAnswers: ["outcomecost"],
    questionType: "happened",
    personas: ["finance", "eng"],
    agentKinds: ["support-bot", "rag", "voice", "extraction", "tools-agent", "generative"],
    requirements: [["cost"], ["model"]],
    build: "built",
    scope: "project",
  },
  {
    id: "fd-failures",
    origin: "pr",
    question: "Which errors does my agent hit most, and where?",
    title: "Failure intelligence (also “Top error types”)",
    why: "Error spans grouped by exception or error type and operation, most frequent first. The same query backs the “Top error types” widget.",
    questionId: "failing",
    alsoAnswers: [],
    questionType: "matters",
    personas: ["eng", "ops"],
    agentKinds: ["support-bot", "rag", "voice", "extraction", "tools-agent", "generative"],
    requirements: [["errors"]],
    build: "built",
    scope: "project",
  },
  {
    id: "fd-quality",
    origin: "pr",
    question: "Is my agent's quality holding while errors move?",
    title: "Quality signal",
    why: "Evaluator pass rate over time, drawn against the trace error rate of the same buckets.",
    questionId: "answers",
    alsoAnswers: [],
    questionType: "changed",
    personas: ["qa", "product"],
    agentKinds: ["support-bot", "rag", "voice", "extraction", "tools-agent", "generative"],
    requirements: [["evals"]],
    build: "built",
    scope: "project",
  },
  {
    id: "fd-feedback",
    origin: "pr",
    question: "What do reviewers think of my agent's answers?",
    title: "User feedback",
    why: "Reviewer thumbs up and down, then the positive share over time. The widget reads reviewer annotations, not end-user feedback; the PR label says otherwise.",
    questionId: "answers",
    alsoAnswers: [],
    questionType: "happened",
    personas: ["qa", "expert"],
    agentKinds: ["support-bot", "rag", "voice", "extraction", "tools-agent", "generative"],
    requirements: [["annotations"]],
    build: "built",
    scope: "project",
  },
  {
    id: "fd-gateway",
    origin: "pr",
    question: "Which gateway keys spend the most?",
    title: "Gateway routing",
    why: "Gateway spend per virtual key (one key per app, team or customer), the five that spend the most.",
    questionId: "orgspend",
    alsoAnswers: ["acctcost"],
    questionType: "matters",
    personas: ["finance", "eng"],
    agentKinds: [],
    requirements: [["gateway"]],
    build: "built",
    scope: "org",
  },
  {
    id: "fd-coding-agents",
    origin: "pr",
    question: "What do my staff's coding agents cost, and do they succeed?",
    title: "Your coding agents",
    why: "Sessions, tokens, cost and success rate per coding agent, with its session trend.",
    questionId: "codingcost",
    alsoAnswers: [],
    questionType: "happened",
    personas: ["eng", "finance"],
    agentKinds: [],
    requirements: [["coding"]],
    build: "built",
    scope: "org",
  },
  {
    id: "ck-kpis",
    origin: "prototype",
    question: "Is my agent doing its job, and what does each success cost?",
    title: "This period",
    why: "Four numbers against the period before: how often my agent succeeds in its own terms (resolved conversations, correct documents, completed calls), how much my agent is used, the share of automatic checks that pass, and the cost of one success.",
    questionId: "finish",
    alsoAnswers: ["outcomecost", "used"],
    questionType: "changed",
    personas: ["leader", "product", "ops"],
    agentKinds: ["support-bot", "rag", "voice", "extraction", "tools-agent", "generative"],
    requirements: [["judge", "outcome"], ["evals"], ["cost"]],
    build: "feature",
    scope: "project",
  },
  {
    id: "ck-status",
    origin: "prototype",
    question: "Is my agent up right now?",
    title: "Status today",
    why: "My agent's errors and response time today, against a typical day of the same weekday.",
    questionId: "failing",
    alsoAnswers: ["fast"],
    questionType: "line",
    personas: ["eng", "ops"],
    agentKinds: ["support-bot", "rag", "voice", "extraction", "tools-agent", "generative"],
    requirements: [["errors"]],
    build: "logic",
    scope: "project",
  },
  {
    id: "ck-attention",
    origin: "prototype",
    question: "What is the one problem I should look at first this week?",
    title: "Needs attention",
    why: "Names the single biggest problem and links to its traces. The widget tries four things in order: the topic or customer whose pass rate fell most this week (if the fall is bigger than normal noise); the failure reason that grew most; an automatic grader that stopped agreeing with human reviewers; the step that fails most.",
    questionId: "answers",
    alsoAnswers: ["change"],
    questionType: "matters",
    personas: ["product", "ops", "eng"],
    agentKinds: ["support-bot", "rag", "voice", "extraction", "tools-agent", "generative"],
    requirements: [["evals"], ["labels", "customer", "topics"]],
    build: "logic",
    scope: "project",
  },
  {
    id: "ck-top-ask",
    origin: "prototype",
    question: "What do users ask for most that my agent cannot do?",
    title: "Top request it cannot serve",
    why: "The topic users ask for most that my agent has no way to serve, how often, and one example request. An automatic grader marks these conversations.",
    questionId: "asking",
    alsoAnswers: [],
    questionType: "matters",
    personas: ["product"],
    agentKinds: ["support-bot", "rag", "voice", "extraction", "tools-agent", "generative"],
    requirements: [["judge"], ["topics"]],
    build: "logic",
    scope: "project",
  },
  {
    id: "ck-trend",
    origin: "prototype",
    question: "Does my agent resolve more conversations each day?",
    title: "Conversations resolved per day",
    why: "Share of closed conversations that went well, per day, with prompt, model and deploy changes marked on the line.",
    questionId: "finish",
    alsoAnswers: [],
    questionType: "changed",
    personas: ["product", "ops", "leader"],
    agentKinds: ["support-bot", "rag", "extraction", "tools-agent", "vendor", "regulated"],
    requirements: [["judge", "outcome"]],
    build: "logic",
    scope: "project",
  },
  {
    id: "up-errors",
    origin: "prototype",
    question: "Which errors does my agent hit each day, and did a change start them?",
    title: "Errors per day",
    why: "Failed traces per day split by error type, the error rate as a line, and prompt, model and deploy changes marked. A spike that starts at a change points to that change.",
    questionId: "failing",
    alsoAnswers: [],
    questionType: "why",
    personas: ["eng"],
    agentKinds: ["support-bot", "rag", "voice", "extraction", "generative", "vendor", "regulated"],
    requirements: [["errors"]],
    build: "ready",
    scope: "project",
  },
  {
    id: "up-where-fails",
    origin: "prototype",
    question: "Which step or tool in my agent fails most?",
    title: "Failing steps",
    why: "Each step and tool call: how often it fails, and how often my agent did not recover (no later retry or fallback fixed it). Fix the one with the most unrecovered failures.",
    questionId: "failing",
    alsoAnswers: ["tools"],
    questionType: "matters",
    personas: ["eng"],
    agentKinds: ["support-bot", "rag", "voice", "extraction", "generative", "vendor", "regulated"],
    requirements: [["steps"], ["errors"]],
    build: "ready",
    scope: "project",
  },
  {
    id: "up-failing-traces",
    origin: "prototype",
    question: "Which of my agent's traces failed or ran slowest?",
    title: "Latest failures",
    why: "The traces that failed or ran slowest in this period. Each opens to the step that broke.",
    questionId: "trace",
    alsoAnswers: ["failing"],
    questionType: "happened",
    personas: ["eng", "ops"],
    agentKinds: ["support-bot", "rag", "voice", "extraction", "tools-agent", "generative"],
    requirements: [["traces"]],
    build: "ready",
    scope: "project",
  },
  {
    id: "up-step-latency",
    origin: "prototype",
    question: "Which step makes my agent slow?",
    title: "Slowest steps",
    why: "Typical and slowest-5% time for each step of a trace. The step that holds most of the slow time is the one to shorten.",
    questionId: "fast",
    alsoAnswers: [],
    questionType: "why",
    personas: ["eng"],
    agentKinds: ["support-bot", "rag", "voice", "extraction", "tools-agent", "generative"],
    requirements: [["steps"]],
    build: "ready",
    scope: "project",
  },
  {
    id: "up-loops",
    origin: "prototype",
    question: "Does my agent go in circles?",
    title: "Loops and retries",
    why: "Traces where my agent calls the same tool with the same input 3 or more times, or retries a step, and what the repeats cost.",
    questionId: "tools",
    alsoAnswers: ["spend"],
    questionType: "happened",
    personas: ["eng"],
    agentKinds: ["support-bot", "rag", "voice", "extraction", "tools-agent", "generative"],
    requirements: [["steps"], ["cost"]],
    build: "logic",
    scope: "project",
  },
  {
    id: "ans-outcomes",
    origin: "prototype",
    question: "How did my agent's conversations end?",
    title: "How conversations ended",
    why: "Closed conversations per day by how they ended: resolved, misunderstood, could not do it, refused without reason, handed to a person. An outcome my app sends wins; otherwise an automatic grader decides.",
    questionId: "finish",
    alsoAnswers: [],
    questionType: "happened",
    personas: ["ops", "product"],
    agentKinds: [
      "support-bot",
      "voice",
      "extraction",
      "tools-agent",
      "generative",
      "vendor",
      "regulated",
    ],
    requirements: [["judge", "outcome"], ["thread"]],
    build: "logic",
    scope: "project",
  },
  {
    id: "ans-evaluators",
    origin: "prototype",
    question: "Are my agent's checks passing?",
    title: "Checks passing",
    why: "Each evaluator's daily pass rate against its threshold line. The failures of an evaluator under its line open from the card.",
    questionId: "answers",
    alsoAnswers: [],
    questionType: "line",
    personas: ["qa", "eng"],
    agentKinds: ["support-bot", "rag", "voice", "extraction", "tools-agent", "generative"],
    requirements: [["evals"]],
    build: "ready",
    scope: "project",
  },
  {
    id: "ans-topics",
    origin: "prototype",
    question: "Which topics does my agent handle well, and which badly?",
    title: "Topics people ask about",
    why: "For each topic users ask about: how many conversations, the share that went well (graded on a sample), and requests my agent could not serve.",
    questionId: "asking",
    alsoAnswers: ["answers"],
    questionType: "compare",
    personas: ["product", "ops", "expert"],
    agentKinds: ["support-bot", "rag", "voice", "extraction", "tools-agent", "generative"],
    requirements: [["topics"], ["evals", "judge"]],
    build: "logic",
    scope: "project",
  },
  {
    id: "ans-idk",
    origin: "prototype",
    question: "On which topics does my agent fail to answer?",
    title: "Unanswered, by topic",
    why: "Share of conversations per topic where my agent gave no answer or refused. Add content or tools for the topics at the top.",
    questionId: "answers",
    alsoAnswers: ["grounded"],
    questionType: "matters",
    personas: ["expert", "product"],
    agentKinds: ["support-bot", "rag", "voice", "vendor", "regulated"],
    requirements: [["judge"], ["topics"]],
    build: "logic",
    scope: "project",
  },
  {
    id: "ans-review",
    origin: "prototype",
    question: "Which conversations should a person review?",
    title: "To review",
    why: "A queue from the last 3 days: conversations that failed or were flagged, plus 1 in 5 picked at random as a check, each with the grader's reason. Bad ones go into a test dataset.",
    questionId: "testset",
    alsoAnswers: ["judges"],
    questionType: "matters",
    personas: ["expert", "qa"],
    agentKinds: ["support-bot", "rag", "voice", "extraction", "tools-agent", "generative"],
    requirements: [["evals", "thumbs"]],
    build: "ready",
    scope: "project",
  },
  {
    id: "ask-cannot",
    origin: "prototype",
    question: "What do users ask for that my agent cannot do?",
    title: "Requests it cannot serve",
    why: "Requests per topic that an automatic grader marked as out of reach: my agent has no tool or content for them. These are product gaps, not bugs.",
    questionId: "asking",
    alsoAnswers: [],
    questionType: "matters",
    personas: ["product"],
    agentKinds: ["support-bot", "rag", "voice", "extraction", "tools-agent", "generative"],
    requirements: [["judge"], ["topics"]],
    build: "logic",
    scope: "project",
  },
  {
    id: "ask-rising",
    origin: "prototype",
    question: "Which topics do users ask about more than before?",
    title: "Rising and new topics",
    why: "Topics whose share of conversations grew against the previous period of the same length, and topics that are new.",
    questionId: "asking",
    alsoAnswers: [],
    questionType: "changed",
    personas: ["product", "ops"],
    agentKinds: ["support-bot", "rag", "voice", "extraction", "tools-agent", "generative"],
    requirements: [["topics"]],
    build: "logic",
    scope: "project",
  },
  {
    id: "ask-again",
    origin: "prototype",
    question: "Do users have to ask again because my agent's first answer missed?",
    title: "Asked again",
    why: "Share of conversations per day where the user rephrased after a missed answer, and how many users came back.",
    questionId: "happy",
    alsoAnswers: ["comeback"],
    questionType: "happened",
    personas: ["product", "expert"],
    agentKinds: ["support-bot", "rag", "voice", "extraction", "tools-agent", "generative"],
    requirements: [["thread"], ["user"], ["judge"]],
    build: "logic",
    scope: "project",
  },
  {
    id: "ship-verdict",
    origin: "prototype",
    question: "Can the new version of my agent ship?",
    title: "New version vs current",
    why: "The new version's test runs against the current version's on the same scenarios: pass rate, the scenarios that got worse by more than their normal flakiness, and the change in cost and response time. Ship when nothing got worse.",
    questionId: "change",
    alsoAnswers: ["tests"],
    questionType: "prove",
    personas: ["qa", "eng", "product"],
    agentKinds: ["support-bot", "rag", "voice", "extraction", "tools-agent", "generative"],
    requirements: [["scenarios", "experiments"]],
    build: "logic",
    scope: "project",
  },
  {
    id: "ship-compare",
    origin: "prototype",
    question: "How do my last test runs compare?",
    title: "Test runs compared",
    why: "The last five test runs side by side against a baseline I choose: scenarios passed, criteria met, grader scores, cost and typical reply time.",
    questionId: "tests",
    alsoAnswers: ["less"],
    questionType: "compare",
    personas: ["qa", "prompt", "eng"],
    agentKinds: [
      "support-bot",
      "rag",
      "extraction",
      "tools-agent",
      "generative",
      "vendor",
      "regulated",
    ],
    requirements: [["experiments", "scenarios"]],
    build: "ready",
    scope: "project",
  },
  {
    id: "ship-suites",
    origin: "prototype",
    question: "Do my test suites keep passing?",
    title: "Test pass rate",
    why: "Each suite's pass rate over time, CI runs apart from local runs. A suite whose CI line drops needs a look.",
    questionId: "tests",
    alsoAnswers: [],
    questionType: "changed",
    personas: ["qa"],
    agentKinds: ["support-bot", "voice", "tools-agent", "generative", "vendor", "regulated"],
    requirements: [["scenarios"]],
    build: "ready",
    scope: "project",
  },
  {
    id: "ship-flaky",
    origin: "prototype",
    question: "Which of my tests flip between pass and fail?",
    title: "Flaky tests",
    why: "The last ten runs of each test scenario as a strip of passes and fails. A scenario that flips cannot be trusted: fix it or set it aside.",
    questionId: "tests",
    alsoAnswers: ["testset"],
    questionType: "matters",
    personas: ["qa"],
    agentKinds: ["support-bot", "rag", "voice", "tools-agent", "vendor"],
    requirements: [["scenarios"]],
    build: "logic",
    scope: "project",
  },
  {
    id: "ship-rollout",
    origin: "prototype",
    question: "Did my agent get worse in production after my last change?",
    title: "Production before and after",
    why: "Up to 7 days after the last prompt, model or deploy change, against the same weekdays a week earlier: pass rate, errors, response time and cost. The topic mix is evened out, so a change in what users ask does not look like a regression.",
    questionId: "change",
    alsoAnswers: [],
    questionType: "changed",
    personas: ["eng", "product", "prompt"],
    agentKinds: ["support-bot", "rag", "generative", "vendor", "regulated"],
    requirements: [
      ["prompts", "deploys"],
      ["evals", "outcome"],
    ],
    build: "logic",
    scope: "project",
  },
  {
    id: "ship-models",
    origin: "prototype",
    question: "Which model gives my agent the same quality for less?",
    title: "Models compared",
    why: "From test runs that compared models: pass rate, cost and slowest-5% reply time for each model or setup. Pick the cheapest one that keeps quality.",
    questionId: "less",
    alsoAnswers: [],
    questionType: "compare",
    personas: ["prompt", "eng"],
    agentKinds: ["voice", "extraction", "tools-agent"],
    requirements: [["experiments"], ["cost"]],
    build: "ready",
    scope: "project",
  },
  {
    id: "cost-verdict",
    origin: "prototype",
    question: "Will I stay within my AI budget this month?",
    title: "Spend",
    why: "Spend so far this month (production, failed runs, evaluations and simulations), the forecast to month end at the last 7 days' pace against my budget, and the cost of one resolved conversation.",
    questionId: "spend",
    alsoAnswers: ["outcomecost"],
    questionType: "line",
    personas: ["finance", "leader"],
    agentKinds: ["support-bot", "rag", "voice", "extraction", "tools-agent", "generative"],
    requirements: [["cost"], ["budget"]],
    build: "feature",
    scope: "project",
  },
  {
    id: "cost-by-source",
    origin: "prototype",
    question: "How much of my AI spend goes on testing, and how much on production?",
    title: "Production vs testing",
    why: "Spend split by where it came from: production traffic, evaluations and simulations.",
    questionId: "evalcost",
    alsoAnswers: [],
    questionType: "compare",
    personas: ["finance", "qa"],
    agentKinds: ["support-bot", "rag", "voice", "extraction", "tools-agent", "generative"],
    requirements: [["cost"]],
    build: "ready",
    scope: "project",
  },
  {
    id: "cost-by-model",
    origin: "prototype",
    question: "Which model costs me the most?",
    title: "Spend by model",
    why: "Spend per model, with its share of traffic. A model that costs more than its share of traffic is the one to move off.",
    questionId: "spend",
    alsoAnswers: [],
    questionType: "matters",
    personas: ["finance", "eng", "prompt"],
    agentKinds: ["support-bot", "rag", "tools-agent", "generative", "vendor"],
    requirements: [["cost"], ["model"]],
    build: "ready",
    scope: "project",
  },
  {
    id: "cost-waste",
    origin: "prototype",
    question: "How much of my AI spend is wasted?",
    title: "Wasted spend",
    why: "Spend on failed runs my agent never recovered from, on retries, and on the repeated part of loops, each counted once, as a share of production spend. Fix the biggest line first.",
    questionId: "spend",
    alsoAnswers: ["costok"],
    questionType: "matters",
    personas: ["eng", "finance"],
    agentKinds: ["support-bot", "rag", "voice", "extraction", "tools-agent", "generative"],
    requirements: [["cost"], ["steps"]],
    build: "logic",
    scope: "project",
  },
  {
    id: "cost-by-segment",
    origin: "prototype",
    question: "Which of my customers or teams cost the most?",
    title: "Spend by customer",
    why: "Spend per customer, team or other group I choose from trace metadata, top ten. Calls that carry no group get their own row.",
    questionId: "acctcost",
    alsoAnswers: [],
    questionType: "matters",
    personas: ["finance", "product"],
    agentKinds: ["generative", "vendor"],
    requirements: [["cost"], ["customer", "labels"]],
    build: "ready",
    scope: "project",
  },
  {
    id: "att-share",
    origin: "prototype",
    question: "Which of my customers use my agent most?",
    title: "Conversations by customer",
    why: "Conversations (or documents, or calls) per customer in the last 7 days, and each customer's share of the total.",
    questionId: "howmany",
    alsoAnswers: ["used"],
    questionType: "compare",
    personas: ["product", "ops"],
    agentKinds: [
      "support-bot",
      "rag",
      "voice",
      "extraction",
      "tools-agent",
      "generative",
      "vendor",
    ],
    requirements: [["customer", "labels"]],
    build: "ready",
    scope: "project",
  },
  {
    id: "att-table",
    origin: "prototype",
    question: "How does my agent do for each of my customers?",
    title: "All customers, last 7 days",
    why: "One row per customer: volume, pass rate and its trend, AI cost and cost per conversation. Each row has a read-only link I can share with that customer.",
    questionId: "answers",
    alsoAnswers: ["acctcost"],
    questionType: "compare",
    personas: ["ops", "product"],
    agentKinds: ["voice", "extraction", "generative", "vendor"],
    requirements: [["customer", "labels"], ["evals"], ["cost"]],
    build: "ready",
    scope: "project",
  },
  {
    id: "att-change",
    origin: "prototype",
    question: "Did my last change break my agent for any customer?",
    title: "After the last change",
    why: "Each customer's pass rate in the 7 days after the last prompt, model or config change, against the 7 days before.",
    questionId: "change",
    alsoAnswers: [],
    questionType: "compare",
    personas: ["eng", "ops"],
    agentKinds: ["extraction", "generative", "vendor"],
    requirements: [["customer", "labels"], ["evals"], ["prompts", "deploys"]],
    build: "logic",
    scope: "project",
  },
  {
    id: "so-verdict",
    origin: "prototype",
    question: "Can risk sign this release of my agent off?",
    title: "Sign-off status",
    why: "This week against last week: what each safety control checked, items flagged but not blocked, review items pending, and how well each automatic grader agrees with human reviewers.",
    questionId: "attacked",
    alsoAnswers: ["pii", "rules"],
    questionType: "prove",
    personas: ["risk"],
    agentKinds: [
      "support-bot",
      "rag",
      "voice",
      "extraction",
      "tools-agent",
      "generative",
      "regulated",
    ],
    requirements: [["guardrails"], ["evals"]],
    build: "logic",
    scope: "project",
  },
  {
    id: "so-rubric",
    origin: "prototype",
    question: "Does my agent pass each policy check?",
    title: "Policy checks",
    why: "Pass rate per policy criterion (accuracy, completeness, made-up facts, inappropriate content), with an error margin, against the minimum I set.",
    questionId: "rules",
    alsoAnswers: [],
    questionType: "line",
    personas: ["risk", "qa"],
    agentKinds: [
      "support-bot",
      "rag",
      "voice",
      "extraction",
      "tools-agent",
      "generative",
      "regulated",
    ],
    requirements: [["evals"]],
    build: "ready",
    scope: "project",
  },
  {
    id: "so-queue",
    origin: "prototype",
    question: "Is the human review queue under control?",
    title: "Review queue",
    why: "Items flagged for review plus random checks: how many reviewers have checked, how many wait, and how long a review takes.",
    questionId: "rules",
    alsoAnswers: ["judges"],
    questionType: "prove",
    personas: ["risk", "ops", "expert"],
    agentKinds: [
      "support-bot",
      "rag",
      "voice",
      "extraction",
      "tools-agent",
      "generative",
      "regulated",
    ],
    requirements: [["annotations"]],
    build: "ready",
    scope: "project",
  },
  {
    id: "so-agreement",
    origin: "prototype",
    question: "Do my automatic graders agree with human reviewers?",
    title: "Judges vs reviewers",
    why: "Each week, an agreement score between each grader and human reviewers on a random sample (0.8 or more is good). A grader whose score falls has drifted.",
    questionId: "judges",
    alsoAnswers: [],
    questionType: "compare",
    personas: ["qa", "expert"],
    agentKinds: ["support-bot", "rag", "voice", "extraction", "tools-agent", "generative"],
    requirements: [["evals"], ["annotations"]],
    build: "logic",
    scope: "project",
  },
  {
    id: "so-changes",
    origin: "prototype",
    question: "Who changed my agent's prompts, models and graders, and when?",
    title: "Change log",
    why: "A log of every prompt version, model, evaluator and setting change, with who made it and when. The audit trail for each release.",
    questionId: "change",
    alsoAnswers: [],
    questionType: "prove",
    personas: ["risk"],
    agentKinds: [
      "support-bot",
      "rag",
      "voice",
      "extraction",
      "tools-agent",
      "generative",
      "regulated",
    ],
    requirements: [["history"]],
    build: "logic",
    scope: "project",
  },
  {
    id: "voice-turn-latency",
    origin: "prototype",
    question: "Which stage makes my voice agent slow to reply?",
    title: "Reply time by stage",
    why: "Slowest-5% time per reply, split into its stages: speech to text, thinking, and text to speech.",
    questionId: "fast",
    alsoAnswers: [],
    questionType: "why",
    personas: ["eng"],
    agentKinds: ["voice"],
    requirements: [["voice"]],
    build: "logic",
    scope: "project",
  },
  {
    id: "voice-task-success",
    origin: "prototype",
    question: "Do my voice agent's calls get the job done, in every language?",
    title: "Task success",
    why: "Share of calls that an automatic check marks as task done, per language. Calls where no task applies are left out.",
    questionId: "finish",
    alsoAnswers: [],
    questionType: "compare",
    personas: ["ops", "product"],
    agentKinds: ["voice"],
    requirements: [["judge", "outcome"], ["labels"]],
    build: "feature",
    scope: "project",
  },
  {
    id: "voice-call-health",
    origin: "prototype",
    question: "Which calls drop, or have my agent repeat itself?",
    title: "Calls not ended and repeated sentences",
    why: "Per 1,000 calls: calls that dropped before an ending, and calls where my agent repeated a sentence.",
    questionId: "failing",
    alsoAnswers: [],
    questionType: "happened",
    personas: ["ops", "eng"],
    agentKinds: ["voice"],
    requirements: [["voice"], ["thread"]],
    build: "logic",
    scope: "project",
  },
  {
    id: "voice-cost-per-call",
    origin: "prototype",
    question: "What does one call with my voice agent cost, speech included?",
    title: "Cost per call with speech vendors",
    why: "LLM cost per call from traces, plus speech to text and text to speech at the speech vendor's rate.",
    questionId: "convcost",
    alsoAnswers: [],
    questionType: "happened",
    personas: ["finance"],
    agentKinds: ["voice"],
    requirements: [["cost"], ["vendor"]],
    build: "feature",
    scope: "project",
  },
  {
    id: "rag-failure-source",
    origin: "prototype",
    question: "When my assistant fails, is the search or the answer at fault?",
    title: "Retrieval or generation",
    why: "Failed traces split by cause: the search found wrong or no passages, or the answer was wrong although the passages were good. Tool errors are shown apart.",
    questionId: "grounded",
    alsoAnswers: [],
    questionType: "why",
    personas: ["eng", "expert"],
    agentKinds: ["rag"],
    requirements: [["rag"], ["judge"]],
    build: "logic",
    scope: "project",
  },
  {
    id: "rag-empty-retrieval",
    origin: "prototype",
    question: "How often does my assistant's search find nothing?",
    title: "Empty retrieval rate",
    why: "Share of questions per day whose search step returned no documents.",
    questionId: "grounded",
    alsoAnswers: [],
    questionType: "happened",
    personas: ["eng", "expert"],
    agentKinds: ["rag"],
    requirements: [["rag"]],
    build: "ready",
    scope: "project",
  },
  {
    id: "rag-dataset-versions",
    origin: "prototype",
    question: "Does my test set still match what users ask?",
    title: "Correctness by dataset version",
    why: "The correctness score of each test-set version, and the same score reweighted to the topic mix of real traffic. A large gap means the test set is out of date.",
    questionId: "testset",
    alsoAnswers: [],
    questionType: "compare",
    personas: ["qa", "expert"],
    agentKinds: ["rag"],
    requirements: [["experiments"], ["topics"]],
    build: "logic",
    scope: "project",
  },
  {
    id: "ext-field-accuracy",
    origin: "prototype",
    question: "Which fields and document types does my agent get wrong?",
    title: "Accuracy per field and document type",
    why: "Share of documents with each field correct, per document type, from an automatic check.",
    questionId: "answers",
    alsoAnswers: [],
    questionType: "matters",
    personas: ["expert", "ops"],
    agentKinds: ["extraction"],
    requirements: [["fields"], ["labels"]],
    build: "logic",
    scope: "project",
  },
  {
    id: "ext-precision-recall",
    origin: "prototype",
    question: "Does the new version of my agent find more fields, and get them right?",
    title: "Field accuracy per test run",
    why: "For each of the last 12 test runs on labelled documents: the share of extracted fields that are right, and the share of real fields my agent found.",
    questionId: "tests",
    alsoAnswers: [],
    questionType: "compare",
    personas: ["qa", "eng"],
    agentKinds: ["extraction"],
    requirements: [["experiments"], ["fields"]],
    build: "logic",
    scope: "project",
  },
  {
    id: "ext-human-review",
    origin: "prototype",
    question: "How many documents does my agent send to a person?",
    title: "Sent to human review",
    why: "Share of documents sent to human review per day, and the document type sent most.",
    questionId: "finish",
    alsoAnswers: [],
    questionType: "changed",
    personas: ["ops"],
    agentKinds: ["extraction"],
    requirements: [["outcome"]],
    build: "ready",
    scope: "project",
  },
  {
    id: "ext-cost-per-doc",
    origin: "prototype",
    question: "What does one document cost my agent to process?",
    title: "Cost per document",
    why: "Production cost per document, overall and per model, with model changes marked.",
    questionId: "convcost",
    alsoAnswers: [],
    questionType: "happened",
    personas: ["finance", "eng"],
    agentKinds: ["extraction"],
    requirements: [["cost"], ["model"]],
    build: "ready",
    scope: "project",
  },
  {
    id: "tools-error-rate",
    origin: "prototype",
    question: "Which of my agent's tools fail, and does my agent recover?",
    title: "Tool error rate",
    why: "Error rate per tool, and the share of those errors a later step fixed.",
    questionId: "tools",
    alsoAnswers: ["failing"],
    questionType: "matters",
    personas: ["eng"],
    agentKinds: ["tools-agent"],
    requirements: [["steps"], ["errors"]],
    build: "logic",
    scope: "project",
  },
  {
    id: "tools-wrong-tool",
    origin: "prototype",
    question: "Does my agent pick the right tool first?",
    title: "Wrong tool rate",
    why: "Share of tasks per day where an automatic grader marks the first tool chosen as wrong.",
    questionId: "tools",
    alsoAnswers: [],
    questionType: "line",
    personas: ["eng", "prompt"],
    agentKinds: ["tools-agent"],
    requirements: [["steps"], ["evals"]],
    build: "logic",
    scope: "project",
  },
  {
    id: "gen-acceptance",
    origin: "prototype",
    question: "Do users keep, edit or redo what my agent writes?",
    title: "Accepted, edited or regenerated",
    why: "Per day: the share of generated outputs that users accepted, edited, regenerated or ignored.",
    questionId: "finish",
    alsoAnswers: ["happy"],
    questionType: "happened",
    personas: ["product"],
    agentKinds: ["generative"],
    requirements: [["thumbs"]],
    build: "ready",
    scope: "project",
  },
  {
    id: "gen-dropoff",
    origin: "prototype",
    question: "At which step do users drop what my agent wrote?",
    title: "Drop-off after generation",
    why: "How many outputs were generated, shown, used and kept. The biggest drop is the step to fix.",
    questionId: "finish",
    alsoAnswers: [],
    questionType: "matters",
    personas: ["product"],
    agentKinds: ["generative"],
    requirements: [["thumbs"], ["outcome"]],
    build: "logic",
    scope: "project",
  },
  {
    id: "users",
    origin: "proposed",
    question: "How many users does my agent have, and who are the heaviest users?",
    title: "",
    why: "Active users per day and the heaviest users. The denominator for every per-user number.",
    questionId: "howmany",
    alsoAnswers: [],
    questionType: "happened",
    personas: ["product", "leader"],
    agentKinds: ["support-bot", "rag", "voice", "extraction", "tools-agent", "generative"],
    requirements: [["user"]],
    build: "ready",
    scope: "project",
  },
  {
    id: "return",
    origin: "proposed",
    question: "Do users come back to my agent?",
    title: "",
    why: "Share of users who come back the next week, by the week they started. Falling return means my agent did not help the first time.",
    questionId: "comeback",
    alsoAnswers: [],
    questionType: "changed",
    personas: ["product", "leader"],
    agentKinds: ["support-bot", "rag", "voice", "tools-agent", "generative"],
    requirements: [["user"]],
    build: "logic",
    scope: "project",
  },
  {
    id: "cost-conv",
    origin: "proposed",
    question: "What does one conversation with my agent cost?",
    title: "",
    why: "Cost per conversation, its spread, and the most expensive conversations. The unit a business compares with the cost of a person.",
    questionId: "convcost",
    alsoAnswers: [],
    questionType: "happened",
    personas: ["finance", "product"],
    agentKinds: ["support-bot", "rag", "voice", "tools-agent"],
    requirements: [["cost"], ["thread"]],
    build: "ready",
    scope: "project",
  },
  {
    id: "cost-outcome",
    origin: "proposed",
    question: "What does each correct outcome of my agent cost?",
    title: "",
    why: "Cost divided by successful tasks, over time. The number falls when quality rises or cost drops.",
    questionId: "outcomecost",
    alsoAnswers: [],
    questionType: "changed",
    personas: ["leader", "finance", "product"],
    agentKinds: ["support-bot", "rag", "voice", "extraction", "tools-agent", "generative"],
    requirements: [["cost"], ["judge", "outcome"]],
    build: "logic",
    scope: "project",
  },
  {
    id: "work-saved",
    origin: "proposed",
    question: "How much manual work does my agent save?",
    title: "",
    why: "Successful tasks times my own value of one task. Shown only when I set that value; never in a default template.",
    questionId: "manual",
    alsoAnswers: [],
    questionType: "happened",
    personas: ["leader", "ops"],
    agentKinds: ["support-bot", "rag", "voice", "extraction", "tools-agent", "generative"],
    requirements: [["judge", "outcome"], ["valueset"]],
    build: "feature",
    scope: "project",
  },
  {
    id: "task-drop",
    origin: "proposed",
    question: "At which step do my agent's tasks drop off?",
    title: "",
    why: "How many tasks reach each step the customer defines (asked, answered, acted, converted).",
    questionId: "finish",
    alsoAnswers: [],
    questionType: "matters",
    personas: ["product", "leader"],
    agentKinds: ["support-bot", "rag", "voice", "extraction", "tools-agent", "generative"],
    requirements: [["outcome"]],
    build: "logic",
    scope: "project",
  },
  {
    id: "user-thumbs",
    origin: "proposed",
    question: "Which answers did users rate badly?",
    title: "",
    why: "End-user thumbs down per day and the latest rated traces, from the thumbs events the app sends.",
    questionId: "happy",
    alsoAnswers: [],
    questionType: "matters",
    personas: ["product", "ops"],
    agentKinds: ["support-bot", "rag", "voice", "tools-agent", "generative"],
    requirements: [["thumbs"]],
    build: "logic",
    scope: "project",
  },
  {
    id: "grounded",
    origin: "proposed",
    question: "How often does my agent make things up?",
    title: "",
    why: "Share of answers a faithfulness check fails, per day and per topic.",
    questionId: "grounded",
    alsoAnswers: [],
    questionType: "changed",
    personas: ["eng", "expert", "qa"],
    agentKinds: ["rag", "support-bot"],
    requirements: [["evals"], ["rag"]],
    build: "ready",
    scope: "project",
  },
  {
    id: "pii",
    origin: "proposed",
    question: "Is personal data leaking through my agent?",
    title: "",
    why: "Personal data found in inputs and outputs per day, and what was blocked.",
    questionId: "pii",
    alsoAnswers: [],
    questionType: "line",
    personas: ["risk"],
    agentKinds: ["support-bot", "rag", "voice", "extraction", "tools-agent", "generative"],
    requirements: [["guardrails", "evals"]],
    build: "ready",
    scope: "project",
  },
  {
    id: "attacks",
    origin: "proposed",
    question: "Is anyone trying to break my agent?",
    title: "",
    why: "Prompt-injection and jailbreak attempts per day, and how many got through.",
    questionId: "attacked",
    alsoAnswers: [],
    questionType: "line",
    personas: ["risk", "eng"],
    agentKinds: ["support-bot", "rag", "voice", "extraction", "tools-agent", "generative"],
    requirements: [["guardrails", "evals"]],
    build: "ready",
    scope: "project",
  },
  {
    id: "off-scope",
    origin: "proposed",
    question: "Does my agent stay on brand and in scope?",
    title: "",
    why: "Share of answers that break a scope, tone or policy check, with examples.",
    questionId: "rules",
    alsoAnswers: [],
    questionType: "line",
    personas: ["product", "risk"],
    agentKinds: ["support-bot", "rag", "voice", "extraction", "tools-agent", "generative"],
    requirements: [["evals"]],
    build: "ready",
    scope: "project",
  },
  {
    id: "data-health",
    origin: "proposed",
    question: "Is my data complete?",
    title: "",
    why: "Share of traces that carry model, cost, user, conversation, labels and outcome. Each gap names what to send and the widgets it unlocks.",
    questionId: "arriving",
    alsoAnswers: [],
    questionType: "matters",
    personas: ["eng"],
    agentKinds: ["support-bot", "rag", "voice", "extraction", "tools-agent", "generative"],
    requirements: [["traces"]],
    build: "logic",
    scope: "project",
  },
  {
    id: "noise",
    origin: "proposed",
    question: "Which of my traces are noise?",
    title: "",
    why: "Test, health-check and duplicate traces that inflate volume and the bill, by source.",
    questionId: "arriving",
    alsoAnswers: [],
    questionType: "matters",
    personas: ["eng", "finance"],
    agentKinds: ["support-bot", "rag", "voice", "extraction", "tools-agent", "generative"],
    requirements: [["traces"]],
    build: "logic",
    scope: "project",
  },
  {
    id: "cost-accuracy",
    origin: "proposed",
    question: "Are my cost figures complete?",
    title: "",
    why: "Traces with a model but no price, and models with no known price. Missing cost understates spend.",
    questionId: "costok",
    alsoAnswers: [],
    questionType: "line",
    personas: ["finance", "eng"],
    agentKinds: ["support-bot", "rag", "voice", "extraction", "tools-agent", "generative"],
    requirements: [["model"]],
    build: "logic",
    scope: "project",
  },
  {
    id: "inventory",
    origin: "proposed",
    question: "Which agents run here, and who owns them?",
    title: "",
    why: "Every project, service and agent seen in traces, with owner and last activity.",
    questionId: "inventory",
    alsoAnswers: [],
    questionType: "happened",
    personas: ["risk", "leader"],
    agentKinds: [],
    requirements: [["projects"]],
    build: "logic",
    scope: "org",
  },
  {
    id: "ai-tools",
    origin: "proposed",
    question: "Which AI tools do my staff use?",
    title: "",
    why: "Staff and teams per AI tool, from coding-agent and gateway traffic.",
    questionId: "inventory",
    alsoAnswers: [],
    questionType: "happened",
    personas: ["finance", "leader", "risk"],
    agentKinds: [],
    requirements: [["coding", "gateway"]],
    build: "logic",
    scope: "org",
  },
  {
    id: "seats",
    origin: "proposed",
    question: "Which AI seats bought for my staff sit unused?",
    title: "",
    why: "Seats bought minus seats assigned, per vendor pool. Counts only paid, per-person pools, as the governance cost screen does.",
    questionId: "codingcost",
    alsoAnswers: [],
    questionType: "matters",
    personas: ["finance"],
    agentKinds: [],
    requirements: [["seats"]],
    build: "feature",
    scope: "org",
  },
  {
    id: "tool-access",
    origin: "proposed",
    question: "Which tools does each of my agents use?",
    title: "",
    why: "Tools seen in each agent's traces. LangWatch sees use, not permissions.",
    questionId: "access",
    alsoAnswers: [],
    questionType: "happened",
    personas: ["risk", "eng"],
    agentKinds: [],
    requirements: [["steps"]],
    build: "logic",
    scope: "org",
  },
  {
    id: "standard",
    origin: "proposed",
    question: "Is every one of my agents held to the same checks?",
    title: "",
    why: "For each project: which evaluators and scenarios run, and its pass rate against the org floor.",
    questionId: "standard",
    alsoAnswers: [],
    questionType: "compare",
    personas: ["risk", "leader"],
    agentKinds: [],
    requirements: [["evals"], ["projects"]],
    build: "logic",
    scope: "org",
  },
  {
    id: "org-spend",
    origin: "proposed",
    question: "What does each team and app spend?",
    title: "",
    why: "Spend per project and team, month to date.",
    questionId: "orgspend",
    alsoAnswers: [],
    questionType: "matters",
    personas: ["finance", "leader"],
    agentKinds: [],
    requirements: [["cost"], ["projects"]],
    build: "ready",
    scope: "org",
  },
  {
    id: "lw-value",
    origin: "proposed",
    question: "What has LangWatch caught for me?",
    title: "",
    why: "Failures found, regressions blocked before release and alerts sent this month.",
    questionId: "value",
    alsoAnswers: [],
    questionType: "happened",
    personas: ["leader", "finance"],
    agentKinds: [],
    requirements: [["traces"], ["evals"]],
    build: "logic",
    scope: "org",
  },
  {
    id: "me-burn-summary",
    origin: "prototype",
    question: "What have my coding agents cost this period, and am I on pace?",
    title: "Burn summary",
    why: "Spend and tokens for the period, this week's pace, and how often I hit rate limits.",
    questionId: "spend",
    alsoAnswers: [],
    questionType: "changed",
    personas: ["eng"],
    agentKinds: ["coding"],
    requirements: [["coding"]],
    build: "logic",
    scope: "project",
  },
  {
    id: "me-expensive-sessions",
    origin: "prototype",
    question: "Which of my coding sessions cost the most?",
    title: "Most expensive sessions",
    why: "My most expensive sessions, ranked. Each one opens its session.",
    questionId: "spend",
    alsoAnswers: [],
    questionType: "matters",
    personas: ["eng"],
    agentKinds: ["coding"],
    requirements: [["coding"]],
    build: "ready",
    scope: "project",
  },
  {
    id: "me-by-pr",
    origin: "prototype",
    question: "Which pull requests did my coding tokens go to?",
    title: "Where it went, by pull request",
    why: "Tokens and cost per pull request.",
    questionId: "spend",
    alsoAnswers: ["outcomecost"],
    questionType: "matters",
    personas: ["eng"],
    agentKinds: ["coding"],
    requirements: [["coding"], ["prs"]],
    build: "logic",
    scope: "project",
  },
  {
    id: "me-spend-by-model",
    origin: "prototype",
    question: "Which models do my coding agents spend on?",
    title: "Spend by model",
    why: "My coding-agent cost per model, per day.",
    questionId: "spend",
    alsoAnswers: [],
    questionType: "matters",
    personas: ["eng"],
    agentKinds: ["coding"],
    requirements: [["coding"]],
    build: "ready",
    scope: "project",
  },
  {
    id: "me-pace",
    origin: "prototype",
    question: "Am I spending faster than in a typical week?",
    title: "Pace vs your typical week",
    why: "Money spent day by day against my typical week. Dots mark rate limits.",
    questionId: "spend",
    alsoAnswers: [],
    questionType: "changed",
    personas: ["eng"],
    agentKinds: ["coding"],
    requirements: [["coding"]],
    build: "logic",
    scope: "project",
  },
  {
    id: "me-cache-gauge",
    origin: "prototype",
    question: "How much of my coding agents' input comes from the cache?",
    title: "Cache hit rate",
    why: "The share of input the model reads from cache instead of processing again. Higher is cheaper; under 60% means caching is not working.",
    questionId: "spend",
    alsoAnswers: [],
    questionType: "line",
    personas: ["eng"],
    agentKinds: ["coding"],
    requirements: [["coding"]],
    build: "logic",
    scope: "project",
  },
  {
    id: "me-tool-round-trips",
    origin: "prototype",
    question: "Which single tool calls sent my coding agent the most tokens?",
    title: "Heaviest tool round-trips",
    why: "The tool calls that returned the most tokens. Filtering or paging these saves the most.",
    questionId: "spend",
    alsoAnswers: ["tools"],
    questionType: "matters",
    personas: ["eng"],
    agentKinds: ["coding"],
    requirements: [["coding"]],
    build: "logic",
    scope: "project",
  },
  {
    id: "me-main-vs-sub",
    origin: "prototype",
    question: "How are my tokens split between the main thread and subagents?",
    title: "Main thread vs subagents",
    why: "Tokens per day, main conversation against subagents.",
    questionId: "spend",
    alsoAnswers: [],
    questionType: "happened",
    personas: ["eng"],
    agentKinds: ["coding"],
    requirements: [["coding"]],
    build: "ready",
    scope: "project",
  },
  {
    id: "me-leaks",
    origin: "prototype",
    question: "Where are my coding agents wasting money?",
    title: "Leak detectors",
    why: "Six fixed rules that find wasted spend in my session data, each with what to do about it.",
    questionId: "spend",
    alsoAnswers: [],
    questionType: "matters",
    personas: ["eng"],
    agentKinds: ["coding"],
    requirements: [["coding"]],
    build: "logic",
    scope: "project",
  },
  {
    id: "me-value-per-token",
    origin: "prototype",
    question: "What does one merged pull request cost me?",
    title: "Value per token",
    why: "Coding-agent cost per merged pull request, and the trend.",
    questionId: "outcomecost",
    alsoAnswers: [],
    questionType: "changed",
    personas: ["eng"],
    agentKinds: ["coding"],
    requirements: [["coding"], ["prs"]],
    build: "logic",
    scope: "project",
  },
  {
    id: "me-shipping-calendar",
    origin: "prototype",
    question: "How many pull requests did I merge each day?",
    title: "Shipping streak",
    why: "Merged pull requests per day, as a calendar.",
    questionId: "used",
    alsoAnswers: [],
    questionType: "happened",
    personas: ["eng"],
    agentKinds: ["coding"],
    requirements: [["prs"]],
    build: "ready",
    scope: "project",
  },
  {
    id: "me-cost-per-pr",
    origin: "prototype",
    question: "Which of my merged pull requests cost far more than usual?",
    title: "Cost per merged PR",
    why: "Coding-agent cost of each merged pull request; the ones far above my median stand out.",
    questionId: "outcomecost",
    alsoAnswers: [],
    questionType: "matters",
    personas: ["eng"],
    agentKinds: ["coding"],
    requirements: [["coding"], ["prs"]],
    build: "logic",
    scope: "project",
  },
  {
    id: "me-babysit",
    origin: "prototype",
    question: "How much does a pull request cost after it opens (CI retries, review fixes)?",
    title: "Doing vs babysitting",
    why: "Cost before the pull request opened against cost after it opened.",
    questionId: "outcomecost",
    alsoAnswers: [],
    questionType: "compare",
    personas: ["eng"],
    agentKinds: ["coding"],
    requirements: [["coding"], ["prs"]],
    build: "logic",
    scope: "project",
  },
  {
    id: "me-pr-leaderboard",
    origin: "prototype",
    question: "Which of my pull requests cost the most?",
    title: "Expensive pull requests",
    why: "My pull requests ranked by coding-agent cost.",
    questionId: "outcomecost",
    alsoAnswers: [],
    questionType: "matters",
    personas: ["eng"],
    agentKinds: ["coding"],
    requirements: [["coding"], ["prs"]],
    build: "logic",
    scope: "project",
  },
  {
    id: "me-output-vs-spend",
    origin: "prototype",
    question: "Is my output keeping up with my coding-agent spend?",
    title: "Output vs spend",
    why: "Merged pull requests and commits next to what I spent, per week.",
    questionId: "outcomecost",
    alsoAnswers: [],
    questionType: "compare",
    personas: ["eng"],
    agentKinds: ["coding"],
    requirements: [["coding"], ["prs"]],
    build: "logic",
    scope: "project",
  },
  {
    id: "me-gantt",
    origin: "prototype",
    question: "What did my coding sessions do today, and when did they wait on me?",
    title: "Today",
    why: "My sessions across the day: working, or waiting for my reply.",
    questionId: "fast",
    alsoAnswers: [],
    questionType: "happened",
    personas: ["eng"],
    agentKinds: ["coding"],
    requirements: [["coding"]],
    build: "logic",
    scope: "project",
  },
  {
    id: "me-waiting-on-you",
    origin: "prototype",
    question: "Which of my coding sessions waited longest for my reply?",
    title: "Waiting on you",
    why: "The sessions that sat longest waiting for me this week.",
    questionId: "fast",
    alsoAnswers: [],
    questionType: "matters",
    personas: ["eng"],
    agentKinds: ["coding"],
    requirements: [["coding"]],
    build: "logic",
    scope: "project",
  },
  {
    id: "me-reply-latency",
    origin: "prototype",
    question: "How long do my coding agents wait for my reply?",
    title: "Your reply latency",
    why: "Time from the end of an agent's turn to my reply.",
    questionId: "fast",
    alsoAnswers: [],
    questionType: "happened",
    personas: ["eng"],
    agentKinds: ["coding"],
    requirements: [["coding"]],
    build: "logic",
    scope: "project",
  },
  {
    id: "me-parallel-heatmap",
    origin: "prototype",
    question: "How many coding sessions do I run at once?",
    title: "Parallel work, by hour",
    why: "Sessions running at the same time, by hour and day.",
    questionId: "used",
    alsoAnswers: [],
    questionType: "happened",
    personas: ["eng"],
    agentKinds: ["coding"],
    requirements: [["coding"]],
    build: "logic",
    scope: "project",
  },
  {
    id: "me-overnight",
    origin: "prototype",
    question: "What did my coding agents do overnight?",
    title: "Overnight runs",
    why: "What ran between midnight and 07:00 this week.",
    questionId: "used",
    alsoAnswers: [],
    questionType: "happened",
    personas: ["eng"],
    agentKinds: ["coding"],
    requirements: [["coding"]],
    build: "logic",
    scope: "project",
  },
  {
    id: "me-active-waiting",
    origin: "prototype",
    question: "How much time do my coding agents work, and how much do they wait on me?",
    title: "Working vs waiting",
    why: "Working time against waiting time, per day.",
    questionId: "fast",
    alsoAnswers: [],
    questionType: "compare",
    personas: ["eng"],
    agentKinds: ["coding"],
    requirements: [["coding"]],
    build: "logic",
    scope: "project",
  },
  {
    id: "me-context-per-call",
    origin: "prototype",
    question: "How big is my coding agents' context each day?",
    title: "Context per call",
    why: "Context size per model call, each day, against the 250k to 450k band.",
    questionId: "spend",
    alsoAnswers: [],
    questionType: "line",
    personas: ["eng"],
    agentKinds: ["coding"],
    requirements: [["coding"]],
    build: "logic",
    scope: "project",
  },
  {
    id: "me-compaction",
    origin: "prototype",
    question: "Do I compact my context at the right size?",
    title: "Where you compact",
    why: "Each compaction at the context size where it happened, against the best point.",
    questionId: "spend",
    alsoAnswers: [],
    questionType: "line",
    personas: ["eng"],
    agentKinds: ["coding"],
    requirements: [["coding"]],
    build: "logic",
    scope: "project",
  },
  {
    id: "me-call-cost",
    origin: "prototype",
    question: "What does one model call cost at each context size?",
    title: "What a call costs",
    why: "Average price of one model call by context size. Compacting earlier makes calls cheaper.",
    questionId: "spend",
    alsoAnswers: [],
    questionType: "compare",
    personas: ["eng"],
    agentKinds: ["coding"],
    requirements: [["coding"]],
    build: "logic",
    scope: "project",
  },
  {
    id: "me-oversized-context",
    origin: "prototype",
    question: "How much do I spend carrying oversized context?",
    title: "Spent on oversized context",
    why: "Money spent on context above the 450k line.",
    questionId: "spend",
    alsoAnswers: [],
    questionType: "line",
    personas: ["eng"],
    agentKinds: ["coding"],
    requirements: [["coding"]],
    build: "logic",
    scope: "project",
  },
  {
    id: "me-subagent-context",
    origin: "prototype",
    question: "How much context does each type of subagent carry?",
    title: "Subagent context",
    why: "Median context per subagent type. A fork carries the whole conversation; a small explorer starts small.",
    questionId: "spend",
    alsoAnswers: [],
    questionType: "compare",
    personas: ["eng"],
    agentKinds: ["coding"],
    requirements: [["coding"]],
    build: "logic",
    scope: "project",
  },
  {
    id: "me-steps",
    origin: "prototype",
    question: "How many model calls do my coding agents take per task?",
    title: "Steps per prompt and per agent",
    why: "Model calls per task, and the long tail.",
    questionId: "depth",
    alsoAnswers: [],
    questionType: "happened",
    personas: ["eng"],
    agentKinds: ["coding"],
    requirements: [["coding"]],
    build: "logic",
    scope: "project",
  },
  {
    id: "me-harness-effect",
    origin: "prototype",
    question: "Do my skills, MCPs and CLIs make my pull requests cheaper?",
    title: "Is it helping?",
    why: "Tokens per merged pull request in sessions that used each one, against sessions that did not. A correlation, not a controlled test.",
    questionId: "change",
    alsoAnswers: ["tools"],
    questionType: "compare",
    personas: ["eng"],
    agentKinds: ["coding"],
    requirements: [["coding"], ["prs"]],
    build: "logic",
    scope: "project",
  },
  {
    id: "me-tool-mix",
    origin: "prototype",
    question: "Which tools send my coding agents the most tokens?",
    title: "Tool mix",
    why: "Result tokens by tool, with shell commands grouped by command.",
    questionId: "tools",
    alsoAnswers: [],
    questionType: "matters",
    personas: ["eng"],
    agentKinds: ["coding"],
    requirements: [["coding"]],
    build: "logic",
    scope: "project",
  },
  {
    id: "me-clis-mcps",
    origin: "prototype",
    question: "Which CLIs and MCP servers do I use, and how much?",
    title: "Your CLIs and MCPs",
    why: "Calls per CLI and MCP server, and the trend.",
    questionId: "tools",
    alsoAnswers: [],
    questionType: "happened",
    personas: ["eng"],
    agentKinds: ["coding"],
    requirements: [["coding"]],
    build: "logic",
    scope: "project",
  },
  {
    id: "me-harness-changes",
    origin: "prototype",
    question: "What changed in my coding setup since last week?",
    title: "Changed since last week",
    why: "Skills, MCPs and CLIs added, removed or changed.",
    questionId: "change",
    alsoAnswers: [],
    questionType: "changed",
    personas: ["eng"],
    agentKinds: ["coding"],
    requirements: [["coding"]],
    build: "logic",
    scope: "project",
  },
  {
    id: "me-skills-in-use",
    origin: "prototype",
    question: "Which of my skills run, and how often?",
    title: "Skills in use",
    why: "How often each skill runs, and what it steers.",
    questionId: "tools",
    alsoAnswers: [],
    questionType: "happened",
    personas: ["eng"],
    agentKinds: ["coding"],
    requirements: [["coding"]],
    build: "logic",
    scope: "project",
  },
  {
    id: "me-harness-speed",
    origin: "prototype",
    question: "Which tools slow my coding agents down?",
    title: "Harness speed",
    why: "Time per tool call, and total time per tool this week.",
    questionId: "fast",
    alsoAnswers: ["tools"],
    questionType: "matters",
    personas: ["eng"],
    agentKinds: ["coding"],
    requirements: [["coding"]],
    build: "logic",
    scope: "project",
  },
  {
    id: "me-dead-weight",
    origin: "prototype",
    question: "Which MCP servers load into every session but are rarely called?",
    title: "Dead weight",
    why: "Servers whose schemas load into every session, with how rarely they are used.",
    questionId: "tools",
    alsoAnswers: ["spend"],
    questionType: "matters",
    personas: ["eng"],
    agentKinds: ["coding"],
    requirements: [["coding"]],
    build: "logic",
    scope: "project",
  },
  {
    id: "me-sub-vs-api",
    origin: "prototype",
    question: "Is my seat cheaper than paying API list prices?",
    title: "Subscription vs API list price",
    why: "My last 30 days priced at API list rates, against my seat price.",
    questionId: "less",
    alsoAnswers: [],
    questionType: "compare",
    personas: ["eng"],
    agentKinds: ["coding"],
    requirements: [["coding"]],
    build: "logic",
    scope: "project",
  },
  {
    id: "me-provider-replay",
    origin: "prototype",
    question: "What would my last month cost with other vendors?",
    title: "Your month on other providers",
    why: "My last 30 days priced on other vendors' rate cards. Prices only, no quality adjustment.",
    questionId: "less",
    alsoAnswers: [],
    questionType: "compare",
    personas: ["eng"],
    agentKinds: ["coding"],
    requirements: [["coding"]],
    build: "logic",
    scope: "project",
  },
  {
    id: "me-context-fit",
    origin: "prototype",
    question: "How many of my calls would be too big for other vendors' context limits?",
    title: "Context fit",
    why: "The share of my calls above each vendor's context limit.",
    questionId: "less",
    alsoAnswers: [],
    questionType: "compare",
    personas: ["eng"],
    agentKinds: ["coding"],
    requirements: [["coding"]],
    build: "logic",
    scope: "project",
  },
  {
    id: "me-cache-sensitivity",
    origin: "prototype",
    question: "How would my bill change at a different cache hit rate?",
    title: "Cache sensitivity",
    why: "My bill at different cache hit rates, per vendor.",
    questionId: "less",
    alsoAnswers: ["spend"],
    questionType: "compare",
    personas: ["eng"],
    agentKinds: ["coding"],
    requirements: [["coding"]],
    build: "logic",
    scope: "project",
  },
  {
    id: "me-peak-hours",
    origin: "prototype",
    question: "Do my tokens fall in vendors' peak-price hours?",
    title: "Peak-hours exposure",
    why: "When my tokens happen in the day, against vendors' peak windows.",
    questionId: "less",
    alsoAnswers: [],
    questionType: "happened",
    personas: ["eng"],
    agentKinds: ["coding"],
    requirements: [["coding"]],
    build: "logic",
    scope: "project",
  },
];
