/**
 * Every template: one dashboard each. Rogerio's boards are preloaded for their agent kinds.
 * Generated from the dashboards library draft on 2026-10-06; edit here from now on.
 */

import type { AgentKind, CatalogueScope, Persona, Trunk } from "./catalogue-labels.ts";

export interface CatalogueTemplate {
  readonly id: string;
  readonly name: string;
  readonly job: string;
  readonly personas: readonly Persona[];
  readonly trunk: Trunk;
  readonly origin: "prototype" | "library";
  readonly scope: CatalogueScope;
  readonly isDefault: boolean;
  /** The widgets, top to bottom, for any agent kind without its own list. */
  readonly widgets: readonly string[];
  readonly byAgentKind: Readonly<Partial<Record<AgentKind, readonly string[]>>>;
  /** The agent kinds whose projects get this board made for them; empty means gallery only. */
  readonly preloadFor: readonly AgentKind[];
}

export const CATALOGUE_TEMPLATES: readonly CatalogueTemplate[] = [
  {
    id: "cockpit",
    name: "Agent Flight Deck",
    job: "Is my agent doing its job and working normally? One glance.",
    personas: ["leader", "product", "ops", "eng"],
    trunk: "Growth",
    origin: "prototype",
    scope: "project",
    isDefault: true,
    widgets: ["ck-kpis", "ck-status", "ck-attention", "ck-top-ask", "ck-trend"],
    byAgentKind: {
      voice: ["ck-kpis", "ck-status", "ck-attention", "ck-top-ask", "voice-task-success"],
      generative: ["ck-kpis", "ck-status", "ck-attention", "ck-top-ask", "gen-acceptance"],
    },
    preloadFor: [
      "support-bot",
      "rag",
      "vendor",
      "voice",
      "extraction",
      "regulated",
      "tools-agent",
      "generative",
    ],
  },
  {
    id: "costs",
    name: "Running costs",
    job: "See where the money goes, and whether I am on budget.",
    personas: ["finance", "eng", "leader"],
    trunk: "Profit",
    origin: "prototype",
    scope: "project",
    isDefault: false,
    widgets: ["cost-verdict", "cost-by-source", "cost-by-model", "cost-waste"],
    byAgentKind: {
      voice: ["cost-verdict", "voice-cost-per-call", "cost-by-source", "cost-waste"],
      extraction: ["cost-verdict", "ext-cost-per-doc", "cost-by-source", "cost-waste"],
    },
    preloadFor: [
      "support-bot",
      "rag",
      "vendor",
      "voice",
      "extraction",
      "tools-agent",
      "generative",
    ],
  },
  {
    id: "unit-cost",
    name: "Cost per result",
    job: "What does each conversation, customer and success cost me?",
    personas: ["leader", "finance", "product"],
    trunk: "Profit",
    origin: "library",
    scope: "project",
    isDefault: false,
    widgets: ["cost-outcome", "cost-conv", "fd-cost-efficiency", "cost-by-segment"],
    byAgentKind: {},
    preloadFor: [],
  },
  {
    id: "models",
    name: "Compare models",
    job: "I am trying a new model or prompt. Is the new one as good, and cheaper?",
    personas: ["prompt", "eng"],
    trunk: "Profit",
    origin: "library",
    scope: "project",
    isDefault: false,
    widgets: ["ship-models", "ship-compare", "cost-by-model", "slowest-models", "top-models"],
    byAgentKind: {},
    preloadFor: [],
  },
  {
    id: "adoption",
    name: "Usage and adoption",
    job: "Who uses my agent, how much, and do users come back?",
    personas: ["product", "leader"],
    trunk: "Growth",
    origin: "library",
    scope: "project",
    isDefault: false,
    widgets: ["traffic", "users", "return", "conversation-length", "topics"],
    byAgentKind: {},
    preloadFor: [],
  },
  {
    id: "asks",
    name: "What users ask",
    job: "Learn what users want, and what my agent cannot do yet.",
    personas: ["product", "expert"],
    trunk: "Growth",
    origin: "prototype",
    scope: "project",
    isDefault: false,
    widgets: ["ask-cannot", "ask-rising", "ans-topics", "ask-again"],
    byAgentKind: {},
    preloadFor: [
      "support-bot",
      "rag",
      "vendor",
      "voice",
      "extraction",
      "regulated",
      "tools-agent",
      "generative",
    ],
  },
  {
    id: "happy",
    name: "Are users happy?",
    job: "Are users happy, and where are they frustrated?",
    personas: ["product", "ops"],
    trunk: "Growth",
    origin: "library",
    scope: "project",
    isDefault: false,
    widgets: ["satisfaction-shift", "user-thumbs", "ask-again", "return"],
    byAgentKind: {},
    preloadFor: [],
  },
  {
    id: "answers",
    name: "Answer quality",
    job: "Check whether my agent's answers are good, and where they fail.",
    personas: ["product", "qa", "expert"],
    trunk: "Growth",
    origin: "prototype",
    scope: "project",
    isDefault: false,
    widgets: ["ans-outcomes", "ans-evaluators", "ans-idk", "so-agreement", "ans-review"],
    byAgentKind: {
      rag: [
        "rag-failure-source",
        "rag-empty-retrieval",
        "ans-idk",
        "ans-evaluators",
        "so-agreement",
        "ans-review",
      ],
      voice: ["ans-outcomes", "ans-evaluators", "ans-idk", "so-agreement"],
      extraction: ["ans-outcomes", "ans-evaluators", "so-agreement", "ans-review"],
      "tools-agent": ["ans-outcomes", "ans-evaluators", "so-agreement", "ans-review"],
      generative: ["ans-outcomes", "ans-evaluators", "so-agreement", "ans-review"],
    },
    preloadFor: [
      "support-bot",
      "rag",
      "vendor",
      "voice",
      "extraction",
      "regulated",
      "tools-agent",
      "generative",
    ],
  },
  {
    id: "unanswered",
    name: "Questions my agent cannot answer",
    job: "I know the subject. Show me where my agent fails to answer, and why.",
    personas: ["expert", "product"],
    trunk: "Growth",
    origin: "library",
    scope: "project",
    isDefault: false,
    widgets: ["ans-idk", "ask-cannot", "ans-review", "so-agreement", "lowest-scores"],
    byAgentKind: {
      rag: [
        "ans-idk",
        "ask-cannot",
        "ans-review",
        "so-agreement",
        "rag-failure-source",
        "rag-empty-retrieval",
      ],
    },
    preloadFor: [],
  },
  {
    id: "breaks",
    name: "Where my agent breaks",
    job: "Find the errors, failing steps and loops in my agent.",
    personas: ["eng", "ops"],
    trunk: "Growth",
    origin: "prototype",
    scope: "project",
    isDefault: false,
    widgets: ["up-errors", "up-where-fails", "up-step-latency", "up-loops", "up-failing-traces"],
    byAgentKind: {
      "tools-agent": [
        "tools-error-rate",
        "tools-wrong-tool",
        "up-loops",
        "up-step-latency",
        "up-failing-traces",
      ],
    },
    preloadFor: [
      "support-bot",
      "rag",
      "vendor",
      "voice",
      "extraction",
      "regulated",
      "tools-agent",
      "generative",
    ],
  },
  {
    id: "speed",
    name: "Make my agent faster",
    job: "Find out what makes my agent slow.",
    personas: ["eng"],
    trunk: "Growth",
    origin: "library",
    scope: "project",
    isDefault: false,
    widgets: [
      "latency-slo",
      "latency-spread",
      "up-step-latency",
      "slowest-models",
      "fd-throughput",
    ],
    byAgentKind: {
      voice: [
        "latency-slo",
        "latency-spread",
        "up-step-latency",
        "slowest-models",
        "voice-turn-latency",
      ],
    },
    preloadFor: [],
  },
  {
    id: "tools",
    name: "Tool use",
    job: "Does my agent pick the right tools, without wasted steps?",
    personas: ["eng", "prompt"],
    trunk: "Growth",
    origin: "library",
    scope: "project",
    isDefault: false,
    widgets: ["tools-error-rate", "tools-wrong-tool", "up-loops", "up-step-latency", "cost-waste"],
    byAgentKind: {},
    preloadFor: [],
  },
  {
    id: "release",
    name: "Release check",
    job: "Decide if the next version of my agent can go out.",
    personas: ["qa", "eng", "product"],
    trunk: "Growth",
    origin: "prototype",
    scope: "project",
    isDefault: false,
    widgets: ["ship-verdict", "ship-suites", "ship-flaky", "ship-compare", "ship-rollout"],
    byAgentKind: {
      rag: ["ship-verdict", "rag-dataset-versions", "ship-flaky", "ship-compare", "ship-rollout"],
      voice: ["ship-verdict", "ship-suites", "ship-flaky", "ship-models"],
      extraction: ["ship-verdict", "ext-precision-recall", "ship-models", "ship-compare"],
      regulated: ["ship-verdict", "ship-suites", "ship-compare", "ship-rollout"],
      "tools-agent": ["ship-verdict", "ship-suites", "ship-flaky", "ship-compare", "ship-models"],
      generative: ["ship-verdict", "ship-suites", "ship-compare", "ship-rollout"],
    },
    preloadFor: [
      "support-bot",
      "rag",
      "vendor",
      "voice",
      "extraction",
      "regulated",
      "tools-agent",
      "generative",
    ],
  },
  {
    id: "change",
    name: "Did my change help?",
    job: "I just changed a prompt, model or tool. Did the change help or hurt?",
    personas: ["eng", "prompt", "product"],
    trunk: "Growth",
    origin: "library",
    scope: "project",
    isDefault: false,
    widgets: [
      "ship-rollout",
      "ans-outcomes",
      "up-errors",
      "token-drift",
      "fd-quality",
      "so-changes",
    ],
    byAgentKind: {},
    preloadFor: [],
  },
  {
    id: "evals",
    name: "Can I trust my evals?",
    job: "Check that my automatic graders, tests and test sets tell the truth.",
    personas: ["qa", "expert"],
    trunk: "Foundation",
    origin: "library",
    scope: "project",
    isDefault: false,
    widgets: [
      "so-agreement",
      "evaluation-coverage",
      "lowest-passing-evaluators",
      "ship-flaky",
      "rag-dataset-versions",
    ],
    byAgentKind: {},
    preloadFor: [],
  },
  {
    id: "data",
    name: "Is my data complete?",
    job: "Check that my traces carry what the dashboards need, and fix what is missing.",
    personas: ["eng"],
    trunk: "Foundation",
    origin: "library",
    scope: "project",
    isDefault: false,
    widgets: ["data-health", "cost-accuracy", "noise", "evaluation-coverage"],
    byAgentKind: {},
    preloadFor: [],
  },
  {
    id: "safety",
    name: "Safety and privacy",
    job: "Is my agent safe: no leaks, no attacks, and on brand?",
    personas: ["risk", "eng"],
    trunk: "Protect",
    origin: "library",
    scope: "project",
    isDefault: false,
    widgets: ["attacks", "pii", "off-scope", "so-rubric", "so-changes"],
    byAgentKind: {},
    preloadFor: [],
  },
  {
    id: "signoff",
    name: "Risk sign-off",
    job: "Give risk the evidence it needs to sign a release off.",
    personas: ["risk"],
    trunk: "Protect",
    origin: "prototype",
    scope: "project",
    isDefault: false,
    widgets: ["so-verdict", "so-rubric", "so-queue", "so-changes"],
    byAgentKind: {},
    preloadFor: ["regulated"],
  },
  {
    id: "customers",
    name: "By customer",
    job: "See how each of my customers uses my agent, and how my agent does for them.",
    personas: ["ops", "product", "finance"],
    trunk: "Growth",
    origin: "prototype",
    scope: "project",
    isDefault: false,
    widgets: ["att-share", "cost-by-segment", "att-table", "att-change"],
    byAgentKind: {},
    preloadFor: ["vendor"],
  },
  {
    id: "calls",
    name: "Call quality",
    job: "Check that my voice agent's calls feel natural and get the job done.",
    personas: ["ops", "eng", "qa"],
    trunk: "Growth",
    origin: "prototype",
    scope: "project",
    isDefault: false,
    widgets: ["voice-turn-latency", "voice-call-health", "att-table", "ans-review"],
    byAgentKind: {},
    preloadFor: ["voice"],
  },
  {
    id: "fields",
    name: "Field accuracy",
    job: "See which fields and document types my agent gets wrong.",
    personas: ["expert", "ops", "qa"],
    trunk: "Growth",
    origin: "prototype",
    scope: "project",
    isDefault: false,
    widgets: ["ext-field-accuracy", "ext-human-review", "att-table", "att-change"],
    byAgentKind: {},
    preloadFor: ["extraction"],
  },
  {
    id: "outputs",
    name: "Outputs users keep",
    job: "See whether users keep what my agent writes.",
    personas: ["product"],
    trunk: "Growth",
    origin: "prototype",
    scope: "project",
    isDefault: false,
    widgets: ["gen-dropoff", "att-table", "att-change", "cost-by-segment"],
    byAgentKind: {},
    preloadFor: ["generative"],
  },
  {
    id: "org",
    name: "LangWatch at a glance",
    job: "See every agent, team and AI tool across my whole org.",
    personas: ["leader", "risk", "finance"],
    trunk: "Foundation",
    origin: "library",
    scope: "org",
    isDefault: false,
    widgets: ["inventory", "ai-tools", "org-spend", "fd-gateway", "standard", "fd-coding-agents"],
    byAgentKind: {},
    preloadFor: [],
  },
  {
    id: "me-tokens",
    name: "My Token Burn Rate",
    job: "Where my coding agents' tokens and money go: by pull request, by model, by token type.",
    personas: ["eng"],
    trunk: "Profit",
    origin: "prototype",
    scope: "project",
    isDefault: false,
    widgets: [
      "me-burn-summary",
      "me-expensive-sessions",
      "me-by-pr",
      "me-spend-by-model",
      "me-pace",
      "me-cache-gauge",
      "me-tool-round-trips",
      "me-main-vs-sub",
      "me-leaks",
    ],
    byAgentKind: {},
    preloadFor: ["coding"],
  },
  {
    id: "me-shipped",
    name: "What have I shipped",
    job: "What my merged pull requests cost in coding-agent use.",
    personas: ["eng"],
    trunk: "Profit",
    origin: "prototype",
    scope: "project",
    isDefault: false,
    widgets: [
      "me-value-per-token",
      "me-shipping-calendar",
      "me-cost-per-pr",
      "me-babysit",
      "me-pr-leaderboard",
      "me-output-vs-spend",
    ],
    byAgentKind: {},
    preloadFor: ["coding"],
  },
  {
    id: "me-speed",
    name: "Building speed",
    job: "My coding sessions through the day: parallel work, idle time, what ran at night.",
    personas: ["eng"],
    trunk: "Growth",
    origin: "prototype",
    scope: "project",
    isDefault: false,
    widgets: [
      "me-gantt",
      "me-waiting-on-you",
      "me-reply-latency",
      "me-parallel-heatmap",
      "me-overnight",
      "me-active-waiting",
    ],
    byAgentKind: {},
    preloadFor: ["coding"],
  },
  {
    id: "me-context",
    name: "Context health",
    job: "How big my context runs and where I compact. Smaller context means cheaper calls.",
    personas: ["eng"],
    trunk: "Profit",
    origin: "prototype",
    scope: "project",
    isDefault: false,
    widgets: [
      "me-context-per-call",
      "me-compaction",
      "me-call-cost",
      "me-oversized-context",
      "me-subagent-context",
      "me-steps",
    ],
    byAgentKind: {},
    preloadFor: ["coding"],
  },
  {
    id: "me-harness",
    name: "My harness",
    job: "The skills, MCPs and CLIs I installed: use, effect and speed.",
    personas: ["eng"],
    trunk: "Growth",
    origin: "prototype",
    scope: "project",
    isDefault: false,
    widgets: [
      "me-harness-effect",
      "me-tool-mix",
      "me-clis-mcps",
      "me-harness-changes",
      "me-skills-in-use",
      "me-harness-speed",
      "me-dead-weight",
    ],
    byAgentKind: {},
    preloadFor: ["coding"],
  },
  {
    id: "me-market",
    name: "The market",
    job: "My real coding-agent use priced on other vendors' rate cards. Prices only, no quality adjustment.",
    personas: ["eng"],
    trunk: "Profit",
    origin: "prototype",
    scope: "project",
    isDefault: false,
    widgets: [
      "me-sub-vs-api",
      "me-provider-replay",
      "me-context-fit",
      "me-cache-sensitivity",
      "me-peak-hours",
    ],
    byAgentKind: {},
    preloadFor: ["coding"],
  },
];
