/**
 * The question tree: every question a dashboard answers, under its branch and trunk. The
 * finder and the "Add a widget" picker file templates and widgets by it.
 */

import type { CatalogueScope, Trunk } from "./catalogue-labels.ts";

/** The tree's branches, trunk by trunk in `TRUNKS` order: the picker's sections. */
export const QUESTION_BRANCHES = [
  { title: "More usage and users", trunk: "Grow", why: "Is my AI used, by whom, and for what?" },
  { title: "Productive agents", trunk: "Grow", why: "How much work does my agent get done?" },
  { title: "Keep users", trunk: "Grow", why: "Are users happy enough to stay?" },
  { title: "Is my agent right?", trunk: "Protect", why: "Quality, grounding and rules" },
  { title: "Is my agent safe?", trunk: "Protect", why: "Attacks, privacy and brand" },
  { title: "Is my agent working?", trunk: "Protect", why: "Errors, failures and single traces" },
  {
    title: "Did a change break my agent?",
    trunk: "Protect",
    why: "Regressions, releases and tests",
  },
  { title: "Can I trust my checks?", trunk: "Protect", why: "Judges, test sets and consistency" },
  {
    title: "Are my agents under control?",
    trunk: "Protect",
    why: "Inventory, usage, access and standards",
  },
  { title: "Spend less", trunk: "Profit", why: "What am I spending, and where does the money go?" },
  { title: "Spend better", trunk: "Profit", why: "What do I get for each unit of spend?" },
  { title: "Can I trust my data?", trunk: "Trust", why: "Completeness and correctness" },
] as const satisfies readonly { title: string; trunk: Trunk; why: string }[];

export type QuestionBranch = (typeof QUESTION_BRANCHES)[number];

export interface TreeQuestion {
  readonly id: string;
  /** The two- or three-word name the library shows. */
  readonly short: string;
  readonly question: string;
  readonly branch: QuestionBranch["title"];
  /** How the answer is measured. */
  readonly metric: string;
  /** What the reader decides with the answer. */
  readonly decision: string;
  readonly scope: CatalogueScope;
}

export const QUESTION_TREE: readonly TreeQuestion[] = [
  {
    id: "spend",
    short: "Total spend",
    question: "What am I spending, on what, and where is money wasted?",
    branch: "Spend less",
    metric:
      "Total cost per day, by model, feature and label. Waste = cost of retries, cache misses and noise traces ÷ total cost.",
    decision: "Set a budget, cut the waste, move traffic to a cheaper model.",
    scope: "project",
  },
  {
    id: "convcost",
    short: "Cost per task",
    question: "What does one conversation or task with my agent cost?",
    branch: "Spend less",
    metric: "Total cost ÷ conversations or tasks, and the spread.",
    decision: "Price the product, cap long conversations, fix the costliest flows.",
    scope: "project",
  },
  {
    id: "acctcost",
    short: "Cost per customer",
    question: "What does each of my customers cost to serve, for billing?",
    branch: "Spend less",
    metric: "Cost per customer or tenant, per month.",
    decision: "Bill, set plan limits, find heavy customers.",
    scope: "project",
  },
  {
    id: "orgspend",
    short: "Spend by team",
    question: "What does each team and app spend on AI?",
    branch: "Spend less",
    metric: "Spend per project, team and gateway key, per month.",
    decision: "Set team budgets; charge back.",
    scope: "org",
  },
  {
    id: "codingcost",
    short: "Staff AI cost",
    question: "What do my staff's coding agents and AI seats cost, and which seats sit unused?",
    branch: "Spend less",
    metric:
      "Coding-agent and AI-tool cost per person and team, per month; seats unused for 30 days.",
    decision: "Set team budgets; cancel unused seats.",
    scope: "org",
  },
  {
    id: "evalcost",
    short: "Test cost",
    question: "What do my evaluations, tests and simulations cost?",
    branch: "Spend less",
    metric: "Cost of eval, experiment and simulation runs ÷ total AI cost.",
    decision: "Sample fewer traces, or use a cheaper judge model.",
    scope: "project",
  },
  {
    id: "outcomecost",
    short: "Cost per outcome",
    question: "What does each correct outcome of my agent cost?",
    branch: "Spend better",
    metric: "Total cost ÷ correct outcomes (an outcome event with a passing eval).",
    decision: "Invest in the agent or pull back; compare with the cost of a person doing the task.",
    scope: "project",
  },
  {
    id: "less",
    short: "Same for less",
    question: "Can my agent get the same quality for less (cheaper model, prompt or setup)?",
    branch: "Spend better",
    metric: "Cost per task and eval score for each model or setup, on the same dataset.",
    decision: "Switch model or prompt when the score holds and the cost drops.",
    scope: "project",
  },
  {
    id: "used",
    short: "Volume",
    question: "How much work does my agent handle?",
    branch: "More usage and users",
    metric: "Traces, conversations and tasks per day, by feature or label.",
    decision: "Plan capacity; see which features take off.",
    scope: "project",
  },
  {
    id: "howmany",
    short: "Users",
    question: "How many users does my agent have, and who are the heaviest users?",
    branch: "More usage and users",
    metric: "Daily and monthly active users; top users and accounts by tasks.",
    decision: "Target onboarding; find power users and silent accounts.",
    scope: "project",
  },
  {
    id: "comeback",
    short: "Return",
    question: "Do users come back to my agent?",
    branch: "Keep users",
    metric: "Share of users active again within 7 and 30 days.",
    decision: "Find what makes users stay; follow up silent accounts.",
    scope: "project",
  },
  {
    id: "happy",
    short: "Satisfaction",
    question: "Are users happy with my agent, and where do they get frustrated?",
    branch: "Keep users",
    metric: "Thumbs-up ÷ rated answers; share of conversations with frustration signals.",
    decision: "Fix the topics and flows with the worst ratings.",
    scope: "project",
  },
  {
    id: "finish",
    short: "Task success",
    question: "Does my agent complete the task?",
    branch: "Productive agents",
    metric:
      "Tasks that reached the right outcome ÷ all tasks. Split by the step reached, and by with or without a person.",
    decision: "Choose which tasks to automate next, and where a person must stay in the loop.",
    scope: "project",
  },
  {
    id: "answers",
    short: "Answer quality",
    question: "Are my agent's answers good?",
    branch: "Is my agent right?",
    metric: "Share of answers that pass the quality eval, per topic and version.",
    decision: "Choose what to fix first; block a release that lowers answer quality.",
    scope: "project",
  },
  {
    id: "grounded",
    short: "Grounding",
    question: "Does my agent make things up, or stick to its sources?",
    branch: "Is my agent right?",
    metric: "Share of answers supported by the retrieved context; retrieval hit rate.",
    decision: 'Fix retrieval or the source documents; add a "don\'t know" path.',
    scope: "project",
  },
  {
    id: "rules",
    short: "Rules",
    question: "Does my agent follow my rules, brand and scope?",
    branch: "Is my agent right?",
    metric: "Share of answers that pass each rule: tone, format, language, scope.",
    decision: "Tighten the prompt, or add a guardrail for the rule that fails most.",
    scope: "project",
  },
  {
    id: "asking",
    short: "Topics",
    question: "What do users ask my agent about?",
    branch: "Productive agents",
    metric: "Share of conversations per topic, and the trend.",
    decision: "Build for the top topics; decide which topics the agent must refuse.",
    scope: "project",
  },
  {
    id: "tools",
    short: "Tool use",
    question: "Does my agent call the right tools, without wasted steps?",
    branch: "Is my agent working?",
    metric: "Share of tool calls that fail, repeat or are not needed; steps per task.",
    decision: "Fix tool descriptions, remove tools, cap loops.",
    scope: "project",
  },
  {
    id: "failing",
    short: "Failures",
    question: "What is failing in my agent, and why?",
    branch: "Is my agent working?",
    metric: "Error rate by step, model and cause, with an alert at a set line.",
    decision: "Fix the top cause; fail over to another provider.",
    scope: "project",
  },
  {
    id: "fast",
    short: "Speed",
    question: "How fast is my agent?",
    branch: "Is my agent working?",
    metric: "Typical and slowest-5% time to the first word and to the full answer, per step.",
    decision: "Change model, add caching or cut steps; set a latency target.",
    scope: "project",
  },
  {
    id: "depth",
    short: "Turns to finish",
    question: "How many turns does my agent take to complete a task?",
    branch: "More usage and users",
    metric: "Turns and minutes per conversation, and the spread.",
    decision: "Find flows that drag on; shorten them or hand off.",
    scope: "project",
  },
  {
    id: "change",
    short: "Change impact",
    question: "Did my last change (prompt, model or code) help or hurt my agent?",
    branch: "Did a change break my agent?",
    metric:
      "Eval score, cost and latency before and after a change, on the same traffic or dataset.",
    decision: "Ship, roll back or keep testing.",
    scope: "project",
  },
  {
    id: "tests",
    short: "Pre-release tests",
    question: "Does my agent pass my tests before every release?",
    branch: "Did a change break my agent?",
    metric:
      "Pass rate of scenarios and experiments per release, and the spread over repeated runs.",
    decision: "Block or allow a release; add tests for new failures.",
    scope: "project",
  },
  {
    id: "standard",
    short: "One standard",
    question: "Is every team's agent held to one standard?",
    branch: "Are my agents under control?",
    metric: "Share of projects that run the shared eval set, and their pass rates.",
    decision: "Require the shared evals before launch.",
    scope: "org",
  },
  {
    id: "manual",
    short: "Work saved",
    question: "How much manual work does my agent save?",
    branch: "Spend better",
    metric: "Minutes saved = tasks finished × baseline minutes per task.",
    decision: "Justify the budget; plan staffing.",
    scope: "project",
  },
  {
    id: "attacked",
    short: "Attacks and harm",
    question: "Can my agent be attacked, misused, or say something harmful?",
    branch: "Is my agent safe?",
    metric: "Blocked and missed attacks or harmful outputs per 1,000 conversations.",
    decision: "Add or tune guardrails; red-team before release.",
    scope: "project",
  },
  {
    id: "pii",
    short: "Privacy",
    question: "Is personal data leaking through my agent?",
    branch: "Is my agent safe?",
    metric: "Conversations with personal data in input, output or logs, and the share masked.",
    decision: "Turn on masking; change what is logged.",
    scope: "project",
  },
  {
    id: "access",
    short: "Access",
    question: "Do my agents and tools hold more access than they should?",
    branch: "Are my agents under control?",
    metric: "Tool and MCP calls per agent outside its allowed list.",
    decision: "Cut permissions to what the agent uses.",
    scope: "org",
  },
  {
    id: "inventory",
    short: "Agent inventory",
    question: "Which agents and AI tools run here, who owns them, and who uses them?",
    branch: "Are my agents under control?",
    metric:
      "Number of agents and AI tools, the share with an owner, and the staff and teams using each.",
    decision: "Give each agent an owner; shut down the ones nobody owns.",
    scope: "org",
  },
  {
    id: "costok",
    short: "Cost accuracy",
    question: "Is my cost data complete and correct?",
    branch: "Can I trust my data?",
    metric: "Share of traces with a priced model; difference from the provider's invoice.",
    decision: "Fix pricing for unknown models before you trust any cost number.",
    scope: "project",
  },
  {
    id: "arriving",
    short: "Trace completeness",
    question: "Are all my traces arriving, complete, and counted the same everywhere?",
    branch: "Can I trust my data?",
    metric: "Traces received ÷ traces sent, and the share with input and output, per source.",
    decision: "Fix instrumentation before you read any chart.",
    scope: "project",
  },
  {
    id: "judges",
    short: "Judge trust",
    question: "Can I trust my automatic graders (LLM judges)?",
    branch: "Can I trust my checks?",
    metric: "Agreement between judge scores and human labels on a sample.",
    decision: "Keep, retune or replace a judge.",
    scope: "project",
  },
  {
    id: "testset",
    short: "Test-set quality",
    question: "Is my test set representative of real traffic?",
    branch: "Can I trust my checks?",
    metric: "Share of production topics and failures that the test set covers.",
    decision: "Add production traces to the dataset.",
    scope: "project",
  },
  {
    id: "trace",
    short: "One trace",
    question: "What happened inside this one trace or call?",
    branch: "Is my agent working?",
    metric: "No metric: the full record of one run (steps, inputs, outputs, cost, time).",
    decision: "Find the cause of one bad answer.",
    scope: "project",
  },
  {
    id: "value",
    short: "LangWatch value",
    question: "What is LangWatch worth to me?",
    branch: "Are my agents under control?",
    metric: "Issues caught, regressions blocked and tests run per month, and the time saved.",
    decision: "Renew or expand LangWatch.",
    scope: "org",
  },
];
