package httpapi

// Staged payload offload — the counterpart to the TS `stagePayload` helper
// (langwatch/src/server/s3/stagePayload.ts) used by `invokeLambda`.
//
// Why this exists
// ---------------
// The Studio invoke fans the whole client event (including the dataset row
// being evaluated) into the AWS Lambda request body. AWS caps a synchronous
// Lambda invoke at 6 MB, so a heavy-agentic row (a multi-megabyte conversation)
// fails before our code runs with "Request must be smaller than 6291456 bytes
// for the InvokeFunction operation". The TS side dodges this by uploading the
// oversized payload to S3 and sending an empty body plus an `X-Payload-S3-URL`
// presigned-GET header (the same trick langevals already uses). This file is
// the receiving half: when the header is present we fetch the real body from
// the presigned URL instead of reading the (empty) request body.
//
// SSRF posture
// ------------
// The URL is self-generated by the TS `stagePayload` helper, so this is
// defense-in-depth. Even so we only fetch https URLs whose host is an AWS S3
// host — a tampered header can't redirect the fetch at the instance metadata
// endpoint, an internal service, or even another AWS service. The presigned
// signature rides in the query string, which we intentionally do not restrict.

import (
	"context"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"
)

// StagedPayloadHeader carries a presigned S3 GET URL for the real request
// body when the TS side offloaded an oversized Studio invoke payload. Must
// match STAGED_HEADER in langwatch/src/server/s3/stagePayload.ts.
const StagedPayloadHeader = "X-Payload-S3-URL"

// stagedPayloadClient fetches offloaded bodies. The 60s timeout covers a
// large (up to maxStagedPayloadBytes) same-region S3 download with margin.
var stagedPayloadClient = &http.Client{Timeout: 60 * time.Second}

// maxStagedPayloadBytes bounds the fetched body so a tampered or unexpectedly
// huge object can't exhaust memory. 256 MiB mirrors the langevals staged
// middleware ceiling (langevals/staged_payload.py).
const maxStagedPayloadBytes = 256 * 1024 * 1024

// validateStagedPayloadURL enforces the SSRF guard: https only, and the host
// must be an AWS S3 host (path-style `s3[.-]<region>.amazonaws.com` or
// virtual-hosted `<bucket>.s3[.-]<region>.amazonaws.com`). Any other host —
// including non-S3 AWS services and the instance metadata endpoint — is
// rejected.
func validateStagedPayloadURL(raw string) error {
	if raw == "" {
		return fmt.Errorf("staged payload url is empty")
	}
	u, err := url.Parse(raw)
	if err != nil {
		return fmt.Errorf("staged payload url is unparseable: %w", err)
	}
	if u.Scheme != "https" {
		return fmt.Errorf("staged payload url must be https, got %q", u.Scheme)
	}
	host := strings.ToLower(u.Hostname())
	if !isAWSS3Host(host) {
		return fmt.Errorf("staged payload url host %q is not an AWS S3 host", host)
	}
	return nil
}

// isAWSS3Host reports whether host is an Amazon S3 endpoint. It requires both
// the amazonaws.com suffix AND an `s3` label so non-S3 AWS hosts (e.g.
// lambda.us-east-1.amazonaws.com) are rejected.
func isAWSS3Host(host string) bool {
	if !strings.HasSuffix(host, ".amazonaws.com") {
		return false
	}
	// path-style: s3.amazonaws.com, s3.us-east-1.amazonaws.com,
	// s3-us-east-1.amazonaws.com
	if strings.HasPrefix(host, "s3.") || strings.HasPrefix(host, "s3-") {
		return true
	}
	// virtual-hosted: <bucket>.s3.<region>.amazonaws.com,
	// <bucket>.s3-<region>.amazonaws.com
	return strings.Contains(host, ".s3.") || strings.Contains(host, ".s3-")
}

// fetchStagedPayload GETs the (already-validated) presigned URL and returns
// the body, bounded to maxStagedPayloadBytes. The caller MUST validate the
// URL with validateStagedPayloadURL first; this function does the transport
// only so it stays unit-testable against an httptest server.
func fetchStagedPayload(ctx context.Context, client *http.Client, raw string) ([]byte, error) {
	if client == nil {
		client = http.DefaultClient
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, raw, nil)
	if err != nil {
		return nil, fmt.Errorf("build staged payload request: %w", err)
	}
	resp, err := client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("fetch staged payload: %w", err)
	}
	defer func() { _ = resp.Body.Close() }()
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return nil, fmt.Errorf("staged payload fetch returned status %d", resp.StatusCode)
	}
	body, err := io.ReadAll(io.LimitReader(resp.Body, maxStagedPayloadBytes))
	if err != nil {
		return nil, fmt.Errorf("read staged payload body: %w", err)
	}
	return body, nil
}

// readStudioRequestBody returns the request body, transparently fetching it
// from the presigned S3 URL when the X-Payload-S3-URL header is present (the
// oversized-payload offload). Without the header it reads the body inline.
func readStudioRequestBody(r *http.Request, client *http.Client) ([]byte, error) {
	if staged := r.Header.Get(StagedPayloadHeader); staged != "" {
		if err := validateStagedPayloadURL(staged); err != nil {
			return nil, err
		}
		return fetchStagedPayload(r.Context(), client, staged)
	}
	return io.ReadAll(r.Body)
}
