"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.ToolExecutionTaskSupport = void 0;
exports.ToolExecutionTaskSupport = {
    Forbidden: "forbidden",
    Optional: "optional",
    Required: "required",
};
