-- Remembering that somebody said "no thanks" to being offered their
-- colleagues' organization (D12, specs/identity/join-before-create.feature).
--
-- One column, defaulted to the empty list and backfilled by that default, so
-- every account that exists today reads as "never dismissed anything" — which
-- is true. Nothing is rewritten and nobody is signed out.
--
-- Per DOMAIN rather than a single flag, because the offer is per domain: a
-- person who dismisses "Acme Corp is here" on acme.com should still be
-- offered their new employer's organization after they change jobs and verify
-- a second address.
--
-- On the account rather than in browser storage on purpose, for the reason
-- the passkey nudge gives: a per-browser record forgets on a new device, and
-- "appears once" that only holds on one device is not "appears once".
--
-- To roll back, uncomment and run manually. Dropping it loses only the
-- dismissals, which costs those people one repeated offer.
-- ALTER TABLE "User" DROP COLUMN "joinOfferDismissedDomains";

ALTER TABLE "User" ADD COLUMN "joinOfferDismissedDomains" TEXT[] DEFAULT ARRAY[]::TEXT[];
