"use strict";
// This file was auto-generated by Fern from our API Definition.
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.MessagesClient = void 0;
const BaseClient_1 = require("../../../../../../../../BaseClient");
const core = __importStar(require("../../../../../../../../core"));
const headers_1 = require("../../../../../../../../core/headers");
const environments = __importStar(require("../../../../../../../../environments"));
const handleNonStatusCodeError_1 = require("../../../../../../../../errors/handleNonStatusCodeError");
const errors = __importStar(require("../../../../../../../../errors/index"));
const serializers = __importStar(require("../../../../../../../../serialization/index"));
const ElevenLabs = __importStar(require("../../../../../../../index"));
class MessagesClient {
    constructor(options = {}) {
        this._options = (0, BaseClient_1.normalizeClientOptions)(options);
    }
    /**
     * Search through conversation transcript messages by full-text and fuzzy search
     *
     * @param {ElevenLabs.conversationalAi.conversations.MessagesTextSearchRequest} request
     * @param {MessagesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link ElevenLabs.UnprocessableEntityError}
     *
     * @example
     *     await client.conversationalAi.conversations.messages.textSearch({
     *         textQuery: "refund policy",
     *         agentId: "agent_id",
     *         callSuccessful: "success",
     *         callStartBeforeUnix: 1,
     *         callStartAfterUnix: 1,
     *         callDurationMinSecs: 1,
     *         callDurationMaxSecs: 1,
     *         ratingMax: 1,
     *         ratingMin: 1,
     *         hasFeedbackComment: true,
     *         userId: "user_id",
     *         evaluationParams: ["evaluation_params"],
     *         dataCollectionParams: ["data_collection_params"],
     *         toolNames: ["tool_names"],
     *         toolNamesSuccessful: ["tool_names_successful"],
     *         toolNamesErrored: ["tool_names_errored"],
     *         mainLanguages: ["main_languages"],
     *         pageSize: 1,
     *         summaryMode: "exclude",
     *         conversationInitiationSource: "unknown",
     *         textOnly: true,
     *         conversationProductType: "agents",
     *         branchId: "branch_id",
     *         topicIds: ["topic_ids"],
     *         sortBy: "search_score",
     *         cursor: "cursor"
     *     })
     */
    textSearch(request, requestOptions) {
        return core.HttpResponsePromise.fromPromise(this.__textSearch(request, requestOptions));
    }
    __textSearch(request, requestOptions) {
        return __awaiter(this, void 0, void 0, function* () {
            var _a, _b, _c, _d, _e, _f, _g, _h, _j, _k, _l, _m;
            const { textQuery, agentId, callSuccessful, callStartBeforeUnix, callStartAfterUnix, callDurationMinSecs, callDurationMaxSecs, ratingMax, ratingMin, hasFeedbackComment, userId, evaluationParams, dataCollectionParams, toolNames, toolNamesSuccessful, toolNamesErrored, mainLanguages, pageSize, summaryMode, conversationInitiationSource, textOnly, conversationProductType, branchId, topicIds, sortBy, cursor, } = request;
            const _queryParams = {
                text_query: textQuery,
                agent_id: agentId,
                call_successful: callSuccessful != null
                    ? serializers.EvaluationSuccessResult.jsonOrThrow(callSuccessful, {
                        unrecognizedObjectKeys: "strip",
                    })
                    : undefined,
                call_start_before_unix: callStartBeforeUnix,
                call_start_after_unix: callStartAfterUnix,
                call_duration_min_secs: callDurationMinSecs,
                call_duration_max_secs: callDurationMaxSecs,
                rating_max: ratingMax,
                rating_min: ratingMin,
                has_feedback_comment: hasFeedbackComment,
                user_id: userId,
                evaluation_params: evaluationParams,
                data_collection_params: dataCollectionParams,
                tool_names: toolNames,
                tool_names_successful: toolNamesSuccessful,
                tool_names_errored: toolNamesErrored,
                main_languages: mainLanguages,
                page_size: pageSize,
                summary_mode: summaryMode != null
                    ? serializers.conversationalAi.conversations.MessagesTextSearchRequestSummaryMode.jsonOrThrow(summaryMode, { unrecognizedObjectKeys: "strip" })
                    : undefined,
                conversation_initiation_source: conversationInitiationSource != null
                    ? serializers.ConversationInitiationSource.jsonOrThrow(conversationInitiationSource, {
                        unrecognizedObjectKeys: "strip",
                    })
                    : undefined,
                text_only: textOnly,
                conversation_product_type: conversationProductType != null
                    ? serializers.ConversationProduct.jsonOrThrow(conversationProductType, {
                        unrecognizedObjectKeys: "strip",
                    })
                    : undefined,
                branch_id: branchId,
                topic_ids: topicIds,
                sort_by: sortBy != null
                    ? serializers.MessageSearchSortBy.jsonOrThrow(sortBy, { unrecognizedObjectKeys: "strip" })
                    : undefined,
                cursor,
            };
            const _headers = (0, headers_1.mergeHeaders)((_a = this._options) === null || _a === void 0 ? void 0 : _a.headers, (0, headers_1.mergeOnlyDefinedHeaders)({ "xi-api-key": (_b = requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.apiKey) !== null && _b !== void 0 ? _b : (_c = this._options) === null || _c === void 0 ? void 0 : _c.apiKey }), requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.headers);
            const _response = yield ((_d = this._options.fetcher) !== null && _d !== void 0 ? _d : core.fetcher)({
                url: core.url.join((_f = (_e = (yield core.Supplier.get(this._options.baseUrl))) !== null && _e !== void 0 ? _e : (yield core.Supplier.get(this._options.environment))) !== null && _f !== void 0 ? _f : environments.ElevenLabsEnvironment.Production, "v1/convai/conversations/messages/text-search"),
                method: "GET",
                headers: _headers,
                queryParameters: Object.assign(Object.assign({}, _queryParams), requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.queryParams),
                timeoutMs: ((_j = (_g = requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.timeoutInSeconds) !== null && _g !== void 0 ? _g : (_h = this._options) === null || _h === void 0 ? void 0 : _h.timeoutInSeconds) !== null && _j !== void 0 ? _j : 240) * 1000,
                maxRetries: (_k = requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.maxRetries) !== null && _k !== void 0 ? _k : (_l = this._options) === null || _l === void 0 ? void 0 : _l.maxRetries,
                abortSignal: requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.abortSignal,
                fetchFn: (_m = this._options) === null || _m === void 0 ? void 0 : _m.fetch,
                logging: this._options.logging,
            });
            if (_response.ok) {
                return {
                    data: serializers.MessagesSearchResponse.parseOrThrow(_response.body, {
                        unrecognizedObjectKeys: "passthrough",
                        allowUnrecognizedUnionMembers: true,
                        allowUnrecognizedEnumValues: true,
                        breadcrumbsPrefix: ["response"],
                    }),
                    rawResponse: _response.rawResponse,
                };
            }
            if (_response.error.reason === "status-code") {
                switch (_response.error.statusCode) {
                    case 422:
                        throw new ElevenLabs.UnprocessableEntityError(_response.error.body, _response.rawResponse);
                    default:
                        throw new errors.ElevenLabsError({
                            statusCode: _response.error.statusCode,
                            body: _response.error.body,
                            rawResponse: _response.rawResponse,
                        });
                }
            }
            return (0, handleNonStatusCodeError_1.handleNonStatusCodeError)(_response.error, _response.rawResponse, "GET", "/v1/convai/conversations/messages/text-search");
        });
    }
    /**
     * Search conversation transcripts by semantic similarity to surface relevant messages based on meaning and intent, rather than exact keyword matches
     *
     * @param {ElevenLabs.conversationalAi.conversations.MessagesSearchRequest} request
     * @param {MessagesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link ElevenLabs.UnprocessableEntityError}
     *
     * @example
     *     await client.conversationalAi.conversations.messages.search({
     *         textQuery: "Customer asking to cancel and get money back",
     *         agentId: "agent_id",
     *         pageSize: 1,
     *         cursor: "cursor"
     *     })
     */
    search(request, requestOptions) {
        return core.HttpResponsePromise.fromPromise(this.__search(request, requestOptions));
    }
    __search(request, requestOptions) {
        return __awaiter(this, void 0, void 0, function* () {
            var _a, _b, _c, _d, _e, _f, _g, _h, _j, _k, _l, _m;
            const { textQuery, agentId, pageSize, cursor } = request;
            const _queryParams = {
                text_query: textQuery,
                agent_id: agentId,
                page_size: pageSize,
                cursor,
            };
            const _headers = (0, headers_1.mergeHeaders)((_a = this._options) === null || _a === void 0 ? void 0 : _a.headers, (0, headers_1.mergeOnlyDefinedHeaders)({ "xi-api-key": (_b = requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.apiKey) !== null && _b !== void 0 ? _b : (_c = this._options) === null || _c === void 0 ? void 0 : _c.apiKey }), requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.headers);
            const _response = yield ((_d = this._options.fetcher) !== null && _d !== void 0 ? _d : core.fetcher)({
                url: core.url.join((_f = (_e = (yield core.Supplier.get(this._options.baseUrl))) !== null && _e !== void 0 ? _e : (yield core.Supplier.get(this._options.environment))) !== null && _f !== void 0 ? _f : environments.ElevenLabsEnvironment.Production, "v1/convai/conversations/messages/smart-search"),
                method: "GET",
                headers: _headers,
                queryParameters: Object.assign(Object.assign({}, _queryParams), requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.queryParams),
                timeoutMs: ((_j = (_g = requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.timeoutInSeconds) !== null && _g !== void 0 ? _g : (_h = this._options) === null || _h === void 0 ? void 0 : _h.timeoutInSeconds) !== null && _j !== void 0 ? _j : 240) * 1000,
                maxRetries: (_k = requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.maxRetries) !== null && _k !== void 0 ? _k : (_l = this._options) === null || _l === void 0 ? void 0 : _l.maxRetries,
                abortSignal: requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.abortSignal,
                fetchFn: (_m = this._options) === null || _m === void 0 ? void 0 : _m.fetch,
                logging: this._options.logging,
            });
            if (_response.ok) {
                return {
                    data: serializers.MessagesSearchResponse.parseOrThrow(_response.body, {
                        unrecognizedObjectKeys: "passthrough",
                        allowUnrecognizedUnionMembers: true,
                        allowUnrecognizedEnumValues: true,
                        breadcrumbsPrefix: ["response"],
                    }),
                    rawResponse: _response.rawResponse,
                };
            }
            if (_response.error.reason === "status-code") {
                switch (_response.error.statusCode) {
                    case 422:
                        throw new ElevenLabs.UnprocessableEntityError(_response.error.body, _response.rawResponse);
                    default:
                        throw new errors.ElevenLabsError({
                            statusCode: _response.error.statusCode,
                            body: _response.error.body,
                            rawResponse: _response.rawResponse,
                        });
                }
            }
            return (0, handleNonStatusCodeError_1.handleNonStatusCodeError)(_response.error, _response.rawResponse, "GET", "/v1/convai/conversations/messages/smart-search");
        });
    }
}
exports.MessagesClient = MessagesClient;
