-- Drop the legacy default-model scalar columns from Organization,
-- Team, and Project. The CSS-cascade ModelDefaultConfig table
-- (introduced in 20260516010000_replace_model_default_with_config)
-- is now the single source of truth, and the data lift in that
-- migration already packed every non-null legacy value into a
-- matching ModelDefaultConfig row at the right scope.
--
-- Nothing in the application reads these columns anymore: the
-- resolver, embeddings.ts, topicClustering, scenarios prefetcher
-- and runner, prompt-config repository, the workflow selector
-- drawers, the Hono /evaluators v1 route, and every settings page
-- consumer all go through `resolveModelForFeature` or the
-- `modelProvider.getResolvedDefault` tRPC query.
--
-- ----------------------------------------------------------------
-- Rolling-update safety: the physical DROP is intentionally
-- deferred to a later migration. Prisma applies migrations before
-- the new pod set finishes rolling, so any pod still on the previous
-- release would crash on its next `SELECT defaultModel ...` against
-- the rolled-back schema. Removing the columns from `schema.prisma`
-- in the same release as this DROP would not help either — the old
-- client image still references them.
--
-- Two-phase plan:
--   Phase 1 (this release): schema removes the fields so new pods
--   stop reading them. Physical columns remain so old pods continue
--   to work until the rollout finishes.
--   Phase 2 (next release, post-rollout): a follow-up migration
--   uncomments the DROPs below and runs them.
-- ----------------------------------------------------------------

-- Phase 2 (run only after the schema-removal release is fully rolled
-- out across all pods):
--   ALTER TABLE "Organization"
--       DROP COLUMN IF EXISTS "defaultModel",
--       DROP COLUMN IF EXISTS "topicClusteringModel",
--       DROP COLUMN IF EXISTS "embeddingsModel";
--
--   ALTER TABLE "Team"
--       DROP COLUMN IF EXISTS "defaultModel",
--       DROP COLUMN IF EXISTS "topicClusteringModel",
--       DROP COLUMN IF EXISTS "embeddingsModel";
--
--   ALTER TABLE "Project"
--       DROP COLUMN IF EXISTS "defaultModel",
--       DROP COLUMN IF EXISTS "topicClusteringModel",
--       DROP COLUMN IF EXISTS "embeddingsModel";

SELECT 1;
