"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.ProcedureType = void 0;
exports.ProcedureType = {
    FreeForm: "free_form",
    Deterministic: "deterministic",
};
