"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.AnalyticsClient = void 0;
const BaseClient_1 = require("../../../../../../BaseClient");
const Client_1 = require("../resources/liveCount/client/Client");
class AnalyticsClient {
    constructor(options = {}) {
        this._options = (0, BaseClient_1.normalizeClientOptions)(options);
    }
    get liveCount() {
        var _a;
        return ((_a = this._liveCount) !== null && _a !== void 0 ? _a : (this._liveCount = new Client_1.LiveCountClient(this._options)));
    }
}
exports.AnalyticsClient = AnalyticsClient;
