"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.ProjectListRequestSortDirection = void 0;
/** Sort by creation time (default 'DESCENDING'). */
exports.ProjectListRequestSortDirection = {
    Ascending: "ASCENDING",
    Descending: "DESCENDING",
};
