"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.VoiceDesignRequestModelModelId = void 0;
/** Model to use for the voice generation. Possible values: eleven_multilingual_ttv_v2, eleven_ttv_v3. */
exports.VoiceDesignRequestModelModelId = {
    ElevenMultilingualTtvV2: "eleven_multilingual_ttv_v2",
    ElevenTtvV3: "eleven_ttv_v3",
};
