/**
 * The URL surface of the application, transcribed from `platform/app`'s `routes.tsx` as
 * it stood before the route table moved into this package — every path in match order,
 * every layout nesting, every retired prefix and where it forwards to.
 */

export const expectedUiRouteTranscript: readonly string[] = [
  "layout -> auth",
  "  route /auth/signin -> pages/auth/signin",
  "  route /auth/signup -> pages/auth/signup",
  "  route /auth/forgot-password -> pages/auth/forgot-password",
  "  route /auth/reset-password -> pages/auth/reset-password",
  "  route /auth/verify-email -> pages/auth/verify-email",
  "  route /auth/error -> pages/auth/error",
  "  route /auth/join -> pages/auth/join",
  "  route /auth/sso-test-complete -> pages/auth/sso-test-complete",
  // Moved under the auth layout 2026-09-18: it is auth's own screen and reads
  // auth's host, which only this layout mounts.
  "  route /invite/accept -> pages/invite/accept",
  "redirect /admin -> /ops/cloud (from /admin)",
  "redirect /admin/* -> /ops (from /admin) [map user=users users=users organization=organizations organizations=organizations project=projects projects=projects sso-connections=sso-connections identity-lookup=identity-lookup directory-sync=directory-sync subscription=cloud/subscriptions subscriptions=cloud/subscriptions licenses=cloud/licenses self-hosted-instances=cloud/self-hosted-instances bug-reports=cloud/bug-reports]",
  "route /share/:id -> pages/share/[id]",
  "route /unsubscribe -> pages/unsubscribe",
  "route /onboarding -> pages/onboarding",
  "route /onboarding/:team/project -> pages/onboarding/[team]/project",
  "route /onboarding/product -> pages/onboarding/product/index",
  "route /onboarding/welcome -> pages/onboarding/welcome",
  "route /cli/auth -> pages/cli/auth",
  "route /authorize -> pages/authorize",
  "route /mcp/authorize -> pages/mcp/authorize",
  "route /:project/chat/:workflow -> pages/[project]/chat/[workflow]",
  "layout -> full-screen",
  "  layout -> layouts/trace-drawer",
  "    layout -> layouts/project-langy",
  "      route /:project/studio/:workflow -> pages/[project]/studio/[workflow]",
  "layout -> chrome",
  "  layout -> layouts/trace-drawer",
  "    route / -> pages/index",
  "    layout -> layouts/project-langy",
  "      route /settings -> pages/settings",
  "      redirect /settings/role-bindings -> /settings/roles (from /settings/role-bindings) [pin tab=assignments]",
  "      route /settings/annotation-scores -> pages/settings/annotation-scores",
  "      route /settings/data-retention -> pages/settings/data-retention",
  "      route /settings/integrations -> pages/settings/integrations",
  "      route /settings/data-privacy -> pages/settings/data-privacy",
  "      route /settings/audit-log -> pages/settings/audit-log",
  "      route /settings/authentication -> pages/settings/authentication",
  "      route /settings/authentication/provider -> pages/settings/authentication/provider",
  "      route /settings/authentication/connectors -> pages/settings/authentication/connectors",
  "      route /settings/security -> pages/settings/security",
  "      route /settings/directory -> pages/settings/directory",
  "      redirect /settings/groups -> /settings/directory (from /settings/groups) [pin tab=groups]",
  "      redirect /settings/access -> /settings/directory (from /settings/access)",
  "      route /settings/connect -> pages/settings/connect",
  "      route /settings/checkup -> pages/settings/checkup",
  "      route /settings/license -> pages/settings/license",
  "      redirect /settings/members -> /settings/directory (from /settings/members)",
  "      route /settings/model-costs -> pages/settings/model-costs",
  "      route /settings/model-providers -> pages/settings/model-providers",
  "      route /settings/plans -> pages/settings/plans",
  "      route /settings/roles -> pages/settings/roles",
  "      route /settings/api-keys -> pages/settings/api-keys",
  "      route /settings/profile -> pages/settings/profile",
  "      redirect /settings/scim -> /settings/directory (from /settings/scim)",
  "      route /settings/secrets -> pages/settings/secrets",
  "      route /settings/subscription -> pages/settings/subscription",
  "      redirect /settings/teams -> /settings/directory (from /settings/teams) [pin tab=teams]",
  "      route /settings/teams/:team -> pages/settings/teams/[team]",
  "      route /settings/topic-clustering -> pages/settings/topic-clustering",
  "      route /settings/usage -> pages/settings/usage",
  "      route /settings/email-suppressions -> pages/settings/email-suppressions",
  "      route /settings/* -> pages/settings/not-found",
  "      route /governance -> pages/governance/index",
  "      route /governance/inventory -> pages/governance/inventory.enterprise",
  "      route /governance/inventory/:id -> pages/governance/ingestion-source-detail.enterprise",
  "      route /governance/people -> pages/governance/people",
  "      route /governance/agents -> pages/governance/agents",
  "      route /governance/costs -> pages/governance/costs",
  "      route /governance/billed -> pages/governance/billed",
  "      route /governance/insights -> pages/governance/insights",
  "      route /governance/analytics -> pages/governance/analytics",
  "      route /governance/signals -> pages/governance/signals",
  "      redirect /governance/cost-centers -> /governance/people (from /governance/cost-centers)",
  "      route /governance/teams -> pages/governance/teams",
  "      route /governance/teams/:id -> pages/governance/teams/[id]",
  "      route /governance/users/:id -> pages/governance/users/[id]",
  "      route /me -> pages/me/index",
  "      route /me/configure -> pages/me/configure",
  "      redirect /me/devices -> /me/configure (from /me/devices) [pin tab=devices]",
  "      route /me/pull-requests -> pages/me/pull-requests",
  "      route /me/sessions -> pages/me/sessions",
  "      route /me/budget/request -> pages/me/budget/request",
  "      redirect /gateway -> /gateway/virtual-keys (from /gateway)",
  "      route /gateway/virtual-keys -> pages/gateway/virtual-keys",
  "      route /gateway/virtual-keys/:id -> pages/gateway/virtual-keys/[id]",
  "      route /gateway/budgets -> pages/gateway/budgets",
  "      route /gateway/budgets/:id -> pages/gateway/budgets/[id]",
  "      route /gateway/routing-policies -> pages/gateway/routing-policies",
  "      route /gateway/usage -> pages/gateway/usage",
  "      route /gateway/cache-rules -> pages/gateway/cache-rules",
  "      route /gateway/guardrails -> pages/gateway/guardrails",
  "      route /gateway/billing-events -> pages/gateway/billing-events",
  "      route /gateway/webhooks -> pages/gateway/webhooks",
  "      redirect /governance/ingestion-sources/* -> /governance/inventory (from /governance/ingestion-sources)",
  "      redirect /governance/ingestion-sources -> /governance/inventory (from /governance/ingestion-sources) [pin tab=sources]",
  "      redirect /governance/catalog/* -> /governance/inventory (from /governance/catalog)",
  "      redirect /governance/catalog -> /governance/inventory (from /governance/catalog) [pin tab=sources]",
  "      redirect /governance/tool-catalog -> /governance/inventory (from /governance/tool-catalog)",
  "      redirect /governance/departments -> /governance/people (from /governance/departments)",
  "      redirect /governance/anomaly-rules -> /governance/inventory (from /governance/anomaly-rules) [pin tab=anomaly-rules]",
  "      redirect /governance/users -> /governance/people (from /governance/users) [pin tab=people]",
  "      redirect /settings/gateway/* -> /gateway (from /settings/gateway)",
  "      redirect /settings/gateway -> /gateway (from /settings/gateway)",
  "      redirect /settings/governance/* -> /governance (from /settings/governance)",
  "      redirect /settings/governance -> /governance (from /settings/governance)",
  "      redirect /settings/routing-policies/* -> /gateway/routing-policies (from /settings/routing-policies)",
  "      redirect /settings/routing-policies -> /gateway/routing-policies (from /settings/routing-policies)",
  "    layout -> layouts/project-langy",
  "      route /:project/agents -> runtime/ui/features/agent-ui-host.adapter",
  "      route /:project/sessions -> pages/[project]/sessions",
  "      route /:project/pull-requests -> pages/[project]/pull-requests",
  "      route /:project/automations/activity -> pages/[project]/automations/activity",
  "      route /:project/evaluators -> pages/[project]/evaluators",
  "      redirect /:project/evaluations -> /:project/experiments (from /:project/evaluations)",
  "      redirect /:project/evaluations/new -> /:project/online-evaluations (from /:project/evaluations/new) [pin drawer.open=evaluatorCategorySelector]",
  "      redirect /:project/evaluations/new/choose -> /:project/online-evaluations (from /:project/evaluations/new/choose) [pin drawer.open=evaluatorCategorySelector]",
  "      redirect /:project/evaluations/wizard -> /:project/experiments/workbench (from /:project/evaluations/wizard)",
  "      route /:project/evaluations/wizard/:slug -> pages/[project]/evaluations/wizard/[slug]",
  "      route /:project/evaluations/:id/edit -> pages/[project]/evaluations/[id]/edit",
  "      route /:project/evaluations/:id/edit/choose -> pages/[project]/evaluations/[id]/edit/choose",
  "      route /:project/traces -> pages/[project]/traces",
  "      redirect /:project/traces/:trace -> /:project/traces (from /:project/traces/:trace) [pin drawer.open=traceV2Details drawer.traceId=:trace]",
  "      redirect /:project/messages -> /:project/traces (from /:project/messages)",
  "      redirect /:project/messages/:trace -> /:project/traces (from /:project/messages/:trace) [pin drawer.open=traceV2Details drawer.traceId=:trace]",
  "      redirect /:project/messages/:trace/:openTab -> /:project/traces (from /:project/messages/:trace/:openTab) [pin drawer.open=traceV2Details drawer.traceId=:trace]",
  "      redirect /:project/messages/:trace/:openTab/:span -> /:project/traces (from /:project/messages/:trace/:openTab/:span) [pin drawer.open=traceV2Details drawer.traceId=:trace drawer.span=:span]",
  "      route /:project/setup -> pages/[project]/setup",
  "      route /:project/workflows -> pages/[project]/workflows",
  "      route /:project/analytics -> pages/[project]/analytics/index",
  "      route /:project/analytics/evaluations -> pages/[project]/analytics/evaluations",
  "      route /:project/analytics/metrics -> pages/[project]/analytics/metrics",
  "      route /:project/analytics/reports -> pages/[project]/analytics/reports",
  "      route /:project/analytics/topics -> pages/[project]/analytics/topics",
  "      route /:project/analytics/users -> pages/[project]/analytics/users",
  "      route /:project/analytics/custom -> pages/[project]/analytics/custom/index",
  "      route /:project/analytics/custom/:id -> pages/[project]/analytics/custom/[id]",
  "      route /:project/dashboards -> pages/[project]/dashboards/index",
  "      route /:project/dashboards/:dashboardId -> pages/[project]/dashboards/[dashboardId]",
  "      route /:project/experiments -> pages/[project]/experiments/index",
  "      route /:project/experiments/workbench -> pages/[project]/experiments/workbench/index",
  "      route /:project/experiments/workbench/:slug -> pages/[project]/experiments/workbench/[slug]",
  "      route /:project/experiments/:experiment -> pages/[project]/experiments/[experiment]",
  "      route /:project/agent-testing -> pages/[project]/agent-testing/[[...path]]",
  "      route /:project/agent-testing/* -> pages/[project]/agent-testing/[[...path]]",
  "      route /:project/simulations/scenarios -> pages/[project]/simulations/scenarios/index",
  "      route /:project/simulations/* -> pages/[project]/simulations/[[...path]]",
  "      route /:project/simulations -> pages/[project]/simulations/[[...path]]",
  "    route /ops -> pages/ops/index",
  "    redirect /ops/queues -> /ops (from /ops/queues)",
  "    route /ops/dejaview -> pages/ops/dejaview",
  "    redirect /ops/scheduler -> /ops/event-sourcing/schedules (from /ops/scheduler)",
  "    route /ops/event-sourcing -> pages/ops/event-sourcing/index",
  "    route /ops/event-sourcing/dead-letters -> pages/ops/event-sourcing/dead-letters",
  "    route /ops/event-sourcing/processes -> pages/ops/event-sourcing/processes",
  "    route /ops/event-sourcing/projections -> pages/ops/event-sourcing/projections",
  "    route /ops/event-sourcing/subscribers -> pages/ops/event-sourcing/subscribers",
  "    route /ops/event-sourcing/schedules -> pages/ops/event-sourcing/schedules",
  "    route /ops/blobs -> pages/ops/blobs",
  "    route /ops/feature-flags -> pages/ops/feature-flags",
  "    route /ops/foundry -> pages/ops/foundry",
  "    route /ops/migrations -> pages/ops/migrations",
  "    redirect /ops/projections -> /ops/event-sourcing/projections (from /ops/projections) [pin replay=open]",
  "    route /ops/projections/:runId -> pages/ops/projections/[runId]",
  "    route /ops/operators -> pages/ops/operators",
  "    route /ops/users -> pages/ops/users",
  "    route /ops/organizations -> pages/ops/organizations",
  "    route /ops/projects -> pages/ops/projects",
  "    route /ops/sso-connections -> pages/ops/sso-connections",
  "    route /ops/identity-lookup -> pages/ops/identity-lookup",
  "    route /ops/directory-sync -> pages/ops/directory-sync",
  "    redirect /ops/cloud -> /ops/cloud/subscriptions (from /ops/cloud)",
  "    route /ops/cloud/subscriptions -> pages/ops/cloud/subscriptions",
  "    route /ops/cloud/licenses -> pages/ops/cloud/licenses",
  "    route /ops/cloud/self-hosted-instances -> pages/ops/cloud/self-hosted-instances",
  "    route /ops/cloud/bug-reports -> pages/ops/cloud/bug-reports",
  "    redirect /ops/backoffice -> /ops/cloud (from /ops/backoffice)",
  "    redirect /ops/backoffice/* -> /ops (from /ops/backoffice) [map user=users users=users organization=organizations organizations=organizations project=projects projects=projects sso-connections=sso-connections identity-lookup=identity-lookup directory-sync=directory-sync subscription=cloud/subscriptions subscriptions=cloud/subscriptions licenses=cloud/licenses self-hosted-instances=cloud/self-hosted-instances bug-reports=cloud/bug-reports]",
  "    route /@project/* -> pages/@project/[...path]/index",
  "  route * -> pages/not-found",
];
