"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.KnowledgeBaseSortBy = void 0;
exports.KnowledgeBaseSortBy = {
    Name: "name",
    CreatedAt: "created_at",
    UpdatedAt: "updated_at",
    Size: "size",
};
