"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.DubbingListRequestFilterByCreator = void 0;
/** Filters who created the resources being listed, whether it was the user running the request or someone else that shared the resource with them. */
exports.DubbingListRequestFilterByCreator = {
    Personal: "personal",
    Others: "others",
    All: "all",
};
