"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.BodyTextToSpeechFullApplyTextNormalization = void 0;
/** This parameter controls text normalization with three modes: 'auto', 'on', and 'off'. When set to 'auto', the system will automatically decide whether to apply text normalization (e.g., spelling out numbers). With 'on', text normalization will always be applied, while with 'off', it will be skipped. */
exports.BodyTextToSpeechFullApplyTextNormalization = {
    Auto: "auto",
    On: "on",
    Off: "off",
};
