"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.VoiceSafetyControl = void 0;
exports.VoiceSafetyControl = {
    None: "NONE",
    Ban: "BAN",
    Captcha: "CAPTCHA",
    EnterpriseBan: "ENTERPRISE_BAN",
    EnterpriseCaptcha: "ENTERPRISE_CAPTCHA",
};
