"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.TurnDetectionType = void 0;
exports.TurnDetectionType = {
    SemanticVad: "semantic_vad",
    ServerVad: "server_vad",
};
