/**
 * Central registry of every feature flag the application recognizes.
 *
 * Two kinds of entries:
 *
 *  - Explicit flag: a single named flag the registry knows by exact key.
 *  - Family: a key prefix that matches a set of dynamically-named flags
 *    sharing a scope and default. Event-sourcing kill switches use this —
 *    their keys (`es-<aggregate>-<component>-<name>-killswitch`) are
 *    generated at runtime from the pipeline graph.
 *
 * Resolution looks up exact keys first, then matches against family
 * prefixes. Anything not registered falls through to the legacy PostHog
 * path with a PRODUCT default so we never silently change behavior for
 * an unknown flag.
 *
 * Scope drives the resolver:
 *   - SYSTEM: env -> postgres -> default. PostHog is never consulted.
 *   - PRODUCT: env -> PostHog -> postgres -> default. PostHog stays the
 *     source of truth for user/A-B targeting; postgres is a self-hosted
 *     and emergency-override fallback.
 */

export type FeatureFlagScope = "SYSTEM" | "PRODUCT";

export interface FeatureFlagDefinition {
  key: string;
  scope: FeatureFlagScope;
  defaultValue: boolean;
  description: string;
  /** Surface for the operator UI; `null` for product flags. */
  family?: string;
  /**
   * Extra env-var name to honor on top of the auto-derived
   * UPPERCASE(key) name. Used when the flag is migrating from an
   * older, differently-named env var and we want existing operator
   * setups to keep working.
   */
  legacyEnvVar?: string;
}

export interface FeatureFlagFamily {
  keyPrefix: string;
  scope: FeatureFlagScope;
  defaultValue: boolean;
  description: string;
  family: string;
}

const EXPLICIT_FLAGS: FeatureFlagDefinition[] = [
  // ----- SYSTEM -----
  // Loop-prevention kill switch (PR #4048). Was a raw process.env read
  // (`LANGWATCH_DISABLE_CAUSALITY_LOOP_GUARD === "1"`), now a registered
  // SYSTEM flag so it can be flipped from the Ops UI without redeploy.
  // Env var still works via the standard env-override path.
  {
    key: "ops_es_causality_loop_guard_disabled",
    scope: "SYSTEM",
    defaultValue: false,
    description:
      "Disables the per-event evaluator causality-loop guard in the trace-processing reactor. Emergency only — bypasses the safeguard that stopped the 2026-05 outage.",
    family: "Event sourcing",
    legacyEnvVar: "LANGWATCH_DISABLE_CAUSALITY_LOOP_GUARD",
  },

  // ----- PRODUCT -----
  // Hot-ish per-project gate, but only checked on workflow execution
  // paths (post_event, runWorkflow, playground, topic clustering, model
  // provider routing) — not on /api/collector. PostHog targeting still
  // useful for per-project rollouts.
  {
    key: "release_nlp_go_engine_enabled",
    scope: "PRODUCT",
    defaultValue: false,
    description:
      "Routes a project's workflow / playground / topic-clustering traffic to the Go nlpgo service instead of the legacy Python langwatch_nlp pipeline.",
  },
  {
    key: "release_ui_sdk_radar_banner_card_enabled",
    scope: "PRODUCT",
    defaultValue: false,
    description: "Shows the SDK radar banner card on the home page.",
  },
  {
    key: "release_ui_dark_mode_enabled",
    scope: "PRODUCT",
    defaultValue: false,
    description: "Enables the dark-mode toggle in the user profile menu.",
  },
  {
    key: "release_ui_negate_filters_enabled",
    scope: "PRODUCT",
    defaultValue: false,
    description: "Enables negate-filter chips on the messages / traces filters.",
  },
  {
    key: "release_ui_ai_gateway_menu_enabled",
    scope: "PRODUCT",
    defaultValue: false,
    description: "Reveals the AI Gateway menu in the project sidebar.",
  },
  {
    key: "release_ui_traces_v2_enabled",
    scope: "PRODUCT",
    defaultValue: false,
    description: "Routes the /messages and trace detail surfaces to the v2 UI.",
  },
];

const FAMILIES: FeatureFlagFamily[] = [
  // Event-sourcing pipeline component kill switches. Names generated by
  // generateKillSwitchKey() in src/server/event-sourcing/utils/killSwitch.ts
  // as `es-<aggregate>-<componentType>-<componentName>-killswitch`. Default
  // is false (component runs) so absence of a row means "let it run".
  // This family is the one that drove the 2026-05 PostHog billing spike —
  // each new (tenant × component) combination minted a fresh cache key.
  {
    keyPrefix: "es-",
    scope: "SYSTEM",
    defaultValue: false,
    description:
      "Per-component kill switch for an event-sourcing projection, map-projection, or command. Setting to true disables that component cluster-wide.",
    family: "Event sourcing",
  },
];

const EXPLICIT_BY_KEY: Map<string, FeatureFlagDefinition> = new Map(
  EXPLICIT_FLAGS.map((f) => [f.key, f]),
);

/**
 * Resolve a flag key to its registered definition, preferring exact
 * matches over family-prefix matches. Returns undefined when the key
 * does not appear in either list — callers should fall through to a
 * legacy PostHog evaluation in that case (back-compat for flags that
 * existed before the registry).
 */
export function resolveFlagDefinition(
  key: string,
): FeatureFlagDefinition | undefined {
  const explicit = EXPLICIT_BY_KEY.get(key);
  if (explicit) return explicit;
  for (const fam of FAMILIES) {
    if (key.startsWith(fam.keyPrefix)) {
      return {
        key,
        scope: fam.scope,
        defaultValue: fam.defaultValue,
        description: fam.description,
        family: fam.family,
      };
    }
  }
  return undefined;
}

export function listExplicitFlags(): readonly FeatureFlagDefinition[] {
  return EXPLICIT_FLAGS;
}

export function listFamilies(): readonly FeatureFlagFamily[] {
  return FAMILIES;
}
