"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.BodyStreamComposedMusicWithADetailedResponseV1MusicDetailedStreamPostModelId = void 0;
/** The model to use for the generation. */
exports.BodyStreamComposedMusicWithADetailedResponseV1MusicDetailedStreamPostModelId = {
    MusicV1: "music_v1",
    MusicV2: "music_v2",
};
