/**
 * Developer-mode card gallery — every card Langy can produce, on demand.
 *
 * Most of Langy's UI only appears in response to a live agent turn: you cannot
 * see the "deleting a dashboard" card without deleting a dashboard, or the
 * agent-at-capacity error without the agent being at capacity. That made the
 * card kit effectively untestable by eye — you shipped a card, then waited for
 * the universe to produce the conditions that render it.
 *
 * This renders the whole kit from FIXTURES, in the panel, in place of the
 * conversation. Open it from ⋯ → Card gallery (developer mode only).
 *
 * The cards here are the REAL components fed real-shaped data — not mock-ups of
 * them. Every capability card goes through `LangyCapabilityRenderer` off a
 * genuine `langwatch.<resource>.<verb>` tool name, so the gallery also exercises
 * the registry: if a rename breaks the tool-name → card resolution, the card
 * silently disappears from this list, and that IS the bug.
 *
 * The error cards are generated by iterating `KNOWN_LANGY_ERROR_KINDS` through
 * `explainLangyError`, so a new backend error kind shows up here automatically
 * with whatever copy it was given (and a `suppress` kind correctly renders as
 * its connect card instead of an error — which is the behaviour item 19 hangs
 * on, made visible).
 */
import { Box, Button, HStack, Text, VStack } from "@chakra-ui/react";
import type { UIMessage } from "ai";
import { X } from "lucide-react";
import { IconButton } from "@chakra-ui/react";
import { LangyCard } from "~/features/asaplangy";
import { useLangyStore } from "../stores/langyStore";
import {
  explainLangyError,
  KNOWN_LANGY_ERROR_KINDS,
} from "../logic/langyErrorExplainer";
import { LangyCapabilityPendingCard } from "./capabilities/LangyCapabilityPendingCard";
import { LangyCapabilityRenderer } from "./capabilities/LangyCapabilityRenderer";
import { LangyError } from "./LangyError";
import { LangyFeedback } from "./LangyFeedback";
import { LangyGitHubConnectCard } from "./github/LangyGitHubConnectCard";
import { LangyGitHubPrCard } from "./github/LangyGitHubPrCard";
import { LangyGitHubProgressCard } from "./github/LangyGitHubProgressCard";
import { LangyPlanLimitCard } from "./LangyPlanLimitCard";
import { LangyRecoveringLine } from "./LangyRecoveringLine";
import { LangyToolActivity } from "./LangyToolActivity";
import { ProposalCard, type LangyProposal } from "./MessageContent";
import { StreamingStatusLine } from "./StreamingStatusLine";

/** A settled tool call, shaped exactly as the stream delivers one. */
function call(name: string, output: unknown, input: unknown = {}) {
  return { name, state: "output-available", input, output };
}

/** Fixed so the gallery's trace times don't drift between renders. */
const TRACE_FIXTURE_NOW = Date.parse("2026-07-11T14:03:00Z");

/**
 * One trace, in the shape `POST /api/trace/search` actually returns under
 * `--format json` (`traceSchema` in `server/tracer/types.ts`): snake_case ids,
 * `input`/`output` as `{ value }` envelopes, `timestamps.started_at` in epoch
 * ms, metrics nested. Fixtures that drift from the real shape are worse than no
 * fixtures — the card would render here and break in the panel.
 */
function traceFixture({
  id,
  startedAt,
  input,
  output,
  totalTimeMs,
  totalCost,
  error,
}: {
  id: string;
  startedAt: number;
  input: string;
  output?: string;
  totalTimeMs: number;
  totalCost: number;
  error?: { message: string };
}) {
  return {
    trace_id: id,
    project_id: "project_gallery",
    timestamps: { started_at: startedAt, inserted_at: startedAt },
    input: { value: input },
    ...(output ? { output: { value: output } } : {}),
    metrics: { total_time_ms: totalTimeMs, total_cost: totalCost },
    ...(error ? { error } : {}),
  };
}

/** The tool-call parts of an assistant message, as AI-SDK emits them. */
function toolMessage(
  parts: Array<{
    name: string;
    state: string;
    input?: unknown;
    output?: unknown;
  }>,
): UIMessage {
  return {
    id: "gallery",
    role: "assistant",
    parts: parts.map((part, index) => ({
      type: `tool-${part.name}`,
      toolCallId: `gallery-${index}`,
      state: part.state,
      input: part.input,
      output: part.output,
    })),
  } as unknown as UIMessage;
}

const PROPOSAL: LangyProposal = {
  langyProposal: true,
  kind: "create_evaluator",
  summary: "Add a Ragas faithfulness evaluator to this project",
  rationale:
    "38% of last week's traces answer with context the retriever never returned. A faithfulness check would catch that at ingestion.",
  payload: {},
};

const DESTRUCTIVE_PROPOSAL: LangyProposal = {
  langyProposal: true,
  kind: "delete_dashboard",
  summary: "Delete the “Legacy latency” dashboard",
  rationale: "Nothing has opened it in 90 days and both charts are broken.",
  destructive: true,
  payload: {},
};

export function LangyCardGallery() {
  const closeCardGallery = useLangyStore((s) => s.closeCardGallery);

  return (
    <VStack align="stretch" gap="18px" paddingX="19px" paddingY="16px">
      <HStack gap={2}>
        <VStack align="start" gap={0} flex={1} minWidth={0}>
          <Text textStyle="sm" fontWeight="600" color="fg">
            Card gallery
          </Text>
          <Text textStyle="2xs" color="fg.muted">
            Every card, from fixtures. Developer mode only.
          </Text>
        </VStack>
        <IconButton
          size="xs"
          variant="ghost"
          color="fg.muted"
          aria-label="Close card gallery"
          onClick={closeCardGallery}
        >
          <X size={15} />
        </IconButton>
      </HStack>

      {/* THE TAXONOMY, one card per intent, quietest → loudest. This is the
          reference kit the other card components migrate onto (asaplangy
          CARD_TAXONOMY): every card Langy renders is one of these five weights,
          and the ramp is the point — warmth is earned, spent only on `ask` and
          `spotlight`, so the low-weight receipts never shout. */}
      <Section title="Card taxonomy — by intent, quietest to loudest">
        <LangyCard
          intent="activity"
          overline="Working"
          title="Reading the checkout traces"
          showDot
          pulseDot
        />
        <LangyCard
          intent="progress"
          overline="In progress"
          title="Analysing 1,204 traces"
          pulseDot
        >
          <Box className="langy-pending-bar" width="full" />
        </LangyCard>
        <LangyCard
          intent="change"
          overline="Created"
          dot="green.fg"
          title="Faithfulness evaluator added"
        >
          <Text textStyle="xs" color="fg.muted">
            Ragas · scoped to this project
          </Text>
        </LangyCard>
        <LangyCard
          intent="ask"
          overline="Needs you"
          title="Add a Ragas faithfulness evaluator?"
          actions={
            <HStack gap={2}>
              <Button size="xs" colorPalette="orange">
                Apply
              </Button>
              <Button size="xs" variant="ghost">
                Discard
              </Button>
            </HStack>
          }
        >
          <Text textStyle="xs" color="fg.muted" lineHeight="1.45">
            38% of last week&apos;s traces answer with context the retriever
            never returned. A faithfulness check would catch that at ingestion.
          </Text>
        </LangyCard>
        <LangyCard
          intent="spotlight"
          overline="Result"
          title="34 traces matched “checkout”"
        >
          <Text textStyle="xs" color="fg.muted" lineHeight="1.45">
            A readable sample sits below; the full set opens in Traces.
          </Text>
        </LangyCard>
      </Section>

      <Section title="In progress">
        <LangyCapabilityPendingCard
          surface="traces"
          overline="Traces"
          headline="Searching traces"
          detail="status:error last 24h"
        />
        <LangyCapabilityPendingCard
          surface="evaluations"
          overline="Evaluations"
          headline="Creating evaluator"
        />
      </Section>

      {/* THE FIXTURES ARE THE REAL FRAMES.
          A gallery is only worth anything if it renders what the stream actually
          sends. These used to be tidied-up frames of our own invention, and they
          were more flattering than reality: the live stream sends a bare `bash`
          carrying a LangWatch command (which rendered "Coding") and opencode's
          `skill` tool (which rendered "Skill"), and neither shape appeared here,
          so the gallery showed a kit that looked fine while the product did not.
          Every frame below is now one the agent genuinely emits. */}
      <Section title="Activity — real frames from the live stream">
        <LangyToolActivity
          message={toolMessage([
            {
              // The exact frame behind the "SKILL / Skill" card.
              name: "skill",
              state: "output-available",
              input: { name: "github" },
            },
            {
              // The exact frame behind the "BASH / Coding…" card. It is a trace
              // search, and it must now say so — and render as a capability.
              name: "bash",
              state: "output-available",
              input: { command: "langwatch trace search --format json" },
              output: { traces: [{ id: "trace_a1", name: "checkout-agent" }] },
            },
            {
              name: "bash",
              state: "output-available",
              input: { command: "git push -u origin HEAD" },
            },
            {
              name: "bash",
              state: "input-available",
              input: { command: "pnpm test:unit src/foo" },
            },
            {
              name: "edit",
              state: "input-available",
              input: { file_path: "src/agents/router.ts" },
            },
          ])}
        />
      </Section>

      <Section title="Capabilities — reads">
        {/* The trace-sample card, fed the REAL search-result shape the CLI's
            `--format json` emits: `{ traces: [...Trace], pagination: {
            totalHits } }`, where a Trace carries `timestamps.started_at`,
            `input.value`, `metrics.total_time_ms` / `total_cost` and `error`.
            34 hits, 3 shown — the honesty rule the card exists to hold.
            The input is opencode's raw shell payload, because that is exactly
            what the CLI envelope forwards, and it is what the "View in Trace
            Explorer" link parses the agent's query back out of. */}
        <LangyCapabilityRenderer
          call={call(
            "langwatch.trace.search",
            {
              traces: [
                traceFixture({
                  id: "trace_a1",
                  startedAt: TRACE_FIXTURE_NOW - 4 * 60_000,
                  input: "Why was my card declined at checkout?",
                  totalTimeMs: 1240,
                  totalCost: 0.0041,
                  error: { message: "UpstreamTimeout: payments-api" },
                }),
                traceFixture({
                  id: "trace_b2",
                  startedAt: TRACE_FIXTURE_NOW - 9 * 60_000,
                  input: "Refund my last order please",
                  output: "I've started a refund for order #4471.",
                  totalTimeMs: 860,
                  totalCost: 0.0029,
                }),
                traceFixture({
                  id: "trace_c3",
                  startedAt: TRACE_FIXTURE_NOW - 21 * 60_000,
                  input: "Where is my delivery?",
                  output: "Your parcel is out for delivery today.",
                  totalTimeMs: 15_420,
                  totalCost: 0.0117,
                }),
              ],
              pagination: { totalHits: 34 },
            },
            {
              command:
                "langwatch trace search --query 'checkout' --start-date 1750000000000 --end-date 1750086400000 --limit 25 --format json",
            },
          )}
        />
        {/* The empty answer is a real answer, and it must not read as a failure. */}
        <LangyCapabilityRenderer
          call={call(
            "langwatch.trace.search",
            { traces: [], pagination: { totalHits: 0 } },
            {
              command: "langwatch trace search --query 'nothing matches this'",
            },
          )}
        />
        {/* THE TURN-LEVEL RULE — the two bugs this section exists to pin.
            The Analytics skill probes with several `trace search` calls, most of
            which match nothing, plus the one that actually answers ("4 random
            traces"). Fed through the SAME turn renderer the panel uses, only the
            answering search earns a card; the empty probes neither bury it (bug 1)
            nor stack into a wall (bug 2). Every frame is one the agent emits. */}
        <LangyToolActivity
          message={toolMessage([
            {
              name: "langwatch.trace.search",
              state: "output-available",
              input: {
                command:
                  "langwatch trace search --query 'status:error' --format json",
              },
              output: { traces: [], pagination: { totalHits: 0 } },
            },
            {
              name: "langwatch.trace.search",
              state: "output-available",
              input: {
                command:
                  "langwatch trace search --query 'latency>5s' --format json",
              },
              output: { traces: [], pagination: { totalHits: 0 } },
            },
            {
              name: "langwatch.trace.search",
              state: "output-available",
              input: {
                command: "langwatch trace search --limit 4 --format json",
              },
              output: {
                traces: [
                  traceFixture({
                    id: "trace_962a67260db8",
                    startedAt: TRACE_FIXTURE_NOW - 3 * 60_000,
                    input: "Summarise this thread for me",
                    output: "Here's the gist of the conversation…",
                    totalTimeMs: 16_701,
                    totalCost: 0.0182,
                  }),
                  traceFixture({
                    id: "trace_fe675be238fe",
                    startedAt: TRACE_FIXTURE_NOW - 7 * 60_000,
                    input: "What's the weather in Berlin?",
                    output: "It's 21°C and clear in Berlin.",
                    totalTimeMs: 940,
                    totalCost: 0.0021,
                  }),
                  traceFixture({
                    id: "trace_2917dd709ecc",
                    startedAt: TRACE_FIXTURE_NOW - 12 * 60_000,
                    input: "Draft a reply to this email",
                    output: "Sure — here's a draft you can send.",
                    totalTimeMs: 3_120,
                    totalCost: 0.0067,
                  }),
                  traceFixture({
                    id: "trace_780ddf5c44df",
                    startedAt: TRACE_FIXTURE_NOW - 18 * 60_000,
                    input: "Translate this paragraph to French",
                    output: "Voici la traduction…",
                    totalTimeMs: 2_040,
                    totalCost: 0.0044,
                  }),
                ],
                pagination: { totalHits: 71 },
              },
            },
            {
              name: "langwatch.trace.search",
              state: "output-available",
              input: {
                command:
                  "langwatch trace search --query 'cost>1' --format json",
              },
              output: { traces: [], pagination: { totalHits: 0 } },
            },
          ])}
        />
        <LangyCapabilityRenderer
          call={call("langwatch.dataset.list", {
            datasets: [{ id: "ds_1", name: "Golden questions" }],
          })}
        />
      </Section>

      <Section title="Capabilities — writes">
        <LangyCapabilityRenderer
          call={call("langwatch.evaluator.create", {
            id: "eval_new",
            name: "Faithfulness (Ragas)",
          })}
        />
        <LangyCapabilityRenderer
          call={call("langwatch.dashboard.delete", { id: "dash_legacy" })}
        />
      </Section>

      <Section title="Proposals">
        <ProposalCard
          proposal={PROPOSAL}
          isDiscarded={false}
          isApplying={false}
          onApply={() => undefined}
          onDiscard={() => undefined}
        />
        <ProposalCard
          proposal={DESTRUCTIVE_PROPOSAL}
          isDiscarded={false}
          isApplying={false}
          onApply={() => undefined}
          onDiscard={() => undefined}
        />
        <ProposalCard
          proposal={PROPOSAL}
          appliedOutcome={{ label: "Open evaluator", href: "#" }}
          isDiscarded={false}
          isApplying={false}
          onApply={() => undefined}
          onDiscard={() => undefined}
        />
      </Section>

      <Section title="Streaming">
        <StreamingStatusLine
          status="Analysing 1,204 traces"
          progress={0.62}
          metrics={[{ label: "Traces", value: 1204 }]}
          segment={{ index: 7, total: 11 }}
        />
        <LangyRecoveringLine message="Langy restarted — picking your reply back up…" />
      </Section>

      <Section title="GitHub">
        <LangyGitHubConnectCard organizationId="gallery" />
        <LangyGitHubProgressCard
          events={[
            { stage: "cloning", detail: "acme/checkout" },
            { stage: "branched", detail: "langy/fix-retriever" },
            { stage: "pushed", detail: "langy/fix-retriever" },
          ]}
        />
        {/* The rich card: everything `gh pr create`'s stdout gave us, enriched
            from the GitHub API with the user's own token. */}
        <LangyGitHubPrCard
          owner="acme"
          repo="checkout"
          number={412}
          url="https://github.com/acme/checkout/pull/412"
          state="open"
          title="Fix the retriever dropping the last chunk on long documents"
          headRef="langy/fix-retriever"
          baseRef="main"
          author="octocat"
          additions={38}
          deletions={12}
          changedFiles={3}
        />
        <LangyGitHubPrCard
          owner="acme"
          repo="checkout"
          number={413}
          url="https://github.com/acme/checkout/pull/413"
          state="draft"
          title="WIP: retry the turn when the worker restarts"
          headRef="langy/turn-recovery"
          baseRef="main"
          author="octocat"
          additions={210}
          deletions={4}
          changedFiles={9}
        />
        {/* DEGRADED. The PR opened — stdout said so — but the GitHub lookup
            failed (expired token / private repo / rate limit). The card shows
            what we KNOW and stops, rather than half-populating or showing an
            error where a pull request should be. */}
        <LangyGitHubPrCard
          owner="acme"
          repo="checkout"
          number={414}
          url="https://github.com/acme/checkout/pull/414"
          state="open"
        />
        <LangyGitHubPrCard
          owner="acme"
          repo="checkout"
          number={401}
          url="https://github.com/acme/checkout/pull/401"
          state="merged"
          title="Add the egress allow-list to the worker"
          headRef="langy/egress"
          baseRef="main"
          author="octocat"
          additions={64}
          deletions={0}
          changedFiles={2}
        />
        {/* A `gh pr create` that FAILED renders NO card at all — a PR that did
            not open must never look like one that did. Shown here as the tool
            activity it actually is. */}
        <LangyToolActivity
          message={
            {
              id: "gallery-pr-failed",
              role: "assistant",
              parts: [
                {
                  type: "tool-bash",
                  toolCallId: "pr-failed",
                  state: "output-error",
                  input: { command: "gh pr create --fill" },
                  errorText:
                    "pull request create failed: GraphQL: No commits between main and langy/fix",
                },
              ],
            } as never
          }
        />
      </Section>

      <Section title="Feedback">
        {/* "preview": a fixture must never pin over a live conversation's
            card or fire real shown-marks at the backend cadence. */}
        <LangyFeedback
          conversationId="gallery"
          messageId="gallery-feedback"
          origin="preview"
        />
      </Section>

      {/* A refusal the reader can DO something about — not a broken step, so
          not a red card. Fixture only; the real one reads its numbers off the
          failure's own meta, and the CTA only appears for whoever can change
          the plan. */}
      <Section title="Plan limits">
        <LangyPlanLimitCard
          presentation={{
            title: "Creating scenario failed",
            message: "Your plan includes 3 scenarios, and all 3 are in use.",
            code: "resource_limit_exceeded",
            limit: { label: "scenarios", type: "scenarios", current: 3, max: 3 },
            terminal: true,
          }}
        />
      </Section>

      {/* Generated from the error registry, so a new kind appears here for free
          — including `langy_github_not_connected`, which correctly renders as
          the connect card above rather than as an error at all. */}
      <Section title="Errors">
        {KNOWN_LANGY_ERROR_KINDS.map((kind) => (
          <LangyError
            key={kind}
            presentation={explainLangyError({
              code: kind,
              meta: {},
              httpStatus: 500,
            })}
            onAction={() => undefined}
          />
        ))}
        <LangyError
          presentation={explainLangyError({
            code: "unknown",
            meta: {},
            httpStatus: 500,
            traceId: "abc123",
          })}
          onAction={() => undefined}
        />
      </Section>
    </VStack>
  );
}

function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <VStack align="stretch" gap={2}>
      <Box
        textStyle="2xs"
        fontWeight="700"
        letterSpacing="0.07em"
        textTransform="uppercase"
        color="fg.subtle"
      >
        {title}
      </Box>
      {children}
    </VStack>
  );
}
