"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.SpeechHistoryItemResponseVoiceCategory = void 0;
exports.SpeechHistoryItemResponseVoiceCategory = {
    Premade: "premade",
    Cloned: "cloned",
    Generated: "generated",
    Professional: "professional",
};
