"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.ConfigEntityType = void 0;
/**
 * Entity types for the API configuration.
 *
 * This enum contains all valid entity type configurations that users can specify:
 * - Parent types (e.g., "name", "financial_id") that expand to all subtypes
 * - Specific subtypes using dot notation (e.g., "name.full_name")
 * - Standalone terminal types (e.g., "email_address")
 *
 * When converted for service use, parent types expand to all their terminal subtypes.
 */
exports.ConfigEntityType = {
    Name: "name",
    NameNameGiven: "name.name_given",
    NameNameFamily: "name.name_family",
    NameNameOther: "name.name_other",
    EmailAddress: "email_address",
    ContactNumber: "contact_number",
    Dob: "dob",
    Age: "age",
    ReligiousBelief: "religious_belief",
    PoliticalOpinion: "political_opinion",
    SexualOrientation: "sexual_orientation",
    EthnicityRace: "ethnicity_race",
    MaritalStatus: "marital_status",
    Occupation: "occupation",
    PhysicalAttribute: "physical_attribute",
    Language: "language",
    Username: "username",
    Password: "password",
    Url: "url",
    Organization: "organization",
    FinancialId: "financial_id",
    FinancialIdPaymentCard: "financial_id.payment_card",
    FinancialIdPaymentCardPaymentCardNumber: "financial_id.payment_card.payment_card_number",
    FinancialIdPaymentCardPaymentCardExpirationDate: "financial_id.payment_card.payment_card_expiration_date",
    FinancialIdPaymentCardPaymentCardCvv: "financial_id.payment_card.payment_card_cvv",
    FinancialIdBankAccount: "financial_id.bank_account",
    FinancialIdBankAccountBankAccountNumber: "financial_id.bank_account.bank_account_number",
    FinancialIdBankAccountBankRoutingNumber: "financial_id.bank_account.bank_routing_number",
    FinancialIdBankAccountSwiftBicCode: "financial_id.bank_account.swift_bic_code",
    FinancialIdFinancialIdOther: "financial_id.financial_id_other",
    Location: "location",
    LocationLocationAddress: "location.location_address",
    LocationLocationCity: "location.location_city",
    LocationLocationPostalCode: "location.location_postal_code",
    LocationLocationCoordinate: "location.location_coordinate",
    LocationLocationState: "location.location_state",
    LocationLocationCountry: "location.location_country",
    LocationLocationOther: "location.location_other",
    Date: "date",
    DateInterval: "date_interval",
    UniqueId: "unique_id",
    UniqueIdGovernmentIssuedId: "unique_id.government_issued_id",
    UniqueIdAccountNumber: "unique_id.account_number",
    UniqueIdVehicleId: "unique_id.vehicle_id",
    UniqueIdHealthcareNumber: "unique_id.healthcare_number",
    UniqueIdHealthcareNumberMedicalRecordNumber: "unique_id.healthcare_number.medical_record_number",
    UniqueIdHealthcareNumberHealthPlanBeneficiaryNumber: "unique_id.healthcare_number.health_plan_beneficiary_number",
    UniqueIdDeviceId: "unique_id.device_id",
    UniqueIdUniqueIdOther: "unique_id.unique_id_other",
    Medical: "medical",
    MedicalMedicalCondition: "medical.medical_condition",
    MedicalMedication: "medical.medication",
    MedicalMedicalProcedure: "medical.medical_procedure",
    MedicalMedicalMeasurement: "medical.medical_measurement",
    MedicalMedicalOther: "medical.medical_other",
};
