/**
 * The workflow module's application: what all five of its doors call. A caller
 * arrives as an argument, never read from a session or a request, so one
 * operation serves a browser session, an API key and a background job alike.
 */
import type { DatasetApi } from "@langwatch/dataset-contract";
import type { Evaluator, EvaluatorApi } from "@langwatch/evaluator-contract";
import type { AuthzPermission } from "@langwatch/authz-contract";
import {
  clearDsl,
  recursiveAlphabeticallySortedKeys,
  WorkflowApi,
  WorkflowExecutionFailedError,
  type ArchiveWorkflowCommand,
  type CopyStudioWorkflowCommand,
  type CopyWorkflowCommand,
  type CreateWorkflowCommand,
  type ExecuteWorkflowComponentInput,
  type LLMConfig,
  type PublishWorkflowCommand,
  type RunWorkflowCommand,
  type StudioClientEvent,
  type StudioServerEvent,
  type StudioWorkflow,
  type UpdateWorkflowCommand,
  type Workflow,
  type WorkflowCaller,
  type WorkflowCascadeArchive,
  type WorkflowCopiesRow,
  type WorkflowCopyWithPath,
  type WorkflowDsl,
  type WorkflowEvaluationRequest,
  type WorkflowEvaluationStarted,
  type WorkflowLineageRow,
  type WorkflowListRow,
  type WorkflowPublicationFlags,
  type WorkflowReference,
  type WorkflowRelatedEntities,
  type WorkflowRunAnswer,
  type WorkflowRunOrigin,
  type WorkflowSourceRow,
  type WorkflowVersion,
  type WorkflowVersionHistoryEntry,
  type WorkflowVersionHistoryMode,
  type WorkflowWithVersion,
} from "@langwatch/workflow-contract";
import type { WorkflowService } from "../services/workflow.service.ts";
import type { FeatureSetup } from "@langwatch/runtime-composition";
import type { Instant } from "@langwatch/time";
import { nanoid } from "nanoid";
import type { WorkflowRowRepository } from "../repositories/workflow-row.repository.ts";
import type { WorkflowStudioDispatchService } from "../services/workflow-studio-dispatch.service.ts";
import { WorkflowStudioCopyService } from "../services/workflow-studio-copy.service.ts";
import { WorkflowStudioVersionService } from "../services/workflow-studio-version.service.ts";

/** Whether one person may act on a project other than the scoped one. */
export interface WorkflowPermissionProbe {
  has(input: {
    userId: string;
    projectId: string;
    permission: AuthzPermission;
  }): Promise<boolean>;
  /**
   * The same probe for many projects at once. Bounded concurrency is the
   * process's concern - a workflow with many copies must not exhaust its
   * connection pool - so the cap lives with whoever owns the pool.
   */
  hasMany(input: {
    userId: string;
    projectIds: readonly string[];
    permission: AuthzPermission;
  }): Promise<ReadonlyMap<string, boolean>>;
}

/**
 * The reads a workflow's lineage and its archive cascade are made of: the
 * process's rows rather than this module's, since a copy names a project, a
 * team and an organization.
 */
export interface WorkflowLineageReads {
  listWithCopyLineage(input: {
    projectId: string;
  }): Promise<readonly WorkflowLineageRow[]>;
  findWorkflow(input: {
    workflowId: string;
    projectId: string;
  }): Promise<Readonly<{ projectId: string }> | null>;
  findCopiesWithPath(input: {
    workflowId: string;
    projectId: string;
  }): Promise<readonly WorkflowCopyWithPath[] | null>;
  findWorkflowWithSource(input: {
    workflowId: string;
    projectId: string;
  }): Promise<WorkflowSourceRow | null>;
  findWorkflowWithCopies(input: {
    workflowId: string;
    projectId: string;
  }): Promise<WorkflowCopiesRow | null>;
  /**
   * The latest version NUMBER of one workflow. Null when the workflow row is
   * gone; `version: null` when it exists but has no latest version.
   */
  findLatestVersionNumber(input: {
    workflowId: string;
    projectId: string;
  }): Promise<Readonly<{ version: string | null }> | null>;
  listAgents(input: {
    workflowId: string;
    projectId: string;
  }): Promise<readonly Readonly<{ id: string; name: string }>[]>;
  listMonitorsForEvaluators(input: {
    projectId: string;
    evaluatorIds: readonly string[];
  }): Promise<readonly Readonly<{ id: string; name: string; evaluatorId: string }>[]>;
  cascadeArchive(input: {
    projectId: string;
    workflowId: string;
    unarchive?: boolean;
  }): Promise<WorkflowCascadeArchive>;
}

/** The publication flags the Optimization Studio reads and writes. */
export interface WorkflowPublicationReads {
  findFlags(input: {
    workflowId: string;
    projectId: string;
  }): Promise<WorkflowPublicationFlags | null>;
  findVersion(input: {
    versionId: string;
    projectId: string;
  }): Promise<Readonly<Record<string, unknown>> | null>;
  setFlags(input: {
    workflowId: string;
    projectId: string;
    isComponent?: boolean;
    isEvaluator?: boolean;
  }): Promise<void>;
  listPublishedComponents(input: { projectId: string }): Promise<unknown>;
}

/** The model call behind an autogenerated commit message. */
export interface WorkflowCommitMessageWriter {
  generate(input: {
    projectId: string;
    previousDsl: string;
    nextDsl: string;
  }): Promise<string>;
}

/** Starting one evaluation run through the deployment's evaluations pipeline. */
export interface WorkflowEvaluationTrigger {
  trigger(input: WorkflowEvaluationRequest): Promise<WorkflowEvaluationStarted>;
}

/** One Monaco completion for the studio's code editor. */
export interface WorkflowCodeCompletions {
  complete(input: { projectId: string; body: unknown }): Promise<unknown>;
}

/** One streaming studio run, opened and read back event by event. */
export interface WorkflowStudioRuns {
  postEvent(input: {
    projectId: string;
    event: StudioClientEvent;
    onEvent: (event: StudioServerEvent) => void;
  }): Promise<void>;
}

/** Where a product signal and an unexpected failure go. */
export interface WorkflowSignals {
  workflowCreated(input: {
    userId: string;
    workflowCount: number;
    workflowId: string;
    projectId: string;
  }): void;
  failed(error: unknown, context: Readonly<{ projectId?: string }>): void;
}

/** One deployed NLP Lambda function, reduced to what the cleanup policy reads. */
export type NlpLambdaFunction = Readonly<{ name: string }>;

/**
 * The account's per-project NLP Lambda functions and their log groups. A
 * technical need rather than a store: the cutoffs are this module's decision,
 * the AWS account they are applied to is the deployment's.
 */
export interface NlpLambdaFleet {
  /** Every function whose name starts with the studio's engine prefix. */
  listFunctions(input: { namePrefix: string }): Promise<readonly NlpLambdaFunction[]>;
  /**
   * When the function last logged, or null when nothing says. Null is not
   * "never used": a missing log group is also unknown, and the policy declines
   * to delete on an unknown rather than guessing.
   */
  tryReadLastActivityAt(input: { functionName: string }): Promise<Instant | null>;
  /** True when the function still exists in the account. */
  functionExists(input: { functionName: string }): Promise<boolean>;
  deleteFunction(input: { functionName: string }): Promise<void>;
  /** Every log group under the studio's engine prefix, by function name. */
  listLogGroups(input: { namePrefix: string }): Promise<readonly string[]>;
  deleteLogGroup(input: { functionName: string }): Promise<void>;
}

/**
 * A cluster-wide store with an expiry for a project's resolved NLP Lambda ARN.
 * Redis in production; a process with none composes an in-memory stand-in,
 * which is slower rather than wrong.
 */
export interface NlpLambdaArnCache {
  tryGet(key: string): Promise<string | null>;
  set(input: { key: string; value: string; ttlSeconds: number }): Promise<void>;
  delete(key: string): Promise<void>;
}

/** What the process supplies this module beside its own graph. */
export interface WorkflowInfrastructure {
  /** Where a studio component executes; absent means nothing executes. */
  studioDispatch?: WorkflowStudioDispatchService;
  /** The ONE workflow graph service on this process. */
  workflows: WorkflowService;
  /** The evaluators a workflow is published as. */
  evaluators: EvaluatorApi;
  /** The dataset copies a Studio graph carries with it into another project. */
  datasets: DatasetApi;
  /** How a Studio graph is prepared before any version of it is written. */
  studioDsl: WorkflowStudioDsl;
  /** The agent mappings a saved Studio graph refreshes, best effort. */
  agentMappings: WorkflowAgentMapping;
  /** The bare row a Studio copy lands in, before its first version exists. */
  workflowRows: WorkflowRowRepository;
  /** Executes a workflow run; absent means nothing executes. */
  execution: WorkflowExecution;
  /** Where a studio graph and a code evaluator both execute. */
  nlpRuntime: WorkflowNlpRuntime;
  /** The engine's streaming studio route, as bytes. */
  studioStream: WorkflowStudioStream;
  /** Mints workflow and version ids. */
  ids: WorkflowId;
  /** Upgrades a persisted graph before it becomes the workflow's current version. */
  dslMigration: WorkflowDslMigration;
  /** Project credentials and decrypted secrets. */
  projectEnvironment: WorkflowProjectEnvironment;
  /** Resolves process-specific LiteLLM credentials without exposing provider rows. */
  llmParameters: WorkflowLlmParameters;
  permissions: WorkflowPermissionProbe;
  lineage: WorkflowLineageReads;
  publications: WorkflowPublicationReads;
  commitMessages: WorkflowCommitMessageWriter;
  evaluations: WorkflowEvaluationTrigger;
  codeCompletions: WorkflowCodeCompletions;
  studioRuns: WorkflowStudioRuns;
  signals: WorkflowSignals;
  nlpLambdaArnResolver: NlpLambdaArnResolver;
  nlpLambdaFunction: NlpLambdaFunctionPort;
  nlpLambdaInvoke: NlpLambdaInvoke;
  nlpLambdaStreamInvoke: NlpLambdaStreamInvoke;
  nlpPayloadStaging: NlpPayloadStaging;
  workflowAiCall: WorkflowAiCall;
  workflowCommitMessageModel: WorkflowCommitMessageModel;
}

type WorkflowSetup = FeatureSetup<
  typeof WorkflowApp.dependencies,
  WorkflowInfrastructure,
  undefined
>;

/** The comparable text of a graph: local configuration stripped, keys sorted. */
function comparableDsl(dsl: StudioWorkflow): string {
  return JSON.stringify(recursiveAlphabeticallySortedKeys(clearDsl(dsl)), null, 2);
}

/** Every project id a workflow's copy lineage names, source and copies alike. */
function relatedProjectIdsOf(workflow: WorkflowLineageRow): readonly string[] {
  return [
    ...(workflow.copiedFrom ? [workflow.copiedFrom.projectId] : []),
    ...workflow.copiedWorkflows.map((copy) => copy.projectId),
  ];
}

export class WorkflowApp implements WorkflowApi {
  static readonly contract = WorkflowApi;
  static readonly dependencies = {} as const;

  static create(setup: WorkflowSetup): WorkflowApp {
    return new WorkflowApp(setup.infrastructure);
  }

  #infrastructure: WorkflowInfrastructure;
  #studioVersions: WorkflowStudioVersionService;
  #studioCopies: WorkflowStudioCopyService;

  private constructor(infrastructure: WorkflowInfrastructure) {
    this.#infrastructure = infrastructure;
    this.#studioVersions = WorkflowStudioVersionService.create({
      workflows: infrastructure.workflows,
      studioDsl: infrastructure.studioDsl,
      agentMappings: infrastructure.agentMappings,
    });
    this.#studioCopies = WorkflowStudioCopyService.create({
      datasets: infrastructure.datasets,
      rows: infrastructure.workflowRows,
    });
  }

  // -- the workflow itself ---------------------------------------------------

  async executeComponent(input: ExecuteWorkflowComponentInput) {
    const dispatch = this.#infrastructure.studioDispatch;

    if (!dispatch) throw new WorkflowExecutionFailedError();

    return dispatch.executeComponent(input);
  }

  /** Every non-archived workflow in the project. */
  list(input: { projectId: string }): Promise<Workflow[]> {
    return this.#infrastructure.workflows.list(input);
  }

  /** One workflow, optionally with its current version. */
  getById(input: {
    id: string;
    projectId: string;
    includeVersion?: boolean;
  }): Promise<WorkflowWithVersion> {
    return this.#infrastructure.workflows.getById(input);
  }

  /** Verifies that a workflow belongs to the requested project. */
  assertInProject(input: { workflowId: string; projectId: string }): Promise<void> {
    return this.#infrastructure.workflows.assertInProject(input);
  }

  listFields(input: { projectId: string; workflowIds: string[] }) {
    return this.#infrastructure.workflows.listFields(input);
  }

  listSummaries(input: { projectId: string; workflowIds: string[] }) {
    return this.#infrastructure.workflows.listSummaries(input);
  }

  archiveLinked(input: WorkflowReference) {
    return this.#infrastructure.workflows.archiveLinked(input);
  }

  deleteUncommitted(input: WorkflowReference) {
    return this.#infrastructure.workflows.deleteUncommitted(input);
  }

  /**
   * One studio event, resolved against the project it will run in: its
   * environment, its LiteLLM parameters and the datasets it names.
   */
  prepareStudioEvent(input: {
    event: StudioClientEvent;
    projectId: string;
  }): Promise<StudioClientEvent> {
    return this.#infrastructure.workflows.prepareStudioEvent(input);
  }

  /** A peer's inbound Studio event, prepared the same way before it re-enters the graph. */
  enrichStudioEvent(input: {
    event: StudioClientEvent;
    projectId: string;
  }): Promise<StudioClientEvent> {
    return this.#infrastructure.workflows.enrichStudioEvent(input);
  }

  /** The evaluator-fields shape a peer's guard and run read off this workflow. */
  getFields(input: { workflowId: string; projectId: string }) {
    return this.#infrastructure.workflows.getFields(input);
  }

  /**
   * Creates a workflow and its first version, attributed to its caller, and
   * fires the product signal a project's new workflow raises. Attribution is
   * here because who wrote a version is a property of the act, not the door.
   */
  async create(
    input: Omit<CreateWorkflowCommand, "authorId">,
    by: WorkflowCaller,
  ): Promise<{ workflow: WorkflowWithVersion; version: WorkflowVersion }> {
    const created = await this.#infrastructure.workflows.create({ ...input, authorId: by.id });

    this.#announceCreated({ workflowId: created.workflow.id, projectId: input.projectId, by });

    return created;
  }

  /** Copies a workflow into another project, attributed to its caller. */
  copy(
    input: Omit<CopyWorkflowCommand, "authorId">,
    by: WorkflowCaller,
  ): Promise<{ workflow: WorkflowWithVersion; version: WorkflowVersion }> {
    return this.#infrastructure.workflows.copy({ ...input, authorId: by.id });
  }

  /** Changes a workflow's own metadata: its name, its icon, its description. */
  update(input: UpdateWorkflowCommand): Promise<Workflow> {
    return this.#infrastructure.workflows.update(input);
  }

  /** The version history of one workflow. */
  getVersionHistory(input: {
    workflowId: string;
    projectId: string;
    mode: WorkflowVersionHistoryMode;
  }): Promise<WorkflowVersionHistoryEntry[]> {
    return this.#infrastructure.workflows.getVersionHistory(input);
  }

  /** Makes a stored version current again. */
  restoreVersion(input: { versionId: string; projectId: string }): Promise<WorkflowVersion> {
    return this.#infrastructure.workflows.restoreVersion(input);
  }

  /** Publishes one version, attributed to the caller who asked for it. */
  publish(input: Omit<PublishWorkflowCommand, "actorId">, by: WorkflowCaller): Promise<Workflow> {
    return this.#infrastructure.workflows.publish({ ...input, actorId: by.id });
  }

  /** Withdraws the published version. */
  unpublish(input: { id: string; projectId: string }): Promise<Workflow> {
    return this.#infrastructure.workflows.unpublish(input);
  }

  /** Archives one workflow, or restores it when `unarchive` is set. */
  archive(input: ArchiveWorkflowCommand): Promise<Workflow> {
    return this.#infrastructure.workflows.archive(input);
  }

  /** Runs a workflow synchronously, on its published version unless one is named. */
  run(input: RunWorkflowCommand): Promise<WorkflowRunAnswer> {
    return this.#infrastructure.workflows.run(input);
  }

  /**
   * Runs the project's published workflow once, on the same service the public
   * run endpoint dispatches through.
   */
  runPublished(input: {
    workflowId: string;
    projectId: string;
    body: Readonly<Record<string, unknown>>;
  }): Promise<WorkflowRunAnswer> {
    return this.#infrastructure.workflows.run({
      workflowId: input.workflowId,
      projectId: input.projectId,
      inputs: { ...input.body },
    });
  }

  /** Starts one evaluation run of a committed version. */
  triggerEvaluation(input: WorkflowEvaluationRequest): Promise<WorkflowEvaluationStarted> {
    return this.#infrastructure.evaluations.trigger(input);
  }

  // -- the Studio's own save and copy ----------------------------------------

  /**
   * Prepares a Studio graph the way saving one does, without writing anything,
   * so what executes is the same graph a save would have persisted.
   */
  prepareStudioDsl(input: { projectId: string; dsl: StudioWorkflow }): Promise<StudioWorkflow> {
    return this.#studioVersions.prepareDsl(input);
  }

  /**
   * Writes a Studio graph as a version, attributed to the caller who asked for
   * it, and refreshes the agent mappings the new graph implies.
   */
  saveStudioVersion(
    input: {
      projectId: string;
      workflowId: string;
      dsl: StudioWorkflow;
      autoSaved: boolean;
      commitMessage: string;
      setAsLatestVersion?: boolean;
    },
    by: WorkflowCaller,
  ): Promise<WorkflowVersion> {
    return this.#studioVersions.saveOrCommit({ ...input, authorId: by.id });
  }

  /**
   * Copies a workflow into another project and answers the new row's id with
   * the graph rewritten to belong to it. The caller commits its first version.
   */
  copyStudioWorkflow(
    input: CopyStudioWorkflowCommand,
  ): Promise<{ workflowId: string; dsl: StudioWorkflow }> {
    return this.#studioCopies.copyWithDatasets(input);
  }

  completeCode(input: { projectId: string; body: unknown }): Promise<unknown> {
    return this.#infrastructure.codeCompletions.complete(input);
  }

  postStudioEvent(input: {
    projectId: string;
    event: StudioClientEvent;
    onEvent: (event: StudioServerEvent) => void;
  }): Promise<void> {
    return this.#infrastructure.studioRuns.postEvent(input);
  }

  reportStudioFailure(error: unknown, context: { projectId: string }): void {
    this.#infrastructure.signals.failed(error, context);
  }

  /**
   * A short commit message for the change between two graphs, both normalised
   * first - local configuration stripped, keys sorted - so a reordering never
   * reaches a model.
   */
  async generateCommitMessage(input: {
    projectId: string;
    prevDsl: StudioWorkflow;
    newDsl: StudioWorkflow;
  }): Promise<string> {
    const previousDsl = comparableDsl(input.prevDsl);
    const nextDsl = comparableDsl(input.newDsl);

    if (previousDsl === nextDsl) return "no changes";

    return await this.#infrastructure.commitMessages.generate({
      projectId: input.projectId,
      previousDsl,
      nextDsl,
    });
  }

  // -- the evaluator a published workflow is wrapped in -----------------------

  /** Every evaluator in the project. */
  listEvaluators(input: { projectId: string }): Promise<Evaluator[]> {
    return this.#infrastructure.evaluators.getAll(input);
  }

  /**
   * Create-or-rename rather than create: a workflow republished after a rename
   * must not leave the picker showing the old name, and a second evaluator for
   * one workflow would be two rows the picker cannot tell apart.
   */
  async linkEvaluatorToWorkflow(input: {
    workflowId: string;
    projectId: string;
    name: string;
  }): Promise<Evaluator> {
    const { workflowId, projectId, name } = input;
    const [existing] = await this.#infrastructure.evaluators.listByWorkflow({
      workflowId,
      projectId,
    });

    if (existing) {
      return this.#infrastructure.evaluators.update({
        id: existing.id,
        projectId,
        data: { name },
      });
    }

    return this.#infrastructure.evaluators.create({
      id: `evaluator_${nanoid()}`,
      projectId,
      name,
      type: "workflow",
      config: {},
      workflowId,
    });
  }

  /**
   * Nothing may keep an evaluator pointing at a workflow that no longer offers
   * itself as one. A workflow never published as an evaluator has nothing to
   * archive, which is a no-op rather than a refusal.
   */
  async unlinkEvaluatorFromWorkflow(input: {
    workflowId: string;
    projectId: string;
  }): Promise<void> {
    const [linked] = await this.#infrastructure.evaluators.listByWorkflow(input);

    if (!linked) return;

    await this.#infrastructure.evaluators.archive({
      id: linked.id,
      projectId: input.projectId,
    });
  }

  // -- what the caller may see elsewhere -------------------------------------

  hasProjectPermission(input: {
    userId: string;
    projectId: string;
    permission: AuthzPermission;
  }): Promise<boolean> {
    return this.#infrastructure.permissions.has(input);
  }

  // -- copy lineage, related entities and the archive cascade ----------------

  /**
   * The project's workflows, with copy lineage redacted to what the caller may
   * see: a source workflow in a project they cannot view is hidden entirely,
   * and the copy count only counts copies they can view.
   */
  async listWithCopyLineage(input: {
    projectId: string;
    viewerUserId: string;
  }): Promise<WorkflowListRow[]> {
    const workflows = await this.#infrastructure.lineage.listWithCopyLineage({
      projectId: input.projectId,
    });

    const relatedProjectIds = [...new Set(workflows.flatMap(relatedProjectIdsOf))];
    const probed = await this.#infrastructure.permissions.hasMany({
      userId: input.viewerUserId,
      projectIds: relatedProjectIds.filter((projectId) => projectId !== input.projectId),
      permission: "workflows:view",
    });
    const isVisible = (projectId: string) =>
      projectId === input.projectId || probed.get(projectId) === true;

    return workflows.map(({ copiedWorkflows, ...workflow }) => {
      const canSeeSource = workflow.copiedFrom !== null && isVisible(workflow.copiedFrom.projectId);

      return {
        ...workflow,
        copiedFromWorkflowId: canSeeSource ? workflow.copiedFromWorkflowId : null,
        copiedFrom: canSeeSource ? workflow.copiedFrom : null,
        _count: {
          copiedWorkflows: copiedWorkflows.filter((copy) => isVisible(copy.projectId)).length,
        },
      };
    });
  }

  findWorkflowOwner(input: {
    workflowId: string;
    projectId: string;
  }): Promise<Readonly<{ projectId: string }> | null> {
    return this.#infrastructure.lineage.findWorkflow(input);
  }

  findCopiesWithPath(input: {
    workflowId: string;
    projectId: string;
  }): Promise<readonly WorkflowCopyWithPath[] | null> {
    return this.#infrastructure.lineage.findCopiesWithPath(input);
  }

  findWorkflowWithSource(input: {
    workflowId: string;
    projectId: string;
  }): Promise<WorkflowSourceRow | null> {
    return this.#infrastructure.lineage.findWorkflowWithSource(input);
  }

  findWorkflowWithCopies(input: {
    workflowId: string;
    projectId: string;
  }): Promise<WorkflowCopiesRow | null> {
    return this.#infrastructure.lineage.findWorkflowWithCopies(input);
  }

  findLatestVersionNumber(input: {
    workflowId: string;
    projectId: string;
  }): Promise<Readonly<{ version: string | null }> | null> {
    return this.#infrastructure.lineage.findLatestVersionNumber(input);
  }

  /**
   * What archiving this workflow would take with it - the evaluators and
   * agents bound to it, and the monitors those evaluators back.
   */
  async getRelatedEntities(input: {
    workflowId: string;
    projectId: string;
  }): Promise<WorkflowRelatedEntities> {
    const evaluators = (await this.listEvaluators({ projectId: input.projectId }))
      .filter((evaluator) => evaluator.workflowId === input.workflowId)
      .map(({ id, name }) => ({ id, name }));

    // Copied out of the readonly views: the confirmation dialog these lists
    // feed types them as plain arrays, and a readonly element type would
    // narrow a client payload that is identical on the wire.
    const agents = [...(await this.#infrastructure.lineage.listAgents(input))];

    const evaluatorIds = evaluators.map((evaluator) => evaluator.id);
    const monitors =
      evaluatorIds.length > 0
        ? [
            ...(await this.#infrastructure.lineage.listMonitorsForEvaluators({
              projectId: input.projectId,
              evaluatorIds,
            })),
          ]
        : [];

    return { evaluators, agents, monitors };
  }

  /**
   * Archives the workflow and everything downstream of it in one transaction:
   * linked evaluators and agents are archived, and the monitors those
   * evaluators back are deleted outright.
   */
  cascadeArchive(input: {
    projectId: string;
    workflowId: string;
    unarchive?: boolean;
  }): Promise<WorkflowCascadeArchive> {
    return this.#infrastructure.lineage.cascadeArchive(input);
  }

  // -- the Optimization Studio's publication flags ---------------------------

  findWorkflowFlags(input: {
    workflowId: string;
    projectId: string;
  }): Promise<WorkflowPublicationFlags | null> {
    return this.#infrastructure.publications.findFlags(input);
  }

  findWorkflowVersionById(input: {
    versionId: string;
    projectId: string;
  }): Promise<Readonly<Record<string, unknown>> | null> {
    return this.#infrastructure.publications.findVersion(input);
  }

  setWorkflowFlags(input: {
    workflowId: string;
    projectId: string;
    isComponent?: boolean;
    isEvaluator?: boolean;
  }): Promise<void> {
    return this.#infrastructure.publications.setFlags(input);
  }

  listPublishedComponents(input: { projectId: string }): Promise<unknown> {
    return this.#infrastructure.publications.listPublishedComponents(input);
  }

  /**
   * Fire-and-forget: the count is read after the write landed, and a failure
   * to count must never fail the create that already succeeded.
   */
  #announceCreated(input: { workflowId: string; projectId: string; by: WorkflowCaller }): void {
    void this.#infrastructure.workflows
      .list({ projectId: input.projectId })
      .then((workflows) => {
        this.#infrastructure.signals.workflowCreated({
          userId: input.by.id,
          workflowCount: workflows.length,
          workflowId: input.workflowId,
          projectId: input.projectId,
        });
      })
      .catch((error: unknown) => {
        this.#infrastructure.signals.failed(error, { projectId: input.projectId });
      });
  }
}

/** One project's resolved function, as the shared cache holds it. */
export type NlpLambdaArnEntry = Readonly<{
  arn: string;
  /** The deployment image it was resolved under; a change invalidates it. */
  imageUri: string;
}>;

/** The AWS flow that finds, creates or updates the project's function. */
export interface NlpLambdaArnResolver {
  resolve(input: { projectId: string; imageUri: string }): Promise<string>;
}

/**
 * Which function one project's engine answers on, as the caller needs it. The
 * resolution behind it is cached and single-flighted; a caller only asks.
 */
export interface NlpLambdaFunctionPort {
  arnFor(input: { projectId: string }): Promise<string>;
}

/** One frame off a streaming invoke. */
export type NlpLambdaStreamChunk =
  | Readonly<{ kind: "payload"; bytes: Uint8Array<ArrayBufferLike> }>
  /** AWS reports a handler failure as a terminal frame, not a rejection. */
  | Readonly<{ kind: "failed"; errorCode: string; details?: string | undefined }>;


export interface NlpLambdaStreamInvoke {
  /**
   * Opens the invocation. The signal aborts the call itself, so a viewer who
   * walks away stops the run rather than leaving it billing until it ends.
   */
  invokeStream(input: {
    functionArn: string;
    payload: string;
    signal?: AbortSignal | undefined;
  }): Promise<AsyncIterable<NlpLambdaStreamChunk>>;
}

/** Resolves one feature key's model for one project. */
export interface WorkflowCommitMessageModel {
  resolve(input: { projectId: string; featureKey: string }): Promise<LanguageModel>;
}

/** The registered feature a call runs under, as the failure policy reads it. */
export type WorkflowAiCallFeature = Readonly<{
  key: string;
  role: ModelRole;
  displayName: string;
}>;

/**
 * Runs one model call for a named feature, turning any provider or SDK failure
 * into the application's typed `ai_call_failed` cause.
 */
export interface WorkflowAiCall {
  run<T>(feature: WorkflowAiCallFeature, call: () => Promise<T>): Promise<T>;
}

/**
 * The header the receiver reads the presigned URL from. Its readers are
 * langevals (`langevals/staged_payload.py`), the Go engine
 * (`services/nlpgo/adapters/httpapi/staged_payload.go`) and this module.
 */
export const STAGED_PAYLOAD_HEADER = "X-Payload-S3-URL";

export type NlpLambdaInvokeResult = Readonly<{
  statusCode: number;
  /** AWS reports a handler failure here rather than as a non-2xx status. */
  functionError?: string | undefined;
  payload: string;
}>;

export interface NlpLambdaInvoke {
  invoke(input: { functionArn: string; payload: string }): Promise<NlpLambdaInvokeResult>;
}

/** One parked payload, as the caller needs it back to reference and discard. */
export interface StagedNlpPayload {
  /** The presigned GET URL the receiver fetches the body from. */
  readonly url: string;
  /**
   * Removes the parked object. Best-effort by contract: a bucket lifecycle
   * rule on the staging prefix is the fallback for the crash paths where the
   * ask never happens.
   */
  discard(): Promise<void>;
}


export interface NlpPayloadStaging {
  stage(input: {
    projectId: string;
    /** The path segment the parked object is filed under. */
    keyPrefix: string;
    serialized: Buffer;
    ttlSeconds: number;
  }): Promise<StagedNlpPayload>;
}

export type WorkflowExecutionInput = {
  projectId: string;
  workflowId: string;
  version: WorkflowVersion;
  inputs: Record<string, unknown>;
  doNotTrace?: boolean;
  runEvaluations?: boolean;
  origin?: WorkflowRunOrigin;
  causalityDepth?: number;
  parentTrace?: { traceId: string; parentSpanId: string };
};

/** Execution is infrastructure: the feature supplies a dispatch port. */
export interface WorkflowExecution {
  execute(input: WorkflowExecutionInput): Promise<WorkflowRunAnswer>;
}

export type WorkflowNlpDispatchInput = {
  projectId: string;
  body: StudioClientEvent;
  origin: WorkflowRunOrigin;
  causalityDepth?: number;
  parentTrace?: { traceId: string; parentSpanId: string };
};

export type WorkflowNlpDispatchResponse = {
  ok: boolean;
  status: number;
  statusText: string;
  json(): Promise<unknown>;
};

export interface WorkflowNlpRuntime {
  dispatch(input: WorkflowNlpDispatchInput): Promise<WorkflowNlpDispatchResponse>;
}

/** One STREAMING studio run, opened against the engine. */
export type WorkflowStudioStreamInput = {
  projectId: string;
  body: StudioClientEvent;
  origin: WorkflowRunOrigin;
};

/**
 * The engine's streaming studio route, as bytes.
 *
 * Separate from {@link WorkflowNlpRuntime} because it is a different
 * conversation rather than a different address: `execute_sync` answers once
 * with a result, and `execute` answers continuously until it says `done`. A
 * process that can do the first cannot necessarily do the second — the
 * platform app reached the streaming route through per-project Lambda
 * routing — so a deployment declares them apart.
 *
 * The port hands back the raw reader rather than decoded events: the SSE
 * framing and the abort protocol are the same on any address, and stating them
 * once in a service is what keeps a second adapter from re-deriving them.
 */
export interface WorkflowStudioStream {
  open(input: WorkflowStudioStreamInput): Promise<ReadableStreamDefaultReader<Uint8Array>>;
}

export interface WorkflowId {
  next(): string;
}

/** Upgrades a persisted graph before it becomes the workflow's current version. */
export interface WorkflowDslMigration {
  migrate(dsl: WorkflowDsl): WorkflowDsl;
}

/** Project credentials and decrypted secrets are application infrastructure. */
export interface WorkflowProjectEnvironment {
  get(input: { projectId: string }): Promise<{ apiKey: string; secrets: Record<string, string> }>;
}

export type WorkflowLlmParameterResolution = {
  model: string;
  provider: string;
  configured: boolean;
  enabled: boolean;
  litellmParams?: Record<string, string>;
};

/** Resolves process-specific LiteLLM credentials without exposing provider rows. */
export interface WorkflowLlmParameters {
  resolve(input: {
    projectId: string;
    models: readonly LLMConfig["model"][];
  }): Promise<readonly WorkflowLlmParameterResolution[]>;
}

/**
 * Application-owned preparation of a Studio graph before it is persisted.
 *
 * Two steps the host owns rather than the feature: editor-only local node
 * configuration is folded into the execution DSL, and every LLM node without a
 * model is filled in from the project's providers. The second reaches the
 * host's model cascade and its registry flagship, so the whole preparation is
 * one port rather than a rule split across the boundary.
 */
export interface WorkflowStudioDsl {
  prepare(input: { projectId: string; dsl: StudioWorkflow }): Promise<StudioWorkflow>;
}

/**
 * The agent-mapping recompute a saved Studio graph triggers.
 *
 * Best effort and outside the save: the agents whose scenario mappings this
 * refreshes are the host's rows, and a failure to refresh them must never fail
 * the version that was already written.
 */
export interface WorkflowAgentMapping {
  recompute(input: { projectId: string; workflowId: string; dsl: StudioWorkflow }): Promise<void>;
}
