"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.ChapterState = void 0;
/** The state of the chapter. */
exports.ChapterState = {
    Default: "default",
    Converting: "converting",
};
