{
 "title": "Main Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "evaluator_type",
    "query": {
     "query": "label_values(evaluation_status_counter,evaluator_type)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Collector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Collector Calls Requests Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{path=\"/api/collector\"}[$__rate_interval])) by (status_code)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Collector Calls Requests per hour",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{path=\"/api/collector\"}[$__rate_interval])) by (status_code)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Time to Index distribution",
   "type": "bargauge",
   "description": "Delay between the trace being received and it actually being stored on elasticsearch",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(le) (increase(collector_index_delay_milliseconds_bucket[$__range]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Average Time to Index (ms)",
   "type": "stat",
   "description": "Delay between the trace being received and it actually being stored on elasticsearch",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(collector_index_delay_milliseconds_sum[$__range])) \n/ \nsum(increase(collector_index_delay_milliseconds_count[$__range]))",
     "legendFormat": "average"
    },
    {
     "expr": "histogram_quantile(\n  0.5,  # 0.5 corresponds to the median (50th percentile)\n  sum by(le) (rate(collector_index_delay_milliseconds_bucket[$__range]))\n)",
     "legendFormat": "median"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by(le) (rate(collector_index_delay_milliseconds_bucket[$__range]))\n)",
     "legendFormat": "95 percentile"
    }
   ]
  },
  {
   "title": "Time to Index over time (ms)",
   "type": "timeseries",
   "description": "Delay between the trace being received and it actually being stored on elasticsearch",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(collector_index_delay_milliseconds_sum[$__rate_interval]))\n/\nsum(rate(collector_index_delay_milliseconds_count[$__rate_interval]))",
     "legendFormat": "time to index"
    }
   ]
  },
  {
   "title": "Payload Size Distribution",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(le) (increase(payload_size_bytes_bucket{endpoint=\"collector\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Spans per Trace Distribution",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(le) (increase(trace_span_count_bucket[$__range]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Collector Endpoint Latency",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(le) (increase(http_request_duration_seconds_bucket{path=\"/api/collector\"}[$__range]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Collector Job Processing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum(increase(job_processing_counter{job_type=\"collector\"}[$__rate_interval])) by (status)",
     "legendFormat": "collector {{status}}"
    },
    {
     "expr": "sum(increase(job_processing_counter{job_type=\"collector_check_and_adjust\"}[$__rate_interval])) by (status)",
     "legendFormat": "check_and_adjust {{status}}"
    },
    {
     "expr": "sum(increase(job_processing_counter{job_type=\"track_event\"}[$__rate_interval])) by (status)",
     "legendFormat": "track_event {{status}}"
    }
   ]
  },
  {
   "title": "Collector Job Latency (ms)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(le) (increase(job_processing_duration_milliseconds_bucket{job_type=\"collector\"}[$__range]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Collector Check and Adjust Job Latency (ms)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(le) (increase(job_processing_duration_milliseconds_bucket{job_type=\"collector_check_and_adjust\"}[$__range]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Studio",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true
  },
  {
   "title": "Lambda Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "dimensions": { "FunctionName": "*" },
     "metricName": "Errors",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  { "title": "Evaluators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Lambda Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "dimensions": { "FunctionName": "*" },
     "metricName": "Errors",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Evaluation Job Processing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "increase(job_processing_counter{job_type=\"evaluation\"}[$__rate_interval])",
     "legendFormat": "evaluation {{status}}"
    }
   ]
  },
  {
   "title": "Evaluators Latency p95",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, evaluator_type) (rate(evaluation_duration_milliseconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "${evaluator_type} execution status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 68 },
   "repeat": "evaluator_type",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum by(status) (increase(evaluation_status_counter{evaluator_type=\"$evaluator_type\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Topic Clustering",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 },
   "collapsed": true,
   "panels": [
    {
     "title": "Topic Clustering Job Processing",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "targets": [
      {
       "expr": "increase(job_processing_counter{job_type=\"topic_clustering\"}[$__rate_interval])",
       "legendFormat": "topic_clustering {{status}}"
      }
     ]
    },
    {
     "title": "Batch Topic Clustering Payload Size Distribution",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(le) (increase(payload_size_bytes_bucket{endpoint=\"topic_clustering_batch\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Incremental Topic Clustering Payload Size Distribution",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(le) (increase(payload_size_bytes_bucket{endpoint=\"topic_clustering_incremental\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "tRPC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 },
   "collapsed": true
  },
  {
   "title": "tRPC Requests Per Hour",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{path=~\"/api/trpc.*\"}[$__rate_interval])) by (path)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "tRPC Latency p95",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, path) (rate(http_request_duration_seconds_bucket{path=~\"/api/trpc.*\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "tRPC Estimated Total Seconds Spent for the Period per Endpoint",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, path) (rate(http_request_duration_seconds_bucket{path=~\"/api/trpc.*\"}[$__range]))) * sum by(le, path) (increase(http_request_duration_seconds_count{path=~\"/api/trpc.*\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}