{{- include "langwatch.validateSecrets" . }}
{{- if not .Values.secrets.existingSecret }}
{{- if .Values.autogen.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.autogen.secretNames.langwatch_nlp | default (printf "%s-langwatch-nlp-secrets" .Release.Name) }}
  labels:
    {{- include "langwatch.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $existingSecret := lookup "v1" "Secret" .Release.Namespace (.Values.autogen.secretNames.langwatch_nlp | default (printf "%s-langwatch-nlp-secrets" .Release.Name)) }}
  {{- if $existingSecret }}
  # Reuse existing secret data
  {{- range $key, $value := $existingSecret.data }}
  {{ $key }}: {{ $value }}
  {{- end }}
  {{- else }}
  # Generate new secrets on first install
  API_TOKEN_JWT_SECRET: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
