import type { CodingAgentSessionRow } from "~/server/event-sourcing/pipelines/trace-processing/projections/codingAgentSession.foldProjection";

/**
 * A complete, zeroed session row for tests. Every numeric fact is 0 and every
 * collection empty so a test only states the fields it is actually about.
 */
export function sessionRow(
  over: Partial<CodingAgentSessionRow>,
): CodingAgentSessionRow {
  return {
    tenantId: "project_1",
    traceId: "trace-1",
    version: "2026-07-11",
    startedAtMs: 1_000,
    agent: "claude_code",
    agentVersion: "2.1.207",
    sessionId: "session-1",
    finalRequestId: "req-1",
    userId: "user-1",
    terminalType: "xterm-256color",
    entrypoint: "cli",
    modelCalls: 0,
    toolCalls: 0,
    subAgents: 0,
    prompts: 0,
    promptChars: 0,
    responseChars: 0,
    steps: [],
    toolCounts: {},
    toolDurationMs: {},
    filesTouched: [],
    skills: [],
    subAgentTypes: [],
    slashCommands: [],
    models: [],
    mcpServers: [],
    mcpTools: [],
    inputTokens: 0,
    outputTokens: 0,
    cacheReadTokens: 0,
    cacheCreationTokens: 0,
    costUsd: 0,
    modelCallMs: 0,
    toolMs: 0,
    ttftMsTotal: 0,
    ttftSamples: 0,
    blockedOnUserMs: 0,
    activeTimeUserSec: 0,
    activeTimeCliSec: 0,
    toolResultBytes: 0,
    toolInputBytes: 0,
    compactions: 0,
    compactionTokensBefore: 0,
    compactionTokensAfter: 0,
    peakContextTokens: 0,
    cacheRebuildCount: 0,
    largestCacheRebuildTokens: 0,
    failedTools: 0,
    errorTypes: {},
    apiErrors: 0,
    rateLimited: 0,
    retriesExhausted: 0,
    retryMs: 0,
    attempts: 0,
    refusals: 0,
    refusalCategories: [],
    internalErrors: 0,
    toolsDenied: 0,
    toolsAborted: 0,
    permissionMode: "default",
    permissionChanges: 0,
    hooksBlocked: 0,
    hooksCancelled: 0,
    hookMs: 0,
    linesAdded: 0,
    linesRemoved: 0,
    commits: 0,
    pullRequests: 0,
    editsAccepted: 0,
    editsRejected: 0,
    languagesEdited: [],
    atMentions: 0,
    stopReason: "end_turn",
    truncated: false,
    ...over,
  };
}
