export {
  emitWarningIfUnsupportedVersion,
  getLongPollPlugin,
  setCredentialFeature,
  setFeature,
  setTokenFeature,
  state,
} from "@aws-sdk/core/client";
export {
  AwsSdkSigV4ASigner,
  AwsSdkSigV4Signer,
  AwsSdkSigV4Signer as AWSSDKSigV4Signer,
  getBearerTokenEnvKey,
  NODE_AUTH_SCHEME_PREFERENCE_OPTIONS,
  NODE_SIGV4A_CONFIG_OPTIONS,
  resolveAwsSdkSigV4AConfig,
  resolveAwsSdkSigV4Config,
  resolveAwsSdkSigV4Config as resolveAWSSDKSigV4Config,
  validateSigningProperties,
} from "@aws-sdk/core/httpAuthSchemes";
export {
  AwsSdkSigV4AAuthInputConfig,
  AwsSdkSigV4AAuthResolvedConfig,
  AwsSdkSigV4AAuthResolvedConfig as AwsSdkSigV4APreviouslyResolved,
  AwsSdkSigV4AuthInputConfig,
  AwsSdkSigV4AuthInputConfig as AWSSDKSigV4AuthInputConfig,
  AwsSdkSigV4AuthResolvedConfig,
  AwsSdkSigV4AuthResolvedConfig as AWSSDKSigV4AuthResolvedConfig,
  AwsSdkSigV4Memoized,
  AwsSdkSigV4AuthResolvedConfig as AwsSdkSigV4PreviouslyResolved,
  AwsSdkSigV4AuthResolvedConfig as AWSSDKSigV4PreviouslyResolved,
} from "@aws-sdk/core/httpAuthSchemes";
export {
  _toBool,
  _toNum,
  _toStr,
  awsExpectUnion,
  AwsEc2QueryProtocol,
  AwsJson1_0Protocol,
  AwsJson1_1Protocol,
  AwsJsonRpcProtocol,
  AwsQueryProtocol,
  AwsRestJsonProtocol,
  AwsRestXmlProtocol,
  AwsSmithyRpcV2CborProtocol,
  JsonCodec,
  JsonShapeDeserializer,
  JsonShapeSerializer,
  loadJsonRpcErrorCode,
  loadRestJsonErrorCode,
  loadRestXmlErrorCode,
  parseJsonBody,
  parseJsonErrorBody,
  parseXmlBody,
  parseXmlErrorBody,
  QueryShapeSerializer,
  XmlCodec,
  XmlShapeDeserializer,
  XmlShapeSerializer,
} from "@aws-sdk/core/protocols";
export { JsonSettings, QuerySerializerSettings, XmlSettings } from "@aws-sdk/core/protocols";
