export const PAYLOAD_BLOCKLIST_EXACT: ReadonlySet<string> = new Set([
  "gen_ai.prompt",
  "gen_ai.completion",
  "gen_ai.response.choices",
  "gen_ai.response.finish_reasons",
  "raw_input",
  "input.value",
  "output.value",
  "input",
  "output",
  "mastra.output",
  "mastra.agent_run.input",
  "mastra.agent_run.output",
  "mastra.model_step.output",
  "mastra.model_step.input",
  "traceloop.entity.input",
  "traceloop.entity.output",
  "langwatch.input",
  "langwatch.output",
  "langwatch.claude_code.request_body",
  "langwatch.claude_code.response_body",
  "retrieval.documents",
  "llm.input_messages",
  "llm.output_messages",
]);

export const PAYLOAD_BLOCKLIST_PREFIXES: readonly string[] = [
  "gen_ai.prompt.",
  "gen_ai.completion.",
  "gen_ai.response.choices.",
  "gen_ai.response.finish_reasons.",
  "llm.input_messages.",
  "llm.output_messages.",
];
