"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.CaptionStyleModelTextTransform = void 0;
exports.CaptionStyleModelTextTransform = {
    None: "none",
    Uppercase: "uppercase",
};
