"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.DashboardClient = void 0;
const BaseClient_1 = require("../../../../../../BaseClient");
const Client_1 = require("../resources/settings/client/Client");
class DashboardClient {
    constructor(options = {}) {
        this._options = (0, BaseClient_1.normalizeClientOptions)(options);
    }
    get settings() {
        var _a;
        return ((_a = this._settings) !== null && _a !== void 0 ? _a : (this._settings = new Client_1.SettingsClient(this._options)));
    }
}
exports.DashboardClient = DashboardClient;
