"use strict";
// This file was auto-generated by Fern from our API Definition.
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.KbExternalSyncJob = void 0;
const core = __importStar(require("../../core"));
const CrawlStatus_1 = require("./CrawlStatus");
const ExternalSyncJobTrigger_1 = require("./ExternalSyncJobTrigger");
const ExternalSyncJobType_1 = require("./ExternalSyncJobType");
const ExternalSyncProvider_1 = require("./ExternalSyncProvider");
exports.KbExternalSyncJob = core.serialization.object({
    type: ExternalSyncProvider_1.ExternalSyncProvider,
    folderId: core.serialization.property("folder_id", core.serialization.string()),
    integrationConnectionId: core.serialization.property("integration_connection_id", core.serialization.string()),
    triggeredBy: core.serialization.property("triggered_by", ExternalSyncJobTrigger_1.ExternalSyncJobTrigger),
    status: CrawlStatus_1.CrawlStatus.optional(),
    syncType: core.serialization.property("sync_type", ExternalSyncJobType_1.ExternalSyncJobType.optional()),
    itemsIdentified: core.serialization.property("items_identified", core.serialization.number().optional()),
    itemsProcessed: core.serialization.property("items_processed", core.serialization.number().optional()),
    errorMessage: core.serialization.property("error_message", core.serialization.string().optional()),
    startedAt: core.serialization.property("started_at", core.serialization.number().optional()),
    completedAt: core.serialization.property("completed_at", core.serialization.number().optional()),
    updatedAt: core.serialization.property("updated_at", core.serialization.number()),
    id: core.serialization.string(),
    createdAt: core.serialization.property("created_at", core.serialization.number()),
});
