"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.AgentDefinitionSource = void 0;
exports.AgentDefinitionSource = {
    Cli: "cli",
    Ui: "ui",
    Api: "api",
    Template: "template",
    Unknown: "unknown",
};
