"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.TranscriptGetTranscriptForDubRequestFormatType = void 0;
/** Format to return transcript in. For subtitles use either 'srt' or 'webvtt', and for a full transcript use 'json'. The 'json' format is not yet supported for Dubbing Studio. */
exports.TranscriptGetTranscriptForDubRequestFormatType = {
    Srt: "srt",
    Webvtt: "webvtt",
    Json: "json",
};
