/**
 * What the Postgres annotation repository lets out of the package.
 * See modules/annotation/specs/annotation-service.feature.
 */
import { annotationSchema } from "@langwatch/annotation-contract";
import { prismaDouble } from "@langwatch/test-harness/client-doubles/prisma";
import { describe, expect, it, vi } from "vitest";

import * as publicSurface from "../../../index.ts";
import { PrismaAnnotationRepository } from "../prisma.annotation.repository.ts";

const NOW = new Date("2026-01-01T00:00:00Z");

const row = {
  id: "annotation-1",
  projectId: "project-1",
  traceId: "trace-1",
  comment: "a comment",
  isThumbsUp: true,
  userId: "user-1",
  email: null,
  scoreOptions: null,
  expectedOutput: null,
  anchorKind: "span",
  anchorId: "span-1",
  anchorPath: null,
  createdAt: NOW,
  updatedAt: NOW,
};

describe("PrismaAnnotationRepository row mapping", () => {
  describe("given a PostgreSQL row is returned", () => {
    /** @scenario "annotation persistence stays private" */
    it("returns the contract's annotation, selecting only the contract's columns", async () => {
      const findFirst = vi.fn().mockResolvedValue(row);
      const repository = PrismaAnnotationRepository.create({
        prisma: prismaDouble({ annotation: { findFirst } }),
      });

      const annotation = await repository.findById({ id: "annotation-1", projectId: "project-1" });

      expect(annotationSchema.validate(annotation)).toBe(true);
      expect(annotation).toEqual({ ...row, scoreOptions: {} });
      expect(Object.keys(findFirst.mock.calls[0]?.[0]?.select).toSorted()).toEqual(
        Object.keys(annotationSchema.shape).toSorted(),
      );
    });

    /** @scenario "annotation persistence stays private" */
    it("exports the module, its transports and nothing generated by Prisma", () => {
      expect(Object.keys(publicSurface).toSorted()).toEqual([
        "annotationProcessModule",
        "annotationRest",
        "annotationScoreTrpcTransport",
        "annotationTrpcTransport",
      ]);
    });
  });
});
