"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.WorkspacesClient = void 0;
const BaseClient_1 = require("../../../../BaseClient");
const Client_1 = require("../resources/apiKeys/client/Client");
class WorkspacesClient {
    constructor(options = {}) {
        this._options = (0, BaseClient_1.normalizeClientOptions)(options);
    }
    get apiKeys() {
        var _a;
        return ((_a = this._apiKeys) !== null && _a !== void 0 ? _a : (this._apiKeys = new Client_1.ApiKeysClient(this._options)));
    }
}
exports.WorkspacesClient = WorkspacesClient;
