"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.SpellingPatience = void 0;
/** Controls if the agent should be more patient when user is spelling numbers and named entities. */
exports.SpellingPatience = {
    Auto: "auto",
    Off: "off",
};
