/**
 * LangWatchQL analytics SQL — the PostgreSQL-resident half of the catalogue, an explicit list of
 * models: a model is queryable only because it is named below, and only by a caller holding its
 * access. Keys are view names; column keys are exposed names, each field listed or omitted.
 */

import type { LangWatchQLViewDefinition } from "../services/langwatch-ql-catalog-shapes.service.ts";
import { defineLwqlCatalog, defineTableCatalogue } from "./lwql-catalogue.rules.ts";
import {
  defineCatalogModel,
  type PostgresDatasetOverride,
} from "./lwql-postgres-catalog-model.rules.ts";
import { CONTENT_POSTGRES_OVERRIDES } from "./lwql-postgres-content-overrides.rules.ts";
import { CORE_POSTGRES_OVERRIDES } from "./lwql-postgres-core-overrides.rules.ts";
import { DESCRIPTIONS_POSTGRES_OVERRIDES } from "./lwql-postgres-descriptions-overrides.rules.ts";
import { PARENTS_POSTGRES_OVERRIDES } from "./lwql-postgres-parents-overrides.rules.ts";
import { VISIBILITY_POSTGRES_OVERRIDES } from "./lwql-postgres-visibility-overrides.rules.ts";

/** The `topics` view — the proving slice for the opt-out Postgres catalog. */

/** The topics override, keyed by its Prisma model name. */
const TOPICS_POSTGRES_OVERRIDES: Record<string, PostgresDatasetOverride> = {
  Topic: {
    description: "One row per topic, with the name a trace's TopicId resolves to.",
    descriptions: {
      TopicId: "Topic identifier. Matches `traces.TopicId`.",
      TopicName: "Display name of the topic.",
      ParentTopicId: "Parent topic in the hierarchy, null for a top-level topic.",
    },
  },
};

/** Combines two override maps model-by-model, not key-by-key. */
function mergePostgresOverride(
  base: PostgresDatasetOverride | undefined,
  addition: PostgresDatasetOverride,
): PostgresDatasetOverride {
  return {
    ...base,
    ...addition,
    columnUnits: { ...base?.columnUnits, ...addition.columnUnits },
    descriptions: { ...base?.descriptions, ...addition.descriptions },
  };
}

/** Every override file's maps, merged model-by-model into the single map the builder reads. */
function mergePostgresOverrides(
  maps: readonly Readonly<Record<string, PostgresDatasetOverride>>[],
): Record<string, PostgresDatasetOverride> {
  const merged: Record<string, PostgresDatasetOverride> = {};
  for (const map of maps) {
    for (const [model, override] of Object.entries(map)) {
      merged[model] = mergePostgresOverride(merged[model], override);
    }
  }
  return merged;
}

export const LWQL_POSTGRES_ALL_OVERRIDES: Record<string, PostgresDatasetOverride> =
  mergePostgresOverrides([
    CORE_POSTGRES_OVERRIDES,
    TOPICS_POSTGRES_OVERRIDES,
    PARENTS_POSTGRES_OVERRIDES,
    CONTENT_POSTGRES_OVERRIDES,
    VISIBILITY_POSTGRES_OVERRIDES,
    DESCRIPTIONS_POSTGRES_OVERRIDES,
  ]);

/**
 * Every catalogued Prisma model, in exposed-view-name order. Models left out (absent =
 * unqueryable) have no owning tenant, an internal-only tenant, or are access-control plumbing;
 * specs/lwql/catalog-inclusion.feature pins the list.
 */
export const LWQL_POSTGRES_CATALOGUE = defineLwqlCatalog({
  agents: defineTableCatalogue({
    sourceTable: "Agent",
    access: { allOf: ["analytics:view", "evaluations:view"] },
    columns: {
      TenantId: { source: "projectId" },
      AgentId: { source: "id" },
      Name: { source: "name" },
      Type: { source: "type" },
      config: "omit", // HTTP agent config carries bearer tokens and passwords
      WorkflowId: { source: "workflowId" },
      CopiedFromAgentId: { source: "copiedFromAgentId" },
      Environment: { source: "environment", content: "output" },
      OwnerUserId: { source: "ownerUserId" },
      HostLabel: { source: "hostLabel" },
      identityKey: "omit", // secret
      LastSeenAt: { source: "lastSeenAt" },
      ArchivedAt: { source: "archivedAt" },
      CreatedAt: { source: "createdAt" },
      UpdatedAt: { source: "updatedAt" },
    },
  }),
  ai_tool_entries: defineTableCatalogue({
    sourceTable: "AiToolEntry",
    access: { allOf: ["analytics:view", "aiTools:view"] },
    columns: {
      TenantId: { source: "organizationId" },
      AiToolEntryId: { source: "id" },
      Scope: { source: "scope" },
      ScopeId: { source: "scopeId" },
      Type: { source: "type" },
      DisplayName: { source: "displayName" },
      Slug: { source: "slug" },
      iconKey: "omit", // secret
      IconAsset: { source: "iconAsset", content: "output" },
      Order: { source: "order" },
      Enabled: { source: "enabled" },
      Config: { source: "config", content: "output" },
      ArchivedAt: { source: "archivedAt" },
      CreatedAt: { source: "createdAt" },
      UpdatedAt: { source: "updatedAt" },
      CreatedById: { source: "createdById" },
      UpdatedById: { source: "updatedById" },
    },
  }),
  ai_tool_entry_departments: defineTableCatalogue({
    sourceTable: "AiToolEntryDepartment",
    access: { allOf: ["analytics:view", "aiTools:view"] },
    columns: {
      TenantId: { source: "entryId" },
      AiToolEntryDepartmentId: { source: "id" },
      EntryId: { source: "entryId" },
      DepartmentId: { source: "departmentId" },
    },
  }),
  ai_tool_entry_teams: defineTableCatalogue({
    sourceTable: "AiToolEntryTeam",
    access: { allOf: ["analytics:view", "aiTools:view"] },
    columns: {
      TenantId: { source: "teamId" },
      AiToolEntryTeamId: { source: "id" },
      EntryId: { source: "entryId" },
    },
  }),
  analytics: defineTableCatalogue({
    sourceTable: "Analytics",
    access: { allOf: ["analytics:view"] },
    columns: {
      TenantId: { source: "projectId" },
      AnalyticsId: { source: "id" },
      key: "omit", // secret
      ValueJson: { source: "value", content: "output" }, // JSON; `value` is a number elsewhere
      NumericValue: { source: "numericValue" },
      StringValue: { source: "stringValue", content: "output" },
      BoolValue: { source: "boolValue" },
      CreatedAt: { source: "createdAt" },
    },
  }),
  annotation_queue_items: defineTableCatalogue({
    sourceTable: "AnnotationQueueItem",
    access: { allOf: ["analytics:view", "annotations:view"] },
    columns: {
      TenantId: { source: "projectId" },
      AnnotationQueueItemId: { source: "id" },
      AnnotationQueueId: { source: "annotationQueueId" },
      UserId: { source: "userId" },
      CreatedAt: { source: "createdAt" },
      UpdatedAt: { source: "updatedAt" },
      CreatedByUserId: { source: "createdByUserId" },
      TraceId: { source: "traceId" },
      DoneAt: { source: "doneAt" },
      MarkedForDatasetAt: { source: "markedForDatasetAt" },
    },
  }),
  annotation_queue_scores: defineTableCatalogue({
    sourceTable: "AnnotationQueueScores",
    access: { allOf: ["analytics:view", "annotations:view"] },
    columns: {
      TenantId: { source: "annotationQueueId" },
      AnnotationQueueId: { source: "annotationQueueId" },
      AnnotationScoreId: { source: "annotationScoreId" },
    },
  }),
  annotation_queues: defineTableCatalogue({
    sourceTable: "AnnotationQueue",
    access: { allOf: ["analytics:view", "annotations:view"] },
    columns: {
      TenantId: { source: "projectId" },
      AnnotationQueueId: { source: "id" },
      Name: { source: "name" },
      Slug: { source: "slug" },
      Description: { source: "description", content: "output" },
      CreatedAt: { source: "createdAt" },
      UpdatedAt: { source: "updatedAt" },
    },
  }),
  annotation_scores: defineTableCatalogue({
    sourceTable: "AnnotationScore",
    access: { allOf: ["analytics:view", "annotations:view"] },
    columns: {
      TenantId: { source: "projectId" },
      AnnotationScoreId: { source: "id" },
      Name: { source: "name" },
      CreatedAt: { source: "createdAt" },
      UpdatedAt: { source: "updatedAt" },
      DeletedAt: { source: "deletedAt" },
      Description: { source: "description", content: "output" },
      Active: { source: "active" },
      DataType: { source: "dataType" },
      Options: { source: "options", content: "output" },
      DefaultValue: { source: "defaultValue", content: "output" },
      Global: { source: "global" },
    },
  }),
  annotations: defineTableCatalogue({
    sourceTable: "Annotation",
    access: { allOf: ["analytics:view", "annotations:view"] },
    columns: {
      TenantId: { source: "projectId" },
      AnnotationId: { source: "id" },
      TraceId: { source: "traceId" },
      Comment: { source: "comment", content: "output" },
      IsThumbsUp: { source: "isThumbsUp" },
      UserId: { source: "userId" },
      CreatedAt: { source: "createdAt" },
      UpdatedAt: { source: "updatedAt" },
      email: "omit", // person email
      ScoreOptions: { source: "scoreOptions", content: "output" },
      ExpectedOutput: { source: "expectedOutput", content: "output" },
      AnchorKind: { source: "anchorKind" },
      AnchorId: { source: "anchorId" },
      AnchorPath: { source: "anchorPath", content: "output" },
    },
  }),
  anomaly_alerts: defineTableCatalogue({
    sourceTable: "AnomalyAlert",
    access: { allOf: ["analytics:view", "anomalyRules:view"] },
    columns: {
      TenantId: { source: "organizationId" },
      AnomalyAlertId: { source: "id" },
      RuleId: { source: "ruleId" },
      Severity: { source: "severity", content: "output" },
      RuleName: { source: "ruleName" },
      RuleType: { source: "ruleType" },
      TriggerWindowStart: { source: "triggerWindowStart" },
      TriggerWindowEnd: { source: "triggerWindowEnd" },
      TriggerSpendUsd: { source: "triggerSpendUsd", access: { allOf: ["cost:view"] } },
      TriggerEventCount: { source: "triggerEventCount" },
      Detail: { source: "detail", content: "output" },
      State: { source: "state", content: "output" },
      DestinationStatus: { source: "destinationStatus" },
      DetectedAt: { source: "detectedAt" },
      AcknowledgedAt: { source: "acknowledgedAt" },
      ResolvedAt: { source: "resolvedAt" },
    },
  }),
  anomaly_rules: defineTableCatalogue({
    sourceTable: "AnomalyRule",
    access: { allOf: ["analytics:view", "anomalyRules:view"] },
    columns: {
      TenantId: { source: "organizationId" },
      AnomalyRuleId: { source: "id" },
      Scope: { source: "scope" },
      ScopeId: { source: "scopeId" },
      Name: { source: "name" },
      Description: { source: "description", content: "output" },
      Severity: { source: "severity", content: "output" },
      RuleType: { source: "ruleType" },
      ThresholdConfig: { source: "thresholdConfig", content: "output" },
      destinationConfig: "omit", // carries auth headers, routing keys and emails
      Status: { source: "status" },
      ArchivedAt: { source: "archivedAt" },
      CreatedAt: { source: "createdAt" },
      UpdatedAt: { source: "updatedAt" },
      CreatedById: { source: "createdById" },
    },
  }),
  batch_evaluations: defineTableCatalogue({
    sourceTable: "BatchEvaluation",
    access: { allOf: ["analytics:view", "datasets:view"] },
    columns: {
      TenantId: { source: "projectId" },
      BatchEvaluationId: { source: "id" },
      ExperimentId: { source: "experimentId" },
      Data: { source: "data", content: "output" },
      Status: { source: "status" },
      Score: { source: "score" },
      Label: { source: "label" },
      Passed: { source: "passed" },
      Details: { source: "details", content: ["input", "output"] }, // quotes input and output
      Cost: { source: "cost", access: { allOf: ["cost:view"] } },
      DatasetSlug: { source: "datasetSlug" },
      DatasetId: { source: "datasetId" },
      Evaluation: { source: "evaluation", content: "output" },
      CreatedAt: { source: "createdAt" },
      UpdatedAt: { source: "updatedAt" },
    },
  }),
  costs: defineTableCatalogue({
    sourceTable: "Cost",
    access: { allOf: ["analytics:view", "cost:view"] },
    columns: {
      TenantId: { source: "projectId" },
      CostId: { source: "id", access: { allOf: ["cost:view"] } },
      CostType: { source: "costType" },
      CostName: { source: "costName", access: { allOf: ["cost:view"] } },
      ReferenceType: { source: "referenceType" },
      ReferenceId: { source: "referenceId" },
      Amount: { source: "amount" },
      Currency: { source: "currency", content: "output" },
      CreatedAt: { source: "createdAt" },
      UpdatedAt: { source: "updatedAt" },
      ExtraInfo: { source: "extraInfo", content: "output" },
    },
  }),
  custom_graphs: defineTableCatalogue({
    sourceTable: "CustomGraph",
    access: { allOf: ["analytics:view"] },
    columns: {
      TenantId: { source: "projectId" },
      CustomGraphId: { source: "id" },
      Name: { source: "name" },
      Graph: { source: "graph", content: "output" },
      Filters: { source: "filters", content: "output" },
      Kind: { source: "kind" },
      CreatedAt: { source: "createdAt" },
      UpdatedAt: { source: "updatedAt" },
      DashboardId: { source: "dashboardId" },
      GridColumn: { source: "gridColumn" },
      GridRow: { source: "gridRow" },
      ColSpan: { source: "colSpan" },
      RowSpan: { source: "rowSpan" },
    },
  }),
  custom_llm_model_costs: defineTableCatalogue({
    sourceTable: "CustomLLMModelCost",
    access: { allOf: ["analytics:view", "cost:view"] },
    columns: {
      TenantId: { source: "projectId" },
      CustomLLMModelCostId: { source: "id", access: { allOf: ["cost:view"] } },
      OrganizationId: { source: "organizationId" },
      ScopeType: { source: "scopeType" },
      ScopeId: { source: "scopeId" },
      Model: { source: "model" },
      Regex: { source: "regex", content: "output" },
      inputCostPerToken: "omit", // secret
      outputCostPerToken: "omit", // secret
      cacheReadCostPerToken: "omit", // secret
      cacheCreationCostPerToken: "omit", // secret
      cacheCreation1hCostPerToken: "omit", // secret
      CreatedAt: { source: "createdAt" },
      UpdatedAt: { source: "updatedAt" },
    },
  }),
  dashboards: defineTableCatalogue({
    sourceTable: "Dashboard",
    access: { allOf: ["analytics:view"] },
    columns: {
      TenantId: { source: "projectId" },
      DashboardId: { source: "id" },
      Name: { source: "name" },
      Order: { source: "order" },
      CreatedAt: { source: "createdAt" },
      UpdatedAt: { source: "updatedAt" },
    },
  }),
  data_privacy_policies: defineTableCatalogue({
    sourceTable: "DataPrivacyPolicy",
    access: { allOf: ["analytics:view", "project:update"] },
    columns: {
      TenantId: { source: "organizationId" },
      DataPrivacyPolicyId: { source: "id" },
      ScopeType: { source: "scopeType" },
      ScopeId: { source: "scopeId" },
      PersonalOnly: { source: "personalOnly" },
      Config: { source: "config", content: "output" },
      CreatedAt: { source: "createdAt" },
      UpdatedAt: { source: "updatedAt" },
    },
  }),
  dataset_records: defineTableCatalogue({
    sourceTable: "DatasetRecord",
    access: { allOf: ["analytics:view", "datasets:view"] },
    columns: {
      TenantId: { source: "projectId" },
      DatasetRecordId: { source: "id" },
      DatasetId: { source: "datasetId" },
      Entry: { source: "entry", content: "output" },
      CreatedAt: { source: "createdAt" },
      UpdatedAt: { source: "updatedAt" },
    },
  }),
  datasets: defineTableCatalogue({
    sourceTable: "Dataset",
    access: { allOf: ["analytics:view", "datasets:view"] },
    columns: {
      TenantId: { source: "projectId" },
      DatasetId: { source: "id" },
      Name: { source: "name" },
      Slug: { source: "slug" },
      ColumnTypes: { source: "columnTypes", content: "output" },
      CreatedAt: { source: "createdAt" },
      UpdatedAt: { source: "updatedAt" },
      ArchivedAt: { source: "archivedAt" },
      Mapping: { source: "mapping", content: "output" },
      UseS3: { source: "useS3" },
      S3RecordCount: { source: "s3RecordCount" },
      ContentLayout: { source: "contentLayout", content: "output" },
      Status: { source: "status" },
      StatusError: { source: "statusError", content: "output" },
      stagingKey: "omit", // secret
      SourceStoredObjectId: { source: "sourceStoredObjectId" },
      UploadFilename: { source: "uploadFilename", content: "output" },
      RowCount: { source: "rowCount" },
      SizeBytes: { source: "sizeBytes" },
      ChunkCount: { source: "chunkCount" },
      ChunkOffsets: { source: "chunkOffsets", content: "output" },
    },
  }),
  department_membership_histories: defineTableCatalogue({
    sourceTable: "DepartmentMembershipHistory",
    access: { allOf: ["analytics:view", "governance:view"] },
    columns: {
      TenantId: { source: "organizationId" },
      DepartmentMembershipHistoryId: { source: "id" },
      UserId: { source: "userId" },
      DepartmentId: { source: "departmentId" },
      ValidFrom: { source: "validFrom" },
      ValidTo: { source: "validTo" },
      CreatedAt: { source: "createdAt" },
    },
  }),
  departments: defineTableCatalogue({
    sourceTable: "Department",
    access: { allOf: ["analytics:view", "governance:view"] },
    columns: {
      TenantId: { source: "organizationId" },
      DepartmentId: { source: "id" },
      Name: { source: "name" },
      CreatedAt: { source: "createdAt" },
      UpdatedAt: { source: "updatedAt" },
      ArchivedAt: { source: "archivedAt" },
    },
  }),
  discovered_agents: defineTableCatalogue({
    sourceTable: "DiscoveredAgent",
    access: { allOf: ["analytics:view", "governance:view"] },
    columns: {
      TenantId: { source: "organizationId" },
      DiscoveredAgentId: { source: "id" },
      Provider: { source: "provider" },
      RawAgentId: { source: "rawAgentId" },
      DisplayText: { source: "displayText", content: "output" },
      Metadata: { source: "metadata", content: "output" },
      FirstSeenAt: { source: "firstSeenAt" },
      LastSeenAt: { source: "lastSeenAt" },
      CreatedAt: { source: "createdAt" },
      UpdatedAt: { source: "updatedAt" },
    },
  }),
  discovered_persons: defineTableCatalogue({
    sourceTable: "DiscoveredPerson",
    access: { allOf: ["analytics:view", "governance:view"] },
    columns: {
      TenantId: { source: "organizationId" },
      DiscoveredPersonId: { source: "id" },
      Provider: { source: "provider" },
      rawActorId: "omit", // raw external-person identity
      displayText: "omit", // raw external-person identity
      Kind: { source: "kind" },
      Department: { source: "department", content: "output" },
      FirstSeenAt: { source: "firstSeenAt" },
      LastSeenAt: { source: "lastSeenAt" },
      ErasedAt: { source: "erasedAt" },
      MoneyRowsPendingAt: { source: "moneyRowsPendingAt", access: { allOf: ["cost:view"] } },
      MoneyRebuildSince: { source: "moneyRebuildSince", content: "output" },
      SuspendedAt: { source: "suspendedAt", access: { allOf: ["cost:view"] } },
      SuspendedReason: { source: "suspendedReason", access: { allOf: ["cost:view"] } },
      CreatedAt: { source: "createdAt" },
      UpdatedAt: { source: "updatedAt" },
    },
  }),
  email_suppressions: defineTableCatalogue({
    sourceTable: "EmailSuppression",
    access: { allOf: ["analytics:view", "triggers:view"] },
    columns: {
      TenantId: { source: "projectId" },
      EmailSuppressionId: { source: "id" },
      email: "omit", // person email
      TriggerId: { source: "triggerId" },
      Reason: { source: "reason", content: "output" },
      CreatedAt: { source: "createdAt" },
    },
  }),
  erased_identifier_suppressions: defineTableCatalogue({
    sourceTable: "ErasedIdentifierSuppression",
    access: { allOf: ["analytics:view", "governance:view"] },
    columns: {
      TenantId: { source: "organizationId" },
      ErasedIdentifierSuppressionId: { source: "id" },
      Provider: { source: "provider" },
      identifierHash: "omit", // secret
      ErasedAt: { source: "erasedAt" },
    },
  }),
  evaluators: defineTableCatalogue({
    sourceTable: "Evaluator",
    access: { allOf: ["analytics:view", "evaluations:view"] },
    columns: {
      TenantId: { source: "projectId" },
      EvaluatorId: { source: "id" },
      Name: { source: "name" },
      Slug: { source: "slug" },
      Type: { source: "type" },
      Config: { source: "config", content: "output" },
      WorkflowId: { source: "workflowId" },
      CopiedFromEvaluatorId: { source: "copiedFromEvaluatorId" },
      ArchivedAt: { source: "archivedAt" },
      CreatedAt: { source: "createdAt" },
      UpdatedAt: { source: "updatedAt" },
    },
  }),
  experiment_versions: defineTableCatalogue({
    sourceTable: "ExperimentVersion",
    access: { allOf: ["analytics:view", "experiments:view"] },
    columns: {
      TenantId: { source: "projectId" },
      ExperimentVersionId: { source: "id" },
      ExperimentId: { source: "experimentId" },
      Version: { source: "version" },
      CounterVersion: { source: "counterVersion" },
      AutoSaved: { source: "autoSaved" },
      CommitMessage: { source: "commitMessage", content: "output" },
      AuthorId: { source: "authorId" },
      AuthorLabel: { source: "authorLabel" },
      RunId: { source: "runId" },
      State: { source: "state", content: "output" },
      SchemaVersion: { source: "schemaVersion" },
      CreatedAt: { source: "createdAt" },
      UpdatedAt: { source: "updatedAt" },
    },
  }),
  experiments: defineTableCatalogue({
    sourceTable: "Experiment",
    access: { allOf: ["analytics:view", "experiments:view"] },
    columns: {
      TenantId: { source: "projectId" },
      ExperimentId: { source: "id" },
      ExperimentName: { source: "name" },
      ExperimentType: { source: "type" },
      ExperimentSlug: { source: "slug" },
      WorkflowId: { source: "workflowId" },
      CreatedAt: { source: "createdAt" },
      UpdatedAt: { source: "updatedAt" },
      ArchivedAt: { source: "archivedAt" },
      WorkbenchState: { source: "workbenchState", content: "output" },
      WorkbenchVersion: { source: "workbenchVersion" },
    },
  }),
  gateway_budget_bucket_boundaries: defineTableCatalogue({
    sourceTable: "GatewayBudgetBucketBoundary",
    access: { allOf: ["analytics:view", "gatewayBudgets:view"] },
    columns: {
      TenantId: { source: "organizationId" },
      GatewayBudgetBucketBoundaryId: { source: "id" },
      BudgetId: { source: "budgetId" },
      BucketScopeId: { source: "bucketScopeId" },
      PeriodStartedAt: { source: "periodStartedAt" },
      CreatedAt: { source: "createdAt" },
      UpdatedAt: { source: "updatedAt" },
    },
  }),
  gateway_budget_ledgers: defineTableCatalogue({
    sourceTable: "GatewayBudgetLedger",
    access: { allOf: ["analytics:view", "gatewayBudgets:view"] },
    columns: {
      TenantId: { source: "budgetId" },
      GatewayBudgetLedgerId: { source: "id" },
      BudgetId: { source: "budgetId" },
      VirtualKeyId: { source: "virtualKeyId" },
      ModelProviderId: { source: "modelProviderId" },
      providerKey: "omit", // secret
      GatewayRequestId: { source: "gatewayRequestId" },
      AmountUsd: { source: "amountUsd", access: { allOf: ["cost:view"] } },
      TokensInput: { source: "tokensInput" },
      TokensOutput: { source: "tokensOutput" },
      TokensCacheRead: { source: "tokensCacheRead" },
      TokensCacheWrite: { source: "tokensCacheWrite" },
      Model: { source: "model" },
      DurationMs: { source: "durationMs" },
      Status: { source: "status" },
      OccurredAt: { source: "occurredAt" },
    },
  }),
  gateway_budgets: defineTableCatalogue({
    sourceTable: "GatewayBudget",
    access: { allOf: ["analytics:view", "gatewayBudgets:view"] },
    columns: {
      TenantId: { source: "organizationId" },
      GatewayBudgetId: { source: "id" },
      ScopeType: { source: "scopeType" },
      ScopeId: { source: "scopeId" },
      providerKey: "omit", // secret
      Name: { source: "name" },
      Description: { source: "description", content: "output" },
      Window: { source: "window" },
      LimitUsd: { source: "limitUsd", access: { allOf: ["cost:view"] } },
      OnBreach: { source: "onBreach" },
      Timezone: { source: "timezone", content: "output" },
      ExternalId: { source: "externalId" },
      Metadata: { source: "metadata", content: "output" },
      SpentUsd: { source: "spentUsd", access: { allOf: ["cost:view"] } },
      CurrentPeriodStartedAt: { source: "currentPeriodStartedAt" },
      ResetsAt: { source: "resetsAt" },
      LastResetAt: { source: "lastResetAt" },
      CycleAnchorAt: { source: "cycleAnchorAt" },
      ArchivedAt: { source: "archivedAt" },
      CreatedAt: { source: "createdAt" },
      UpdatedAt: { source: "updatedAt" },
      CreatedById: { source: "createdById" },
      ManagedByVirtualKeyId: { source: "managedByVirtualKeyId" },
    },
  }),
  gateway_cache_rules: defineTableCatalogue({
    sourceTable: "GatewayCacheRule",
    access: { allOf: ["analytics:view", "gatewayCacheRules:view"] },
    columns: {
      TenantId: { source: "organizationId" },
      GatewayCacheRuleId: { source: "id" },
      Name: { source: "name" },
      Description: { source: "description", content: "output" },
      Priority: { source: "priority" },
      Enabled: { source: "enabled" },
      Matchers: { source: "matchers", content: "output" },
      ActionConfig: { source: "action", content: "output" }, // not an action label
      ModeEnum: { source: "modeEnum" },
      ArchivedAt: { source: "archivedAt" },
      CreatedAt: { source: "createdAt" },
      UpdatedAt: { source: "updatedAt" },
      CreatedById: { source: "createdById" },
    },
  }),
  gateway_change_events: defineTableCatalogue({
    sourceTable: "GatewayChangeEvent",
    access: {
      allOf: ["analytics:view", "gatewayProviders:view", "virtualKeys:view", "gatewayBudgets:view"],
    },
    columns: {
      TenantId: { source: "projectId" },
      Revision: { source: "revision" },
      OrganizationId: { source: "organizationId" },
      Kind: { source: "kind" },
      VirtualKeyId: { source: "virtualKeyId" },
      BudgetId: { source: "budgetId" },
      ModelProviderId: { source: "modelProviderId" },
      Payload: { source: "payload", content: "output" },
      CreatedAt: { source: "createdAt" },
    },
  }),
  gateway_guardrails: defineTableCatalogue({
    sourceTable: "GatewayGuardrail",
    access: { allOf: ["analytics:view", "gatewayGuardrails:view"] },
    columns: {
      TenantId: { source: "projectId" },
      GatewayGuardrailId: { source: "id" },
      Name: { source: "name" },
      Description: { source: "description", content: "output" },
      EvaluatorId: { source: "evaluatorId" },
      Direction: { source: "direction" },
      FailureMode: { source: "failureMode" },
      ArchivedAt: { source: "archivedAt" },
      CreatedAt: { source: "createdAt" },
      UpdatedAt: { source: "updatedAt" },
      CreatedById: { source: "createdById" },
      UpdatedById: { source: "updatedById" },
    },
  }),
  gateway_realtime_sessions: defineTableCatalogue({
    sourceTable: "GatewayRealtimeSession",
    access: { allOf: ["analytics:view", "gatewayUsage:view"] },
    columns: {
      TenantId: { source: "projectId" },
      GatewayRealtimeSessionId: { source: "id" },
      OrganizationId: { source: "organizationId" },
      VirtualKeyId: { source: "virtualKeyId" },
      ModelProviderId: { source: "modelProviderId" },
      Vendor: { source: "vendor", content: "output" },
      AgentId: { source: "agentId" },
      Model: { source: "model" },
      RequestedModel: { source: "requestedModel" },
      VendorConversationId: { source: "vendorConversationId" },
      Status: { source: "status" },
      MintedAt: { source: "mintedAt" },
      ClosedAt: { source: "closedAt" },
      CloseReason: { source: "closeReason", content: "output" },
      TraceId: { source: "traceId" },
      VendorCostRaw: { source: "vendorCostRaw", access: { allOf: ["cost:view"] } },
      CreatedAt: { source: "createdAt" },
      UpdatedAt: { source: "updatedAt" },
    },
  }),
  github_branch_pull_request_checks: defineTableCatalogue({
    sourceTable: "GithubBranchPullRequestCheck",
    access: { allOf: ["analytics:view", "traces:view"] },
    columns: {
      TenantId: { source: "organizationId" },
      GithubBranchPullRequestCheckId: { source: "id" },
      RepositoryHost: { source: "repositoryHost" },
      RepositoryFullName: { source: "repositoryFullName" },
      HeadBranch: { source: "headBranch", content: "output" },
      LastCheckedAt: { source: "lastCheckedAt" },
      PrCount: { source: "prCount" },
      NotFoundAt: { source: "notFoundAt" },
      RecheckAfter: { source: "recheckAfter" },
      Attempts: { source: "attempts" },
      LastRequestedAt: { source: "lastRequestedAt" },
      CreatedAt: { source: "createdAt" },
      UpdatedAt: { source: "updatedAt" },
    },
  }),
  github_installations: defineTableCatalogue({
    sourceTable: "GithubInstallation",
    access: { allOf: ["analytics:view", "organization:view"] },
    columns: {
      TenantId: { source: "organizationId" },
      GithubInstallationId: { source: "id" },
      InstallationId: { source: "installationId" },
      accountLogin: "omit", // a user account's GitHub handle, as authorLogin
      AccountType: { source: "accountType" },
      AccountId: { source: "accountId" },
      RepositorySelection: { source: "repositorySelection", content: "output" },
      Repositories: { source: "repositories", content: "output" },
      SuspendedAt: { source: "suspendedAt", access: { allOf: ["cost:view"] } },
      CreatedAt: { source: "createdAt" },
      UpdatedAt: { source: "updatedAt" },
    },
  }),
  github_pull_requests: defineTableCatalogue({
    sourceTable: "GithubPullRequest",
    access: { allOf: ["analytics:view", "traces:view"] },
    columns: {
      TenantId: { source: "organizationId" },
      GithubPullRequestId: { source: "id" },
      RepositoryHost: { source: "repositoryHost" },
      RepositoryFullName: { source: "repositoryFullName" },
      HeadBranch: { source: "headBranch", content: "output" },
      PrNumber: { source: "prNumber" },
      HtmlUrl: { source: "htmlUrl" },
      Title: { source: "title", content: "input" }, // quotes the prompt, as coding_sessions
      State: { source: "state", content: "output" },
      IsDraft: { source: "isDraft" },
      authorLogin: "omit", // raw external-person identity (GitHub handle)
      PrCreatedAt: { source: "prCreatedAt" },
      PrClosedAt: { source: "prClosedAt" },
      PrMergedAt: { source: "prMergedAt" },
      PrUpdatedAt: { source: "prUpdatedAt" },
      MappedAt: { source: "mappedAt" },
      LastCheckedAt: { source: "lastCheckedAt" },
      CreatedAt: { source: "createdAt" },
      UpdatedAt: { source: "updatedAt" },
    },
  }),
  governance_tenant_histories: defineTableCatalogue({
    sourceTable: "GovernanceTenantHistory",
    access: { allOf: ["analytics:view", "governance:view"] },
    columns: {
      TenantId: { source: "organizationId" },
      GovernanceTenantHistoryId: { source: "id" },
      tenantId: "omit", // internal tenant id, not the owning project
      FirstUsedAt: { source: "firstUsedAt" },
      LastUsedAt: { source: "lastUsedAt" },
    },
  }),
  identity_match_suggestions: defineTableCatalogue({
    sourceTable: "IdentityMatchSuggestion",
    access: { allOf: ["analytics:view", "governance:view"] },
    columns: {
      TenantId: { source: "organizationId" },
      IdentityMatchSuggestionId: { source: "id" },
      DiscoveredPersonId: { source: "discoveredPersonId" },
      UserId: { source: "userId" },
      Score: { source: "score" },
      ComputedAt: { source: "computedAt" },
    },
  }),
  identity_matches: defineTableCatalogue({
    sourceTable: "IdentityMatch",
    access: { allOf: ["analytics:view", "governance:view"] },
    columns: {
      TenantId: { source: "organizationId" },
      IdentityMatchId: { source: "id" },
      DiscoveredPersonId: { source: "discoveredPersonId" },
      UserId: { source: "userId" },
      EvidenceKind: { source: "evidenceKind" },
      ValidFrom: { source: "validFrom" },
      ValidTo: { source: "validTo" },
      CreatedAt: { source: "createdAt" },
    },
  }),
  ingestion_pull_run_projections: defineTableCatalogue({
    sourceTable: "IngestionPullRunProjection",
    access: { allOf: ["analytics:view", "ingestionSources:view"] },
    columns: {
      TenantId: { source: "projectId" },
      IngestionPullRunProjectionId: { source: "id" },
      SourceId: { source: "sourceId" },
      Enabled: "inherit",
      Cron: { content: "output" },
      Cursor: { content: "output" },
      LastRunAt: "inherit",
      LastRunOutcome: { content: "output" },
      LastRunEventCount: "inherit",
      LastRunError: { content: "output" },
      LastRunErrorCode: "inherit",
      ConsecutiveErrors: "inherit",
      LastSuccessAt: "inherit",
      LastRunScheduledFor: "inherit",
      LastReadThroughAt: "inherit",
      LastRunCompleteness: { content: "output" },
      LastAgentsListingAt: "inherit",
      LastAgentsListingOutcome: { content: "output" },
      LastAgentsListingCount: "inherit",
      LastAgentsListingReason: { content: "output" },
      LastAgentsListingStatus: "inherit",
      LastPeopleListingAt: "inherit",
      LastPeopleListingOutcome: { content: "output" },
      LastPeopleDirectoryCount: "inherit",
      LastPeopleWithheldCount: "inherit",
      LastPeopleListingReason: { content: "output" },
      LastPeopleListingStatus: "inherit",
      CreatedAt: "inherit",
      UpdatedAt: "inherit",
      OccurredAt: "inherit",
      AcceptedAt: "inherit",
      LastEventId: "inherit",
      ProjectionVersion: "inherit",
    },
  }),
  ingestion_sources: defineTableCatalogue({
    sourceTable: "IngestionSource",
    access: { allOf: ["analytics:view", "ingestionSources:view"] },
    columns: {
      TenantId: { source: "teamId" },
      IngestionSourceId: { source: "id" },
      OrganizationId: { source: "organizationId" },
      SourceType: { source: "sourceType" },
      Name: { source: "name" },
      Description: { source: "description", content: "output" },
      ingestSecretHash: "omit", // secret
      parserConfig: "omit", // config JSON nests credential hashes
      pollerCursor: "omit", // config JSON nests credential hashes
      ErrorCount: { source: "errorCount" },
      PullSchedule: { source: "pullSchedule", content: "output" },
      Status: { source: "status" },
      TraceProjectId: { source: "traceProjectId" },
      ProviderAccountId: { source: "providerAccountId" },
      LastEventAt: { source: "lastEventAt" },
      LastSuccessAt: { source: "lastSuccessAt" },
      LastReadThroughAt: { source: "lastReadThroughAt" },
      LastRunCompleteness: { source: "lastRunCompleteness", content: "output" },
      UnpricedUsageSince: { source: "unpricedUsageSince", access: { allOf: ["cost:view"] } },
      UnpricedUsageThrough: { source: "unpricedUsageThrough", access: { allOf: ["cost:view"] } },
      ArchivedAt: { source: "archivedAt" },
      CreatedAt: { source: "createdAt" },
      UpdatedAt: { source: "updatedAt" },
      CreatedById: { source: "createdById" },
    },
  }),
  ingestion_templates: defineTableCatalogue({
    sourceTable: "IngestionTemplate",
    access: { allOf: ["analytics:view", "ingestionSources:view"] },
    columns: {
      TenantId: { source: "organizationId" },
      IngestionTemplateId: { source: "id" },
      Slug: { source: "slug" },
      SourceType: { source: "sourceType" },
      DisplayName: { source: "displayName" },
      Description: { source: "description", content: "output" },
      IconAsset: { source: "iconAsset", content: "output" },
      credentialSchema: "omit", // secret
      OttlRules: { source: "ottlRules", content: "output" },
      PlatformPublished: { source: "platformPublished" },
      Enabled: { source: "enabled" },
      ArchivedAt: { source: "archivedAt" },
      CreatedAt: { source: "createdAt" },
      UpdatedAt: { source: "updatedAt" },
      CreatedById: { source: "createdById" },
      UpdatedById: { source: "updatedById" },
    },
  }),
  langy_active_turns: defineTableCatalogue({
    sourceTable: "LangyActiveTurn",
    access: { allOf: ["analytics:view", "langy:view"] },
    columns: {
      TenantId: { source: "projectId" },
      LangyActiveTurnId: { source: "id" },
      ConversationId: { source: "conversationId" },
      TurnId: { source: "turnId" },
      RequestId: { source: "requestId" },
      UserId: { source: "userId" },
      Status: { source: "status" },
      LeaseOwner: { source: "leaseOwner", content: "output" },
      LeaseExpiresAt: { source: "leaseExpiresAt" },
      CreatedAt: { source: "createdAt" },
      UpdatedAt: { source: "updatedAt" },
    },
  }),
  langy_conversation_projections: defineTableCatalogue({
    sourceTable: "LangyConversationProjection",
    access: { allOf: ["analytics:view", "langy:view"] },
    columns: {
      TenantId: { source: "projectId" },
      LangyConversationProjectionId: { source: "id" },
      ConversationId: "inherit",
      UserId: "inherit",
      Title: { content: "input" }, // quotes the prompt, as coding_sessions
      TitleSource: "inherit",
      Status: "inherit",
      IsShared: "inherit",
      SharedAt: "inherit",
      SharedById: "inherit",
      MessageCount: "inherit",
      LastActivityAt: "inherit",
      CurrentTurnId: "inherit",
      LastError: { content: "output" },
      LastModel: "inherit",
      PendingHandoffToken: "omit", // secret
      PendingHandoffTurnId: "inherit",
      RunToken: "omit", // secret
      ArchivedAt: "inherit",
      CreatedAt: "inherit",
      UpdatedAt: "inherit",
      OccurredAt: "inherit",
      AcceptedAt: "inherit",
      LastEventId: "inherit",
      ProjectionVersion: "inherit",
    },
  }),
  langy_conversation_turn_projections: defineTableCatalogue({
    sourceTable: "LangyConversationTurnProjection",
    access: { allOf: ["analytics:view", "langy:view"] },
    columns: {
      TenantId: { source: "projectId" },
      LangyConversationTurnProjectionId: { source: "id" },
      ConversationId: "inherit",
      TurnId: "inherit",
      Status: "inherit",
      QuestionParts: { content: "output" },
      AnswerParts: { content: "output" },
      ToolCallsPayload: { source: "ToolCalls", content: "output" }, // not the ToolCalls count
      PlanPayload: { source: "Plan", content: "output" }, // not a plan label
      Error: { content: "output" },
      StartedAt: "inherit",
      EndedAt: "inherit",
      CreatedAt: "inherit",
      UpdatedAt: "inherit",
      OccurredAt: "inherit",
      AcceptedAt: "inherit",
      LastEventId: "inherit",
      ProjectionVersion: "inherit",
    },
  }),
  langy_message_projections: defineTableCatalogue({
    sourceTable: "LangyMessageProjection",
    access: { allOf: ["analytics:view", "langy:view"] },
    columns: {
      TenantId: { source: "projectId" },
      LangyMessageProjectionId: { source: "id" },
      ConversationId: "inherit",
      MessageId: "inherit",
      Role: "inherit",
      Parts: { content: "output" },
      SourceEventId: "inherit",
      OccurredAt: "inherit",
      AcceptedAt: "inherit",
      CreatedAt: "inherit",
      UpdatedAt: "inherit",
    },
  }),
  langy_turn_requests: defineTableCatalogue({
    sourceTable: "LangyTurnRequest",
    access: { allOf: ["analytics:view", "langy:view"] },
    columns: {
      TenantId: { source: "projectId" },
      LangyTurnRequestId: { source: "id" },
      UserId: { source: "userId" },
      RequestId: { source: "requestId" },
      ConversationId: { source: "conversationId" },
      TurnId: { source: "turnId" },
      Status: { source: "status" },
      LeaseOwner: { source: "leaseOwner", content: "output" },
      LeaseExpiresAt: { source: "leaseExpiresAt" },
      CreatedAt: { source: "createdAt" },
      UpdatedAt: { source: "updatedAt" },
    },
  }),
  model_default_config_scopes: defineTableCatalogue({
    sourceTable: "ModelDefaultConfigScope",
    access: { allOf: ["analytics:view", "project:view"] },
    columns: {
      TenantId: { source: "configId" },
      ModelDefaultConfigScopeId: { source: "id" },
      ConfigId: { source: "configId" },
      ScopeType: { source: "scopeType" },
      ScopeId: { source: "scopeId" },
      CreatedAt: { source: "createdAt" },
    },
  }),
  model_default_configs: defineTableCatalogue({
    sourceTable: "ModelDefaultConfig",
    access: { allOf: ["analytics:view", "project:view"] },
    columns: {
      TenantId: { source: "organizationId" },
      ModelDefaultConfigId: { source: "id" },
      Config: { source: "config", content: "output" },
      AuthorId: { source: "authorId" },
      CreatedAt: { source: "createdAt" },
      UpdatedAt: { source: "updatedAt" },
    },
  }),
  model_provider_scopes: defineTableCatalogue({
    sourceTable: "ModelProviderScope",
    access: { allOf: ["analytics:view", "gatewayProviders:view"] },
    columns: {
      TenantId: { source: "modelProviderId" },
      ModelProviderScopeId: { source: "id" },
      ModelProviderId: { source: "modelProviderId" },
      ScopeType: { source: "scopeType" },
      ScopeId: { source: "scopeId" },
      CreatedAt: { source: "createdAt" },
    },
  }),
  model_providers: defineTableCatalogue({
    sourceTable: "ModelProvider",
    access: { allOf: ["analytics:view", "gatewayProviders:view"] },
    columns: {
      TenantId: { source: "organizationId" },
      ModelProviderId: { source: "id" },
      Name: { source: "name" },
      Provider: { source: "provider" },
      RoutingHandle: { source: "routingHandle", content: "output" },
      Enabled: { source: "enabled" },
      customKeys: "omit", // secret
      extraHeaders: "omit", // raw provider auth headers
      CustomModels: { source: "customModels", content: "output" },
      CustomEmbeddingsModels: { source: "customEmbeddingsModels", content: "output" },
      DeploymentMapping: { source: "deploymentMapping", content: "output" },
      RateLimitRpm: { source: "rateLimitRpm" },
      RateLimitTpm: { source: "rateLimitTpm" },
      RateLimitRpd: { source: "rateLimitRpd" },
      RotationPolicy: { source: "rotationPolicy" },
      ProviderConfig: { source: "providerConfig", content: "output" },
      FallbackPriorityGlobal: { source: "fallbackPriorityGlobal" },
      LangySkipPermissionsModels: { source: "langySkipPermissionsModels", content: "output" },
      HealthStatus: { source: "healthStatus" },
      CircuitOpenedAt: { source: "circuitOpenedAt" },
      LastHealthCheckAt: { source: "lastHealthCheckAt" },
      DisabledAt: { source: "disabledAt" },
      CreatedAt: { source: "createdAt" },
      UpdatedAt: { source: "updatedAt" },
    },
  }),
  monitors: defineTableCatalogue({
    sourceTable: "Monitor",
    access: { allOf: ["analytics:view", "evaluations:view"] },
    columns: {
      TenantId: { source: "projectId" },
      MonitorId: { source: "id" },
      ExperimentId: { source: "experimentId" },
      EvaluatorId: { source: "evaluatorId" },
      CheckType: { source: "checkType" },
      Name: { source: "name" },
      Slug: { source: "slug" },
      ExecutionMode: { source: "executionMode" },
      Enabled: { source: "enabled" },
      Preconditions: { source: "preconditions", content: "output" },
      Parameters: { source: "parameters", content: "output" },
      Mappings: { source: "mappings", content: "output" },
      Sample: { source: "sample" },
      Level: { source: "level", content: "output" },
      ThreadIdleTimeout: { source: "threadIdleTimeout" },
      CreatedAt: { source: "createdAt" },
      UpdatedAt: { source: "updatedAt" },
    },
  }),
  notifications: defineTableCatalogue({
    sourceTable: "Notification",
    access: { allOf: ["analytics:view", "organization:manage"] },
    columns: {
      TenantId: { source: "projectId" },
      NotificationId: { source: "id" },
      OrganizationId: { source: "organizationId" },
      Metadata: { source: "metadata", content: "output" },
      CreatedAt: { source: "createdAt" },
      UpdatedAt: { source: "updatedAt" },
      SentAt: { source: "sentAt" },
    },
  }),
  pinned_traces: defineTableCatalogue({
    sourceTable: "PinnedTrace",
    access: { allOf: ["analytics:view", "traces:view"] },
    columns: {
      TenantId: { source: "projectId" },
      PinnedTraceId: { source: "id" },
      TraceId: { source: "traceId" },
      UserId: { source: "userId" },
      Source: { source: "source" },
      Reason: { source: "reason", content: "output" },
      CreatedAt: { source: "createdAt" },
    },
  }),
  process_manager_inboxes: defineTableCatalogue({
    sourceTable: "ProcessManagerInbox",
    access: { allOf: ["analytics:view", "project:manage"] },
    columns: {
      TenantId: { source: "projectId" },
      ProcessManagerInboxId: { source: "id" },
      ProcessName: { source: "processName" },
      processKey: "omit", // secret
      tenantId: "omit", // internal tenant id, not the owning project
      SourceEventId: { source: "sourceEventId" },
      sourceEventKey: "omit", // secret
      ConsumedAt: { source: "consumedAt" },
    },
  }),
  process_manager_instances: defineTableCatalogue({
    sourceTable: "ProcessManagerInstance",
    access: { allOf: ["analytics:view", "project:manage"] },
    columns: {
      TenantId: { source: "projectId" },
      ProcessManagerInstanceId: { source: "id" },
      ProcessName: { source: "processName" },
      processKey: "omit", // secret
      tenantId: "omit", // internal tenant id, not the owning project
      UserId: { source: "userId" },
      State: { source: "state", content: "output" },
      Revision: { source: "revision" },
      NextWakeAt: { source: "nextWakeAt" },
      UpdatedAt: { source: "updatedAt" },
    },
  }),
  process_manager_outbox_attempts: defineTableCatalogue({
    sourceTable: "ProcessManagerOutboxAttempt",
    access: { allOf: ["analytics:view", "project:manage"] },
    columns: {
      TenantId: { source: "projectId" },
      ProcessManagerOutboxAttemptId: { source: "id" },
      OutboxId: { source: "outboxId" },
      Attempt: { source: "attempt" },
      OccurredAt: { source: "occurredAt" },
      Outcome: { source: "outcome" },
      ErrorType: { source: "errorType" },
      ErrorMessage: { source: "errorMessage", content: "output" },
      RetryAfterMs: { source: "retryAfterMs" },
    },
  }),
  process_manager_outboxes: defineTableCatalogue({
    sourceTable: "ProcessManagerOutbox",
    access: { allOf: ["analytics:view", "project:manage"] },
    columns: {
      TenantId: { source: "projectId" },
      ProcessManagerOutboxId: { source: "id" },
      ProcessName: { source: "processName" },
      processKey: "omit", // secret
      tenantId: "omit", // internal tenant id, not the owning project
      UserId: { source: "userId" },
      messageKey: "omit", // secret
      IntentType: { source: "intentType" },
      Payload: { source: "payload", content: "output" },
      TraceCarrier: { source: "traceCarrier", content: "output" },
      SourceEventId: { source: "sourceEventId" },
      Status: { source: "status" },
      Attempts: { source: "attempts" },
      NextAttemptAt: { source: "nextAttemptAt" },
      LeasedUntil: { source: "leasedUntil" },
      leaseToken: "omit", // secret
      DispatchedAt: { source: "dispatchedAt" },
      CreatedAt: { source: "createdAt" },
      UpdatedAt: { source: "updatedAt" },
    },
  }),
  projects: defineTableCatalogue({
    sourceTable: "Project",
    access: { allOf: ["analytics:view", "project:view"] },
    columns: {
      TenantId: { source: "id" },
      ProjectName: { source: "name" },
      ProjectSlug: { source: "slug" },
      apiKey: "omit", // secret
      lwqlKey: "omit", // secret
      TeamId: { source: "teamId" },
      Language: { source: "language", content: "output" },
      Framework: { source: "framework", content: "output" },
      Kind: { source: "kind" },
      FirstMessage: { source: "firstMessage" },
      Integrated: { source: "integrated" },
      CreatedAt: { source: "createdAt" },
      UpdatedAt: { source: "updatedAt" },
      UserLinkTemplate: { source: "userLinkTemplate", content: "output" },
      TraceSharingEnabled: { source: "traceSharingEnabled" },
      PresenceEnabled: { source: "presenceEnabled" },
      S3Endpoint: { source: "s3Endpoint", content: "output" },
      s3AccessKeyId: "omit", // secret
      s3SecretAccessKey: "omit", // secret
      S3Bucket: { source: "s3Bucket", content: "output" },
      ArchivedAt: { source: "archivedAt" },
      IsPersonal: { source: "isPersonal" },
      OwnerUserId: { source: "ownerUserId" },
      PersonalFeatures: { source: "personalFeatures", content: "output" },
      DepartmentId: { source: "departmentId" },
      LangyEgressAllowlist: { source: "langyEgressAllowlist", content: "output" },
      LastCodingAgentSessionAt: { source: "lastCodingAgentSessionAt" },
      LastCodingAgentPullRequestAt: { source: "lastCodingAgentPullRequestAt" },
    },
  }),
  prompt_tag_assignments: defineTableCatalogue({
    sourceTable: "PromptTagAssignment",
    access: { allOf: ["analytics:view", "prompts:view"] },
    columns: {
      TenantId: { source: "projectId" },
      PromptTagAssignmentId: { source: "id" },
      ConfigId: { source: "configId" },
      VersionId: { source: "versionId" },
      TagId: { source: "tagId" },
      CreatedAt: { source: "createdAt" },
      UpdatedAt: { source: "updatedAt" },
      CreatedById: { source: "createdById" },
      UpdatedById: { source: "updatedById" },
    },
  }),
  prompt_tags: defineTableCatalogue({
    sourceTable: "PromptTag",
    access: { allOf: ["analytics:view", "prompts:view"] },
    columns: {
      TenantId: { source: "organizationId" },
      PromptTagId: { source: "id" },
      Name: { source: "name" },
      CreatedAt: { source: "createdAt" },
      UpdatedAt: { source: "updatedAt" },
      CreatedById: { source: "createdById" },
      UpdatedById: { source: "updatedById" },
    },
  }),
  prompt_versions: defineTableCatalogue({
    sourceTable: "LlmPromptConfigVersion",
    access: { allOf: ["analytics:view", "prompts:view"] },
    columns: {
      TenantId: { source: "projectId" },
      PromptVersionId: { source: "id" },
      VersionNumber: { source: "version" },
      CommitMessage: { source: "commitMessage", content: "output" },
      AuthorId: { source: "authorId" },
      PromptId: { source: "configId" },
      ConfigData: { source: "configData", content: "output" },
      SchemaVersion: { source: "schemaVersion" },
      RuntimeParameters: { source: "runtimeParameters", content: "output" },
      CreatedAt: { source: "createdAt" },
    },
  }),
  prompts: defineTableCatalogue({
    sourceTable: "LlmPromptConfig",
    access: { allOf: ["analytics:view", "prompts:view"] },
    columns: {
      TenantId: { source: "projectId" },
      PromptId: { source: "id" },
      PromptHandle: { source: "handle", content: "output" },
      PromptName: { source: "name" },
      CreatedAt: { source: "createdAt" },
      UpdatedAt: { source: "updatedAt" },
      DeletedAt: { source: "deletedAt" },
      OrganizationId: { source: "organizationId" },
      Scope: { source: "scope" },
      CopiedFromPromptId: { source: "copiedFromPromptId" },
    },
  }),
  retention_policies: defineTableCatalogue({
    sourceTable: "RetentionPolicy",
    access: { allOf: ["analytics:view", "project:update"] },
    columns: {
      TenantId: { source: "organizationId" },
      RetentionPolicyId: { source: "id" },
      ScopeType: { source: "scopeType" },
      ScopeId: { source: "scopeId" },
      Category: { source: "category", content: "output" },
      RetentionDays: { source: "retentionDays" },
      CreatedAt: { source: "createdAt" },
      UpdatedAt: { source: "updatedAt" },
    },
  }),
  routing_policies: defineTableCatalogue({
    sourceTable: "RoutingPolicy",
    access: { allOf: ["analytics:view", "routingPolicies:view"] },
    columns: {
      TenantId: { source: "organizationId" },
      RoutingPolicyId: { source: "id" },
      Name: { source: "name" },
      Description: { source: "description", content: "output" },
      ModelProviderIds: { source: "modelProviderIds" },
      ModelAliases: { source: "modelAliases", content: "output" },
      DefaultModel: { source: "defaultModel" },
      PolicyRules: { source: "policyRules", content: "output" },
      IsDefault: { source: "isDefault" },
      CreatedAt: { source: "createdAt" },
      UpdatedAt: { source: "updatedAt" },
      CreatedById: { source: "createdById" },
      UpdatedById: { source: "updatedById" },
    },
  }),
  routing_policy_scopes: defineTableCatalogue({
    sourceTable: "RoutingPolicyScope",
    access: { allOf: ["analytics:view", "routingPolicies:view"] },
    columns: {
      TenantId: { source: "routingPolicyId" },
      RoutingPolicyScopeId: { source: "id" },
      RoutingPolicyId: { source: "routingPolicyId" },
      ScopeType: { source: "scopeType" },
      ScopeId: { source: "scopeId" },
      CreatedAt: { source: "createdAt" },
    },
  }),
  saved_views: defineTableCatalogue({
    sourceTable: "SavedView",
    access: { allOf: ["analytics:view", "traces:view"] },
    columns: {
      TenantId: { source: "projectId" },
      SavedViewId: { source: "id" },
      UserId: { source: "userId" },
      Name: { source: "name" },
      Filters: { source: "filters", content: "output" },
      Query: { source: "query", content: "output" },
      Period: { source: "period", content: "output" },
      Order: { source: "order" },
      Kind: { source: "kind" },
      CreatedAt: { source: "createdAt" },
      UpdatedAt: { source: "updatedAt" },
    },
  }),
  scenario_versions: defineTableCatalogue({
    sourceTable: "ScenarioVersion",
    access: { allOf: ["analytics:view", "scenarios:view"] },
    columns: {
      TenantId: { source: "projectId" },
      ScenarioVersionId: { source: "id" },
      ScenarioId: { source: "scenarioId" },
      Version: { source: "version" },
      AuthorId: { source: "authorId" },
      AuthorLabel: { source: "authorLabel" },
      ChangeDescription: { source: "changeDescription", content: "output" },
      Snapshot: { source: "snapshot", content: "output" },
      SchemaVersion: { source: "schemaVersion" },
      CreatedAt: { source: "createdAt" },
    },
  }),
  scenarios: defineTableCatalogue({
    sourceTable: "Scenario",
    access: { allOf: ["analytics:view", "scenarios:view"] },
    columns: {
      TenantId: { source: "projectId" },
      ScenarioId: { source: "id" },
      Name: { source: "name" },
      Situation: { source: "situation", content: "output" },
      Criteria: { source: "criteria", content: "output" },
      Labels: { source: "labels" },
      Parameters: { source: "parameters", content: "output" },
      SimulatorModel: { source: "simulatorModel" },
      JudgeModel: { source: "judgeModel" },
      MaxTurns: { source: "maxTurns" },
      MinTurns: { source: "minTurns" },
      Fields: { source: "fields", content: "output" },
      CallerVoice: { source: "callerVoice", content: "output" },
      TestSuiteId: { source: "testSuiteId" },
      Version: { source: "version" },
      LastUpdatedById: { source: "lastUpdatedById" },
      ArchivedAt: { source: "archivedAt" },
      CreatedAt: { source: "createdAt" },
      UpdatedAt: { source: "updatedAt" },
    },
  }),
  scheduled_jobs: defineTableCatalogue({
    sourceTable: "ScheduledJob",
    access: { allOf: ["analytics:view", "triggers:view"] },
    columns: {
      TenantId: { source: "projectId" },
      ScheduledJobId: { source: "id" },
      TargetType: { source: "targetType" },
      TargetId: { source: "targetId" },
      Cron: { source: "cron", content: "output" },
      Timezone: { source: "timezone", content: "output" },
      NextRunAt: { source: "nextRunAt" },
      LastSlot: { source: "lastSlot" },
      CurrentSlot: { source: "currentSlot" },
      Attempts: { source: "attempts" },
      LastError: { source: "lastError", content: "output" },
      Active: { source: "active" },
      CreatedAt: { source: "createdAt" },
      UpdatedAt: { source: "updatedAt" },
    },
  }),
  share_links: defineTableCatalogue({
    sourceTable: "ShareLink",
    access: { allOf: ["analytics:view", "traces:share"] },
    columns: {
      TenantId: { source: "projectId" },
      ShareLinkId: { source: "id" },
      token: "omit", // secret
      ResourceType: { source: "resourceType" },
      ResourceId: { source: "resourceId" },
      ThreadId: { source: "threadId" },
      UserId: { source: "userId" },
      Visibility: { source: "visibility" },
      ExpiresAt: { source: "expiresAt" },
      MaxViews: { source: "maxViews" },
      ViewCount: { source: "viewCount" },
      CreatedAt: { source: "createdAt" },
      UpdatedAt: { source: "updatedAt" },
    },
  }),
  simulation_suites: defineTableCatalogue({
    sourceTable: "SimulationSuite",
    access: { allOf: ["analytics:view", "scenarios:view"] },
    columns: {
      TenantId: { source: "projectId" },
      SimulationSuiteId: { source: "id" },
      Name: { source: "name" },
      Slug: { source: "slug" },
      Description: { source: "description", content: "output" },
      ScenarioIds: { source: "scenarioIds" },
      Targets: { source: "targets", content: "output" },
      RepeatCount: { source: "repeatCount" },
      Labels: { source: "labels" },
      SimulatorModel: { source: "simulatorModel" },
      JudgeModel: { source: "judgeModel" },
      Kind: { source: "kind" },
      ScopeConfig: { source: "scope", content: "output" }, // not a scope label
      Fields: { source: "fields", content: "output" },
      Evaluators: { source: "evaluators", content: "output" },
      ArchivedAt: { source: "archivedAt" },
      CreatedAt: { source: "createdAt" },
      UpdatedAt: { source: "updatedAt" },
    },
  }),
  topic_clustering_run_history_projections: defineTableCatalogue({
    sourceTable: "TopicClusteringRunHistoryProjection",
    access: { allOf: ["analytics:view", "traces:view"] },
    columns: {
      TenantId: { source: "projectId" },
      TopicClusteringRunHistoryProjectionId: { source: "id" },
      Runs: { content: "output" },
      CreatedAt: "inherit",
      UpdatedAt: "inherit",
      OccurredAt: "inherit",
      AcceptedAt: "inherit",
      LastEventId: "inherit",
      ProjectionVersion: "inherit",
    },
  }),
  topic_clustering_run_projections: defineTableCatalogue({
    sourceTable: "TopicClusteringRunProjection",
    access: { allOf: ["analytics:view", "traces:view"] },
    columns: {
      TenantId: { source: "projectId" },
      TopicClusteringRunProjectionId: { source: "id" },
      LastRequestedAt: "inherit",
      LastRequestTrigger: { content: "output" },
      LastRunAt: "inherit",
      LastRunOutcome: { content: "output" },
      LastRunMode: { content: "output" },
      LastRunSkippedReason: { content: "output" },
      LastRunError: { content: "output" },
      LastRunErrorCode: "inherit",
      LastRunErrorUserActionable: "inherit",
      LastRunTracesProcessed: "inherit",
      LastRunTopicsCount: "inherit",
      LastRunSubtopicsCount: "inherit",
      LastRunPages: "inherit",
      InProgressRunId: "inherit",
      InProgressTraces: "inherit",
      InProgressPages: "inherit",
      InProgressStartedAt: "inherit",
      CreatedAt: "inherit",
      UpdatedAt: "inherit",
      OccurredAt: "inherit",
      AcceptedAt: "inherit",
      LastEventId: "inherit",
      ProjectionVersion: "inherit",
    },
  }),
  topic_model_projections: defineTableCatalogue({
    sourceTable: "TopicModelProjection",
    access: { allOf: ["analytics:view", "traces:view"] },
    columns: {
      TenantId: { source: "projectId" },
      TopicModelProjectionId: { source: "id" },
      CreatedAt: "inherit",
      UpdatedAt: "inherit",
      OccurredAt: "inherit",
      AcceptedAt: "inherit",
      LastEventId: "inherit",
      ProjectionVersion: "inherit",
    },
  }),
  topics: defineTableCatalogue({
    sourceTable: "Topic",
    access: { allOf: ["analytics:view", "traces:view"] },
    columns: {
      TenantId: { source: "projectId" },
      TopicId: { source: "id" },
      TopicName: { source: "name" },
      ParentTopicId: { source: "parentId" },
      embeddings_model: "omit", // clustering internal, not customer data
      centroid: "omit", // clustering internal, not customer data
      p95Distance: "omit", // clustering internal, not customer data
      AutomaticallyGenerated: { source: "automaticallyGenerated" },
      lastEventId: "omit", // clustering internal, not customer data
      CreatedAt: { source: "createdAt" },
      UpdatedAt: { source: "updatedAt" },
    },
  }),
  trace_edit_overlays: defineTableCatalogue({
    sourceTable: "TraceEditOverlay",
    access: { allOf: ["analytics:view", "traces:view"] },
    columns: {
      TenantId: { source: "projectId" },
      TraceEditOverlayId: { source: "id" },
      TraceId: { source: "traceId" },
      Patch: { source: "patch", content: "output" },
      CreatedById: { source: "createdById" },
      UpdatedById: { source: "updatedById" },
      CreatedAt: { source: "createdAt" },
      UpdatedAt: { source: "updatedAt" },
    },
  }),
  trigger_sents: defineTableCatalogue({
    sourceTable: "TriggerSent",
    access: { allOf: ["analytics:view", "triggers:view"] },
    columns: {
      TenantId: { source: "projectId" },
      TriggerSentId: { source: "id" },
      TriggerId: { source: "triggerId" },
      TraceId: { source: "traceId" },
      CustomGraphId: { source: "customGraphId" },
      ResolvedAt: { source: "resolvedAt" },
      openIncidentKey: "omit", // secret
      CreatedAt: { source: "createdAt" },
      UpdatedAt: { source: "updatedAt" },
    },
  }),
  triggers: defineTableCatalogue({
    sourceTable: "Trigger",
    access: { allOf: ["analytics:view", "triggers:view"] },
    columns: {
      TenantId: { source: "projectId" },
      TriggerId: { source: "id" },
      Name: { source: "name" },
      Action: { source: "action" },
      TriggerKind: { source: "triggerKind" },
      actionParams: "omit", // carries Slack webhook URLs and recipient emails
      Filters: { source: "filters", content: "output" },
      FilterQuery: { source: "filterQuery", content: "output" },
      LastRunAt: { source: "lastRunAt" },
      CreatedAt: { source: "createdAt" },
      UpdatedAt: { source: "updatedAt" },
      Active: { source: "active" },
      PausedReason: { source: "pausedReason", content: "output" },
      PausedAt: { source: "pausedAt" },
      Message: { source: "message", content: "output" },
      Deleted: { source: "deleted" },
      AlertType: { source: "alertType" },
      SlackTemplateType: { source: "slackTemplateType" },
      SlackTemplate: { source: "slackTemplate", content: "output" },
      emailSubjectTemplate: "omit", // person email
      emailBodyTemplate: "omit", // person email
      NotificationCadence: { source: "notificationCadence", content: "output" },
      TraceDebounceMs: { source: "traceDebounceMs" },
      CustomGraphId: { source: "customGraphId" },
    },
  }),
  virtual_key_scopes: defineTableCatalogue({
    sourceTable: "VirtualKeyScope",
    access: { allOf: ["analytics:view", "virtualKeys:view", "virtualKeys:viewOtherPersonal"] },
    columns: {
      TenantId: { source: "virtualKeyId" },
      VirtualKeyScopeId: { source: "id" },
      VirtualKeyId: { source: "virtualKeyId" },
      ScopeType: { source: "scopeType" },
      ScopeId: { source: "scopeId" },
      CreatedAt: { source: "createdAt" },
    },
  }),
  virtual_keys: defineTableCatalogue({
    sourceTable: "VirtualKey",
    access: { allOf: ["analytics:view", "virtualKeys:view", "virtualKeys:viewOtherPersonal"] },
    columns: {
      TenantId: { source: "organizationId" },
      VirtualKeyId: { source: "id" },
      Name: { source: "name" },
      Description: { source: "description", content: "output" },
      Status: { source: "status" },
      Purpose: { source: "purpose" },
      ExternalId: { source: "externalId" },
      Metadata: { source: "metadata", content: "output" },
      DisabledAt: { source: "disabledAt" },
      DisabledReason: { source: "disabledReason", content: "output" },
      ExpiresAt: { source: "expiresAt" },
      hashedSecret: "omit", // secret
      DisplayPrefix: { source: "displayPrefix", content: "output" },
      PrincipalUserId: { source: "principalUserId" },
      TraceProjectId: { source: "traceProjectId" },
      Config: { source: "config", content: "output" },
      Revision: { source: "revision" },
      previousHashedSecret: "omit", // secret
      previousSecretValidUntil: "omit", // secret
      RevokedAt: { source: "revokedAt" },
      RevokedById: { source: "revokedById" },
      CreatedAt: { source: "createdAt" },
      UpdatedAt: { source: "updatedAt" },
      CreatedById: { source: "createdById" },
      LastUsedAt: { source: "lastUsedAt" },
      RoutingPolicyId: { source: "routingPolicyId" },
      RoutingMode: { source: "routingMode" },
      ConnectServices: { source: "connectServices", content: "output" },
      licenseTokenHash: "omit", // secret
      LicenseInstanceId: { source: "licenseInstanceId" },
      LicenseExpiresAt: { source: "licenseExpiresAt" },
    },
  }),
  webhook_endpoint_deliveries: defineTableCatalogue({
    sourceTable: "WebhookEndpointDelivery",
    access: { allOf: ["analytics:view", "webhookEndpoints:view"] },
    columns: {
      TenantId: { source: "projectId" },
      WebhookEndpointDeliveryId: { source: "id" },
      Channel: { source: "channel" },
      OrganizationId: { source: "organizationId" },
      EndpointId: { source: "endpointId" },
      TriggerId: { source: "triggerId" },
      DispatchId: { source: "dispatchId" },
      Attempt: { source: "attempt" },
      EventCount: { source: "eventCount" },
      ResponseStatus: { source: "responseStatus" },
      LatencyMs: { source: "latencyMs" },
      Error: { source: "error", content: "output" },
      Response: { source: "response", content: "output" },
      Outcome: { source: "outcome" },
      FiredAt: { source: "firedAt" },
      CreatedAt: { source: "createdAt" },
    },
  }),
  workflow_versions: defineTableCatalogue({
    sourceTable: "WorkflowVersion",
    access: { allOf: ["analytics:view", "workflows:view"] },
    columns: {
      TenantId: { source: "projectId" },
      WorkflowVersionId: { source: "id" },
      Version: { source: "version" },
      CommitMessage: { source: "commitMessage", content: "output" },
      AuthorId: { source: "authorId" },
      WorkflowId: { source: "workflowId" },
      ParentId: { source: "parentId" },
      AutoSaved: { source: "autoSaved" },
      CreatedAt: { source: "createdAt" },
      UpdatedAt: { source: "updatedAt" },
      Dsl: { source: "dsl", content: "output" },
    },
  }),
  workflows: defineTableCatalogue({
    sourceTable: "Workflow",
    access: { allOf: ["analytics:view", "workflows:view"] },
    columns: {
      TenantId: { source: "projectId" },
      WorkflowId: { source: "id" },
      Name: { source: "name" },
      Icon: { source: "icon", content: "output" },
      Description: { source: "description", content: "output" },
      CreatedAt: { source: "createdAt" },
      UpdatedAt: { source: "updatedAt" },
      LatestVersionId: { source: "latestVersionId" },
      CurrentVersionId: { source: "currentVersionId" },
      PublishedId: { source: "publishedId" },
      PublishedById: { source: "publishedById" },
      ArchivedAt: { source: "archivedAt" },
      IsEvaluator: { source: "isEvaluator" },
      IsComponent: { source: "isComponent" },
      CopiedFromWorkflowId: { source: "copiedFromWorkflowId" },
    },
  }),
});

/** The views the catalogue renders, one per table, in catalogue order. */
export const LWQL_POSTGRES_CATALOG: readonly LangWatchQLViewDefinition[] = Object.entries(
  LWQL_POSTGRES_CATALOGUE,
).map(([name, table]) =>
  defineCatalogModel({ name, table, overrides: LWQL_POSTGRES_ALL_OVERRIDES }),
);
