name: langwatch-server-publish

on:
  release:
    types:
      - published
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish-pypi:
    if: startsWith(github.event.release.tag_name, 'langwatch-server-') || (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: "3.11"

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Setup pnpm
        uses: pnpm/action-setup@eae0cfeb286e66ffb5155f1a79b90583a127a68b # v2
        with:
          version: 10.24.0

      - name: Build mcp-server
        working-directory: mcp-server
        run: pnpm install && pnpm run build

      - name: Install dependencies
        run: |
          cd langwatch
          pnpm install
          pnpm build
          cd ..
          uv pip install build

      - name: Build package
        run: |
          uv run python -m build

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e
        with:
          packages_dir: python-sdk/dist/
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
