name: langwatch-app-gate-check

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read
  checks: read
  pull-requests: read

jobs:
  gate:
    uses: ./.github/workflows/utility-gated-requirement-checks.yml
    with:
      workflow-name: 'langwatch-app-ci'
      path: 'langwatch'
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
