name: Publish Docker Images to Marketplace ECR

on:
  release:
    types:
      - published
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-push:
    if: startsWith(github.event.release.tag_name, 'onprem-') || (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          role-skip-session-tagging: true

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registries: "709825985650" # Marketplace repository ID

      - name: Extract version from package.json
        id: extract_version
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build and push langwatch_nlp Docker image
        run: |
          cd langevals
          IMAGE_URI="709825985650.dkr.ecr.us-east-1.amazonaws.com/langwatch/onprem_langevals"
          docker buildx build . -f Dockerfile --platform="linux/amd64" -t $IMAGE_URI:$VERSION --push
          cd -

      - name: Build and push Docker image
        run: |
          IMAGE_URI="709825985650.dkr.ecr.us-east-1.amazonaws.com/langwatch/onprem_langwatch_saas"
          docker buildx build . -f Dockerfile --platform="linux/amd64" -t $IMAGE_URI:$VERSION --push

      - name: Build and push langwatch_nlp Docker image
        run: |
          cd langwatch/langwatch_nlp
          make generate_proxy_config
          IMAGE_URI="709825985650.dkr.ecr.us-east-1.amazonaws.com/langwatch/onprem_langwatch_nlp"
          docker buildx build . -f Dockerfile --platform="linux/amd64" -t $IMAGE_URI:$VERSION --push
          cd -
