name: sdk-javascript-gate-check

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read
  checks: read

jobs:
  javascript-sdk-gate:
    uses: ./.github/workflows/utility-gated-requirement-checks.yml
    with:
      workflow-name: 'sdk-javascript-ci'
      path: 'typescript-sdk'
      token: ${{ secrets.token }}
