name: sdk-python-gate-check

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read
  checks: read

jobs:
  python-sdk-gate:
    uses: ./.github/workflows/utility-gated-requirement-checks.yml@feature/workflow-gate-pattern
    with:
      workflow-name: 'sdk-python-ci'
      path: 'python-sdk'
