name: skynet-ci

on:
  pull_request:
    paths-ignore:
      - "skynet/**"

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - run: echo "no modifications, skipping typecheck"

  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "no modifications, skipping build"
