"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.HistoryListRequestSortDirection = void 0;
exports.HistoryListRequestSortDirection = {
    Asc: "asc",
    Desc: "desc",
};
